### ISSUE TITLE
Add zoom level notification

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1002]
I like new pop-up notification about active symbol in Android version. Please note - there is no way to find out current zoom level on Android device. It would be cool to add pop-up notification when zoom level changing.

### Configuration
Operating System: Android

**Comment by Zerbembasqwibo** [comment]
I see no use of this, I would rather prefer as few pop-ups and other diturbing things while working.
But maybe I misunderstand you: what will be the use of knowing level of zoom?

**Comment by yevhenmazur** [comment]
For example, I've chosen convenient zoom level and work in it. But now I want to zoom map in and then back to previous zoom level. How can I be sure that this is the the same zoom level in which I worked before? Can I be sure that my approximate drawings is not distorted due to incorrect zoom level?

**Comment by Zerbembasqwibo** [comment]
OK, you have other demands than me. I change zoom level all the time. I use
small screen device so big objects I zoom out (of course bot very much),
and with more detailed I zoom in. In between I zoom out very  much and
sometime in very much for making very detailed drawing. I can't say I have
one "main" zoom level. Maybe need of this increases with bigger screens
used?

But if to implement this, maybe better to be able to define such "basezoom"
that you always can fall back to? To use maybe on double click on any zoom
button?

2017-11-07 20:23 GMT+01:00 Yevhen Mazur <notifications@github.com>:

**Comment by lpechacek** [comment]
It has come to my mind recently that I'd also like to have the possibility to revert zoom level to some sort of "base setting". In issue #534 mlerjen suggests a button to return to mapping scale, which is usually larger than actual map scale. My idea was adding a zoom button function which would reset the zoom level to 1:1 with map scale upon tap-and-hold. As my device has high pixel density display (294 PPI), it is capable of displaying the map at almost print quality. Implementation of my idea crashed on the fact that the Qt buttons do not report tap-and-hold by default and I'm not (yet) willing to clutter Mapper code base with hacks.

Reading the above comments, I'd say we are in agreement that there should be some sort of configurable base zoom level accessible via a single action. @dg0yt, any advice for implementation?

**Comment by dg0yt** [comment]
@Zerbembasqwibo  These popup are Android "Toasts" and not very intrusive. At they moment they display what is sent as temporary message to the status bar for the desktop. Indicating zoom as it changes sound like a good idea.

@lpechacek What can be added easily to the QToolButtons is a popup menu on long press. This is what I added to the symbol button:
https://github.com/OpenOrienteering/mapper/blob/4d20b4b711fced1e43ba600c6ea89763516ad4c6/src/gui/map/map_editor.cpp#L1372-L1375

plus some
~~~
button->setMenu(mobile_symbol_button_menu);
~~~

**Comment by Zerbembasqwibo** [comment]
@kai I am for sure extreme, but I almost think the pop-up "Map saved" takes
too much time... :)
Since I zoom in and out very much I guess I'll be disturbed. But maybe is
it possible to work even a pop-up is shown?
Or if it's only me, I will not try to stop this, of course!

2017-11-07 23:52 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
This toast does not block user input, except for the small area it covers.

**Comment by Zerbembasqwibo** [comment]
OK.

2017-11-08 6:38 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by lpechacek** [comment]
@dg0yt, thanks for the hint. That reminds me that I learned about the symbol button context menu only from reading code while researching for the zoom reset feature. I've just added a hint about the context menu to the mapper-manual pull request. I'm curious if single-item context menu will trigger the action immediately or whether two taps will be required. My dream is a single-tap operation.

**Comment by ollesmaps** [comment]
In fact the new toast slows me down a little bit. It gets over the Snap button. I have to wait a little so I can start snapping. Could the toast be above the Snap/Angl/etc buttons?

**Comment by Zerbembasqwibo** [comment]
I told you... :)

2017-12-01 10:45 GMT+01:00 Aleš Hejna <notifications@github.com>:

**Comment by dg0yt** [comment]
Thanks for feedback. I will try to move the toast a little bit away from its current (default) position. I could also shorten the time until it gets hidden again (currently 2 s).
Do you use the pinch gesture or the buttons for zoom control in these situations? Maybe I could hide the toast immediately when the pinch gesture is finished, but this doesn't help with the buttons.

**Comment by ollesmaps** [comment]
The fact is I have not encounred this problem with zoom toast. Because after zooming you have to push symbol button anyway (and it does not obscure symbol button). 
So this delay occurs with Symbol name toast, when the toast gets over Snap/Angle/etc.
I use pinching seldomly. I use buttons for zooming. A shorter time would be great. I estimate my stylus gets there in 0,5 sec. If the toast gets a little bit higher, that would solve it definitely.
BTW Is there a limit of characters in the symbol toast? Now it seems all available characters get in there. However I have not tried it with a long symbol. Just guessing.
