### ISSUE TITLE
Symbol icon size on "Symbols" widget is only 50% of size in "Settings" (Android)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1011]
### Steps to reproduce
1. Launch "Mapper" on Android;
2. Go to "Settings" and set "Symbol icon size" to `10mm` and save settings;
3. Open any map and go to "Symbols" widget (where all symbols showed);
4. Check size of each symbol icon.

### Actual behaviour
If symbol icon size in "Settings" described as `10mm`, then on "Symbols" widget it showed as `5mm`.

If increase size in "Settings" widget to `20mm`, then on widget symbol icon size only `10mm`.

Look like symbol icon size on widget "Symbols" is only 50% of size that was setted in "Settings".

### Expected behaviour
If symbol icon size in "Settings" described as `10mm`, then on "Symbols" widget size of it also should be `10mm`.

### Configuration
Mapper Version: 0.7.92
Operating System: Android 6.0, ARMv7
Display size: `720 x 1280`, diagonal `5.0"`

**Comment by Symbian9** [comment]
@dg0yt, also update now builds of `v0.7.92` for Android
* https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.92

**Comment by dg0yt** [comment]
The bug was in all versions, but it is only visible when there is a difference between logical and physical resolution. (It is not always 50%.)
v0.7.92 cannot be updated. It refers to a version of the source code which has the bug. You can easily choose a different setting, so stop pushing for another release.

**Comment by ollesmaps** [comment]
Some of the symbol icons in 0.7.92 Android got simpler. Lines with symbols - earh wall, stone wall, fence - their symbols in icons disappeared. It is now hard to distinguish between icons.

**Comment by dg0yt** [comment]
Can you provide a screen shot? Is it from an OCD map?
Does this issue appear with the example maps, too? 

I acknowledge that readability is not always better at the moment (e.g. Major power line, Impassable pipeline), but I can't reproduce missing symbols.

**Comment by ollesmaps** [comment]
- forest sample.omap - symbol icons are correct
![screenshot_forest](https://user-images.githubusercontent.com/20535899/33627449-d93f5bd4-d9fd-11e7-9401-e4fde58d7916.png)
- complete map.omap - some get incorrect (high fence)
![screenshot_complete](https://user-images.githubusercontent.com/20535899/33627776-cf2ab17e-d9fe-11e7-9ed5-826b0b7c2253.png)
- my map - some get incorrect (high fence and other), yes it is imported from Ocad
![screenshot_olles](https://user-images.githubusercontent.com/20535899/33627479-edb0a906-d9fd-11e7-8c44-53ac47100be3.png)

**Comment by ollesmaps** [comment]
The icon for area symbol field could have more dots.
