### ISSUE TITLE
OCAD zone Switzerland / CH1903 does not import

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1012]
### Steps to reproduce
1. Open lhc.ocd from attached lhc-epsg21781.zip

[lhc-epsg21781.zip](https://github.com/OpenOrienteering/mapper/files/1498365/lhc-epsg21781.zip)

### Actual behaviour
Mapper says: Could not load the coordinate reference system '14001'.

### Expected behaviour
EPSG:21781 projection is applied
.
### Configuration
Mapper Version: git-3d036b28867409233073b078ceb5172267d659bc
Operating System: openSUSE Tumbleweed

**Comment by dg0yt** [comment]
I guess this was a mistake. I think it would be safe to cherry-pick the fix from #1016 to master.

**Comment by lpechacek** [comment]
There is pull request 1013 against master with the same fix and updated commit message

The three pull requests in place build one on top of another. Pull request #1013 is a plain fix, #1014 is a proposed optimization and #1016 is experimental work in progress. The latest pull request requires changes from previous two, which is why it contains the same changes. However, on a rebase, those which enter origin/dev will be eliminated. Hope this explains the duplication.
