### ISSUE TITLE
OCAD-like navigation

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#1017]
One person asked me via email to create this issue for him:

> I miss the most convenient navigation, which was added in the latest versions of OCAD, so my suggestion concerns the behavior of the mouse wheel:
> * A simple scrolling of the wheel - vertical scrolling
> * Scrolling the wheel with the Shift pressed - horizontal scrolling
> * To zoom, use Ctrl + wheel
>
> And, it works regardless of the current drawing / navigation mode.
> In my opinion, this is much more convenient than simple scaling, tied to the mouse wheel in the current version of OOMapper. Either make this mouse wheel behavior customizable via options, for orthodoxes)

**Comment by dg0yt** [comment]
I have seen this behaviour in OCAD 11 Viewer, and I find it quite confusing. I'm trained to move the map with the middle mouse button (mouse wheel as button).

More opinions welcome.

**Comment by krticka** [comment]
I will not support this proposal. I am long year OCAD user, but using middle mouse button in OO Mapper is much more comfortable and faster.

**Comment by lpechacek** [comment]
I've seen the vertical/horizontal scrolling behavior, as described above, in LibreOffice Calc and some other text oriented applications. But for a map drawing application I do not appreciate the separation of vertical and horizontal move. The current behavior is sweet and efficient from my POV.

**Comment by ollesmaps** [comment]
I prefer current OMapper settings.

**Comment by marcovandersson** [comment]
I also definitely supports the current Omap behaviour. Do not change! :-)
