### ISSUE TITLE
Accidentaly selecting symbol that is already selected

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1018]
### Expected behaviour
When accidentaly selecting symbol that is already selected , make it possible to return by clicking on the white empty space bellow symbols on Symbol selection screen. (Instead of eyeballing and searching for the already selected).

### Configuration
Android app: 0.7.92

**Comment by dg0yt** [comment]
Did you try the back button? (I have no more white space since I increased icon size ...)

**Comment by ollesmaps** [comment]
I have not :) Thank you that works! 
Mine back button is small and black, thus harder to push. But I see now with the scalable symbol icons this is not worth pursuing. Consider it solved.

**Comment by dg0yt** [comment]
Well, documentation is one of the remaining work items for 0.8.0:
You should be able to select a symbol directly by a short tap. Only if you do a long tap, or if you swipe over the symbols - in order to get a symbol name tooltip - you will need another tap to confirm.
