### ISSUE TITLE
Open/Import PBF (osm.pbf, etc.)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1027]
### Actual behaviour
Currently Mapper can open/import only raw OSM XML (`*.osm`), but PBF (`*.pbf`) format widely as much compact binary format for OSM (`*.osm.pbf`)

### Expected behaviour
Add support for opening/import PBF files directly in Mapper using:
- https://github.com/CanalTP/libosmpbfreader
- https://github.com/osmcode/osmium-tool
  - https://github.com/osmcode

About PBF
- http://wiki.openstreetmap.org/wiki/PBF_Format

### Configuration
Mapper Version: 0.8.x
Operating System: All

**Comment by dg0yt** [comment]
Mapper can already import .pbf if you choose filter "All files". It is supported even by GDAL 1.x. However:
- There is no such workaround for templates.
- GDAL before 2.0 does not provide information about extensions supported by individual drivers.
- Mapper has a bug which prevents using all secondary extensions reported by GDAL 2.x drivers.
