### ISSUE TITLE
Search http://www.openorienteering.org/

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1039]
Could there be a search bar?
So stuff can be found faster.

**Comment by dg0yt** [comment]
We can't easily add a local search engine, but we could use an external service, e.g.

https://metager.de/en/sitesearch?site=openorienteering.org

**Comment by ollesmaps** [comment]
I think it is worth including.

**Comment by dg0yt** [comment]
Done.
