### ISSUE TITLE
"World of O Maps" link is not working

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#1042]
![screenshot1](https://user-images.githubusercontent.com/688044/35748010-8b3d0254-085d-11e8-871b-3059a0e6a475.jpg)

[World of O Maps](http://maps.worldofo.com/?zoom=15&lat=56.0565&lng=40.4398):
> 19/11/2013: Due to changes with Google Maps the overview map is currently disabled and only the search interface works (Note that the advanced search interface lets you search by position). It will be looked at within a few weeks time. Sorry for the inconvenience - please tell me if this was an important function for you at jan [at] kocbach.net!

**Comment by dg0yt** [comment]
Yes, this "a few weeks" since Nov 2013. However, it might be possible to switch to the search form if we provide a rectangle:
http://maps.worldofo.com/searchmaps.php?name=&owner=&country=&region=&sourceid=&year=&minlat=48.5&minlng=8.5&maxlat=49&maxlng=9&over=&mapmaker=&sortby=name

**Comment by dg0yt** [comment]
The new search form doesn't help that much: It will center & zoom to the known maps it finds for the given rectangle, not to the rectangle itself. And it won't show anything if doesn't find a known map at all.

**Comment by ollesmaps** [comment]
Question from Jan Kocbach: "Do you know what this is actually used for? Does anybody use the old map archive? Most want the omap archive, and that is a different link...?"

**Comment by dg0yt** [comment]
I used to find this useful to find nearby maps...

What's "the omap archive"? http://omaps.worldofo.com/? Note that I had to look for the term "omap" on http://worldofo.com/ to find that link - the "Maps" button/menu does link to http://maps.worldofo.com. I also see no way to load a particular location.

**Comment by ollesmaps** [comment]
"Omaps" are maps with routes uploaded by orienteers (usually very good resolution). "Maps" are maps uploaded by federations - usually archives of existing maps - only very few countries have that (usually bad resolution or just an outline without the real map).

**Comment by ollesmaps** [comment]
I believe Jan can supply a link if we specify what we want. I prefer omaps to maps - bigger variety, more uptodate and bigger resolution.

**Comment by sikmir** [comment]
A lot of O-maps (primarly for Russia) can be found on https://nakarte.me, so osm and worldofo links can be replaced with:
`https://nakarte.me/#m=18/%1/%2&l=O/U/R` (layers: O - OpenStreetMap, U - Races, R - O-sport)

**Comment by ollesmaps** [comment]
@sikmir That is an interesting and valuable source of maps! I see you can download bitmap tiles in jnx format. Is there a way how to open it in OOM ?

**Comment by sikmir** [comment]
> Is there a way how to open it in OOM ?

OOM doesn't support JNX templates, but you can download any rectangle as jpg as well.

**Comment by Symbian9** [comment]
> OOM doesn't support JNX templates, but you can download any rectangle as jpg as well.

JFTR, Some extra info on *JNX* file format:

- http://whiter.brinkster.net/en/JNX.shtml

As JNX is tile-based format it depend on implementing WMS/TMS templates in *Mapper*:

- https://github.com/OpenOrienteering/mapper/issues/84

**Comment by dl3sdo** [comment]
Note: "World of O Maps" link is removed by #2246.
