### ISSUE TITLE
OOMapper can not import DXF files with comment lines (group code 999)

### ISSUE THREAD

**Issue by t-miyakawa** [OpenOrienteering/mapper#1044]
### Steps to reproduce
I use GIS software named "VectorMapMaker" to convert the elevation point data to contours. This software exports contour line data to DXF file. In this DXF file, comment lines (group code 999) indicating the name of the software and the name of the author is written at the beginning of the data.
I attach a sample file. (Please change the extension "txt" to "dxf")
* [kiusu.txt](https://github.com/OpenOrienteering/mapper/files/1695058/kiusu.txt)

### Actual behaviour
When importing this DXF file with the Open Orenteering Mapper, an error message will be displayed and it fails. 
> "There was an error reading the DXF file C:/ProgramData/VectorMapMaker/map/kiusu.dxf:
The file is not an DXF file."

### Expected behaviour
So I am manually deleting the first 4 lines. Can not you improve it to skip comment lines? OCAD 8 can import the same file without problems.

### Configuration
Mapper Version: OpenOrienteeringMapper Ver. 0.7.0
Operating System: Windows 10 Home Ver. 1709

OCAD Ver. 8.12
[VectorMapMaker Ver. 11.2 ](http://www.geocities.jp/morita_shin2/vectormapmaker/vectormapmaker.htm)

**Comment by xc-racer99** [comment]
I can reproduce this with 0.7.0 on Debian Stretch.

A workaround is to enable the GDAL DXF import (File->Settings->GDAL/OGR->Select DXF) as that imports it just fine.

**Comment by dg0yt** [comment]
So did the GDAL importer work for you?

**Comment by t-miyakawa** [comment]
> So did the GDAL importer work for you?

Yes.
I can import my sample file.
