### ISSUE TITLE
OCAD-exported file cannot handle Ö(ÄÅ) in path for background

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#1046]
### Steps to reproduce
1. Make map, include background, use folder with ÅÄÖ in the name
2. Export to -ocd
3. Open in OCAD (9)

### Actual behaviour
Background files are not found, due to misprinted letter "ö" in path for background file

### Expected behaviour
At export more kind of letters should be handled correctly in the paths for backgrounds.

### Configuration
Mapper Version: 0.8.0
Operating System: Win 7 Pro
![image](https://user-images.githubusercontent.com/16168975/36076511-50c4c678-0f5d-11e8-8d0c-25d5c373bdf0.png)

**Comment by dg0yt** [comment]
Please check the 8-bit encoding in the settings. It is used when when writing OCD 8 format.

**Comment by dg0yt** [comment]
Any news?

**Comment by Zerbembasqwibo** [comment]
Actually I didn't want to diturb, but I coundn't figure out how I should do
that.

2018-03-09 8:30 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment]
I tried to check 8-code and tested some of the options I thought were
correct, same result in 0.8.0.

UTF-8, and several windows 1250-2-3-4. Same result.

2018-03-10 7:35 GMT+01:00 Sven Lundbäck <sven.lundback@gmail.com>:

**Comment by dg0yt** [comment]
You and me need code page Windows-1252. But instead of properly converting umlauts, Mapper's current OCD exporter (sometimes?) writes literal `?`.
