### ISSUE TITLE
I cannot open this OCAD file

### ISSUE THREAD

**Issue by ondatra646** [OpenOrienteering/mapper#1047]
### Steps to reproduce
1. Try to open this file in OOM (example)

### Actual behaviour
When I try it OOM is not responding

### Expected behaviour
I think that the problem is with symbols and colours. In OCAD I added symbols and colours from other file. (isom2017_ocd10). Then I saved it and tried to open it in OOM.

### Configuration
Mapper Version: 0.8.0
Operating System: Windows 8.1
OCAD 10

[Nová složka.zip](https://github.com/OpenOrienteering/mapper/files/1716838/Nova.slozka.zip)

**Comment by dg0yt** [comment]
The issue centers around area symbols with explicit border symbols, such as 301.x "Uncrossable Body of Water".

 - In the isom2017_ocd10 file, there is a 301.0 "Uncrossable Body of Water" which declares its border symbol to be 301.2 which is "Bank line" in this file. This is consistent - no problems.

 - In the example.ocd, area symbol 301.2 "Uncrossable Body of Water" declares its border symbol to be 301.2! 
Mapper blindly accepts this cyclic reference, running into a loop later. This is what you finally observe as Mapper not responding (or crashing). 
According to the icon in the free OCAD Viewer, I would expect a black border line, such as 301.1 Bank line. It seems to me that replacing/merging the symbol sets failed to adjust the border symbol numbers. 

I can fix the crash in Mapper and add import warnings. But I see now way how to find out the actual border symbol. When I modify the example file in a binary editor to use 301.2 for the object which is 415.0 at the moment, the OCAD Viewer doesn't draw a border - the symbol is broken anyway.

**Comment by ondatra646** [comment]
OK, thanks for your time.
