### ISSUE TITLE
joint point of linear objects

### ISSUE THREAD

**Issue by biker2s** [OpenOrienteering/mapper#1048]
### Steps to reproduce
1. draw a linear object with brazier curves.
2. close the line with enter
3.

### Actual behaviour
when  I edit that point (start,end - square), it does not pick both circles next to point
It looks like the ocad points...

### Expected behaviour
To have 2 options : a) like ocad (angle on brezier point), b) to behave like a mid point in brezier curve

### Configuration
Mapper Version: 0.8.0   (A true gift!)
Operating System: windows XP , service pack 3, 

![foto 1](https://user-images.githubusercontent.com/36484895/36219596-9671cb16-11c0-11e8-8532-eab14d144778.JPG)

**Comment by dg0yt** [comment]
> when I edit that point (start,end - square), it does not pick both circles next to point
It looks like the ocad points...

The handle at the end of the closed seems to stick to its position when it shouldn't. This is a bug.

> Mapper Version: 0.8.0 (A true gift!)

Oh, thanks!

> Operating System: windows XP , service pack 3,

Probably this will stop working rather sooner than later...
