### ISSUE TITLE
Query ignores key with is not null parameter

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1050]
### Steps to reproduce
1. From OSM data you want to extract all buildings. 
2. Start Query editor in Find objects and build query: building != ""
3.  ==

### Actual behaviour
All polygons (also with different key) are selected.
The same behaviour for: building != "null".

### Expected behaviour
Only buildings are selected. 

### Configuration
Mapper Version: 0.8.0
Operating System: Win x64
[Olomouc.zip](https://github.com/OpenOrienteering/mapper/files/1726996/Olomouc.zip)

**Comment by dg0yt** [comment]
In the first place, this is a [documentation issue](http://www.openorienteering.org/mapper-manual/pages/find_objects.html). The (new) query language section for `key != word` says *'having a tag with the given key and a value different from "word"'* but omits a part from the query editor/comparison section on "is not": *"If the tag doesn't exist, the condition is true."*

What does work at the moment is: `building ~= ""`. This asks for having a `building` tag which contains an empty string.

I'm not sure which change to make: Fix the documentation, or change the behaviour of `building != ""`. In the end, it is probably best to make the language work as you would expect from SQL or similar languages. 
Note that the current behaviour allows you to easily test for all objects which do not have a particulary key-value combination.

**Comment by krticka** [comment]
> What does work at the moment is: building ~= "". This asks for having a building tag which contains an empty string. 

This is not logical for me how it works as value field is not empty. Probably SQL approach is better.
Is it possible to use any wildcards (* or %)?

**Comment by dg0yt** [comment]
Well, any string contains the empty string. Wildcards are not implemented yet.

This is just a simple language on top of what was contributed as "tag selector", enabling features such as the OSM CRT file. For sure, there is much room for improvement.

**Comment by krticka** [comment]
> Well, any string contains the empty string.

Thanks for clarification. This also helped me to understand [https://stackoverflow.com/a/18399216](https://stackoverflow.com/a/18399216)

Than `building ~= "" ` is OK for me and fix of documentation is suitable solution.

**Comment by dg0yt** [comment]
https://github.com/OpenOrienteering/mapper-manual/commit/328a6f7682d9461ca83d0db56a683231fcd95119

Thanks for reporting. More feedback welcome.
