### ISSUE TITLE
Small symbols get tiny icons if there are many large symbols

### ISSUE THREAD

**Issue by akom5224** [OpenOrienteering/mapper#1051]
### Steps to reproduce
Compare appearance (size) of symbols in icons in the symbol set when opening maps with considerably different numbers of symbols in the symbol set. An example of the omap file (zipped) with about 500 symbols in the set to see very clearly the effect is attached:
[tinySymbols.zip](https://github.com/OpenOrienteering/mapper/files/1727103/tinySymbols.zip).

### Actual behaviour
Symbols in icons of the symbol set are very tiny and unreadable. See example:
![symbolstiny](https://user-images.githubusercontent.com/24692842/36250951-b513888c-123f-11e8-9704-a52fa0c70973.jpg)

This behavior started with version 0.8.0. When the same map is opened in OOMapper 0.7.xx, symbols in icons are nicely large. Some testing (gradual extension of the symbol set) shows that size of symbols in icons decreases when new symbols are added to the symbol set. At the same time, size of symbols in the icons do not seem to depend on the size of the icon square (which can be adjusted in 0.8.0). The same behavior was observed on Linux and Windows desktops as well on Android.

### Expected behaviour
Symbol within the icon should always "occupy" given proportion of the icon square, its size should somehow be related to the size of the icon square. Otherwise, it does not make much sense to adjust the size of the icon square.

### Configuration
Mapper Version: 0.8.0
Operating System: Linux Debian, Android, Windows 7

**Comment by dg0yt** [comment]
Thanks for reporting. It is obvious that icon scaling doesn't work for your symbol set. The particular trigger is the big number (360!) of (helper) symbols of app. 10 mm size.

The icon size setting is unrelated to this issue: This is a tool for adjusting to individual preferences, especially on touch screen devices such as mobile phones.

We also don't want to simply scale all symbols to the full icon space: The relative size of the individual symbols is important visual information, especially for size variations of the same shape and color.

Until Mapper v0.7.0 we had a fixed scale factor of app. 2. Symbols which would exceed the icon space were scaled down (like your helper symbols). This approach worked well for some map scales and icon sizes, but not for others: Icons at 1:15000 (ISOM) or 1:20000 (ISMTBOM) were tiny. No matter whether tiny or scaled down, it could be difficult to spot a difference between size variations.

Mapper v0.8.0 studies the actual distribution of symbol sizes. Pivotal factor is the size of the symbol at the 80th percentile. This eliminates the influence of map scale and even of huge outliers such as the OpenOrienteering logo. In addition, Mapper also takes into account the symbol size at the 20th percentile if this symbol would not reach 10% size at the initial guess.

https://github.com/OpenOrienteering/mapper/blob/cdd48c35ffe890e96c2624e6c5f9b04972f1695b/src/core/map.cpp#L1975-L2002

Now look back at your particalar symbol set: More than half of the symbols are 10 mm, so this is what we get at the 80th percentile. The scale at the 20th percentile doesn't help that much, it is more close to the value which we normally get for the 80th percentile.

So how can deal with this?
- We could ignore symbols which exceed a certain size (map setting? program setting?)
- We could ignore symbols which are marked helper symbols.
- We could use a fixed reference zoom (map setting).
- We could use a more complex scaling function.

**Comment by akom5224** [comment]
Thanks for clarification. In my view, I would not look for a more complex scaling function as it is probably never possible to make it such that it fits reasonably well to all possible situations. My preference would be that by default it does what it does now (attempt to find a reasonable scaling factor which probably works well in most situations) but allow user to switch this off (probably better in the map setting) and to choose his own fixed reference zoom. Nevertheless, remaining two suggestions (ignore symbols which exceed a certain size or ignore symbols which are marked as helper symbols) look also fine. If symbols which exceed a certain size are to be ignored then I would put this option into the program setting.

**Comment by dg0yt** [comment]
> - We could ignore symbols which are marked helper symbols.

This is what I get when implementing my 2nd proposal, after marking all "Azimuth ..." symbols as being helper symbols:

![scaling-helper-symbols](https://user-images.githubusercontent.com/13567791/36582693-b67303d6-1872-11e8-8793-d0c57b9848c1.png)

Doesn't work that bad? Note that instead of editing 360 individual symbols, I used a text editor, replacing `name="Azimuth "`by `is_helper_symbol="true" name="Azimuth`.

And its only two trivial lines of code.

**Comment by akom5224** [comment]
Thanks, this look perfect!
