### ISSUE TITLE
Issue with importing dxf

### ISSUE THREAD

**Issue by kfjellerup** [OpenOrienteering/mapper#1054]
### Steps to reproduce
1. Choose "Import"  
2. Choose .dxf file
3. OOM crashes and shuts down

### Actual behaviour
When i try to import a dxf file the software crashes and shuts down. I have in a previous version of OOM been able to import the dxf file to my map. Have also tried creating a new map file and importing with no effect.

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: 0.8.0
Operating System: Windows 10
[FOT2007.zip](https://github.com/OpenOrienteering/mapper/files/1744162/FOT2007.zip)

**Comment by dg0yt** [comment]
The file (or OGR) declares "pen" style for a point geometry. We used to handle "symbol" and "label" style here, and use "pen" for line geometries. But it is not an excuse for crashing. Will use the default point symbol, and color it according the pen.

**Comment by dg0yt** [comment]
New master builds (Windows, Linux) are triggered.
