### ISSUE TITLE
Previous GPX track may be lost

### ISSUE THREAD

**Issue by ogeo-project** [OpenOrienteering/mapper#1055]
### Steps to reproduce
1.
2.
3.

### Actual behaviour
During mapping with GPS trace record activated, the battery stops (power 0%). When I restart with new power bank. Mapper file restart with automated backup, and only objects add during last backup was lose.
At home, when I load mapper file all is right except the GPX file :  containing only trace after power crash.
Usually this problem not occur during mapping when I stop/start application.

### Expected behaviour
GPX should be backup with sync with mapper file.

### Configuration
Mapper Version: 0.8.0 for android ARM
Operating System: Android 4.4.2 (Lenovo A3500FL)

**Comment by dg0yt** [comment]
Bug: The previous track gets lost when 
- GPX tracks are loaded with GDAL/OGR (now default setting), and
- the map is closed and reopened, and
- recording is started again on the same day the previous recording was started.

Workaround: Uncheck GPX in Settings > GDAL/OGR.

Broken in MapEditorController::enableGPSDisplay.
