### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by dfgeorge** [OpenOrienteering/mapper#1056]
### Steps to reproduce
Editing a small map (just tracing a logo). App got slow then crashed:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Mapper.exe
  Application Version:	0.8.0.0
  Application Timestamp:	babababa
  Fault Module Name:	libstdc++-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	babababa
  Exception Code:	c0000005
  Exception Offset:	000d8130
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3081
  Additional Information 1:	86a2
  Additional Information 2:	86a2174608f8b0f866a60c741ff0eae7
  Additional Information 3:	50a9
  Additional Information 4:	50a96d45c27bf8296e01925cc09731f0

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: 0.8.0
Operating System: Windows 7 x86

**Comment by dg0yt** [comment]
You need to provide more information: template type. Tool used when the crash occured.

**Comment by krticka** [comment]
I can reproduce problem during editing of points (Ctrl+Fast clicking on points to remove them) when you accidentally click on different object. See screenshot (I was editing cultivated land and accidentally clicked on contour).
![clipboard02](https://user-images.githubusercontent.com/15969434/36540028-132ac4a0-17d9-11e8-8686-dc1a5142bdeb.jpg)

**Comment by dfgeorge** [comment]
Template was a JPG file. I was using an area fill, yellow, when it crashed.

**Comment by dg0yt** [comment]
I was not yet able to reproduce this.

@dfgeorge By "using an area fill", did you mean you were using the fill tool (Tools > Fill / Create border), or did you simply refer to an area object you were editing?

@krticka Did you also the x86 version? The screenshot indicates there were at least two object selected when it crashed: The cultivated land and the contour. But I also see the start point (bigger square) and the end point (cross) of a line object which neither seem to belong to the cultivated land (closed path anyway) nor to this particular contour (start point not located on the contour).

**Comment by dfgeorge** [comment]
I was using an area object. It was a modified copy of open land. It had a white dot screen in it. I had used it several times before the crash with no problem.

**Comment by dg0yt** [comment]
I still found no way to trigger this issue. Even a special build in [libstdc++ debug mode](https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html) didn't hit any bugs.

@krticka Did you also the x86 version? With Ctrl+click I'm unable to select another object, but your screenshot shows multiple objects being selected. The crash might be related to that, and it is an area of code which was probably modified between v0.7 and v0.8.

**Comment by krticka** [comment]
@dg0yt no, just x64. I tried to reproduce it again and I was succesfull approximately in 1 of 10 attempts. Always it was connected with very very fast mouse clicking on points, but I am not able to specify causes of crash more clearly.

**Comment by dl3sdo** [comment]
I was just able to also crash mapper (0.8.0, x64), by very fast clicking on objects for some time, mostly deleting them by keeping Ctrl pressed.

**Comment by dg0yt** [comment]
I wasn't able to reproduce this yet. Maybe I need a slower PC? I guess there is a race in the process of switching between tool states quickly.

**Comment by dl3sdo** [comment]
The crash happened for an i7-4790K, 16GB RAM....not the slowest PC ;-)
Something with undo history maybe?

**Comment by dg0yt** [comment]
![stacktrace](https://user-images.githubusercontent.com/13567791/37238613-7b14ed54-242a-11e8-836e-22e92b733cc4.png)

**Comment by dg0yt** [comment]
![stacktrace-2](https://user-images.githubusercontent.com/13567791/37239262-aab0dc4a-2438-11e8-9e54-9626f78166ee.png)

**Comment by dg0yt** [comment]
This is for @dl3sdo :smile: 

https://github.com/OpenOrienteering/mapper/blob/59d4e2224819f5c6675951bda09a87c2bf73b4bb/src/tools/tool_base.cpp#L651-L689
