### ISSUE TITLE
GeoreferencingTest fails twice (testGridScaleFactor & testCRS(EPSG:4326))

### ISSUE THREAD

**Issue by realnickel** [OpenOrienteering/mapper#1062]
### Steps to reproduce
1. Run tests

### Actual behaviour

********* Start testing of GeoreferencingTest *********
Config: Using QtTest library 5.9.4, Qt 5.9.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.3.1 20170118 (ALT 6.3.1-alt2))
PASS   : GeoreferencingTest::initTestCase()
PASS   : GeoreferencingTest::testEmptyProjectedCRS()
FAIL!  : GeoreferencingTest::testGridScaleFactor() Compared doubles are not the same (fuzzy compare)
   Actual   (ground_distance_mercator / scale_factor): 0.00015683
   Expected (ground_distance_utm)                    : 1000
   Loc: [/usr/src/RPM/BUILD/openorienteering-mapping-0.8.0/test/georeferencing_t.cpp(114)]
FAIL!  : GeoreferencingTest::testCRS(EPSG:4326) 'georef.setProjectedCRS(id, spec)' returned FALSE. (no system list, errno: 2
)
   Loc: [/usr/src/RPM/BUILD/openorienteering-mapping-0.8.0/test/georeferencing_t.cpp(141)]
PASS   : GeoreferencingTest::testCRS(UTM)
PASS   : GeoreferencingTest::testCRSTemplates()
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Koblenz UTM)
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Koblenz GK3)
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Pruem UTM)
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Pruem GK2)
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Landau UTM)
PASS   : GeoreferencingTest::testProjection(LVermGeo RLP Landau GK3)
PASS   : GeoreferencingTest::testProjection(EPSG 5514 ČÚZK Dolní Temenice)
PASS   : GeoreferencingTest::cleanupTestCase()
Totals: 12 passed, 2 failed, 0 skipped, 0 blacklisted, 1ms

********* Finished testing of GeoreferencingTest *********

### Expected behaviour
Test should pass

### Configuration
Mapper Version: 0.8.0
Operating System: ALTLinux (Sisyphus)

**Comment by dg0yt** [comment]
`no system list`: Maybe you miss the EPSG data of the proj library? It is `/usr/share/proj/epsg` on Ubuntu.

**Comment by dg0yt** [comment]
`testGridScaleFactor` relies on EPSG data, too.

**Comment by realnickel** [comment]
You're totally right! EPSG data is provided with a separate package libproj-nad in ALTLinux.
Adding the data makes all tests to PASS.
Thank you.
PS: Isn't it worth adding a check for presence of vital data before running tests?

**Comment by dg0yt** [comment]
> PS: Isn't it worth adding a check for presence of vital data before running tests?

We make no assumptions about data. We test behaviors which are expected to succeed in a proper environment. The only thing we could do is check upfront whether using a common EPSG number succeeds, and ask the user to check for data when it fails. That's little more than what you already got: `no system list`.
