### ISSUE TITLE
Android touch cursor not working

### ISSUE THREAD

**Issue by valentin5007** [OpenOrienteering/mapper#1063]
### Steps to reproduce
1.
2.
3.

### Actual behaviour
The touch cursor can't be used since the 0.8 version

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: OpenOrienteering-Mapper-0.8.0-Android-armeabi-v7a.apk
Operating System: Android on différents smartphone.

**Comment by dg0yt** [comment]
Confirmed. I can't remember that I touched this feature...

**Comment by dg0yt** [comment]
Wrong initalization of `MapEditorTool::uses_touch_cursor` since c97ebf4.
