### ISSUE TITLE
ESRI Shapefiles Export

### ISSUE THREAD

**Issue by mpickering** [OpenOrienteering/mapper#1066]
The standard vector file format for QGIS is the ESRI Shapefile. It would be a useful feature to be able
to export a map in this format.

It is possible to write ESRI files with GDAL. 

http://www.gdal.org/drv_shapefile.html

There is also an example of how to create the shape file using the library.

http://www.gdal.org/ogr_apitut.html

Specifically, I think that it would be simplest to export one layer for each symbol type. 

The use cases for this are interesting visualisation examples. For example, taking an urban map, underlying a DEM and giving the buildings some height would create an interesting visualisation experience. 

I haven't investigated how exactly the map information is stored but this seems plausible to implement.

**Comment by dg0yt** [comment]
Effectively, this is general geospatial vector data export via GDAL/OGR. It is the same interface for Shapefile, DXF etc.
