### ISSUE TITLE
Missing template menu, and missing menu items, on macOS

### ISSUE THREAD

**Issue by ohartvic** [OpenOrienteering/mapper#1067]
### Steps to reproduce
1. install OOM 0.8
2. set appearance "Language: Czech"
3. create new or open existing omap file
4. Template ("Podklady") menu is missing

### Actual behaviour
After opening file the main menu item "Template" or ("Podklady" in czech) is missing.

When Czech language is selected:
![image](https://user-images.githubusercontent.com/19303491/36923344-4b83160c-1e6b-11e8-94c1-9ff4047e2942.png)

In English it is fine:
![image](https://user-images.githubusercontent.com/19303491/36931684-8e17ca94-1ebb-11e8-8fce-28cdad2317f6.png)

### Configuration
Mapper Version: 0.8
Operating System: macOS 10.13

**Comment by dg0yt** [comment]
In addition, I get map georeferencing settings instead of regular settings. 

Maybe it is the automatism for moving some items to the special menu with the apple. It has caused trouble before.

**Comment by dg0yt** [comment]
I found more menu items - and the priority 1 (critical) but closed bug report [QTBUG-30812](https://bugreports.qt.io/browse/QTBUG-30812).

**Comment by dg0yt** [comment]
For your interest:

The Template menu disappears because all menu items start with letter "o" which happens to be the Czech word for "About", and Qt these are About menu item... Hezky Cesky ;-)

https://bugreports.qt.io/browse/QTBUG-30812?focusedCommentId=394707&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-394707

**Comment by ohartvic** [comment]
Just a note:

Funny, is not it. This is IT for you; I keep saying that the end of the IT industry comes when various calendar implementation will become compatible. This is similar to the Qt internationalisation issue. 

Thank you for working on OOMapper, I like it very much!
