### ISSUE TITLE
Weird placement of text object at import

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1069]
### Steps to reproduce
1. open georef. map
2. import another georef. map 

### Actual behaviour
everything looks ok except one text object that is placed somewhere very different

### Configuration
Mapper Version: 0.8.0 (x64)
Operating System: Win7

I'll send test file via email

**Comment by dg0yt** [comment]
Actually both text object get very strange extents...

**Comment by dg0yt** [comment]
.. they just happen to have different text alignment.

**Comment by dg0yt** [comment]
These text objects are using a box, not an anchor. Mapper uses two MapCoord to save the box, but the second MapCoord is just to save the dimension (size), not actual coordinates. This is bound to fail in every transformation that assumes that MapCoord are MapCoord. Grml...

**Comment by dg0yt** [comment]
Todo: scale the box when scaling the data.
