### ISSUE TITLE
Bug: Point symbols loose rounded line cap property on import from OCAD

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1070]
### Steps to reproduce
1. Import an OCAD file with point symbols containing lines with "line cap:rounded"
![image](https://user-images.githubusercontent.com/15611653/37177418-ab94a08e-231f-11e8-8496-e297acdb9428.png)
fig.1. screenshot OCAD

### Actual behaviour
The "line cap" property is switched to "flat".
![image](https://user-images.githubusercontent.com/15611653/37177495-e3cf654c-231f-11e8-8a3f-6d44ab284ed2.png)
fig.2. screenshot mapper

### Expected behaviour
Should stay "rounded"

### Configuration
Mapper Version: 0.8.0
Operating System: windows 7

**Comment by Zerbembasqwibo** [comment]
I think I noticed that end and corner is mixed up somewhere?
