### ISSUE TITLE
Correction of the magnetic indicator direction to the North  (Mobile version)

### ISSUE THREAD

**Issue by Dostapo** [OpenOrienteering/mapper#1073]
I'd like to add to mobile version app ability, which allows to set correction of the direction to the North of magnetic indicator on map interface.
I think, magnetic sensor in gadget automatic add a magnetic declination for the result value. (I test this in several apps on my device). As a result, I see that the direction to the North on real magnetic compass and indicator in app are diffrent, in despite of set the correct value of the declination in a map georeferencing (Map\Georeferencing\Map north\Declination).
I offer add ability of setting of the angle correction in app options (or map options). Generally, value of angle correction may be positive or negative.

**Comment by ollesmaps** [comment]
Do you trust compass inside tablet/phone (besides the mn issue)? I do not use it much, however it might be a good tool.

**Comment by Dostapo** [comment]
On the my device (Xiaomi Mi Max) magnetic sensor is good (that was such a surprise for me).
When I work in the field/forest, often there is a need true map orientation with North, because I draw some objects "by eye" (in the end of the day, when I feel huge tiredness, lazily floating from one mound to another :) ).

**Comment by dg0yt** [comment]
Some users seem to consider this a bug in the firmware, as it affects other apps, too: http://en.miui.com/thread-318457-1-1.html
OTOH it might be an issue with calibration: http://c.mi.com/in/thread-14819-1-0.html

**Comment by Dostapo** [comment]
I'm tested my device, other device and conclude: problem in my "Xiaomi Mi Max".
It stably distorts by 10-12 degrees real direction to the North :(
I'm sad.
