### ISSUE TITLE
Building from source fails to find GDAL in non-standard location

### ISSUE THREAD

**Issue by mpickering** [OpenOrienteering/mapper#1079]
I am trying to package mapper for Nix. Nix works differently to most package managers, libraries
are not installed globally so you have specify the right paths, hard coded paths aren't going to work.

Specifically on OS X, the location of GDAL is found incorrectly, 

```
-- Found GDAL: /Library/Frameworks/gdal.framework 
```

This is the default system location. 

It should be 

```
Found GDAL: /nix/store/gz63s143cj7d7ss6f0qv19nnixa4kc7i-gdal-2.2.3/lib/libgdal.dylib (2.2.3)`
```

I don't understand where CMAKE gets this path from but it is wrong. Especially as I am also passing `-DCMAKE_FIND_FRAMEWORK=never` to cmake. 

I fixed this by copying the `FindGDAL.cmake` file from `QGIS`. Please can you consider adding a `FindGDAL.cmake` file to mapper?

**Comment by dg0yt** [comment]
IMO there is no point in adding `FindGDAL.cmake`, as the one which comes with CMake should be fine. If the documentation isn't enought, look at the head of the file: You can set the environment variables `GDAL_DIR` or `GDAL_ROOT` to point to the desired root (from where it will try to find `include.../gdal.h`).

Remember that you will have to clear the cached locations when running CMake again, i.e. pass `-UGDAL*`.

**Comment by mpickering** [comment]
I tried specifying `GDAL_DIR`, `GDAL_ROOT` and `GDAL_ROOT_DIR` and all the options are ignored and the wrong path is selected. Cmake warns they are not used.

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    GDAL_DIR
    GDAL_ROOT
    GDAL_ROOT_DIR
```

**Comment by dg0yt** [comment]
This look like you are setting CMake variables, not environment variables. And they will remain in cache until you remove them. To clean up, run in your build directory:

~~~
GDAL_ROOT=/nix/store/gz63s143cj7d7ss6f0qv19nnixa4kc7i-gdal-2.2.3 cmake . -UGDAL* -UCMAKE_INSTALL_INCLUDEDIR -UCMAKE_INSTALL_LIBDIR
~~~

**Comment by mpickering** [comment]
I set `GDAL_ROOT` and `GDAL_DIR` appropriately as an env var and it still finds the wrong version.

There is no cache, each build happens in a fresh sandboxed environment. If I enter the build environment then I confirm that `GDAL_ROOT` is definitely set.

```
echo $GDAL_ROOT
/nix/store/gz63s143cj7d7ss6f0qv19nnixa4kc7i-gdal-2.2.3
```

**Comment by dg0yt** [comment]
Again, check the head of `FindGDAL.cmake` which comes with CMake (assuming this is the one loaded).  
The next option is to pass `-DGDAL_CONFIG=/nix/store/gz63s143cj7d7ss6f0qv19nnixa4kc7i-gdal-2.2.3/bin/gdal-config`, i.e. the path to the program which will print the GDAL paths.

Try yourself:
~~~
/nix/store/gz63s143cj7d7ss6f0qv19nnixa4kc7i-gdal-2.2.3/bin/gdal-config --prefix
~~~

**Comment by mpickering** [comment]
Thanks @dg0yt 

I didn't realise that cmake bundled a lot of modules in the installation. It looks like the `FindGDAL` bundled with my version of cmake hard codes these paths in... 

```
find_path(GDAL_INCLUDE_DIR gdal.h                                                  
  HINTS                                                                            
    ENV GDAL_DIR                                                                   
    ENV GDAL_ROOT                                                                  
  PATH_SUFFIXES                                                                    
     include/gdal                                                                  
     include/GDAL                                                                  
     include                                                                       
  PATHS                                                                            
      ~/Library/Frameworks/gdal.framework/Headers                                  
      /Library/Frameworks/gdal.framework/Headers                                   
      /sw # Fink                                                                   
      /var/empty/local # DarwinPorts                                               
      /var/empty/csw # Blastwave                                                   
      /var/empty                                                                   
)                 
```

**Comment by dg0yt** [comment]
All right. You see the `HINTS` directing CMake to look into the environment variables `GDAL_DIR` or `GDAL_ROOT`. And of course you can set `GDAL_INCLUDE_DIR` directly. 
(It took me long to learn how to use CMake properly, and CMake improved a lot in the mean time. Hope that GDAL soon provides a `config.cmake`, making these find-modules obsolete.)

**Comment by mpickering** [comment]
It looks like it has been rewritten quite a lot since cmake 3.10.2. https://github.com/Kitware/CMake/blob/master/Modules/FindGDAL.cmake

**Comment by dg0yt** [comment]
It is still old style: It doesn't provide an "imported target".

**Comment by mpickering** [comment]
I set the cmake variables `-DGDAL_INCLUDE_DIR`, `-DGDAL_CONFIG` and `-DGDAL_LIBRARY` appropriately and it now works.
