### ISSUE TITLE
Save/SaveAs crashes on MacOS

### ISSUE THREAD

**Issue by ohartvic** [OpenOrienteering/mapper#1084]
### Steps to reproduce
1. Open map file (attached)
2. Try to Save or Save As the  opened file
3. Mapper freezes and as you try to resize or minimise its window it crashes (crash report attached).

### Actual behaviour
See steps to reproduce. 
[Mapper-CrashReport.txt](https://github.com/OpenOrienteering/mapper/files/1860683/Mapper-CrashReport.txt)
[Predni_Pecky_WIP.omap.zip](https://github.com/OpenOrienteering/mapper/files/1860689/Predni_Pecky_WIP.omap.zip)

The file I was opening was located on a Google Drive (locally saved, synchronised copy).

### Expected behaviour
File would be saved.

### Configuration
Mapper Version: 0.8.1.1
Operating System: MacOS 10.13.3 (17D102)

**Comment by dg0yt** [comment]
Hm, I don't see an immediate crash, but it crashes reproducibly when I try to open the Settings just after "Save as".

**Comment by dg0yt** [comment]
Please test v0.8.1.2.

**Comment by mstahv** [comment]
Tried the latest build, can't reproduce the issue I still had with 0.8.1.1 (#1077).

Thanks!

**Comment by ohartvic** [comment]
Also working for me now.

**Comment by dg0yt** [comment]
Thanks!
