### ISSUE TITLE
Point symbol doesn't retain Registration Black color

### ISSUE THREAD

**Issue by xc-racer99** [OpenOrienteering/mapper#1086]
### Steps to reproduce
1. Create a new point symbol
2. Set the inside color to Registration Black
3. Save and close the file
4. Re-open the file

### Actual behaviour
The point symbol has no color.

### Expected behaviour
The point symbol has the inside color of Registration Black.

By examining the XML, the color appears to be saved correctly, but isn't restored properly, I believe due to https://github.com/OpenOrienteering/mapper/blob/master/src/core/symbols/point_symbol.cpp#L666 as registration black has color code -900 Line and Area symbols appear unaffected.

### Configuration
Mapper Version: 0.8.1
Operating System: Debian 9 (Stretch)

**Comment by dg0yt** [comment]
Indeed. The PointSymbol's dot and ring seem to be the only spots which don't handle registration black in the XML file format.
