### ISSUE TITLE
Cannot open files on Android

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#1087]
I will put more info, if I can, but maybe some one else also noticed? It now happened on two devices, what I see is that without georeferencing it opens. How could it be connected? Seems like older files, prepared in older versions on PC, still open.

OOM says it cannot read the file. 

I change to `+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`, than opens without problems. (But GPS-pont ends up wrong)

### Steps to reproduce
1. Prepare georeferenced map in 0.8.1 on PC, choose UTM 33N
2. Transfer to Android
3. Try to open

### Actual behaviour
File cannot be read

### Expected behaviour
Map should open

### Configuration
Mapper Version: 0.8.1
Operating System: Android/PC

**Comment by dg0yt** [comment]
I'm not aware of any changes since v0.8.0 which might explain such a change in behavior. Attaching a smaller zipped map, even empty, to the issue, would be helpful.

**Comment by dg0yt** [comment]
I cannot reproduce this issue at 50N 15E. An empty map opens on Mapper 0.8.1 (Android) with UTM 33 N as well as with `+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`.

**Comment by Zerbembasqwibo** [comment]
Try open this file, at least I cannot open it on Android but on pc. Have
not examined the file.


fredag 13 april 2018 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
I guess there was an attachment to the e-mail, but it is dropped by Github. Send me a direct e-mail, or add the attachment in the issue's web page

**Comment by Zerbembasqwibo** [comment]
Trying again.
[files.zip](https://github.com/OpenOrienteering/mapper/files/1906196/files.zip)

**Comment by dg0yt** [comment]
The file is truncated in the objects section. The issues is unrelated to the georeferencing. Probably it was corrupted during transfer to the device.
