### ISSUE TITLE
Intermittent trail symbol fails sometimes in map file conversion from OCAD 9

### ISSUE THREAD

**Issue by bellis89** [OpenOrienteering/mapper#1092]
### Steps to reproduce
1.Open an existing OCAD map file in OOM 
2.
3.

### Actual behaviour
Some small intermittent trails appear as a continuous black line in the OOM map. They have the correct line width but lack the appropriate gaps. Switching symbols back and forth (e.g. between 'small intermittent trail' and 'small trail' does not help. 
I have no idea why this only happens sporadically; i.e. some trails come through the conversion OK. On the other hand, if a trail fails to convert properly, it does so consistently, so it seems that there is something problematic in the way it was drawn in the original OCAD version. Has anyone else run into this problem?

### Expected behaviour
The conversion should be correct and consistent

### Configuration
Mapper Version: 0.7.0
Operating System: Windows 10

**Comment by bellis89** [comment]
The problem might be that the person who prepared the original OCAD basemap had created/used a symbol set in which two different versions of the 'small footpath' symbol were being used (507.0 and 507.2), and the 507.2 symbol might have been duplicated and edited to create the 'less distinct small footpath' symbol (508.0). It is the 508.0 symbol that fails to appear as an intermittent dashed line in the OOM map file, even though the symbol description in the Symbols Table seems to be correct. Puzzling...

**Comment by dg0yt** [comment]
I think what you describe is already known as #251: Short dashed line objects shown as continuous line.

**Comment by bellis89** [comment]
Thanks, Kai – I had looked back through the posts but didn’t go back as far as 2013 (which was well before I started using OOM ;-) I resume it is still not resolved?
Brian

**Comment by dg0yt** [comment]
No, it is unresolved. It is not just a conversion error: It is different implementation how to deal with line objects which are too short to be dashed properly.

**Comment by bellis89** [comment]
OK – no problem, Kai. The mystery is cleared up and I now know how I will deal with it.
Many thanks again for this great project!
Brian

Brian Ellis, President
Orienteering BC
[logo_small]
