### ISSUE TITLE
Measure tool hard to close on small screens

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1093]
On phone (5,7 inches) you can not close measurement box by clicking again on the command because the box hides it (...). And you have to point and miss on the little cross.

### Expected behaviour
The box can appear somewhere else, where it is not obstructed.
Or the measurement icon can be moved to other place (not right corner).

**Comment by lpechacek** [comment]
FWIW, on my tablet the box can be grabbed at the top bar and moved elsewhere so that it no longer obstructs the icon. Yet, measurement box covering the icon is indeed an annoyance.

**Comment by ollesmaps** [comment]
@lpechacek I did not know that. Thank you for the trick. I passed it on to my colleague with the 5,7 screen. It works fine and as measuring is not a frequent operation, it is good as it is.
