### ISSUE TITLE
Measure angle

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1095]
### Steps to reproduce
Is there a way to measure angles?
Good to have when comparing declination in terrain with calculated one. And of course there can be myriad other reasons.

### Expected behaviour
I suggest to measure angle within the Measure tool.  Appliable only for lines.

**Comment by otoomet** [comment]
I'd like to have measuring tool that a) tells the compass bearings of the lines; and b) adds helper lines to the map (without creating a bogus object length of which one measures).  

I am not sure what is your usage case, I was once using pace-counting and compass to locate one object by approaching it from three different directions.  Would be nice to be able to draw these different approaches as helper lines in correct length and correct bearing, and afterwards get these automatically removed by re-clicking the measure tool or like that.

**Comment by mlerjen** [comment]
Isn't this issue solved by #985?

**Comment by ollesmaps** [comment]
You are right. That is solved. Thanks for pointing out.
