### ISSUE TITLE
Add template, draft template name (scribbling in app)

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1104]
I suggest to have the option "Add template" at the bottom of the scriblling templates list. That would limit chance of adding template by accident.

I suggest to name the newly added scribbling template by name of the .omap file, either instead of Draft or before Draft . I know this was talked about before, I have not had an opinion on that previously, now I have. 
I can have as much as ten projects on my tablet and it is hard to sort out which Draft belongs to which project.

**Comment by mlerjen** [comment]
![2018-06-08-23-22-09](https://user-images.githubusercontent.com/15611653/41181703-06a4afaa-6b73-11e8-81c8-9150acb09a84.png)
I keep my map projects in different folders, so roject name might be redunant (in my case).  But  I agree with Aleš, that the naming convention can be improved. The project I worked on today is up to 12! scribble layers, four of the I switch in between at this stage. With the actual nameing it is not easy to identfiy a layer.  In my case something like draft_xxx_projectname would make it easier.

**Comment by ollesmaps** [comment]
I use folders now as @mlerjen suggested. So I do not deem this necessary any more.
