### ISSUE TITLE
Trash bin icon appears in unexpected place.

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1105]
### Steps to reproduce
1. Add any template
2. Save the map and close Mapper
3. Move/rename the template file
4. Open map file and look in to Template setup window.

### Actual behaviour
![selection_260](https://user-images.githubusercontent.com/10380431/41299974-5200c734-6e6d-11e8-9572-7643b8c91969.png)

### Expected behaviour
I like new icon, but it is suitable only for show remove/delete action. Red cross is more universal and can be used to mark removed/renamed template. I expect to see the red cross or other suitable icon in the Template setup window.

### Configuration
Mapper Version: starting from cd48423c49f9005fd1b0440bfaedcc1246607c65
Operating System: All platforms

**Comment by Zerbembasqwibo** [comment]
Red cross is fine, maybe not 100% logical since red cross in the app means delete.

**Comment by dg0yt** [comment]
I replaced the red cross (for *delete*) with the trash bin, but there is still the dark cross (for *close*): https://github.com/OpenOrienteering/mapper/blob/master/images/close.png

**Comment by lpechacek** [comment]
How about a [dead smiley face](https://www.google.com/search?q=dead+smiley+face)? We don't have to be always serious, do we?

**Comment by Zerbembasqwibo** [comment]
I don't know how to do pull requests.

2018-06-19 10:24 GMT+02:00 Libor Pecháček <notifications@github.com>:

**Comment by lpechacek** [comment]
I didn't know either until I learned it. There is [fine documentation on that](https://help.github.com/categories/collaborating-with-issues-and-pull-requests/).

**Comment by dg0yt** [comment]
Note that we can't accept artwork without knowing original copyright.

Alternatively, this is a plain composition of icons we already use:
![a](https://user-images.githubusercontent.com/13567791/41760038-d15675f2-75f1-11e8-9764-1a70b02c555c.png)

**Comment by mlerjen** [comment]
How about a simple question mark? A missing template requires resolving action by the user. (to re-establish the linking).

**Comment by dg0yt** [comment]
Looking at the icon naming specification again (#1085), it seems that we need either the `emblem-unreadable` or the `image-missing` icon. Cf. https://commons.wikimedia.org/wiki/Comparison_of_icon_sets

**Comment by lpechacek** [comment]
@dg0yt, working on this one?

**Comment by dg0yt** [comment]
Not at the moment. What I would do is trying to make the dark cross available under an `image-missing` alias.

**Comment by ollesmaps** [comment]
The dustbin icon works perfectly. Thank you!
