### ISSUE TITLE
"Start symbol" & "End symbol" always combined with "Mid symbol"

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1111]
### Steps to reproduce

1. Run *OpenOrienteering Mapper*;
2. Create new symbol set;
3. Create new "Line" symbol;
4. Set only "Mid symbol" (left "Start symbol" & "End symbol" color blank) in this "Line" symbol settings.

### Actual behavior

When only "Mid symbol" defined both "Start symbol" & "End symbol" use it's settings.

![img 1](http://i.imgur.com/NfaL4kO.png)

![img 2](http://i.imgur.com/CNzLyoT.png)

In same time we has option for "Suppress the dash symbol at line start and line end", but it only suppress "Dash symbol" (if set) and not suppress "Mid symbol".

![img 3](http://i.imgur.com/nuIXsI8.png)

If try define "Start symbol" (for rewrite automatic "Mid symbol" settings applying) it still combined with "Mid symbol"

![img 4](http://i.imgur.com/cbtoKvq.png)

### Expected behavior

Add option that will give possibility for creating lines with defined "Mid symbol", but in same time with suppressed "Start symbol" & "End symbol".

### Configuration

Mapper Version: `0.8.x`, `0.9.x`
Operating System: Debian 9.x "Stretch" (Linux) , x86_64 (64bit)

**Comment by dg0yt** [comment]
You need to specify the "Distance from line end" value. It is zero in your screenshot, but non-zero e.g. for ISOM2017 105 Earth wall.

(This distance applies to both "line ends" at the moment.)
