### ISSUE TITLE
New colour added, but not displaying in new symbol.

### ISSUE THREAD

**Issue by ardfman** [OpenOrienteering/mapper#1112]
### Steps to reproduce
1. create new colour e.g. navy rgb #00007f
2. new colour shows correctly in colour window
3. create new symbol, set Area settings/ Area colour = Navy

### Actual behaviour
no colour sample showing next to symbol number in symbol settings dialogue window,
  even though colour navy has been selected.
new symbol in  symbol window shows no colour fill,  just showing blank

### Expected behaviour
reverse of above

### Configuration
Mapper Version: 0.6.2
Operating System: Windows 7 32bit

**Comment by Zerbembasqwibo** [comment]
Try first to use newer version, it's already 0.8.1 as lastest stable version.
https://github.com/OpenOrienteering/mapper/releases/tag/v0.8.1

**Comment by ardfman** [comment]
Worked in 0.8.1 but only after deleting existing colour definition and symbol. Thanks

**Comment by dg0yt** [comment]
Don't forget to define the spot color composition of new colors, or it will have to be ignored for the map and for the symbol icon in overprinting simulation mode.
