### ISSUE TITLE
TransformTest failing on oS TW and Rawhide

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1116]
```
[  330s] 16: FAIL!  : TransformTest::testEstimateSimilarityTransformation() Compared values are not the same
[  330s] 16:    Actual   (QPointF(passpoints[0].calculated_coords)): QPointF(1.95943e-15,-32)
[  330s] 16:    Expected (QPointF(passpoints[0].dest_coords))      : QPointF(0,-32)
[  330s] 16:    Loc: [/home/abuild/rpmbuild/BUILD/openorienteering-mapper-master-0.8.20180416/test/transform_t.cpp(368)]
```

Guess this has something to do with GCC 8. I'll look into it.

**Comment by dg0yt** [comment]
Nope, it is a Qt 5.11.1 bug. You can prepare a change to disable that test for 5.11.1.

More references:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903237
https://codereview.qt-project.org/#/c/227223/
https://bugreports.qt.io/browse/QTBUG-69368
https://codereview.qt-project.org/#/c/227223/

**Comment by lpechacek** [comment]
Thanks for the pointers.

It is, however, difficult to understand what you mean with "_disabling that test for 5.11.1._" Is it switching off the whole `transform_t` on (c)makefile level, `testEstimateSimilarityTransformation` part of `transform_t` or the failing part of `testEstimateSimilarityTransformation`?

**Comment by dg0yt** [comment]
I didn't want to be more detailed. Either solution is okay if it is limited to Qt 5.11.1. Disabling the failing part (or better adding an expected failure, `QEXPECT_FAIL`) is the most specific solution, making it easy to understand what was disabled and why.
