### ISSUE TITLE
New OCD export broken

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1123]
### Steps to reproduce
1. Save map project into new OCD format (version 8 to 12)
2. Program crashes
3. 

### Actual behaviour
After save program crashes. New files have 0 kB size. File extension is six-digit random string

### Expected behaviour
Save properly to new OCD format.

### Configuration
Mapper Version: 0.9.20180813
Operating System: Windows 10 Enterprise

![clipboard01](https://user-images.githubusercontent.com/15969434/44164568-b1b1fa00-a0c6-11e8-9c06-e83585ef02e8.jpg)

**Comment by dg0yt** [comment]
- The file with the six-digit random string extension is a temporary file. It will be renamed to the target file name only after writing the file was successful. The crash happens before everything is saved.
- I cannot reproduce the crash here (Linux or Windows 7, "complete map.omap" example file, saved as OCD 11).

Please test with the "complete map.omap" example file, saving as OCD 11. If this works, I will need to look at your map file.

**Comment by krticka** [comment]
I can confirm that saving "complete map.omap" works OK. I will send you my map file for analysis. Thank you.

**Comment by dg0yt** [comment]
Crash confirmed with provided test file, now on Linux.

**Comment by dg0yt** [comment]
New packages are coming (unstable version 0.9.20180815-501 or higher). Thanks for reporting.
