### ISSUE TITLE
Support line symbol distance from start/end

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1125]
### Steps to reproduce
1. Import symbols that have round caps. As for example cliffs.
2. In case the round cap have in Ocad defined distance from start/ end - this distance does not get transferred.
3. This is problem especially by cliffs as minimum sizes, distances are effected

![rounded_caps](https://user-images.githubusercontent.com/20535899/44307716-a5b88780-a3a7-11e8-9c91-e95228ffd8cb.jpg)

### Expected behaviour
1. I suggest to have the round cap length adjustable also in Mapper.
2. I realize the double definition in Ocad - distance from start and also from end - is a problem. Perhaps if both are same it get transferred?

### Configuration
Mapper Version: 0.8.0
Windows 8

**Comment by ollesmaps** [comment]
Is it really implemented? At 0.8.4 I can not mak it work.
The cap length for round cap is unadjustable.
![caplength](https://user-images.githubusercontent.com/20535899/59252115-a159a580-8c2b-11e9-97c4-3ea6b8f3f384.jpg)

**Comment by dg0yt** [comment]
This issue is marked "Milestone v0.9.0". So this is not implemented in v0.8.4.

**Comment by ollesmaps** [comment]
Thank you for clarification. I will try to read better.

**Comment by ollesmaps** [comment]
As an interim solution. There is the option to use a point symbol at the end.
![hedge2](https://user-images.githubusercontent.com/20535899/59267047-7b42fe00-8c49-11e9-995f-77eb1a39b574.jpg)
OOM file: [hedge_roundedcap.zip](https://github.com/OpenOrienteering/mapper/files/3276163/hedge_roundedcap.zip)
