### ISSUE TITLE
Crash in GDAL/OGR Settings Window

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1127]
### Steps to reproduce
1. Start Mapper and go to "Settings"
2. Choose GDAL/OGR tab
3. In Configuration table, delete a parameter, i.e. the line is removed
4. Press Reset button => crash

### Actual behaviour
Mapper crashes when pressing the Reset button after having deleted a parameter setting in GDAL/OGR tab

### Configuration
Mapper Version: OpenOrienteering Mapper unstable 0.9.20180815
Operating System: Win7x64

**Comment by dg0yt** [comment]
Reprocible in unstable and v0.8.2
