### ISSUE TITLE
Android app improvement - 'commonly used symbols' selection box 

### ISSUE THREAD

**Issue by croxford** [OpenOrienteering/mapper#1137]
I've been using the mapper app on a Samsung Galaxy tablet and love it.  But I have a functionality suggestion which would speed up fieldwork for me.  It would be nice to have a 'commonly used symbols' selection box at the bottom of the main window.  It would be a bit like in minecraft where I could select say 10 symbols to be able to be clicked on without switching to the symbols selection screen.  It would speed up mapping in a detailed area.  Just a thought.  Cheers and keep up the brilliant work!

**Comment by ollesmaps** [comment]
I agree! 
This has been already suggested, see #948.

**Comment by dg0yt** [comment]
I suggest that you add :+1: to 948.
