### ISSUE TITLE
Symbol sets translation

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#114]
**dg0yt reported on Sourceforge [[tickets:#114](https://sourceforge.net/p/oorienteering/tickets/114)]:**

Symbols shall have translated names and descriptions.
Color names need to be translated, too.

I see two possible implementations:
- Maintain symbol set translations as part of the source code using Qt's translation framework. Advantages: No change to the file format. Lower file size of symbol sets and maps. Disadvantages: Won't work well for non-standard symbols and for unrelated combinations of Mapper program and data files.
- Maintain translations as part of the symbol set files. Advantages: Symbol set maintainer is in full control of translation. No versioning problems. Disadvantages: Requires a change to the file format (an incompatible change for the "native" format). Size of symbol set files increases. Size of maps increases (unless the user may drop translations).

**Comment by dg0yt** [comment]
We have got some translated symbol sets now. To ease maintenance of the symbols sets and to reduce binary package size, these translations should perhaps be handled by Qt tools like the UI translations, usingQt Linguist, Weblate or an integrated tool as the frontent for translators.

**Comment by dg0yt** [comment]
Translation extracted, Weblate component requested.
Still needs to be used in Mapper.

**Comment by dg0yt** [comment]
Now we have got a Weblate component for "Map Symbols":
https://hosted.weblate.org/projects/openorienteering/map-symbols/

![weblate](https://user-images.githubusercontent.com/13567791/27756745-c3645744-5dfa-11e7-977a-d6ac04e78ea5.png)

**Comment by sikmir** [comment]
FYI, Weblate status widgets on [wiki](https://github.com/OpenOrienteering/mapper/wiki/Translation) became incorrect. I've opened https://github.com/WeblateOrg/weblate/issues/1541.

**Comment by xianchb** [comment]
Why Chinese symbol set translation can't be seen in the new version?

**Comment by dg0yt** [comment]
> Why Chinese symbol set translation can't be seen in the new version?

I need to add it to the list of symbol sets which get installed. Thanks for reporting.

**Comment by xianchb** [comment]
> > Why Chinese symbol set translation can't be seen in the new version?
> 
> I need to add it to the list of symbol sets which get installed. Thanks for reporting.

Why Chinese symbol set translation can't be seen in the new version 0.9.3 ?

**Comment by dg0yt** [comment]
> Why Chinese symbol set translation can't be seen in the new version 0.9.3 ?

I'm sorry, there is a file name issue. If you rename `map_symbols_zh_HANS.qm` to `map_symbols_zh_CN.qm` (in the `translations` folder), then you see the result of your contribution in v0.9.3.

**Comment by xianchb** [comment]
> > Why Chinese symbol set translation can't be seen in the new version 0.9.3 ?
> 
> I'm sorry, there is a file name issue. If you rename `map_symbols_zh_HANS.qm` to `map_symbols_zh_CN.qm` (in the `translations` folder), then you see the result of your contribution in v0.9.3.

OK，thanks.
