### ISSUE TITLE
Enhancement: Switch to default drawing tool when choosing Symbol

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1143]
### Steps to reproduce
1. I work on scribble mode to map vegetation features
2. I come to a stone. I want to draw it. I open the symbol dialog and choose the stone symbol.

### Actual behaviour
Returning to the main screen I am still in the scribble mode. Thus I have to choose the point feature tool, before I can draw the stone. 

### Expected behaviour
Why would I choose a symbol, if I wanted to continue scribbling?  

Switch to symbols default drawing tool instead. 

### Configuration
Mapper Version: 0.8.2
Operating System: Android

**Comment by ollesmaps** [comment]
The same as #989.

**Comment by dg0yt** [comment]
Updated title of #989.

**Comment by lpechacek** [comment]
Scribble->Draw transition is indeed missing and this report is not a true duplicate of #989.

**Comment by lpechacek** [comment]
Will be in upcoming v0.9.
