### ISSUE TITLE
Enhancement: Temporary highlight GPS Position

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1145]
### Steps to reproduce
1. Working with a pretty good external GPS, the symbol representing the actual position gets highly unremarkable, especially over heavy background templates or scribbled areas.

### Actual behaviour
![image](https://user-images.githubusercontent.com/15611653/46208520-45fcb700-c32b-11e8-8691-326083ceb348.png)
fig.1. not best example but it gets close to invisible on the red or brown areas

### Expected behaviour
I seek an opiton to temporarily highlight the GPS Position by using a more prominent symbology for a short while (3 seconds) before returning to the normal symbology. Highlight might be somehow triggered for example by switching on and off GPS positioning.

### Configuration
Mapper Version: 0.8.2.
Operating System: Android

**Comment by lpechacek** [comment]
Doesn't [![image](https://user-images.githubusercontent.com/5584406/46217421-3f2d6e80-c342-11e8-9ec7-38ac5444f260.png) Move to location](https://www.openorienteering.org/mapper-manual/pages/android-app.html#-move-to-location) button help here? It always adjusts map view so that actual position is in the center.

**Comment by krticka** [comment]
For me better solution is to add customization of GPS position and GPS track. Record temporary trace is not recording track on my Note 4 when screen is off. Thus I usually rely on very tiny system GPS track (this is one is really hard to see).

**Comment by ollesmaps** [comment]
Relates to #986.

**Comment by jmacura** [comment]
Might be more interesting to allow user to customize the diameter of the outer red circle, which shows the precision of GNSS signal. Now it's hard set to 66,66 %, if I am not mistaken, so presenting a slider in the settings of Android which would allow a user to change it to other (higher) value, it should make it more useful and also better visible in the devices with very precise GPS.

**Comment by mlerjen** [comment]
How about combining highlighting with the "move to location" function? I would love that.

**Comment by sfroyen** [comment]
While we're in here, I would like to see the gray distance circles get a thicker line width.

**Comment by dg0yt** [comment]
I wonder if some sort of (slow) animation, such as blinking or spinning highlight, would be useful (and justify increased power consumption).

**Comment by dg0yt** [comment]
For the record:

> Working with a pretty good external GPS, the symbol representing the actual position gets highly unremarkable

Current diameter of the red dot is 1 mm on screen:
https://github.com/OpenOrienteering/mapper/blob/aa21231712266c9684105c138cf20ef875cc7e74/src/sensors/gps_display.cpp#L204

Curreent line width of the red accuracy circle is 0.2 mm on screen:
https://github.com/OpenOrienteering/mapper/blob/aa21231712266c9684105c138cf20ef875cc7e74/src/sensors/gps_display.cpp#L231

> While we're in here, I would like to see the gray distance circles get a thicker line width.

Current line width is 0.1 mm on screen:
https://github.com/OpenOrienteering/mapper/blob/aa21231712266c9684105c138cf20ef875cc7e74/src/sensors/gps_display.cpp#L216

> I seek an opiton to temporarily highlight the GPS Position by using a more prominent symbology for a short while (3 seconds) before returning to the normal symbology. Highlight might be somehow triggered for example by switching on and off GPS positioning.

Activating the compass should change the red dot into an red arrow of app. 2 mm length, but this is broken, and it wouldn't be much more visible in the given example. (Will fix it anyway.)
