### ISSUE TITLE
Enhancement: Changing position of a georeferenced template

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#1148]
When using georeferenced images, e.g., from Google Maps (Satellite), sometimes different images do not line up properly. It is therefore useful to be able to move a template after it has been opened as a georeferenced one. I have tweaked the code to always display the "move_by_hand_button" instead of the "georef_button". This allows me to move any template. However, saving and reopening the map causes any adjustment to be lost. I suspect there is some simple change (perhaps unsetting the is_georeferenced flag) that will make the new position permanent. The is_georeferenced flag is protected, however,  so it will be more involved than a one line change and I would appreciate some feedback or comments on how best to make the new position stick.

The final user experience should probably be something like this:

1) Tap the (renamed) Georeferenced button.
2) Tap away some type of warning.
3) Tap the move or edit buttons.
4) Move or edit the template position.
Step 4 side effect: template becomes not georeferenced,
5) If the template is removed and opened (not reopened) again, the original georeferenced position is restored

**Comment by jmacura** [comment]
This is a common problem in OpenStreetMap mapping. Perhaps it could be a good starting point to check the implementation in [JOSM](https://github.com/openstreetmap/josm) .
The UX in JOSM is like this:

1. open a WMS (i.e. georeferenced) template like Bing aerial layer or Mapbox Satellite imagery
2. as they are often displaced by tens of metres, user choose to correct the local position of the WMS layer
3. window pops-up with a possibility to type in the local offset in metres or you can drag and drop the layer by mouse => visually align it with the data in the area of interest
4. click "OK" and the new position is temporarily stored, until the end of session (closing of the program).
4b. but there is a [plugin](https://github.com/openstreetmap/josm-plugins/tree/master/imagery_offset_db) which allows you to store the position permanently in some online db shared with other users.

In Mapper, the storing of additional offset of a particular template, might be saved in the .omap file, hence the georeferencing of the template will not change.

**Comment by sfroyen** [comment]
Thanks for the comments. I don't really want to mess with the template load/import process. For the vast majority of the imports that I do, the georeferencing is adequate. Futhermore, since Mapper has a mechanism for adjusting templates, I want to use that.
Spending a little more time the issue, I was able to turn off the "georeferenced" flag. Once that was done, any position adjustments were saved in the .omap file and restored the next time the map was opened. I have attached a set diffs with the implementation. The user interface has two changes, (i)  the "Georeferenced" button is gone and (ii) the "Edit" menu has an added "Release georefence" menu item if the template has a georeference lock. Because of an implementation issue, this choice is inactive unless the template is visible.
Implementation-vise, I added a two methods, Template::releaseGeoreference and TemplateListWidget::releaseGeorefClicked.
Remaining issues:
1) If Template::releaseGeoreference is called for a template that has not yet been visible (since the map was opened), the georeferencong is lost. I suspect that the world-file is processed the first time the template is made visible. The assert that I added in Template::releaseGeoreference is ineffective. There's probably an easy fix for this.
2) My build of Mapper crashes whenever I close the "Positioning..." popup. I don't think this is related to my patches, but you never know.

[patch-src_gui_widgets_template_list_widget_cpp.txt](https://github.com/OpenOrienteering/mapper/files/2453498/patch-src_gui_widgets_template_list_widget_cpp.txt)
[patch-src_gui_widgets_template_list_widget_h.txt](https://github.com/OpenOrienteering/mapper/files/2453499/patch-src_gui_widgets_template_list_widget_h.txt)
[patch-src_templates_template_cpp.txt](https://github.com/OpenOrienteering/mapper/files/2453500/patch-src_templates_template_cpp.txt)
[patch-src_templates_template_h.txt](https://github.com/OpenOrienteering/mapper/files/2453501/patch-src_templates_template_h.txt)

**Comment by dg0yt** [comment]
@sfroyen May I ask for proper pull requests? Even it takes some time for you to learn how to do it, it will help to speed up feedback and integration. For example, I can't see immediately which branch your files apply to. In a pull request, I can comment on individual lines, and I may even stage additional commits.

We don't have specific instruction, but Github has general information, https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by lpechacek** [comment]
FWIW, the patch from previous is at https://github.com/lpechacek/mapper/commits/sfroyen-issue-1148 .

I like the approach in general. However, there seems to be a bug in implementation:
1) load georeferenced template
2) remove georeferencing
3) remove/close the template
4) without closing the editing session reopen the template

At this point the template position cannot be adjusted and Edit button does not offer "Release georeference".

**Comment by sfroyen** [comment]
Thank you for cleaning up and adding the patches to the repository!

Now, for some reason, I’m unable to reproduce your observation. So, a couple of comments and questions.

Comments:

I’m using a Mac to develop and test. I’m also using NetBSD pkgsrc as the development environment. This means, e.g., that I’m using Qt 5.11.1. Also, because I have not fixed some cmake issues, I’m missing GDAL. I don’t think, however, that these are issues are relevant here.

As mentioned in a couple of comments, when I open a map and release an (existing) unchecked (not visible) template, the positioning information is reset. If I check and uncheck the template before releasing, the template position is OK. This means I’m missing something about template loading. I would appreciate suggestions on how to fix this.

Finally, we’re probably using different versions of Mapper. Can you give me instructions on how to retrieve your version?

Questions:

What do you see after reopening the template? Do you see the move button? Is is grayed out? Do you see the edit menu? Can you open it? What does it contain? Are the entries grayed out?

Thanks,
Sverre

**Comment by lpechacek** [comment]
> Finally, we’re probably using different versions of Mapper. Can you give me instructions on how to retrieve your version? 

Perhaps the easiest one for you is downloading the .zip file from `https://github.com/lpechacek/mapper/archive/sfroyen-issue-1148.zip`. If you are knowledgeable of Git, clone `https://github.com/lpechacek/mapper.git sfroyen-issue-1148`. HTH

> What do you see after reopening the template? Do you see the move button? Is is grayed out? Do you see the edit menu? Can you open it? What does it contain? Are the entries grayed out? 

I got to correct my previous statement. "Move template" is active and the template position can be adjusted. I looked at a different template entry in my previous testing.

My testing procedure is: load georeferenced template; drop georeferencing; move the template a bit; close the template; click "Add template..." button (green plus sign) and select "Reopen template..."; move the previously closed template to the active templates list; select the template in the templates dialog. The template is still non-georeferenced at this point.

However, I'm no longer sure it is a bug as the positioning can be edited. :) I concur with Kai that "remove georeferencing" should be complemented with "restore georeferencing". A checkbox in the menu under "Edit" button looks like appropriate solution to me: Checked - template is georeferenced, unmovable; Unchecked - non-georeferenced, movable, rotatable.

**Comment by lpechacek** [comment]
@sfroyen, please ack your original patch in pull request #1154, tell us if you want to be stated as the patch author and whether your name and e-mail address are correct there. Thanks!

**Comment by sfroyen** [comment]
Not sure what you want me to ack or how, but I would certainly like to see the revised version of the patch in the official release. And there’s no need to list my name as the patch author.

**Comment by dg0yt** [comment]
> And there’s no need to list my name as the patch author.

There is some need indeed.

If you claim copyright in the parts you contributed, we must keep track of your name contact. 
This partially done in the header of the files (not in the changes here), and partiall also by the author field in git commit message, using name and e-mail address (this is the case in e084c15). This is where "insights" such as the Github's [list of Mapper contributors](https://github.com/OpenOrienteering/mapper/graphs/contributors) get their data from.
If you don't want your name or e-mail adress permanently recorded, please let us know now. This means I will put e084c15 fully under my authorship and copyright.

There is also a list of names of contributors in the about dialog which is update occassionally.

**Comment by sfroyen** [comment]
Understood. Is this sufficient?

I do not claim copyright over the parts I contributed in template-georef (#1154).Please feel free to place e084c15 fully under your authorship and copyright.

Sverre Froyen

**Comment by dg0yt** [comment]
Thanks for clarification. I updated the pull request.
Libor, raise your thumb and I will merge.
