### ISSUE TITLE
Creating contours and hillshades from .xyz files

### ISSUE THREAD

**Issue by Franci5kus** [OpenOrienteering/mapper#1151]
Hi,
I'm quite new in mapping and really appreciate using OOM as a free mapping software affordable for everyone!
But I faced some difficulties. As OOM doesn't have appropriate tools for processing LiDar data, what is the best way getting contours and hillshades from .xyz LiDar file? I've tried using QGIS, but result wasn't succesful.

Thank you in advance of any support!

**Comment by krticka** [comment]
Hi, 
there is not such functionality in OOM. But you can try [OL Laser](http://oapp.se/Applikationer/OL_Laser.html). Under "Ladda ner" you can find files for download.

**Comment by Franci5kus** [comment]
> What problems did you have using QGIS? Did you set the right projection for the data?

I don't know what the right projection should be, hence I've watched some tutorials and just experimented.

At first from .xyz file I made raster one (.tiff) with qgis 2.18.16 (because somehow 3.2.2 showed some errors, though older one didn't). Of course it looked not very promising:
![Uploading 76_32.jpg…]( ) (I import tiff to jpg converted file as forum doesn't support tiffs)

Then with 3.2.2 qgis version I've made _extraction>clip raster by extent_:
![capture 76_32 clip](https://user-images.githubusercontent.com/43929668/46584092-dba0f080-ca67-11e8-868d-5457e19950fb.PNG)

and then _extraction>contour_: 
![capture 76_32](https://user-images.githubusercontent.com/43929668/46583894-d93d9700-ca65-11e8-95ba-bda5f884c04b.PNG)

In the same area an old orienteering map looks like this:
![capture map](https://user-images.githubusercontent.com/43929668/46583899-e3f82c00-ca65-11e8-84b5-3f779d10ee5a.PNG)

I've done also some experimentations with „interval between contour lines“, but it looked also meaningless.
Thus, that was my unsuccesful result with qgis which I mentioned above.

Mathew, could you explain how to treat .xyz files correctly and maybe you understand what mistakes I've done?

**Comment by Franci5kus** [comment]
> Hi,
> there is not such functionality in OOM. But you can try [OL Laser](http://oapp.se/Applikationer/OL_Laser.html). Under "Ladda ner" you can find files for download.

I've been trying to use it, but it has installed for me in swedish (a bit problematic to understand everything). I've also tried to convert .xyz to grid, but it informed me that there is too much points in a file and it has required a lot memory, which OL Laser wasn't able to process.

**Comment by krticka** [comment]
Hi,
regarding coordinate system - Vilnia river is Lithuania, right? Would be good to post some sample of XYZ data to see the coordinate values.
Not sure what you did with conversion, but I am suspicious that interpolation was not done correctly.

**Comment by Franci5kus** [comment]
Yes, you are totally right, It's in Lithuania! 
Here you can download .xyz file which I've been using: https://drive.google.com/file/d/1crOEG4OQYDClzMIadSRFsvbIPTwAM_f3/view?usp=sharing

**Comment by krticka** [comment]
Well, it works for me in some way. The strange thing is, that under buildings elevation data are completely missing.
1. Coordinate system is LKS94 / Lithuania TM [https://epsg.io/3346](https://epsg.io/3346)
2. You need to do interpolation, not only vector to raster conversion to be able to process data correctly. I used Interpolate (cubic spline) from SAGA toolbox, but there are similar tools in QGIS/Interpolation toolbox. Than you are able to generate contours, hillshade, etc.
![clipboard01](https://user-images.githubusercontent.com/15969434/46585487-c6c95a80-ca71-11e8-9431-7897805ff5ff.jpg)
3. Good idea to close this issue as it is not Mapper related. Next time posting in Orienteering Mappers on Facebook would be better.

**Comment by lpechacek** [comment]
Marking resolved. Thanks, Luděk, for the explanation.

**Comment by dg0yt** [comment]
For the record, if you are on Linux (or Mac) and cannot use OL Laser or similar, you may use the GDAL command line tools:
- `gdal_grid` for converting ungridded XYZ files to gridded. (This may take a lot of computing time.)
- `gdaldem` for creating hillshading raster images.
- `gdal_contour` for creating contour vector data.
See Agnar Renolen's 2016 presentation on [LiDAR Experiences: Preparing basemaps using LIDAR data](http://lidarbasemaps.org/IOF-2016-Agnar-Renolen-LIDAR-experiences-Preparing0-base-maps.pdf).

The gdal tools may also process free SRTM data, for a rough overview of the terrain.

While I don't know when I will have time to make Mapper access these algorithms directly, it should be a pure packaging task to create a Mapper-GDAL package for Windows which would include these tools.   Anyone interested in trying out such a package and writing down a couple of lines with instructions for others?
