### ISSUE TITLE
Drawing toolbar impossible to get back

### ISSUE THREAD

**Issue by jerviservi** [OpenOrienteering/mapper#1155]
Version 8.2
Close the drawing toolbar.
Can't get it back (yes you can access the functionality by going to the 'Tools' drop down, but that isn't great.
Resetting preferences, or uninstalling doesn't fix the issue

**Comment by dg0yt** [comment]
Right-click anywhere on a toolbar or dock widget. Click the missing toolbar's name.

**Comment by Symbian9** [comment]
> Right-click anywhere on a toolbar or dock widget. Click the missing toolbar's name.

Here is screenshot how to enable/disable toolbars via mouse click on toolbars:

![pic.1](https://i.imgur.com/Uo88Hdi.png)

P.S.: Maybe, need add "Toolbars" entry in "View" menu too, @dg0yt ?

![pic.2](https://i.imgur.com/9ZJkNBL.png)
