### ISSUE TITLE
Map template in magenta color

### ISSUE THREAD

**Issue by and-hom** [OpenOrienteering/mapper#1161]
### Steps to reproduce
1. Start app. 
2. Click File -> New
3. Go to https://www.openstreetmap.org. Click Export on top of the screen and save *.osm file
4. Click Templates -> Open template. Select downloaded *.osm file

### Actual behaviour
I see all template objects in the magenta color. You can see screenshot here: https://drive.google.com/file/d/1m61LbOnr-kyBBg4VcQpC-ffgTYtPv82W/view?usp=sharing

Also if I do the same with kml or map file, I see magenta solid-filled rectangle.

### Expected behaviour
See map objects in different colors

### Configuration
Mapper Version: 0.8.3
Operating System: Ubuntu 18.04.1 
Linux and-hom 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
qt4 - 4.8.7
qt5 - 5.9.5

**Comment by dg0yt** [comment]
There is not enough information for the desired behaviour. These types of geospatial vector data do not come with any style information which Mapper could use when displaying these templates.

Regarding the rendering of OSM data:
-  The default color (magenta) cannot be changed at the moment.
- Area objects are displayed in the same halftone of magenta, which is an issue especially with OSM files. 

Workarounds:
- Reduce the opacity of the template to 50% to make overlapping areas (e.g. buildings) and details below this template more visible.
- Import the data into a regular (georeferenced) map file, and use this map file as template instead. For OSM, we provide CRT files which convert OSM data to ISOM symbols. But you may use your own symbols 
- Disable OSM in the settings for GDAL/OGR. This will leave areas blank. However, I plan to remove this option in v0.9 (#1160) for maintainability reasons. It seems like I really need to find a solution for colors and areas with GDAL/OGR.

**Comment by Symbian9** [comment]
FTR, here is rendering of "OSM template" (100% opacity)

![pic.1](http://i.imgur.com/NSdxalb.png)

And here is "OSM template" with reduced opacity to 50% (to make overlapping areas and details below this template more visible)

![pic.2](http://i.imgur.com/ecdu5PD.png)
