### ISSUE TITLE
Bug when printing in vecteur mode with background raster

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#1163]
### Steps to reproduce
1. Open a raster template without géoréférencing. (aérial photo .jpg)
2. Move the angle
3. Draws some vectors on it (contours)
4. Print it in vertor mode with "show template" activated

### Actual behaviour
The preview is good, but the template does not appear in the final printed map.

I have an other issue with the same map imported from Ocad 2018:
The preview is good.
In the final printed map, the template appear corectly, but the vectors are very smal in the top left corner 

### Expected behaviour
If i make an PDF export, all is good.

### Configuration
Mapper Version: 0.8.3
Operating System: Windows seven

edit:
screenshots with printing/export dialog settings widget:
![image](https://user-images.githubusercontent.com/44468453/47987349-92cc6e00-e0df-11e8-9c4e-f470f75d81c4.png)
Résult with a virtual or réal printer:
![image](https://user-images.githubusercontent.com/44468453/47987568-24d47680-e0e0-11e8-9603-208c9a1d906e.png)
zoom top left corner:
![image](https://user-images.githubusercontent.com/44468453/47987630-4b92ad00-e0e0-11e8-8a1b-e66c944ba8f5.png)

**Comment by Symbian9** [comment]
Please, add also screenshots with printing/export dialog settings widget.

**Comment by eolmapper** [comment]
add done

**Comment by dg0yt** [comment]
@Symbian9, what did you find out with the screenshots?

**Comment by Symbian9** [comment]
> what did you find out with the screenshots?

I see that "Resolution:" set to `1200 dpi` (by default, Mapper use 600 dpi)

Also, I see that map has unusual scale: `1:3000`.

Maybe, those factors in some way generate issue with printer properties (e.g., settings of `HP67B610 (HP OfficeJet Pro 6230)`).

@eolmapper, could you also add screenshot with printer properties dialog?

![pic.1](https://i.imgur.com/sVdjvIW.png)

Also, add screenshot with your template (background image) positioning properties:

![pic.2](https://i.imgur.com/NUf4X2i.png)

**Comment by dg0yt** [comment]
1200 dpi is fine. 1:3000 also. There is nothing unusual about it.

**Comment by Symbian9** [comment]
@eolmapper, can you explain, what method you use for hide unused parts on this background image?

![pic.1](https://i.imgur.com/vBrSNcr.png)

**Comment by eolmapper** [comment]
Dont focus to my screenshots exemple.

With new file, scale 10000, 600dpi, random jpg

**Comment by Symbian9** [comment]
> Dont focus to my screenshots exemple.
> 
> When i put an angle (0.01 for exemple) to the template in the positionning windows:

I just tried reproduce all steps, print it as *"Print - Save as PDF"* and *"Print - Boomaga (virtual printer)"* , but it not reproducible under *Linux* (*Debian 9.x, x86_64*).

Maybe, this issue related to printing under *Windows*/*Windows 7*?

P.S.: Only virtual printer I found for Linux is *Boomaga*

- http://boomaga.github.io

**Comment by dg0yt** [comment]
Yesterday I was able to reproduce this issue on Windows. As I expected, this is specific to Windows. (Printing is platform-dependant, unlike PDF export. For Windows, I needed to implement extra workarounds. On Linux, I use printing regularly.)

@Symbian9 Most Linux distributions offer a virtual PDF printer. In Ubuntu 16.04, it is the `printer-driver-cups-pdf` package.

**Comment by Symbian9** [comment]
> Most Linux distributions offer a virtual PDF printer. In Ubuntu 16.04, it is the `printer-driver-cups-pdf` package.

Yes, I know ;-)

I tried *Boomaga* just in hope to reproduce this issue using 3rd-party non-standart virtual printer on Linux, as CUPS output never give me such output as described in this issue.

**Comment by Symbian9** [comment]
FTR, @dg0yt,  when on Linux set in "Print ..." dialog choos "Save to PDF": it export to PDF using internal "Export... - PDF" or export to PDF using CUPS?

![pic.1](https://i.imgur.com/Dyye0Yb.png)

If this is CUPS, then we should be clear and show it as:

![pic.2](https://i.imgur.com/LBAN4d4.png)

Think, if there are NO any virtual (such as CUPS, Boomaga, etc.) or real printers detected then Mapper should show only such info dialog:

![pic.3](https://i.imgur.com/2kApJhY.png)

**Comment by dg0yt** [comment]
Attaching test files.

[#1163 vector printing.zip](https://github.com/OpenOrienteering/mapper/files/2598694/1163.vector.printing.zip)

**Comment by Symbian9** [comment]
> Attaching test files.
>
> [#1163 vector printing.zip](https://github.com/OpenOrienteering/mapper/files/2598694/1163.vector.printing.zip)

Due to not yet solved issue https://github.com/OpenOrienteering/mapper/issues/1178, this test case may not work on `unstable` build under Windows

![pic.1](http://i.imgur.com/Cajr2Vw.png)

**Comment by dg0yt** [comment]
Please verify that the latest master build fixes the issue for you. Thanks!

**Comment by eolmapper** [comment]
it's working well
