### ISSUE TITLE
Bug: Saving a map while Automatic North Alignment toggle is on results in rotated map

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1165]
![image](https://user-images.githubusercontent.com/15611653/47560108-9f023f80-d917-11e8-802d-1da9ca4e56ae.png)

### Steps to reproduce
1. Saving a map on Android while Automatic North Alignment toggle is on.
2. Open saved map on Windows 7

### Actual behaviour
Map is now displayed rotated (fig.1)

### Expected behaviour
Display rotation should not be saved. (as I do not see an easy way to reset it in the Desktop Version)

### Configuration
Mapper Version: 0.8.3.
Operating System: Android & Windows 7

**Comment by dg0yt** [comment]
Reprocible even on the Android device itself. Has been like this since the beginning of the Android version...
The fix is on the way, so the next master builds will solve this problem on the desktop.
