### ISSUE TITLE
Unexpected version from OBS

### ISSUE THREAD

**Issue by Abbe98** [OpenOrienteering/mapper#1167]
### Steps to reproduce

1. Originally installed Mapper with the instructions for Ubuntu 18.04 on OBS
2. running `apt-cache policy openorienteering-mapper`

### Actual behaviour

The latest version is not available from OBS.

```
openorienteering-mapper:
  Installed: 0.8.1.1-1build1
  Candidate: 0.8.1.1-1build1
  Version table:
 *** 0.8.1.1-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status

```
### Expected behaviour

Based on the release page I expect the candidate version to be 8.3.

### Configuration

Mapper Version: 0.8.8.1-1build1
Operating System: Ubuntu 18.04

**Comment by dg0yt** [comment]
You seem to get only the outdated package from the official Ubuntu distribution. My guess is your system has an expired/outdated key for the OBS repository. (I remember that I had to update the key on my Ubuntu 16.04 desktop, too.) Note the errors when running `apt-get update`.

**Comment by Abbe98** [comment]
I recently reinstalled my Ubuntu machine and I did not run into the issue a
second time.

Den fre 14 dec. 2018 kl 09:30 skrev Kai Pastor <notifications@github.com>:
