### ISSUE TITLE
Android: Baseline view broken and cannot be turned off

### ISSUE THREAD

**Issue by satokaj** [OpenOrienteering/mapper#1172]
### Steps to reproduce
1. Save map in Windows version with Baseline view checked
2. Open map in Android version

### Actual behaviour
Android version can't toggle/switch Baseline view.
Only dots for point symbol shows, areas and/or line symbol can be selected but are not visible.
#1049 solves visibility for lines, but not the possibility to get normal map view back in field.

### Expected behaviour
Button(s) to toggle Baseline view, Area view in Android version.
Start Android mapper with Baseline view off? 

### Configuration
Mapper Version: Android 8.3 
Operating System: Android 8.0

**Comment by lpechacek** [comment]
I'm sorry if I've rose hopes high. The fact that I have working code somewhere does not mean it will be included in Mapper. I'm not a project maintainer and I don't intend placing a pull request for the aforementioned change unless I'm requested to do so.

That said, leave the issue open if you want to see it resolved. Kai will decide which solution will be implemented and perhaps also does the code change.

That said I'm reopening the issue. Feel free to close it again in case I misunderstood your previous action. Thanks!

**Comment by dg0yt** [comment]
Let's try to sort it out.

> Android version can't toggle/switch Baseline view.

I would classify this sub issue as a feature request to add this switch. This probably isn't something I would work on soon.

lpechacek/mapper@1423a22 seems to already have an implementation, but lpechacek states that he doesn't intend placing a pull request for this change unless he is requested to do so. It is not clear to me who is expected to request this, and when. In general, the OpenOrienteering project kindly calls for contributions, and submitting a pull request would be the most natural way to do so.

Anyway, one of the most controversial issues with the mobile app is where to add buttons for such actions, and how many. So it might be good idea to discuss such changes with other users e.g. on the base of screenshots ("Is it the right thing?"). This may lead to a different result than a more technical code review ("Is it done right?"). Both views need to be taken into account when dealing with a solution.

> Only dots for point symbol shows, areas and/or line symbol can be selected but are not visible.

That's a bug which ws should fix ASAP. It happens only on Android devices (and emulator) where I hardly ever use this mode. Mobile mode on desktop is not affected, which probably contributes to overlooking this issue.

> #1049 solves visibility for lines,

Indeed, and also for areas in *baseline* view.

> I travelled (to spontaneously and light...) 350km to my map area just to realize i couldnt use my Android for mapping...

Sorry for this inconvenience. Of course I would recommend checking the map after each transfer. There is just too much room for surprises with these kind of devices and the compromises they involve, despite all confidence in our software.

> This issue should be open if you don't think your code will be implemented soon.

It should be left open until solved, rejected, or identified as duplicated.

**Comment by lpechacek** [comment]
This issue was effectively closed with commit c6370fd54bc9c96fdd21c0f8cb5f171e835ff0a9 which was merged in PR#1417. As neither the pull request nor the commit contained a reference to this issue, no automatic close happened. I'm closing the issue now.
