### ISSUE TITLE
Hiccups while drawing Bezier curves with stylus

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1176]
I saw this misbehavior occur frequently on zlenhart's tablet. After being demoed to me I realized that I see the same on my one but ignored it as the bug triggers much less frequently there.

### Steps to reproduce
1. Select Draw paths tool
2. Start drawing a Bezier line with the typical tap-and-drag movements

### Actual behavior
It is possible to either tap-and drag to continue a curve or just tap to continue with straight segment.
Occasionally the drawing movement continues with a weird mid-state. After the tap-and-drag there is continuation like if there was a tap, i.e. with a straight line, and the object preview ends on the previously drawn point and does not extend to the newly added point.

As a result there is a place looking like a corner point. Two control control points and two end points share the same coordinates:

![image](https://user-images.githubusercontent.com/5584406/48402792-ce44e900-e72c-11e8-9b42-e29e1b16e1f2.png)

There is a video capturing the bug in motion at http://liborpechacek.wz.cz/oomapper/mapper-issue-1176.mp4 (occurs at time 1:07) .

### Expected behavior
Every tap-and-drag in Draw path mode should result in curve point being added.

### Configuration
Mapper Version: 0.8.3
Operating System: Android

**Comment by lpechacek** [comment]
There's a bug in code that handles drawing of corner points.

**Comment by ollesmaps** [comment]
Propably unrelated. In the Draw paths mode when drawing straight segments, sometimes paths ends unintentionally.
- usually after drawing short segments
- usually drawing in a fast pace

This concerns Android only, no problem on PC.
A assume the abrupt end of path drawing is caused by confusion with doubleclick. 
Is it a bug?

**Comment by lpechacek** [comment]
If you mention some behavior in context of a bug, it suggests that it is annoying and at least a usability issue. However, it looks unrelated to the problem at hand. Please file a separate ticket with additional details like device information and how frequently this happens. TIA!

**Comment by lpechacek** [comment]
Aieee... I had the impression that I placed a pull request but it obviously is not the case. On my side it is the fix I intend to offer for merge. I'll create the pull request.

**Comment by lpechacek** [comment]
Wrong. The pull request is in place for about a month (https://github.com/OpenOrienteering/mapper/pull/1179) and awaiting your review.

Thanks for the reminder anyway!

**Comment by dg0yt** [comment]
Thanks for bearing with me...
