### ISSUE TITLE
Importer is unable to transform the coordinates for polygon and point shapefiles

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1181]
[shpDataForImport.zip](https://github.com/OpenOrienteering/mapper/files/2591815/shpDataForImport.zip)
[project.zip](https://github.com/OpenOrienteering/mapper/files/2591816/project.zip)

### Steps to reproduce
1. Set project CRS to EPSG 3857
2. Import polygon or point shapefile in EPSG 4326
3. Import ends with warning: The map import generated warnings.
Unable to load 641 objects, reason: Failed to transform the coordinates.

### Actual behaviour
No polygon or point objects are imported. Works well for line layers.

### Expected behaviour
Import and transformation should work for all geometry types.

### Configuration
Mapper Version: 0.8.3, 0.9.20181030
Operating System: Windows-x64

**Comment by dg0yt** [comment]
I get "Unable to load 377 objects" on import, but I can use it as a template. Strange.

**Comment by dg0yt** [comment]
In all cases, the data is imported into a `Map` object which stores (real or fake) "paper" coordinates. This is what differs:
- When loading the EPSG 4326 data as a template for the EPGS 3857 map:  
  The template uses an internal `Map` configured as EPSG 3857.  
  The data is *successfully* transformed from EPSG 3857 to 4326.
- When importing the EPSG 4326 data into the EPGS 3857 map:  
  The import uses a temporary `Map` configured with an orthographic projection (`+proj=ortho +datum=WGS84 +ellps=WGS84 +units=m +lat_0=0.000000 +lon_0=0.000000 +no_defs`).  
  OGR gives us a coordinate transformation from EPSG 3857 to this projection, but attempts to do actually use it with the coordinates from the data fail.
- When opening the shape file directly, there is no projection given in the file. Again, Mapper tries to work with the orthographic projection.

1. There may be a good explanation why these coordinate transformations fail here. Maybe there is better default projection to use. I just don't know it at the moment.
2. In the second case, the import should use a temporary Map configured to the original Map's georeferencing, making the transformation work directly, as in the first case. However, before I can change this, I need to to understand how this affects other cases, when the map or the data do not have a georeferencing. You don't want to see surprises with you existing maps/templates.

**Comment by dg0yt** [comment]
Actually, the orthographic projection is not created around `+lat_0=0.000000 +lon_0=0.000000` but the at the average latitude/longitude. This works well for GPX, but returns 0,0 for this SHP file.

**Comment by krticka** [comment]
Thanks for fixing this issue.
