### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#1189]
I think there is a mistake in the French translation:
Declination => Déclinaison magnétique
Grivation => Déclinaison (Déclinaison magnétique + convergence)

**Comment by sikmir** [comment]
Could you please suggest your translation here: https://hosted.weblate.org/projects/openorienteering/mapper/fr/?

**Comment by dg0yt** [comment]
I added some comments there. "Grivation" seems to be the most difficult term: https://hosted.weblate.org/translate/openorienteering/mapper/fr/?checksum=a2749c11820fe386
