### ISSUE TITLE
Cannot open the manual

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#1193]
`Help > Open Manual` doesn't work.

### Steps to reproduce
```bash
$ pacman -Syu
$ pacman -S home_dg0yt_Arch_Community/openorienteering-mapper-unstable
$ assistant -collectionFile "/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc" -showUrl qthelp://openorienteering.mapper-0.9.0.help/manual/index.html -enableRemoteControl -style fusion
```

### Actual behaviour
```bash
Error reading collection file '/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc': Cannot create index tables in file /usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc..
```

### Expected behaviour
The manual opened with no errors.

### RCA
Probably, indexing should be done once at package build:
```bash
$ sudo chmod o+w /usr/share/doc/openorienteering-mapper-unstable
$ sudo chmod o+w "/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc"
$ assistant -collectionFile "/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc" -showUrl qthelp://openorienteering.mapper-0.9.0.help/manual/index.html -enableRemoteControl -style fusion
<no errors>
$ sudo chmod o-w /usr/share/doc/openorienteering-mapper-unstable
$ sudo chmod o-w "/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc"
$ assistant -collectionFile "/usr/share/doc/openorienteering-mapper-unstable/Mapper unstable 0.9.20181202 Manual.qhc" -showUrl qthelp://openorienteering.mapper-0.9.0.help/manual/index.html -enableRemoteControl -style fusion
<no errors>
```

### Configuration
Mapper Version: `home_dg0yt_Arch_Community/openorienteering-mapper-unstable 0.9.20181202-0`
Operating System: ArchLinux

**Comment by dg0yt** [comment]
I would rather not want to run Qt Assistant at build or install time because it is a GUI app.

Maybe you are running a 5.12 Qt  Assistant? There were some change in Qt Help (dropping CLucene, merging ``qcollectiongenerator` into `qhelpgenerator`), and there is now [QTBUG-72174](https://bugreports.qt.io/browse/QTBUG-72174) which indicates a serious conceptual flaw.

**Comment by sikmir** [comment]
> I would rather not want to run Qt Assistant at build or install time because it is a GUI app.

Sure, I meant maybe qcollectiongenerator has some options to create proper index tables.

> Maybe you are running a 5.12 Qt Assistant?

Yes.

> ... there is now QTBUG-72174 which indicates a serious conceptual flaw.

I see. Thanks for pointing out.

**Comment by dg0yt** [comment]
build.opensuse.org is now picking up the Qt 5.12 packages for building. I guess this will resolve the issue.

**Comment by dg0yt** [comment]
And of course we need to apply 9665e231 or similar on top of v0.8.3, to make it build again.

**Comment by sikmir** [comment]
> I guess this will resolve the issue.

The same problem on master:
```bash
$ pacman -Syu
$ pacman -S home_dg0yt_Arch_Community/openorienteering-mapper-master
$ assistant -collectionFile "/usr/share/doc/openorienteering-mapper-master/Mapper master 0.8.20181211 Manual.qhc" -showUrl qthelp://openorienorienteering.mapper-0.8.3.help/manual/index.html -enableRemoteControl -style fusion
Error reading collection file '/usr/share/doc/openorienteering-mapper-master/Mapper master 0.8.20181211 Manual.qhc': .
```

**Comment by dg0yt** [comment]
Master was just rebuilt with Qt 5.12 a few minutes ago. Verify that you got the latest package.

To make v0.8.3 build with Qt 5.12, it is enough to add `-DQt5Help_QCOLLECTIONGENERATOR_EXECUTABLE=qhelpgenerator` to the cmake options in `PKGBUILD`.

**Comment by dg0yt** [comment]
"0.8.20181211" probably meant you were using a build with Qt 5.12. So yes, it is seriously broken in Qt.

**Comment by sikmir** [comment]
> Cf. https://build.opensuse.org/request/show/657081

By the way:
```bash
sed -i -e 's/Mapper/Mapper${BRANCH_SUFFIX}/;/^Name=/s/${BRANCH_SUFFIX}/ (${BRANCH})/'
```
Replace ' to ", otherwise it will not work.

**Comment by dg0yt** [comment]
> Replace ' to ", otherwise it will not work.

Indeed. (In the other build scripts, there are Makefile and RPM variables.)

**Comment by dg0yt** [comment]
Bug in Qt 5.12.0.
Affects: Arch Linux, openSUSE Tumbleweed (unless backporting a fix or upgrading to a version which contains a fix)
Fix backported in OpenOrienteering superbuild of Qt 5.12.

**Comment by sikmir** [comment]
I think we can close this issue, as far as no further actions required from OOM's side.

**Comment by dg0yt** [comment]
Okay. OpenOrienteering Superbuild uses Qt 5.12.2 now.
