### ISSUE TITLE
Bug: while using the cut out tool on .osm import a bug appear

### ISSUE THREAD

**Issue by samlaminilepre** [OpenOrienteering/mapper#1196]
### Steps to reproduce
1.Import .osm file
2.Draw a close line passing trough a big area like a forest going far out the map
3. Use the cut out tool

### Actual behaviour
The area symbol when is big have problem to cut, and many point move south to infinity

### Expected behaviour
A normal cut out

### Configuration
Mapper Version: 0.8.3
Operating System: windows 8.1
![oddeo](https://user-images.githubusercontent.com/45790530/50353263-f7387500-0547-11e9-9259-5010d891b963.JPG)

**Comment by dg0yt** [comment]
Thanks for reporting. I guess this is related to the fact that your drawing is very far away from the origin of the paper coordinates. (Cf. the coordinates in bottom right corner.) I would recommend to choose the map's georeferencing so that the data is located more close to point "0 0 mm" unless you really want to test the limits.

**Comment by samlaminilepre** [comment]
Hi, i thought that the problem could be something about the big size of the
areas... the problem is that i didn't choose the coordinates origin, it was
done automatically importing .osm file. How can i avoid it?
Thanks

Il giorno ven 21 dic 2018, 21:57 Kai Pastor <notifications@github.com> ha
scritto:

**Comment by dg0yt** [comment]
> the problem is that i didn't choose the coordinates origin, it was done automatically importing .osm file. How can i avoid it?

Either setup georeferencing manually (menu Map > Georeferencing). Start with the UTM coordinate reference system and the approximate geographic coordinates.
Or load the OSM file as a template first. This will trigger the georeferencing dialog with coordinates derived from the data.

**Comment by dg0yt** [comment]
I guess there is no further action needed on this issue.
