### ISSUE TITLE
OCD import broken for area with border objects containing holes

### ISSUE THREAD

**Issue by pinnabilli** [OpenOrienteering/mapper#1198]
### Steps to reproduce
1. See the attached test file [AreaWithBorderConversion.zip](https://github.com/OpenOrienteering/mapper/files/2796848/AreaWithBorderConversion.zip).

### Actual behaviour
![areawithborderconversion](https://user-images.githubusercontent.com/31986463/51757032-ad9cf600-20c2-11e9-9a4d-3f3437120ed4.png)
There is some vertex shuffling going on for areas with border.

### Expected behaviour
Areas with border should have the same shape as the ones without border.

### Configuration
Mapper Version: 0.8.4
Operating System: Xubuntu 16.04

**Comment by dg0yt** [comment]
Thanks for the test file. I can repoduce it in v0.8.4. In *unstable* it is already much better, but still not perfect (see below). I probably won't be able to fix this before v0.9.0, OCD support will be signicantly better there.

![unstable](https://user-images.githubusercontent.com/13567791/51769455-5fe4b580-20e3-11e9-8c12-842fccca92ce.png)

**Comment by pinnabilli** [comment]
Yes, it looks almost fine. As a memo, a quick workaround to close any leftover border gaps is to apply the "Unify areas" tool (at least two similar objects must be selected).

**Comment by dg0yt** [comment]
I'm preparing a fix. I wonder if something like that can also be created with curves?

**Comment by pinnabilli** [comment]
> I wonder if something like that can also be created with curves?

I'm not sure I got the point of the question... after some testing of the current _unstable_ with the fix, I didn't spot any issues also in case of areas with curved outline.
