### ISSUE TITLE
"Protect objects with this symbol" function does not protect against delete

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1199]
This is a minor issue.

### Steps to reproduce
1. Select a symbol and click Protect objects with this symbol to make the objects immutable
2. Press Ctrl-A to select all map objects
3. Hit Delete

### Actual behaviour
Objects which were supposed to be protected were deleted.

### Expected behaviour
The intuitive understanding of "protects" leads to expectation that protected objects will be retained after delete operation.

### Configuration
Mapper Version: stable branch build 0.8.20181215
Operating System: openSUSE Tumbleweed

**Comment by dg0yt** [comment]
What is our desired behaviour?
a) Ctrl-A selects *all* objects, but Delete omits protected objects.
b) Ctrl-A selects all but protected objects, but Delete removes all selected objects.

Mind:
- What do you expect from Copy and Paste?
- What do you expect when you set a some symbol to protected while some objects with symbol are selected?

**Comment by lpechacek** [comment]
Pretty good questions, Kai! :)

I propose aligning the behavior with OCAD 8. _Select all objects_ omits protected ones, which feels like an oxymoron but anyway, option b). Object that cannot be selected cannot be copied. OCAD resets object selection upon symbol protection change. The solution may feel clumsy but looks robust to me.

**Comment by dg0yt** [comment]
It shouldn't be too hard to remove "protected" objects from the selection, by `std::copy_if`.

**Comment by lpechacek** [comment]
It is indeed just Ctrl-A which is inconsistent in its behavior. Rectangle select with Edit tool behaves properly.

How about this fix?
```
diff --git a/src/gui/map/map_editor.cpp b/src/gui/map/map_editor.cpp
index c24e54e96830..88b6a8ed2eb2 100644
--- a/src/gui/map/map_editor.cpp
+++ b/src/gui/map/map_editor.cpp
@@ -2871,7 +2871,9 @@ void MapEditorController::selectAll()
        auto num_selected_objects = map->getNumSelectedObjects();
        map->clearObjectSelection(false);
        map->getCurrentPart()->applyOnAllObjects([this](Object* object) {
-               map->addObjectToSelection(object, false);
+               const auto object_symbol = object->getSymbol();
+               if (!object_symbol->isProtected() && !object_symbol->isHidden())
+                       map->addObjectToSelection(object, false);
        });
        
        if (map->getNumSelectedObjects() != num_selected_objects)
```

**Comment by lpechacek** [comment]
Yep, placing the check deeper makes sense.

```
diff --git a/src/core/map.cpp b/src/core/map.cpp
index 2b160aec6590..a1b7639cc160 100644
--- a/src/core/map.cpp
+++ b/src/core/map.cpp
@@ -989,6 +989,12 @@ void Map::drawSelection(QPainter* painter, bool force_min_size, MapWidget* widge
 void Map::addObjectToSelection(Object* object, bool emit_selection_changed)
 {
 	Q_ASSERT(!isObjectSelected(object));
+
+	// we omit hidden and protected objects from any kind of selection
+	const auto object_symbol = object->getSymbol();
+	if (object_symbol->isProtected() || object_symbol->isHidden())
+		return;
+
 	object_selection.insert(object);
 	addSelectionRenderables(object);
 	if (!first_selected_object)
```

As this is a minor bug, would you like a pull request against `master` or `dev`?

**Comment by lpechacek** [comment]
Pull request is in place. Closing.
