### ISSUE TITLE
Allow deleting all symbols in one run

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1200]
Suggested enhancement.

### Steps to reproduce
1. Select many symbols
2. Trigger Delete symbols operation

### Actual behaviour
Every symbol that is associated with an object in the map triggers a Yes/No dialog asking for confirmation.

### Expected behaviour
A "Yes to all" option in the dialog would be convenient.

### Configuration
Mapper Version: stable branch build 0.8.20181215
Operating System: openSUSE Tumbleweed

**Comment by lpechacek** [comment]
I've placed a pull request against `dev` containing a straightforward implementation of the enhancement. However, while testing the change, I can see the user experience is not yet perfect. When a large symbol set is selected and delete operation is triggered by mistake, the operation can neither be canceled nor undone. I can imagine this might be a fearful moment for some users spiced with uncertainty how to restore lost symbols.

I'm wondering what are your preferences for handling this situation. I can see following options:
1) Add Cancel button to the dialog. That way only unused symbols up to the first used one are lost.
2) Implement undo for symbol deletion.
3) Implement undo capability for all symbol changes while we are at it.
4) _... any better idea_

Feel free to share your thoughts in comments.

**Comment by lpechacek** [comment]
> In the long term, we always need undo (i.e. 2, 3).

I'm working on 3 and I'm wrestling with map object ownership transfer between `MapPart` and `UndoStep`. I'm tempted to turn `MapPart::ObjectList` into `std::vector<std::shared_ptr<Object>>` for the manual resource management is just annoying. Any advice or information about preferred solution would be welcome.

**Comment by dg0yt** [comment]
I wouldn't mind modernizing ownership, however this is a separate development topic with huge impact. 
- It works even better with full C++14 (having `std::make_unique`), which requires the successful switch to clang for Android (work in progress).
- In this particular spot, I would rather expect a `std::unique_ptr`, because there is quite clear, exclusive ownership. And with passing and returning `std::unique_ptr`, it becomes clear where ownership is transfered. There are spots where this is done already, although not always according to best practise (e.g. `void UndoManager::push(std::unique_ptr<UndoStep>&& step)`, which should be `void UndoManager::push(std::unique_ptr<UndoStep> step)`.
- IMO the key problem here is not object ownership but identity. We use both pointers and index numbers, and this what is so fragile. We need a stable identity, also to facilitate tracking and versioning of map data.

**Comment by lpechacek** [comment]
I came to the same conclusions. `std::unique_ptr` is definitely a good choice here. It indeed has significant impact on the code base and API. I'm half way through the rewrite but my hardware became unstable last night so I'll have to focus on that part now.

Regarding object identity, I came to the same conclusions. Identifying objects by position in some internal array is weird as much as use of pointer comparison. I was thinking about a transient run-time numeric id and I'm fine with going a step further with making the ids persistent.

I'll continue hacking on the prototype and share results when there are some. The cleanup is needed.

**Comment by dg0yt** [comment]
Great. I will to my best to review and merge, as soon as you mark some milestone ready.

I'm still stuck with building Qt 5.12 reliably across all platforms.

**Comment by lpechacek** [comment]
First version that at least compiles: https://github.com/lpechacek/mapper/commit/8a6b67bd6623392289b8b8c8348c9605d105a73c . I'm aware that it's full of insect but following things I'd like to keep:

* `deleteObject(Object *, bool remove_only)` is converted into pair of methods: `deleteObject()` and `releaseObject()`. With this distinction it is clear when the object is actually deleted and when it is merely released from classes' internal structures. Naming can of course change as needed.
* clear ownership of object through use of `std::unique_ptr`. It clarifies what is happening with the map object in transfers between undo buffer and map and between map parts like in the below example.

Before - object reference is obtained from `target`, the object is deleted (sic!) and then added to `source`.
```
			auto object = target->getObject(i);
			if (map->getCurrentPart() == target && map->isObjectSelected(object))
				map->removeObjectFromSelection(object, false);
			target->deleteObject(i, true);
			source->addObject(object);
```
After - object is extracted from `target` and passed on to `source`.
```
			auto object_ptr = target->releaseObject(i);
			if (map->getCurrentPart() == target && map->isObjectSelected(object_ptr.get()))
				map->removeObjectFromSelection(object_ptr.get(), false);
			source->addObject(std::move(object_ptr));
```

**Comment by dg0yt** [comment]
Maybe this discussion could be better held in a WIP PR?

Big :+1: for killing `bool remove_only`.

I would like to propose having just a single `std::unique_ptr<...> takeObject(...)` (i.e. the same signature as `releaseObject` above). 

Pros:
- As demonstrated by your implementation of `deleteObject`, that functionality is included.
- Concerns about a unpleasant habit of ignoring return values (in case of deletion) might be mitigated by explicit calls to `reset()` on the return value, maybe complemented by an attribute on the function that forbids ignoring the return value.
- For `unique_ptr` itself, `release` is about ownership, but in a different way.

Cons:
- The users intentions can't be expressed more explicitly than by `deleteObject`.

I didn't find any best practice hints on this topic.

The code example illustrates a change which asks for trouble: There will be event handlers/slots triggered synchonously when removing the object from the selection, and in this moment the object won't belong to any part. But that is an invariant which should hold when triggering unknown paths.

My version:
~~~
			auto object = target->getObject(i);
			if (map->getCurrentPart() == target && map->isObjectSelected(object))
				map->removeObjectFromSelection(object, false);
			source->addObject(target->takeObject(i)); // No explicit move needed!
~~~

**Comment by lpechacek** [comment]
> Maybe this discussion could be better held in a WIP PR?

Ack.
