### ISSUE TITLE
print area alignment error

### ISSUE THREAD

**Issue by pkturner** [OpenOrienteering/mapper#1209]
When using a printer that requires margins along the edges of the page, the area which actually gets printed is offset or trimmed from the area selected by the user.

### Steps to reproduce
1. The first print action after starting up Mapper.
2. Choose Single page.
3. See and select a rectangle which has been automatically sized to the printable portion of the page.

### Actual behaviour
The printed area is offset by the top and left margins of the page from the selected area. In other words, the top-left of the printed paper is the same as the top-left of the print area that the user selected. A portion of the selected rectangle along its top and left fails to be printed.

### Expected behaviour
The selected rectangle of the map should be aligned and printed in the printable portion of the paper.

### Further observations
After a single page has been printed, the user sees and selects a rectangle sized to the area of the paper. This behavior might be acceptable if it were consistent. However, it would be preferable if Mapper would take care of the required margins automatically.

Also, if a custom print area requires multiple pages, the automatic page overlap of 0.4 mm does not provide for the unprintable portion of the paper.

After printing a single page has caused the print widget to show a rectangle sized to the paper, selecting a new "Page format" resets the displayed page rectangle to the smaller printable portion of the page.

In each case, the print area numeric parameters agree with the rectangle(s) displayed in the view.

I am willing to develop a fix for this, however it's unclear to me what the intended behavior is. The line `printer->setFullPage(true);` looks suspicious.

### Configuration
Mapper Version: 0.8.4
Operating System: Linux, Macintosh, Windows
Printer: HP LaserJet Pro 400, Letter size paper, driver indicating margins of 4.32 mm on all 4 edges.

**Comment by dg0yt** [comment]
Is this still an issue with v0.9.0/Qt 5.12? `printer->setFullPage(true);` isn't a problem if used properly, but there have been issues with that Qt feature IIRC.

**Comment by pkturner** [comment]
I tested with v0.9.0 on MacOS. I also tested with v0.9.0 built with Qt 5.12.5 on Linux. The behavior remained as described above for a single page. I also tested a 2-page custom area, and as before a strip through the center of the selected area was assigned to the unprintable margins, so that strip did not appear in the printed output.

The unprinted strip, and the earlier-mentioned offset are simply bugs. The aspect that I'm unsure of involves the width and height of the print rectangle that the user manipulates. Currently these dimensions are usually sized to the full page, which is at best awkward. The following is how I suppose it should work.

- In the Print dialog, when the user chooses "Single page" the width and height should be for the printer's printable rectangle, excluding unprintable margins.
- When the user chooses "Custom area" the selection GUI should show the map being broken up into pages based on the printer's printable rectangle.

**Comment by dg0yt** [comment]
IIRC our printing is designed to use the full page and to ignore margins because margin information is sometimes unreliable. Thus the actual unprinted margin is left to the printer hardware instead of the printer driver.

- For a full-page map, the content is expect to be placed at the edes of the paper. Due to printer limitations, there will indeed be a margin of the selected area which is not printed.
- For a single-page map, less than full page size, it is easy to have it centered within the full page size, thus ensuring that the selected area is not cut unneccessarily.
- For a multi-page map, the adjustable overlap is meant to solve the problem of unprintable margins. There shall be no missing strips between neighboring pages. But again, the actual margin is left to the printer hardware.

**Comment by pkturner** [comment]
Thanks for explaining how printing generally works. #1464 contains a proposed fix.

While working on the problem, I found the quickest way to reproduce it was to change the target Printer in the PrintWidget. If the new target has margins, then the print area gets set smaller than the paper size, which leads to inconsistency. When the Print button is clicked, the MapPrinter obtains and uses the full paper size.
