### ISSUE TITLE
Support for PROJ 6.0.0

### ISSUE THREAD

**Issue by sebastic** [OpenOrienteering/mapper#1214]
OpenOrienteering Mapper still uses `proj_api.h` which is deprecated in PROJ 6.0.0 and will be removed in PROJ 7.0.0 (scheduled for March 2020).

When using `proj_api.h` with PROJ 6.0.0 `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` needs to be added to `CFLAGS` to prevent a compiler error.

OpenOrienteering Mapper should be updated to (also) support the `proj.h` API.

**Comment by pkturner** [comment]
I looked a little into updating from `proj_api.h` to `proj.h`. I didn't find a direct replacement in the new API for Mapper's use of `pj_set_searchpath`, `pj_set_finder`, and `pg_strerrno`. Can someone provide a clue to what Mapper is doing with the management of projection definitions (init files), or what the PROJ people had in mind by dropping that functionality? Apart from that hurdle, I could create a PR for this.

**Comment by sebastic** [comment]
The developers on the proj@lists.osgeo.org mailinglist should be able to help you with the PROJ side of that.

**Comment by dg0yt** [comment]
Thanks for reporting here. I already got failing builds on build.opensuse.org for openSUSE and Fedora.

It is easy to workaround by passing `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H` with CXXFLAGS (https://build.opensuse.org/package/rdiff/home:dg0yt:staging/openorienteering-mapper-master?linkrev=base&rev=53). However I ran in failing unit tests, probably due to the removed `proj_def.dat` file / `+no_defs` option.

@pkturner Pull request welcome. I will eventually try to cover old and new PROJ in our new CI setup.

**Comment by dg0yt** [comment]
> I didn't find a direct replacement in the new API for Mapper's use of pj_set_searchpath, pj_set_finder, and pg_strerrno. Can someone provide a clue to what Mapper is doing with the management of projection definitions (init files) [...]

Cf. https://proj4.org/development/migration.html#function-mapping-from-old-to-new-api
- `pj_set_searchpath`: No equivalent. `PROJ_LIB` seems to be the only way now.
- `pj_set_finder`: No equivalent. We use this on Android to extract definition files as needed from the assets to a temporary file. If there is no other as-needed trigger, we will have to extract all files in advance.
- `pj_strerrno`: No equivalent. We use this to provide validation information in the georeferencing dialog.

> [...] or what the PROJ people had in mind by dropping that functionality.

It seem it is very much work in progress, with open PROJ issues.

**Comment by pkturner** [comment]
@sebastic, @dg0yt 
Thanks, I will give it a try.

**Comment by dg0yt** [comment]
With the above macro defined, Mapper builds with PROJ 6.0.0, and the tests pass on Linux and macOS (https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=159).

However I wasn't yet able to test with Android where we actually need 'pj_set_finder` at the moment.

**Comment by pkturner** [comment]
I've created PR #1218 which updates Georeferencing to use the PROJ 5.1 API. This should work with PROJ 6.0.0 without need of a `CFLAGS ` definition. I need to build on Android (first time for me) for more testing.

**Comment by dg0yt** [comment]
I downloaded, signed and tested an APK based on PROJ 6.0.0 from CI, and GPS worked with my test map. So probably the deprecated functions are still okay, but I think it might be good to add a test for the feature which is otherwise used only on Android, before merging the superbuild update.

**Comment by dg0yt** [comment]
Mapper v0.9.0 defines `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` and uses `proj_api.h` only with PROJ lower than 6.1. This version added proj_normalize_for_visualization().

We need to use more of the modern features from PROJ, but this particular issue can be closed now.

**Comment by dg0yt** [comment]
Another remark:
`ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` is used to switch implementations in Mapper.  If the macro is defined via flags passed to the build system, Mapper will use old PROJ includes and API.
