### ISSUE TITLE
When changing north and rotate map GPS-track ends up wrong

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#1228]
### Steps to reproduce
1. Chose degree for map north
2. Allow to rotate the map
3. Open GPX-track

### Actual behaviour
GPX-track doesn't longer fit.
![image](https://user-images.githubusercontent.com/16168975/55883804-3fd37700-5ba7-11e9-8a65-571081fb6b5f.png)

### Expected behaviour
GPX-track should fit
![image](https://user-images.githubusercontent.com/16168975/55884039-a789c200-5ba7-11e9-86e4-be9278594dbd.png)

### Configuration
Mapper Version: 0.8.4
Operating System: Windows 7 Pro

Related #981 #331

**Comment by dg0yt** [comment]
That may be related to #1235. #981 was for non-georeferenced templates, but I suppose your GPX track is georeferenced.

**Comment by Zerbembasqwibo** [comment]
It is. I have noticed it's difficult to understand when changing where
north is, if you should or not, also rotate the map. Maybe I just do it
wrong (due to lack of knowledge).

tisdag 30 april 2019 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
Please read https://github.com/OpenOrienteering/mapper/issues/1235#issuecomment-488564818, and see if this helps.

**Comment by Zerbembasqwibo** [comment]
Thanks, must run through all steps to confirm my problems are solved!


torsdag 2 maj 2019 skrev Kai Pastor <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment]
I tried the instruction in #1235 and now everything works fine. Thanks! :)

**Comment by dg0yt** [comment]
I think this is solved already.
