### ISSUE TITLE
Template visibility not exported to OCD

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1236]
### Steps to reproduce
1. Start a new  map in Mapper
2. Add e.g. 2 templates, set opacity of one to something less than 100%, Hide all or single templates
3. Export to OCD10 or OCD12 format
4. Open in OCAD10 or OCAD12

### Actual behaviour
All templates are visible and undimmed

### Expected behaviour
Export visibility and opacity. Note: importing OCD10 maps with individual settings for visibility and opacity works fine.

### Configuration
Mapper Version: unstable 0.9.20190326 (64bit)
Operating System: Win7x64

**Comment by jmacura** [comment]
I just wanted to report the very same bug. But I thought that it's a side-bug of #1234  ... When I open the exported map in OCAD 10 and all the complains about "BackgroundMapOptions.LoadBackgroundMap" finishes (7 times for the file I was trying to import/export through the Mapper this time), almost all the templates are visible, even though they were hidden before import to Mapper and even _in_ the Mapper (before export to ocd10).
There are 39 background files in the current map and 31 of them has turned visible after the export. Quite annoying to turn them off one by one.. 😕 

(OT: I've just noticed that I've really created an issue with number 1234, nice :D )

**Comment by dg0yt** [comment]
Indeed, we do always import "dimming" and "visibility" from the "setup string", but in the best case, we export just zero dimming ATM.
