### ISSUE TITLE
Mapper-unstable snapshot for Android

### ISSUE THREAD

**Issue by jmacura** [OpenOrienteering/mapper#1238]
Would it be possible to compile the current unstable version of Mapper in an .apk for Android? The same way the snapshots for OS X were released? I am willing to test the unstable version of Mapper on Android, to provide the necessary feedback and perhaps push the 0.9.0 version a little bit further to its official release.. :-)
Based on the last comment in #1065, it might be possible with Superbuild now..?

### Configuration
Mapper Version: dev
Operating System: Android

**Comment by Symbian9** [comment]
FTR, it is possible setup Travis-CI for APK "nightly" builds

- https://github.com/mkulesh/microMathematics/blob/master/.travis.yml

**Comment by dg0yt** [comment]
I will probably provide another snapshot soon, for macOS and Android. Not sure if that will already be automated, but this isn't required anyway.

**Comment by lpechacek** [comment]
While putting myself in danger of being marked "off-topic", I dare to say that Symbinan9's remark was perhaps not that useless. There is a [Gist showing how resulting test build binaries can be pushed back into a Git repo](https://gist.github.com/willprice/e07efd73fb7f13f917ea). While it's tailored for Travis, maybe the script could be adapted for Pipelines. As a result there would be test .apk's "for free".

**Comment by dg0yt** [comment]
@lpechacek We are not to push binaries into a Git repo. We are to use Github releases. And Azure Pipelines has a [task for managing Github releases](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops).

I want:
- [ ] a reliable way to publish not just the APK or DMK but the full corresponding sources
- [ ] a safe migration path from sideloading-type installation to Play store installation (#607)
- [ ] a safe way for users to install and remove "unstable" builds (sideloaded) next to stable ones (from Play store).

Does this sound reasonable?

**Comment by dg0yt** [comment]
After being side-tracked by Travis-CI related posts, I would like to add that with some privileges granted to you in our Azure project, you could already download the APK. I would still have to add an APK signing step (cf. https://github.com/OpenOrienteering/mapper/wiki/Continuous-Integration#testing-the-binary-artifacts).

**Comment by lpechacek** [comment]
@dg0yt I agree to the requirements and I consider them useful and reasonable. At the same time I want to declare my belief that for a certain group of power users (at this point I avoid spelling out names but I have three in mind) the missing safety features are a non-issue. These people understand that data need to be backed up and their device might need reset to factory defaults after heavy experimenting. Hindering these people from testing until safety rails are in place is IMHO missed opportunity.

On a more personal note, after two years of following this project and attempting to contribute code I've got growing feeling that interested project contributors should gather somewhere for a face to face meeting to discuss past experiences, interests, standards for cooperation, future plans and building mutual trust. A multi-day orienteering event might be a good opportunity for such a meeting.

Thanks for giving second thought to the APK build topic. :)

**Comment by dg0yt** [comment]
There is now the first published unstable snapshot build on Azure Pipelines:
https://github.com/OpenOrienteering/mapper/releases/tag/v20190608.1

I manually signed and published the APK with our *release* key. This *'dev'* version can be installed in addition to the regular version.

**Comment by dg0yt** [comment]
I managed to add APK signing to the release job. The APK and app is now also visibly named like the Release.

In addition, I started adding extra badges to the releases on Github to make release quality more visible.

Snapshot release process on Azure Pipelines is now:
1. On Azure:

     Pick the latest successful "Mapper" build for `dev` from the build pipelines, and select "Release".
     (Alternatively, a release can be created from the Azure release pipelines.)

     Once the release is created, the "deployment" (signing, publishing to Github) should run automatically.

2. On Github:

     When deployment finished, there is a draft (non-public) release on Github. Review the release notes, test the binaries, and finally hit "Publish release".

**Comment by dg0yt** [comment]
Note that the latest APK use target API level 28. This means that newer devices might add extra features and restrictions which could for example affect how Mapper operates (or is killed) when put into the background. This should really get some testing before v0.9.0

**Comment by jmacura** [comment]
Awesome! I will test it as soon as I find some time for it :-)
