### ISSUE TITLE
Text features oriented to north

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1241]
### Steps to reproduce
1. Most text features of an orienteering map are "oriented to north". That means, that if the map gets rotated due to change of declination, these features should face towards the new magnetic north.

### Actual behaviour
As it is now. The texts get rotated with the rest of the map and thus end up skewed on the map.
![image](https://user-images.githubusercontent.com/15611653/57070330-574ddd80-6cd7-11e9-8d6d-8459ec23abf6.png)

### Expected behaviour
Introduce an "oriented to north" option for text features alike already in use for point features.

### Configuration
Mapper Version: 0.8.4.
Operating System: Windows 7

**Comment by dg0yt** [comment]
I guess we could make this option default to 'enabled' when loading old maps, at least if there is no object which is already rotated.

**Comment by dg0yt** [comment]
How did this interact with OCD export? We treated text symbols as always rotatable in Mapper, but the (new) OCD export didn't set the corresponding flag in the OCD symbol.
