### ISSUE TITLE
Area symbol line pattern glitch at top and left edge

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1249]
ISSprOM 2019 brings a lot of hatched patterns. So far there are two minor issues.

1. The hatched lines of a pattern do not always reach the area border.
![image](https://user-images.githubusercontent.com/15611653/58089313-b90db300-7bc4-11e9-8d00-2b6c24f95d72.png)
2. If rotated to have an angle of about 45 degrees towards the running direction on the lower running level, the hatch pattern does no longer correspond with the one of adjacent areas.
![image](https://user-images.githubusercontent.com/15611653/58089694-bcee0500-7bc5-11e9-94ce-30f5cf33c68d.png)

(Seems that a hatch-line  is set to the "rotation center". In this use-case such seems not useful.) 

### Expected behaviour
1) Patterns should fill the area
2) Adjustable patterns should correspond if rotated by the same angle.

### Configuration
Mapper Version: 0.8.4
Operating System: Windows

**Comment by yevhenmazur** [comment]
This issue not reproduced on current dev build.

**Comment by dg0yt** [comment]
@mlerjen Can you provide a test file for reproducing this issue with our `dev` builds?

**Comment by mlerjen** [comment]
[1909_Sample Hatched.zip](https://github.com/OpenOrienteering/mapper/files/3614943/1909_Sample.Hatched.zip)

Sample file contains: An area Symbol which pattern can be rotated with rotate pattern function. Screenshot is from dev 20190915.17
![image](https://user-images.githubusercontent.com/15611653/64937969-903cb800-d85c-11e9-9da1-46101f540e74.png)

**Comment by mlerjen** [comment]
Work around:
* Select all objects to rotate pattern to the same direction
* Rotate pattern
![image](https://user-images.githubusercontent.com/15611653/64946060-5080cb00-d872-11e9-893d-f806cd2f996e.png)

**Comment by dg0yt** [comment]
I don't think the workaround would have worked in general. It is just the particular setup of the top-left corner in your example that hides the bug with the top and left edges. But it is fixed in the next release anyway. Thanks for reporting!

**Comment by mlerjen** [comment]
Clarification: The work-around fixes problem 2. If you want a group of "candy" patterns to fit each other after pattern rotation, you have to rotate their patterns in one single move.
