### ISSUE TITLE
Background in top bar is missing

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1255]
### Steps to reproduce
1. Open the map file.
2. 
3.

### Actual behaviour
Background in top bar is missing , icons are poorly readable.
![Screenshot_2019-06-08-16-21-58](https://user-images.githubusercontent.com/15969434/59148548-9f64cc00-8a0a-11e9-9f03-87b2baa97202.jpg)

### Expected behaviour
Top bar should have background as is usual.

### Configuration
Mapper Version: dev v20190608.1
Operating System: Android 6.0.1

**Comment by dg0yt** [comment]
Thanks for reporting. IIRC this also affects "mobile mode" on the desktop.

Apart from this visual glitch, the app still isn't using "native" Android style at the moment.

**Comment by lpechacek** [comment]
Interesting. Never saw this on Android but transparent top bar is common in mobile mode on desktop. Might be a result of switch to newer Qt.

FWIW, I solved the bug in my mobile UI experimental branch this way:
```
commit e16dd191fbd3c7b31c4d2fcafcde33137730f0db
Author: Libor Pechacek <lpechacek@gmx.com>
Date:   Sun Mar 11 22:06:02 2018 +0100

    Mobile UI: Fix top action bar integration
    
    Make top action bar part of the layout instead of the map.

diff --git a/src/gui/map/map_editor.cpp b/src/gui/map/map_editor.cpp
index 2227ee7741a1..2f2c3eb94db3 100644
--- a/src/gui/map/map_editor.cpp
+++ b/src/gui/map/map_editor.cpp
@@ -1473,12 +1473,11 @@ void MapEditorController::createMobileGUI()
        
        bottom_action_bar->setToUseOverflowActionFrom(top_action_bar);
        
-       top_action_bar->setParent(map_widget);
-       
        auto container_widget = new QWidget();
        auto layout = new QVBoxLayout();
        layout->setMargin(0);
        layout->setSpacing(0);
+       layout->addWidget(top_action_bar);
        layout->addWidget(map_widget, 1);
        layout->addWidget(bottom_action_bar);
        container_widget->setLayout(layout);
```
Not sure if this is the right approach, but seeing the buttons as part of the map view felt odd to me. I can place a pull request if this is an acceptable fix.

**Comment by dg0yt** [comment]
@lpechacek I do agree your change would restore the canonical way of handling the widgets. However, the difficult thing is the hiding/unhiding of the top bar. By adding it to the layout, it affects the size of the map widget [cache], so toggling visibility invalidates the map widget's graphics cache... This needs a more elaborated solution.

**Comment by yevhenmazur** [comment]
Not sure this comment will be helpful, but the same bug reproduced in version 0.6.7 from F-droid repository. Probably the root of cause in the build method.

**Comment by lpechacek** [comment]
> By adding it to the layout, it affects the size of the map widget [cache], so toggling visibility invalidates the map widget's graphics cache...

Thanks for the comment, Kai. I agree that moving the top bar into layout indeed makes the map widget's size change. It also results in slight map view move upon hiding the top bar.

I've just looked into map_widget's code to learn what cache gets invalidated. It looks to me like it's the generated map view which can be noticed upon _Pan map_ operation. As far as I can tell, the cached rectangle gets re-generated on any map view move (`MapView::setCenter() [emits viewChanged signal]> MapWidget::viewChanged() -> updateEverything() -> MapWidget::update(widget extent) [GUI core schedules paintEvent]> MapWidget::paintEvent() -> updateAllDirtyCaches() -> MapWidget::updateMapCache() [object renderables get painted]`), zoom and perhaps couple more operations. Unfortunately, the reason why cache invalidation requires extra handling is still beyond my understanding of the system and application use cases.

**Comment by dg0yt** [comment]
With the native style activated again on Android (another Qt quirk since Qt 5.12.0), the issue is resolved for that platform.
I remember that I tried various ways to solve this properly also for the desktop, but nothing worked out.

**Comment by dg0yt** [comment]
> Unfortunately, the reason why cache invalidation requires extra handling is still beyond my understanding of the system and application use cases.

The point is that the cache image is as large as the map widget. After changing the map widget's size the cache image no longer matches. It is the same thing which happens on the desktop when you hide toolbars or resize the window, but there it doesn't hurt so much.
