### ISSUE TITLE
Geospatial vector data export creates area layer with empty geometry

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1256]
### Steps to reproduce
1. Export map using Geospatial vector data function
2. Add .pix file into project in GIS (for example in QGIS)
3. Browse area layer, area objects are not visible.

### Actual behaviour
Attribute table contains records (name of the map symbol), however geometry seems to be completely empty. When zooming to selected record, I am getting message: "Cannot zoom to selected feature(s) : No extent could be determined." 
Tried to rebuild spatial indexes and extent, but with no luck. Point and line layers are OK.

### Expected behaviour
Area objects are not missing.

### Configuration
Mapper Version:  dev-20190608.1
Operating System: Win10

**Comment by dg0yt** [comment]
Do I understand correctly  that in 1., you did export to a ".pix" file? I don't know the format, and I also don't know QGIS very well. I need more details if I am to reproduce the issue.

What I can say is that the GDAL's export capabilities varies by format, and some formats will require adjustments in Mapper. The more common and the less proprietary, the better. So to track this down, try also another format, e.g. OSM.

**Comment by krticka** [comment]
The *.pix format was quite surprising. The problem is, that when exporting there is not option to select file format, only Geospatial vector data is available.
![Clipboard01](https://user-images.githubusercontent.com/15969434/59253900-7a04d780-8c2f-11e9-8e15-7ba2d30f3767.jpg)
*.pix (PCIDSK) is widely used in [Geomatica software](http://www.pcigeomatics.com/geomatica-help/references/gdb_r/gdb3N265.html) for storing imaginary data, so handling of vector data is quite surprising, thought handling of vector segments  [seems to be possible from GDAL 2.0](https://gdal.org/drivers/raster/pcidsk.html). Maybe the capability is limited only to point and line features, but attribute data for area objects were also created in my case.
From your comment I suppose, that more options for file format should be available for the export, however, these are not available at the moment in my installation.

**Comment by Symbian9** [comment]
> The *.pix format was quite surprising. The problem is, that when exporting there is not option to select file format, only Geospatial vector data is available.

So, when you tried to export map from Mapper as *"Geospatial vector data"*, Mapper automatically exported it as `*.pix`, right?

Then need choose better name for this option:

- *"Geospatial vector data (input format extension too)"*

**Comment by dg0yt** [comment]
Doesn't Mapper/GDAL simply choose the format based on the extension you add to the filename?

**Comment by Symbian9** [comment]
> From your comment I suppose, that more options for file format should be available for the export, however, these are not available at the moment in my installation.

@krticka, for *"Export > Geospatial vector data"* you should input not only name of file, but file format extension too (take a look on GDAL docs for full list of supported formats), for example:

- for export to OSM input it as `<file_name>.osm`
- for export to Shapefile input it as `<file_name>.shp`
- for export to AutoCAD DXF input it as `<file_name>.dxf`

P.S.: Need add more info about this option in *«Mapper Manual»*.

**Comment by krticka** [comment]
Now I can confirm that this is the case. I think we have here problem of too high expectations on users data format knowledge. I am afraid that many users will not know/remember what are the possible options of data format export and exact naming of all extensions. Typically open-source projects using GDAL are using standard drop down menu with extensive list of file formats.

**Comment by dg0yt** [comment]
I suppose that users might know their favorite extensions (.gpx, .osm, .dxf) but could be overwhelmed when asked to choose between 50 different partially obscure formats.

This export feature is a fairly young contribution (#1068), and surely could get some polishing. But I cannot request too many changes from new contributors: I'm glad to have this feature at all.

**Comment by Symbian9** [comment]
> Typically open-source projects using GDAL are using standard drop down menu with extensive list of file formats.

From one side, "drop down menu with extensive list of file formats" is good, but from other side current Mapper implementation of *"Geospatial vector data"* is simpler and more flexible.

> I am afraid that many users will not know/remember what are the possible options of data format export and exact naming of all extensions.

The easiest solution for Mapper is add to file name input field *pop-up message* with cheat sheet/list of most popular format extensions + link to full list of formats supported by GDAL.

**Comment by krticka** [comment]
Link "How to save to different formats" in export menu would be very helpful.Dne 11. 6. 2019 9:21 odp. napsal uživatel app4soft <notifications@github.com>:
Typically open-source projects using GDAL are using standard drop down menu with extensive list of file formats.

From one side, "drop down menu with extensive list of file formats" is good, but from other side current Mapper implementation of "Geospatial vector data" is simpler and more flexible.

I am afraid that many users will not know/remember what are the possible options of data format export and exact naming of all extensions.

The easiest solution for Mapper is add to file name input field pop-up message with cheat sheet/list of most popular format extensions + link to full list of formats supported by GDAL.

**Comment by Symbian9** [comment]
> I am afraid that many users will not know/remember what are the possible options of data format export and exact naming of all extensions.

When user will not know/remember something, then user should read the «Mapper Manual» (bundled with mapper, PDF or online version)

![pic.1](https://i.imgur.com/FS2dwxD.png)

And that is why told above that we should add more info about *"Export as... > Geospatial vector data"* feature in «[Mapper Manual](https://github.com/openorienteering/mapper-manual)».
