### ISSUE TITLE
Linux builds for "dev" branch

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1261]
What about Linux builds for "dev YYYMMDD.X" releases?

- https://github.com/OpenOrienteering/mapper/releases/tag/v20190608.1
- https://github.com/OpenOrienteering/mapper/releases/tag/v20190610.2

Seems like OBS has no such builds

- https://download.opensuse.org/repositories/home:/dg0yt/Debian_9.0/amd64/

**Comment by dg0yt** [comment]
The `dev` builds on OBS are still called "unstable". They are just one feature behind the Azure builds at the moment.

**Comment by Symbian9** [comment]
How often OBS builds updated? Because it still has only `unstable-0.9.20190604` builds.

**Comment by dg0yt** [comment]
OBS builds need to be triggered manually at the moment.
