### ISSUE TITLE
Enhancement - Smaller export image needed

### ISSUE THREAD

**Issue by M0OJM** [OpenOrienteering/mapper#1271]
### Steps to reproduce
1.Export map as image
2.Only two options 600 & 1200dpi
3.Select 600dpi & export
### Actual behaviour
600dpi option produces a file too large to use in Routegadget which has a maximum of 200kb

### Expected behaviour
Additional options to choose different resolutions

### Configuration
Mapper Version:0.8.4
Operating System:Windows 8.1

**Comment by dg0yt** [comment]
You may not select but just enter directly any desired value.

**Comment by M0OJM** [comment]
Thanks Kai

Duh. I did not try that!!

As an aside has there been any progress on being able to select a hole &
move it? I couldn't see on github that it had been resolved & I couldn't
get it to work.

Thanks

John

**Comment by Symbian9** [comment]
> As an aside has there been any progress on being able to select a hole & move it? I couldn't see on github that it had been resolved & I couldn't get it to work.

You mean https://github.com/OpenOrienteering/mapper/issues/1101 ? (if so, then add comments in related issue thread)

**Comment by dg0yt** [comment]
No progress on edition holes (#94), unfortunately.

**Comment by dg0yt** [comment]
We do have a default list of 150, 300, 600, 1200 dpi. But even for image export, we use the default printer's list of resolutions if available (yes on Window, no on Linux).
