### ISSUE TITLE
Crash after cutting line twice

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1276]
### Steps to reproduce
1. select a line object
2. chose 'cut' tool with right mouse click
3. click at least twice on one of the line points inside the selected line
4. press undo or close the map with discarding changes
-> Mapper crashes

### Actual behaviour
After the second click, the whole line changes its color.
And there happens something interesting:
the first click cuts the line in two parts, that's ok.
the second click duplicates one part, i.e. you can move two segments from the place where the line was cut. It seems that the first cut operation is not properly finished.

### Configuration
Mapper Version: 0.84 (x64), 0.90 dev-20190622.5 (x64), latest build
Operating System: Win7x64

**Comment by lpechacek** [comment]
Thanks for the detailed report! This defect is difficult to spot. It looks to me that it has previously been reported in issue #1227.
