### ISSUE TITLE
convert contour to curves while preserving the original

### ISSUE THREAD

**Issue by otoomet** [OpenOrienteering/mapper#1288]
### Steps to reproduce
1. create/load a contour that is made of linear segments, not smooth splines
2. click 'convert to curves'

### Actual behaviour
The contour will be _replaced_ by a corresponding smoothed one

### Expected behaviour
There should be an option to preserve the original and instead of replacing it, create a smoothed copy.  Currently it is easy with small objects, just copy-paste and you have a copy.  Unfortunately the copy is not created on the exact same location (could there be a tool like _duplicate object_ that does this?).  For large and long contours it is almost impossible to move those back to the correct location.

Here is a small screenshot about just selecting the contour (in a much larger zoom level), copy-pasting it back.  It rezooms the map and places the contour way off.  Even more, I cannot select the whole contour on high zoom level, just individual nodes.

![contour-copy-paste](https://user-images.githubusercontent.com/13666380/61186116-7b526700-a616-11e9-8914-b2e69beb8951.png)

The particular usage case is simplifying lidar contours.  I'd like to preserve the original in a form of some hidden symbol, just in case I need to consult the small details, or maybe I'd like a different behavior at a different place of the map.  

### Configuration
Mapper Version: 0.8.4
Operating System: Ubuntu 18

**Comment by Zerbembasqwibo** [comment]
It's possible to first duplicate it, and than make one of them to curve. I got that answer on quite same question and I was happy with that. :) Does that fulfill your dreams?

**Comment by otoomet** [comment]
How do you duplicate and object while retaining it's position?  The image above shows what happens with copy/paste...

Otherwise it would work, perhaps not quite fulfilling the dreams...

**Comment by tobbywilson** [comment]
There's a duplicate button, or you can press D when the object is selected.
![image](https://user-images.githubusercontent.com/2275540/61191846-53d0cc80-a6f2-11e9-9eed-19a3d06bddba.png)

**Comment by otoomet** [comment]
Cool!  Thanks _tobbiwilson_! This seems to be exactly what I want.  I'll close the issue if this works for me.

I was looking around in the edit menu but could not see anything promising there.

**Comment by tobbywilson** [comment]
It's under "tools"

**Comment by otoomet** [comment]
It appears to me you have to press `d`, i.e. lower case `d`, no shift, no control (ubuntu 18).  Is this the intended behavior?   The _Tools_ menu lists `D`, i.e. shift-`d`.

**Comment by otoomet** [comment]
Worked very well.  Thank you so much!

**Comment by dg0yt** [comment]
> It appears to me you have to press d, i.e. lower case d, no shift, no control (ubuntu 18). Is this the intended behavior? The Tools menu lists D, i.e. shift-d.

The intented behaviour is to automatically follow the platform standard. In general, `D` is also the label on the physical keyboard. Complex shortcuts are written in complex terms, cf. 'Save as...', `Ctrl+Shift+S` (unless you are on a Mac :-).
