### ISSUE TITLE
Android: Toolbar buttons very small on some devices

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#1293]
### Steps to reproduce
Compare toolbar button sizes on various devices. Example:
![android-toolbar-size](https://user-images.githubusercontent.com/13567791/61577589-e35aee80-aae9-11e9-91f0-113ecc1c20fd.jpg)

### Actual behaviour
On some devices (cf. tablet above), the buttons are tiny, less than 5 mm.

### Expected behaviour
- [ ] The button should not be smaller than a certain size.
- [ ] Optionally, the button size could be a configuration option.

### Configuration
Mapper Version: 0.8.4, `dev v201906xx`
Operating System: Android

**Comment by dg0yt** [comment]
Sidenote: The Measure widget title bar and its icons are a separate story, partly visible in #787.

**Comment by lpechacek** [comment]
Ack. Feel free to cherry-pick https://github.com/OpenOrienteering/mapper/commit/df0a41dce3057d2a5877c5e2cd1840aee281cd9d and https://github.com/OpenOrienteering/mapper/commit/64b1f471377de553bd10238036b95592738b2cdf.

**Comment by Zerbembasqwibo** [comment]
Very small toolbar buttons in 0.9.0 now. Android 6.0.1

![image](https://user-images.githubusercontent.com/16168975/67633138-5378cd80-f8ac-11e9-9bc1-6e6ff3b71380.png)

**Comment by dg0yt** [comment]
@Zerbembasqwibo Please go to the settings and verify/adjust the size there.

**Comment by Zerbembasqwibo** [comment]
Size of "Åtgärdsknapp"-value solved it. Great!
