### ISSUE TITLE
File export when tags exist

### ISSUE THREAD

**Issue by mintore174** [OpenOrienteering/mapper#1299]
### Steps to reproduce
1. Map made using Open Street Map tagged objects
2. Export from mapper to .ocd
3. Use map in Condes at the canvas

### Actual behaviour
Several maps produced this way only show the tagged objects but none of the mapped objects.  The problem occurs whether the current release is used or the development version that has multiple versions of ocd output
Tag selector doesn't appear in Mapper now and deleting the objects is not possible??

### Expected behaviour
Functional ocd file is exported

### Configuration
Mapper Version: 0.8.4 and current developer version
Operating System: Mac OS 10.13.6

**Comment by dg0yt** [comment]
> Tag selector doesn't appear in Mapper now and deleting the objects is not possible??

Did you try menu Edit > Find...? It is [more powerful](https://www.openorienteering.org/mapper-manual/pages/find_objects.html) than it seems, but it includes the former "tag selector", now labeled "Query editor".

Apart from this, I don't see how tags could interfer with OCD export - they are completely ignored in this process. If you can't provide example files publicly, I can share a private folder for upload. (But I don't have Condes anyway.)

**Comment by dg0yt** [comment]
Any ideas how to let me reproduce the problem with Mapper or with OCAD Viewer?

You might also want to check if your objects were assigned to different map parts during import, although map parts should be merged during OCD export anyway.

**Comment by dg0yt** [comment]
Without more information, this cannot be handled. Please reopen when you have more information.
