### ISSUE TITLE
More friendly download page

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1314]
Mapper become more popular in my country. Increasingly, people who don’t understand English are asking me where to download Mapper. In fact, find correct package on openorienteering.org could be challenging, especially if the website's language is an incomprehensible for you. I propose to update main page, inspired by [Purple Pen website](http://purplepen.golde.org/).

### Actual behaviour
To get Mapper:
go to openorienteering.org -> Mapper -> Download Mapper -> scroll down and find Assets (in mobile version click on Assets) -> choose correct package.

### Expected behaviour
Big blue button 'Download Mapper' with download icon on first screen of main OpenOrienteering page. This button should link to current stable package for Windows x64 (the most popular platform). Smaller link to packages for other platforms.

**Comment by jmacura** [comment]
I feel like this issue belongs rather to this repo: https://github.com/OpenOrienteering/OpenOrienteering.github.io
but can't see the _Issues_ tab there...
Well, at least you can realise the desired changed via Pull request there.

In general I agree, that the process might be more straight-forward (download available directly from the website, not redirecting user to GH), but disagree with the Win64 protege approach. In ideal case, the website should check the user's current OS version and propose him/her the right version (while still keeping the small "other versions" somewhere around). I quite like the way e.g. LibreOffice handles it: https://www.libreoffice.org/download/download/

**Comment by dg0yt** [comment]
OpenOrienteering never tried to be only Mapper, although so far effectively it is just that.

With regard to the actual behaviour, there is a "Downloads" button on the latest news item.

With regard to the desired behaviour, it should link the most likely match, not simply Win64. After all, Mapper is quite popular for macOS and Android.

**Comment by dg0yt** [comment]
Done on openorienteering.org, for the latest blog entry, and for the stable release on the Mapper page.  
For Linux the button leads to the OBS download selection page.
For Windows, macOS and Android, the button selects x64 installer, DMG and arm-v7eabi APK, respectively. These are the most frequently downloaded variants.

**Comment by dg0yt** [comment]
For reference: 
https://github.com/OpenOrienteering/OpenOrienteering.github.io/commit/e5b074e13a9ccc75df537cddcea71fd82c73fcdd
