### ISSUE TITLE
Ubuntu 16.04 software signature expired

### ISSUE THREAD

**Issue by dorienj** [OpenOrienteering/mapper#1319]
Routine Ubuntu package upgrade fails, complaining that it requires installation of untrusted packages.

Output of sudo apt-get upgrade includes:
Reading package lists... Done
W: http://repo.acestream.org/ubuntu/dists/trusty/InRelease: Signature by key E1254F21D636B7EFDE41D2AF50E2BCF0E3805CD8 uses weak digest algorithm (SHA1)
W: GPG error: http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04  InRelease: The following signatures were invalid: KEYEXPIRED 1538036441
W: The repository 'http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04  InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Index of OpenSUSE repositories https://drpmsync.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04/  suggests that this is the home of the OpenOrienteering Mapper code.

My understanding of this stuff is limited, but it appears that the package signature needs updating.

**Comment by dg0yt** [comment]
Do you really still use Ubuntu 16.04? It is no longer on my list for Mapper v0.9...

> ~~~
> Output of sudo apt-get upgrade includes:
> Reading package lists... Done
> W: http://repo.acestream.org/ubuntu/dists/trusty/InRelease: Signature by key E1254F21D636B7EFDE41D2AF50E2BCF0E3805CD8 uses weak digest algorithm (SHA1)
> ~~~

This unrelated to the Mapper repository.

> ~~~
> W: GPG error: http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04 InRelease: The following signatures were invalid: KEYEXPIRED 1538036441
> W: The repository 'http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04 InRelease' is not signed.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ~~~

AFAICT this means that you need to import an updated key:
~~~
wget -nv https://download.opensuse.org/repositories/home:dg0yt/Ubuntu_16.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
~~~

References:  
https://software.opensuse.org//download.html?project=home%3Adg0yt&package=openorienteering-mapper  
https://help.ubuntu.com/community/SecureApt

**Comment by dorienj** [comment]
Thank you!
