### ISSUE TITLE
Lost georeference on Android when phone crash before drawing or saving file

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#1322]
### Steps to reproduce
1. Go to forest with georeferenced map in Android 0.8.4, external GPS connected via Bluetooth GPS and turn on GPS in app
2. Before starting to draw or save, cause phone to crash (or accidently reboot it...)
3. Turn on device again, start up map

### Actual behaviour
Not possible to start GPS again. It seems like georeferencing gets lost, unfortunately I had to fix this so I could get a new (old) copy of the map from hoe computer and I didn't backuped the file to check what happend. When you put the same file back it works again. [Test at home] Also if you take the file from Android to computer, open, it looks OK, close without saving, put back to Android device, it works again... All these files are with same date stamp.

### Expected behaviour
The file should not lose the possibility to use GPS after such crash.

### Configuration
Mapper Version: 0.8.4
Operating System: Android

**Comment by dg0yt** [comment]
Android has some specific behaviours (and that's why there were corrupted transfers back to PC in the past). But neither is a file modified when it is not saved, nor did any issues persist after a reboot.

> Not possible to start GPS again. 

Do you mean the button is disabled? Or is enabled, but you see no reaction? Are you talking about a single incident, or were you actual able to reproduce the issue?

BTW you can always try the complete-map example. It is georeferenced, so the button should be enabled, although your position won't be on the map.

**Comment by Zerbembasqwibo** [comment]
The button is disabled. Yes, I can reproduce it.

This happend to me two times in the forest.

I reproduced it agian now, same result. I tried Complete-map example and in
that one it works (GPS is enabled). I tried my own map again, still
disabled.

Den lör 10 aug. 2019 kl 23:03 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
> I reproduced it agian now, same result. I tried Complete-map example and in
that one it works (GPS is enabled). I tried my own map again, still
disabled.

And this happens after a reboot, or after terminating the app?

**Comment by dg0yt** [comment]
There probably won't be any fixes to 0.8.4 anyway. The dev branch is pretty close to releasing 0.9.0, some components have significant changes and updates. Could you please also test with the latest dev pre-release?

**Comment by Zerbembasqwibo** [comment]
Yes, after reboot. I turned off the phone, and I did it before I saved or
draw anything.

Den lör 10 aug. 2019 kl 23:17 skrev Kai Pastor <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment]
I'll try exact same with latest!

Den lör 10 aug. 2019 kl 23:20 skrev Kai Pastor <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment]
Sorry, have to stop for now. I installed dev on computer, opened the map,
saved. Transferred it to device and opened with same dev. It crases. :(

So I cannot see if that "bug" appears.

Den lör 10 aug. 2019 kl 23:21 skrev Sven Lundbäck <sven.lundback@gmail.com>:

**Comment by dg0yt** [comment]
Maybe you can at least provide me a test file with the same georeferencing...

**Comment by Zerbembasqwibo** [comment]
Check your email.

Den sön 11 aug. 2019 kl 00:10 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
I think I resolved the crash in `dev` (#1303). Now the map loads, and georeferencing works also after killing and restarting the app in my tests. I will make a new release, but you will need to wait a little bit, as I have to go through continuous integration four times, and I can't always stage the next run immediately.

**Comment by dg0yt** [comment]
Please test https://github.com/OpenOrienteering/mapper/releases/tag/v20190813.2. In my testing, it does not crash, and it does not loose georeferencing with internal GPS.

**Comment by dg0yt** [comment]
> Please test https://github.com/OpenOrienteering/mapper/releases/tag/v20190813.2.

Could you do that please?

**Comment by Zerbembasqwibo** [comment]
I am short of time, but I come back when I tested. If not any else is faster.

**Comment by dg0yt** [comment]
Considering this as closed.

**Comment by Zerbembasqwibo** [comment]
Confirmed closed in 0.9.0. Great!

Den lör 26 okt. 2019 kl 16:51 skrev Kai Pastor <notifications@github.com>:
