### ISSUE TITLE
GeoTiff exported from OCAD not recognized as georeferenced template

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1335]
> NOTE: This issue reported to me by user on Facebook.

### Steps to reproduce

1. Generate Tiff via DEM tool in *OCAD*;
2. Import resulted Tiff into *Mapper* as template.

### Actual behaviour

*Mapper* not recognize such Tiff as GeoTiff.

![pic.1](https://i.imgur.com/tU6pdun.png)

Here is what I see when try import this Tiff into *QGIS* as «Raster Layer»

![pic.2](https://i.imgur.com/SSmatjt.png)

### Expected behaviour

Mapper should recognize *OCAD*-generated Tiff's as GeoTiff (if generated Tiff is really GeoTiff; I'm not sure).

### Configuration

Mapper Version: `dev v0.9.20190820.3`

Operating System: all

### Sample file

This sample of OCAD-generated Tiff (GeoTiff?) provided by original user:

- `Untitled_DSM_LasIntensity.tif` - https://drive.google.com/drive/folders/1ohKIMbx3foJ_AhjO3xeQIBtpiUD9EnhU

**Comment by dg0yt** [comment]
I doubt there is georeferencing information in this file. Your QGIS screenshot doesn't indicate that QGIS would know better (and it relies on GDAL, too).

`listgeo` reports the following:
~~~
TIFFFetchNormalTag: Warning, ASCII value for tag "Software" does not end in null byte.
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         0                 0                 0                
      ModelPixelScaleTag (1,3):
         0                 0                 0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      End_Of_Keys.
   End_Of_Geotiff.

Projection Linear Units: User-Defined (1.000000m)

Corner Coordinates:
Upper Left    (       0.000,       0.000)
Lower Left    (       0.000,       0.000)
Upper Right   (       0.000,       0.000)
Lower Right   (       0.000,       0.000)
Center        (       0.000,       0.000)
~~~

And `file` says the following:
~~~
Untitled_DSM_LasIntensity.tif: TIFF image data, little-endian
~~~
whereas my test file produces
~~~
2920.tiff: TIFF image data, little-endian, direntries=22, height=5000, bps=294, compression=deflate, PhotometricIntepretation=RGB, width=5000
~~~

So either there is no more meta-data, or it is invalid. "TIFFFetchNormalTag: Warning, ASCII value for tag "Software" does not end in null byte." is a quite suspicious warning.

I can't do anything more from this information. If it doesn't even work in QGIS, this is more likely be a bug in the creating software. If it is from the OCAD software, I would assume OCAD would be glad to learn about it and fix it, if there are more customers using QGIS.
