### ISSUE TITLE
failed check for trailing question on weblate

### ISSUE THREAD

**Issue by leela52452** [OpenOrienteering/mapper#1339]
both translation and source string end with question mark.
however, it shows as failed check.
see https://hosted.weblate.org/translate/openorienteering/mapper/fr/?checksum=40472363ed6197f4

**Comment by dg0yt** [comment]
Thanks for reporting. After a quick review of the French translation file, I tried inserting ' ' (i.e. a single space character) before the question mark, and this seems to be the solution for French.

PS: Please take a look at the comments or history when changing translations. I will probably revert https://hosted.weblate.org/translate/openorienteering/mapper/de/?checksum=91faf1b42309c13a again... until I eventually find a good occassion to change the English source string.
