### ISSUE TITLE
Mirror function

### ISSUE THREAD

**Issue by skovorodochka** [OpenOrienteering/mapper#1342]
### Steps to reproduce
1. Add mirror function.

### Actual behaviour
I have some part of map and need to copy/paste and, the main step, mirror it. 

### Expected behaviour
Mirror function for any object or group of objects is available.

### Configuration
Mapper Version: 0.8.4
Operating System: Windows

**Comment by dg0yt** [comment]
Thanks for your feedback. This is probably a duplicate of #1262.
