### ISSUE TITLE
Enhancement: corner point editing

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1345]
### Problem statement
It is currently possible to establish corner points on a smooth curve by moving curve handles while holding Shift key down. In mobile version Snap button serves the same purpose. The functionality looks appropriate at first glance. However, in practice editing of corner points involves following steps: choose point for editing - look at the point and **realize** that it is a corner point - press Shift key / activate Snap button - make the intended handle adjustment - release Shift key / deactivate Snap button. After a few hours of field work the editing operation feels somewhat cumbersome as forgetting to activate Shift/Snap results in unintended move of the other curve handle and additional operations to rectify the erroneous step.

### Proposal
Neighboring curve handles are independent at corner point as long as their angle is < 180°. When the angle between handles reaches value close to 180° during editing the handles "click in" and the point turns into normal (smooth) point. Then corner point editing operations would work as follows:
1) Create corner point - hold down Shift / activate Snap, move handle
2) Adjust one of the curves meeting at corner point - move handle
3) Turn inner (convex) corner into outer (concave) one and vice versa - move handle while holding Shift / Snap
4) Remove corner point - align handles in straight line during editing, they start moving together

**Comment by lpechacek** [comment]
First implementation illustrating what I mean with the above proposal. Feedback on the new functionality is welcome.

**Comment by jmacura** [comment]
Now when I can see it on the video, I think it's quite cool and elegant! Thumb up.

**Comment by lpechacek** [comment]
As an afterthought... on a dashed line, do we want to make the newly created corner point a dash point?
