### ISSUE TITLE
Crash when opening map editor window

### ISSUE THREAD

**Issue by Torpedeo** [OpenOrienteering/mapper#1366]
### Steps to reproduce
1.I've used the program for a few days when it suddenly crashed.
2.I haven't been able to restart the progra. I've deleted the program-reinstalled etc.
3.

### Actual behaviour
When I start the program I the click on "create map" . I chose the "1:10000 scale". I chose the "ISOM2017_1000"
I click "create"
The program shuts down and disappears.
The same thing happens when I try to "open" an excisting map.

### Expected behaviour
The program should start as before

### Configuration
Mapper Version: 0.8.4
Operating System: Windows 10 64 bits

**Comment by dg0yt** [comment]
Could you please try to remove the OpenOrienteering settings from the Windows registry? 
The settings path is `HKEY_CURRENT_USER\Software\OpenOrienteering.org\Mapper`.
You may do that either in `regedit`, or at a Command Prompt using  
`reg delete HKEY_CURRENT_USER\Software\OpenOrienteering.org\Mapper`.

**Comment by Torpedeo** [comment]
yes!
that worked!
thank you!

/Peter

Den mån 23 sep. 2019 kl 20:05 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
Thanks for your confirmation. I don't the error is in our source code. But IIRC it is not the first time, and we may need to find a way to discover and stop this situation.

**Comment by Torpedeo** [comment]
The same happened to me again and now I know when.
It happens when I try to change the scale of the map in settings.

/Peter

Den mån 23 sep. 2019 kl 21:14 skrev Kai Pastor <notifications@github.com>:
