### ISSUE TITLE
Android: Self-snapping behaviour on v2019090915.17

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1373]
### Steps to reproduce
1. Draw a line feature.
2. Try to slightly adjust position of a point of this line

### Actual behaviour
If the new position is to close to the original position, the point snaps back to the original position.

### Expected behaviour
Remove that behaviour. Slight adjustments shall be possible. 

(This behavior also snaps short tangents back to its point and thus makes an unwanted corner on that point)

### Configuration
Mapper Version: v2019090915.17
Operating System: only on Android. Different aka expected behavior on Windows7

**Comment by lpechacek** [comment]
Oh yeah, that's what I've also observed but attributed it to the new hardware I'm using. I suspect the misbehavior has something to do with the slow movement involved in slight position adjustments. Fast long moves work reliably.

![snapback mp4](https://user-images.githubusercontent.com/5584406/66189954-38d77e00-e68b-11e9-94cb-6cdb7b5e9163.gif)

**Comment by dg0yt** [comment]
Confirmed. Only on Android, not on PC even in touch mode. I wonder if it is related to the Android specific code in settings (in combination with recent code changes):

https://github.com/OpenOrienteering/mapper/blob/e1794f7ecb5edf052b3374d4d07ff8587ee8eafa/src/settings.cpp#L107-L117

**Comment by dg0yt** [comment]
Bad news: There is a "mouse release event" coming from Qt if you don't move the finger quick enough over some minimal distance. So it is not a regression in Mapper. I need to find out if this behavioural change in Qt is intentional and can be worked around, or if it is a bug. (I doubt that it is coming from Android itself.)

**Comment by dg0yt** [comment]
Cf. https://bugreports.qt.io/browse/QTBUG-72408

**Comment by jmacura** [comment]
I must note that this issue is still present in the last pre-release I found on Github (dev v20190915.17)
Tested on LG Q7 with Android 8.1 (O).

**Comment by dg0yt** [comment]
Well, this issue was reported against this version, and it was closed with a commit from Oct 5, 2019. 

FTR, QTBUG-72408 was just closed by reverting the offending change in Qt, so I may revert our workaround in a future release.

**Comment by lpechacek** [comment]
@jmacura, yes, that pre-release is buggy. Upcoming v0.9 will have the fix.
