### ISSUE TITLE
Lighten area object when cutting

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1379]
### Steps to reproduce
1. At this moment objects darken when selected.
2. That is beneficial at is obvious which object is chosen.
3. However when cutting areas - the darkening makes it harder to see draft in background.

### Expected behaviour
4. I suggest to lighten back the color of object when _Cut object_ or _Cut hole_ commands are selected.
5. This will ensure better cutting.

### Configuration
Mapper Version: 0.8.4
Operating System: Android

**Comment by lpechacek** [comment]
Aleš, would availability of "Hatch areas" or "Baseline view" display in the mobile version solve your issue? I can imagine that baseline view would be useful for aerial photo analysis in the field as well.

**Comment by ollesmaps** [comment]
Libor, that would settle it down, I assume. Thanks for asking :)

As a a side note: 
1. When .omap gets saved on PC i Hatch areas mode. 
2. This mode gets also into Android.
3. However there is no way how to switch to normal mode on Android.

**Comment by dg0yt** [comment]
> This mode gets also into Android.

@ollesmaps Is this a statement about 0.9.0?

**Comment by ollesmaps** [comment]
@dg0yt It is not. I have not tried the newest one yet.

**Comment by dg0yt** [comment]
@ollesmaps Your issue is reported as GH-1172. Please ping there.

**Comment by lpechacek** [comment]
@dg0yt, below is a bottom panel arrangement I've been using for about eighteen months now. Draw on template and Clear temporary marks buttons are hidden in menus under corresponding Draw on template and Record trace buttons. Space I've freed up I'm using for Hatch areas view and Baseline view buttons. The large Pan view button is not part of the proposal for the moment.

It seems to me that more users would benefit from these changes. I'll place a pull request soon.

![image](https://user-images.githubusercontent.com/5584406/68549048-253ed600-03f4-11ea-84c4-57c3fef1045b.png)

For the record, I've seen (professional) mappers avoid using area symbols and draw only boundary lines during fieldwork. They use color dots to distinguish the area type. The method looks like a substitute for missing baseline view to me.

**Comment by dg0yt** [comment]
@lpechacek This is GH-1172 stuff IIUC. Can we move to that issue?

**Comment by lpechacek** [comment]
I beg to disagree. In GH-1172 the poor user ended up with essentially empty display after leaving the map in baseline view display mode and moving it over to Android device. Here the user asks for an enhancement which would help him work with dark colored templates. While my proposal aims at fixing both with one change, the issue content is not the same. It is only the "side note" few comments above that duplicates the older issue.

And thanks for the reminder about GH-1172. I thought it has been resolved by automatic switch to normal mode upon map loading. My pull request will reference both items then.

**Comment by dg0yt** [comment]
@ollesmaps For the record, we didn't implement lightening of area objects when cutting but added  baseline view and area hatching to the Android user interface. Re-open this issue if you still want your original proposal to be implemented.

**Comment by ollesmaps** [comment]
@dg0yt I understand. Baseline and Hatch view mode are very welcomed solutions!
