### ISSUE TITLE
KMZ export

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#138]
**puzzlepaint reported on Sourceforge [[tickets:#138](https://sourceforge.net/p/oorienteering/tickets/138)]:**

Add kmz export capability, optionally only for selected objects. For georeferenced maps only. 
The internal process would be to export the map as raster image and cut it into tiles.

This can be used for example to display the map in Google Earth as overlay or use it as custom map on some Garmin devices.

**Comment by dominikzalewski** [comment]
I have already written a piece of code to do that for 'Simple Course'. I was using it to export automatically to KML in order to upload it to my Suunto Ambit 3 watch and use that course for training - the watch simply beeps when I'm at the control and I don't have to setup anything in the woods upfront.

The code is of very poor quality, but still maybe it will be useful to put it here. I will do that as soon as I get back to the place where I have my other computer with that code.

Having said that, I  have given enough thought on how this process of preparing trainings could be enhanced. I actually come to the conclusion that maybe it would be better to have a proper OCD export with georeferencing in OO Mapper, so that we could already use existing GPX export functionality in Purple Pen (after loading the OCD map into that other program).

**Comment by harzol** [comment]
This can be very useful for me. 

Today I'm using OCAD to convert omap file to kmz.
First I have to save as OCAD file, than I can export KMZ file from OCAD.

But now I'm faceing an issue when I save ocad file in oomapper. - "Coordinates are adjusted to fit into the OCAD 8 drawing area"

How is it possible to turn off this coordinate adjustion?

**Comment by dg0yt** [comment]
> Today I'm using OCAD to convert omap file to kmz.
> First I have to save as OCAD file, than I can export KMZ file from OCAD.

Thanks to GDAL, we do have KMZ export via File > Export as... > Geospatial vector data. However, it is probably not what you will expect after using the other software, or from the first post here. 

(I recently read how MapRun wants maps to be exported to KMZ: raster tiles indeed, not vector data.)

> But now I'm faceing an issue when I save ocad file in oomapper. - "Coordinates are adjusted to fit into the OCAD 8 drawing area"
> 
> How is it possible to turn off this coordinate adjustion?

Don't use OCD 8. If you think there is a bug in loading or save your file, please open a separate issue.

**Comment by SimonStarkey** [comment]
This would be a useful feature with our increasing use of MapRun through lockdown.  Currently exporting map as an image then re-referencing the map in the MapRun utility

**Comment by dg0yt** [comment]
> This would be a useful feature with our increasing use of MapRun through lockdown. 

Sure. Implementing export should be more feasible once I can load the result into Mapper again. So I'm working on KMZ reading at the moment, in order to verify the expected results.
https://github.com/OpenOrienteering/mapper/pull/1793
https://github.com/OpenOrienteering/superbuild/pull/85

> Currently exporting map as an image then re-referencing the map in the MapRun utility.

There is also a webservice which accepts JPG+world file to create KMZ, but you must temporarily change the georefencing of the map before JPG export:
http://maprunners.weebly.com/maps---kmz-files.html 
http://www.p.fne.com.au/rg/cgi-bin/o-utils.cgi

**Comment by SimonStarkey** [comment]
Thanks for the info.

Simon

**Comment by dg0yt** [comment]
Implementation notes.
- The tile size is fixed at 512x512 pixels.
- The image format is fixed as JPG, quality 75/100.

KMZ requirements for MapRunF (http://maprunners.weebly.com/maps---kmz-files.html):
- [x] 512x512 tiles.
- [x] 150dpi: User choice.
- [x] KMZ size max 1 MB: Not checked, but indirectly controlled by user via resolution and map area.

KMZ requirements for Garmin (https://support.garmin.com/en-IE/?faq=FtEncUXbaE0xE04yZ7gTq5):
- [x] KML file named `doc.kml`.
- [x] Image format is JPEG.
  - [ ] (unknown) without progressive image.
- [x] Image size not over 1 megapixel.
- [x] Image size less than 3 MB: Not checked, but reasonable assumtion for tile size and quality parameter.

**Comment by dg0yt** [comment]
> * [x] 150dpi: User choice.

Not yet entirely true for Windows: #1815

**Comment by dg0yt** [comment]
Oh, MapRunF is much more restricted than expected:
> Error: Error in the file content - Error in the KMZ file format - (Exception: Tiles in the KMZ file need to be named as a grid of files/tile_x_y.jpg - Instead found: files/0.jpg)
