### ISSUE TITLE
No georeferencing information in Geotiff with cyrillic characters

### ISSUE THREAD

**Issue by EugeneAzhogin** [OpenOrienteering/mapper#1380]
When I am trying to open a template in the GeoTIFF format, Mapper do not recognize georeferencing information if the file path contains a cyrillic characters.

### Steps to reproduce
1. Create a GeoTIFF image with name "google.tif" and place it in folder "D:\Temp\template\". The full path is "D:\Temp\template\google.tif"
2. In Mapper with new map choose menu item "Templates -> Open template...".
3. In the opening dialog the image is recognized as "Georeferenced (GeoTIFF)".
4. Rename file to "google_мск.tif" ('мск' is Russian letters) so the full path is "D:\Temp\template\google_мск.tif".
5. Again, In Mapper with new map choose menu item "Templates -> Open template...".
6. In the opening dialog the image is not recognized georeferencing information and it option is disabled.
7. Rename folder to "template_мск" ('мск' is Russian letters) so the full path is "D:\Temp\template_мск\google.tif".
8. Again, In Mapper with new map choose menu item "Templates -> Open template...".
9. In the opening dialog the image is not recognized georeferencing information and it option is disabled.

### Actual behaviour

If path to the template image file contains a cyrillic characters, Mapper do not recognize georeferencing information in it.

### Expected behaviour

Mapper should recognize georeferencing information in template image file with any path.

### Configuration
Mapper Version: dev v20190915.17
Operating System: Windows 10

**Comment by dg0yt** [comment]
Thanks for reporting! This should be fixed in the next (pre-) release.
