### ISSUE TITLE
OSM template not working in dev v20190915.17

### ISSUE THREAD

**Issue by huirad** [OpenOrienteering/mapper#1383]
#### Preconditions
0. OpenOrienteering Mapper dev v20190915.17
1. Starting point is a non-georeferenced map with some contour lines (OCad Format)
2. Import this map successfully
3. Now add as template a .tif georeferenced in Gauss-Krüger, Zone 4 -> chose to geo-reference the map also as Gauss-Krüger
4. Shift the map center a bit to improve the alignment
5. Save that map as reference
#### Here comes the issue
6. Attempt to load an OSM extract as template - a dialog appears asking for the coordinate system: real or map ("Karte"). No matter what I chose, I do not get any reasonable template
#### Workaround with OpenOrienteering Mapper 0.8.4
7. Open the map stored in step 5 with v 0.8.4: It complains a bit that there will be some data lost due to import from new file format. Nevertheless, the map is loaded, contour lines are still there, geo-reference is still auss-Krüger, Zone 4, the .tif template is still there.
8. Attempt to load the same OSM extract as template - works perfectly fine!
9. Now store this map
#### Try again with OpenOrienteering Mapper dev v20190915.17
10. Close OOM 0.8.4 and start dev v20190915.17. 
11. Open the map stored in step 9
Now I get the following error message "Warnung beim Laden der Vorlage 'map.osm':
Kann Bezugssystem "+proj=tmerc +lat_0=0 +lon_0=12 +k=1.000000 +x_0=4500000 +y_0=0 +ellps=bessel +datum=potsdam +units=m +no_defs +wktext" für GDAL nicht einrichten: 5
Konnte 247 Objekte nicht laden, Grund: Koordinatentransformation kann nicht bestimmt werden: Cannot find coordinate operations from `EPSG:4326' to `ENGCRS["Local SRS",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]'"

### Actual behaviour
Cannot load an OSM map as template in dev v20190915.17 if the map is already georeferenced as Gauss-Krüger, Zone 4

### Expected behaviour
OSM map can successfully be loaded as template in dev v20190915.17 if the map is already georeferenced as Gauss-Krüger, Zone 4.  Similar to working behaviour in 0.8.4.

### Configuration
Mapper Version: OpenOrienteering Mapper dev v20190915.17
Operating System: Windows

![grafik](https://user-images.githubusercontent.com/4027039/67006343-36424300-f0e5-11e9-8ec6-773ae5f14c7d.png)

**Comment by dg0yt** [comment]
Thank you very much for reporting this issue. I was able to reproduce this issue on Windows. I guess this is another issue related to the PROJ modernization.

**Comment by dg0yt** [comment]
> I guess this is another issue related to the PROJ modernization. 

In fact, another result of the bug I found in PROJ, "potsdam" misspelled as "postdam"...
