### ISSUE TITLE
OCAD import - cutted line parts visible

### ISSUE THREAD

**Issue by Andreasox** [OpenOrienteering/mapper#1384]
### Steps to reproduce
1. Cut a line to hide some parts of it, eg. a meridian, in OCAD
2. Open the OCAD file in Mapper
3. Check visibility of cutted line parts

### Actual behaviour
All line parts are displayed with the line symbol

### Expected behaviour
Cutted line parts should not be visible

### Configuration
Mapper Version: 0.8.4
Operating System: macOS 10.14.6

**Comment by krticka** [comment]
Just to be sure, is the cutted line in OCAD virtual gap? If yes, this functionality is not implemented yet. See #150 .

**Comment by Andreasox** [comment]
Yes I thought I had seen it before. So I close this issue as duplicate.
