### ISSUE TITLE
Failed to transform the coordinates for EPSG 5514

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#1392]
### Steps to reproduce
1. Have an map project in EPSG 5514 in Mapper 0.8.4. Project is using as basemap contours in OCD and some cadastral data in shapefile, all in EPSG 5514.
2. Open the same project in Mapper 0.9.0
3. Basemaps in shapefile are lost, 0.9.0 is unable to transform the coordinates.

### Actual behaviour
When opening, the map import generated warnings:
Warnings when loading template 'HraniceParcel.shp':
Unable to load 582 objects, reason: Failed to transform the coordinates.
Warnings when loading template 'StavebniObjekty.shp':
Unable to load 103 objects, reason: Failed to transform the coordinates.

I made few test importing shapefile into the project. In EPSG 5514 data have typically XY coordinates negative, however after the import there seems to be some axis switch for one coordinate to positive sector and data are rotated by 90°. Moreover, it is not simple XY axis switch as coordinates have also different values. Maybe problem related to new PROJ6?

[testdata.zip](https://github.com/OpenOrienteering/mapper/files/3761647/testdata.zip)

### Expected behaviour
It should work in the same way as in 0.8.4, basemaps in shapefile are loaded. 

### Configuration
Mapper Version: 0.9.0
Operating System: Win64

**Comment by dg0yt** [comment]
Thanks for reporting. The switch to PROJ6 is likely to cause some glitches. PROJ is much more accurate, including axis order. Sometimes it is also more dependant on "datumgrid" files for coordinate operations which worked (but less precises) in previous versions.

I tried to load the data into an empty map, and I observe the suggested PROJ4 strings:
~~~
SHP data in Mapper v0.9.0 (PROJ 6.2):
+proj=krovak +axis=swu +lat_0=49.5 +lon_0=24.8333333333333  +alpha=30.2881397222222  +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel                             +units=m +no_defs

SHP data in Mapper v0.8.4 (PROJ 4.9):
+proj=krovak           +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel                             +units=m +no_defs 

https://epsg.io/5514:
+proj=krovak           +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs 
~~~

So we have extra axis info now. If I accept the proposed georeferencing in v0.9.0, I receive a map with axis swapped and a declination of app. 90°.

**Comment by krticka** [comment]
X have East and Y north orientation, so the correct axis info should be +axis=enu according to [PROJ documentation](https://proj.org/usage/projections.html). There is also a note that +axis argument does not work with the proj command line utility.

**Comment by dg0yt** [comment]
`+axis=swu` ist wrong order indeed. s instead of n and w instead of e indicate a difference in sign.

I'm debugging into PROJ 6. I'm now at the spot where coordinates are transformed. PROJ determined these average coordinates for the first geometry: 
avgx -686912.9557692307
avgy -969483.4907692306

With these coordinates, it tries to find the best transformation from a list of four, each with bounds like:
minx 911137.7509007914
miny 159523.53474957866
maxx 1353322.8862039025
maxy 951555.9378801632

I guess you see why it fails...  I just can't tell what is wrong: either it should change the sign for the geometry's coordinates first, or the transformation should have bounds with a different sign.

**Comment by dg0yt** [comment]
Actually I'm looking into GDAL/OGR, not PROJ. 

Axis order sw is what OGR reports from the data source (WKT2):
~~~
PROJCRS[ S_JTSK_Krovak_East_North",
  BASEGEOGCRS["GCS_S-JTSK",
    DATUM["System of the Unified Trigonometrical Cadastral Network",
      ELLIPSOID["Bessel 1841",6377397.155,299.1528128,LENGTHUNIT["metre",1]],
      ID["EPSG",6156]
    ],
    PRIMEM["Greenwich",0,ANGLEUNIT["Degree",0.0174532925199433]]
  ],
  CONVERSION["unnamed",
    METHOD["Krovak",ID["EPSG",9819]],
    PARAMETER["Latitude of projection centre",49.5,ANGLEUNIT["Degree",0.0174532925199433],ID["EPSG",8811]],
    PARAMETER["Longitude of origin",24.8333333333333,ANGLEUNIT["Degree",0.0174532925199433],ID["EPSG",8833]],
    PARAMETER["Co-latitude of cone axis",30.2881397222222,ANGLEUNIT["Degree",0.0174532925199433],ID["EPSG",1036]],
    PARAMETER["Latitude of pseudo standard parallel",78.5,ANGLEUNIT["Degree",0.0174532925199433],ID["EPSG",8818]],
    PARAMETER["Scale factor on pseudo standard parallel",0.9999,SCALEUNIT["unity",1],ID["EPSG",8819]],
    PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],
    PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]
  ],
  CS[Cartesian,2],
  AXIS["southing",south,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],
  AXIS["westing",west,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]
]
~~~

However, the .prj files contain:
~~~
PROJCS["S_JTSK_Krovak_East_North",
  GEOGCS["GCS_S-JTSK",
    DATUM["D_S_JTSK",
      SPHEROID["Bessel_1841",6377397.155,299.1528128]
    ],
    PRIMEM["Greenwich",0],
    UNIT["Degree",0.017453292519943295]
  ],
  PROJECTION["Krovak"],
  PARAMETER["latitude_of_center",49.5],
  PARAMETER["longitude_of_center",24.83333333333333],
  PARAMETER["azimuth",30.28813972222222],
  PARAMETER["pseudo_standard_parallel_1",78.5],
  PARAMETER["scale_factor",0.9999],
  PARAMETER["false_easting",0],
  PARAMETER["false_northing",0],
  UNIT["Meter",1]
]
~~~

**Comment by dg0yt** [comment]
Opened https://github.com/OSGeo/PROJ/issues/1690 for the axis order issue.

**Comment by dg0yt** [comment]
PROJ fixed the axis order heuristics for `"S_JTSK_Krovak_East_North"`, and this solves that issue.

Now we have two signifcant bugs, Potsdam datum and Krovak axis order, to be fixed in PROJ 6.2.1. 
I don't know when PROJ 6.2.1 will be released. If a solution is urgent for you, I could integrate that patch on top of PROJ 6.2.0.

**Comment by dg0yt** [comment]
@krticka  BTW we still override `+init=epsg:5514` with:  
+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +pm=greenwich +towgs84=542.5,89.2,456.9,5.517,2.275,5.516,6.96 +units=m +no_defs
(cf. #542)

Now PROJ has a new database of authorative data. The new data expressed in old-style representation still differs:
+proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs +type=crs

This is what we override at the moment. But we will have to move away from these strings, to plain references like EPSG:5514 for authorative data and WKT2 for custom specifications. I don't think it will be feasible to continue with overriding forever. If PROJ or EPSG is not right, someone should take to get it fixed.

**Comment by krticka** [comment]
Thanks for solving this issue.
I agree that overriding the PROJ is not good for further development. But +towgs84=589,76,480,0,0,0,0 is old military transformation key [http://epsg.io/15965](http://epsg.io/15965) which is not suitable to use because of low precision.

PROJ 5.2 in my QGIS offers also these transformations:
[http://epsg.io/1623](http://epsg.io/1623) this one is standard in GIS applications for Czechia and is OK
[http://epsg.io/4836](http://epsg.io/4836) for area of Slovakia
[http://epsg.io/5239](http://epsg.io/5239) replaces 1623, but very similar

+towgs84=542.5,89.2,456.9,5.517,2.275,5.516,6.96 which we now use is relatively new sub meter transformation which can be used for area of former Czechoslovakia (mean positional error <0.7 m).

My question is how is +towgs84 argument built in new PROJ database? Is the +towgs84=589,76,480,0,0,0,0 the only option now?

**Comment by dg0yt** [comment]
I think it is coming from the authorative EPSG dataset. In PROJ source code/database, it is probably now in `data/sql/helmert_transformation.sql`:

~~~
INSERT INTO "helmert_transformation" VALUES('EPSG','15965','S-JTSK to WGS 84 (3)','Derived at 6 stations.','For military purposes. Accuracy 4m, 2m and 3m in X, Y and Z axes.','EPSG','9603','Geocentric translations (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1306',6.0,589.0,76.0,480.0,'EPSG','9001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NIMA-Cze',0);
~~~

But this is a topic for https://github.com/OSGeo/PROJ/issues/233 or a new PROJ issue.

**Comment by krticka** [comment]
`data/sql/helmert_transformation.sql` contains most of the transformations:

<pre>363: INSERT INTO "helmert_transformation" VALUES('EPSG','1622','S-JTSK to ETRS89 (1)','May be taken as approximate transformation S-JTSK to WGS 84 - see code 1623. Replaced by S-JTSK/05 to ETRS89 (1) (code 5226) in 2009.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4258','EPSG','1079',1.0,570.8,85.7,462.8,'EPSG','9001',4.998,1.587,5.261,'EPSG','9104',3.56,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CUZK-Cze',0);
364: INSERT INTO "helmert_transformation" VALUES('EPSG','1623','S-JTSK to WGS 84 (1)','Parameter values from S-JTSK to ETRS89 (1) (code 1622). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation. Replaced by S-JTSK to WGS 84 (5) (code 5239).','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1079',1.0,570.8,85.7,462.8,'EPSG','9001',4.998,1.587,5.261,'EPSG','9104',3.56,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EPSG-Cze',0);
365: INSERT INTO "helmert_transformation" VALUES('EPSG','1624','S-JTSK to ETRS89 (2)','May be taken as approximate transformation S-JTSK to WGS 84 - see code 1625.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4258','EPSG','1211',1.0,559.0,68.7,451.5,'EPSG','9001',7.92,4.073,4.251,'EPSG','9104',5.71,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'UGKK-Svk',1);
366: INSERT INTO "helmert_transformation" VALUES('EPSG','1625','S-JTSK to WGS 84 (2)','Parameter values from S-JTSK to ETRS89 (2) (code 1624). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1211',1.0,559.0,68.7,451.5,'EPSG','9001',7.92,4.073,4.251,'EPSG','9104',5.71,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EPSG-Svk',1);
695: INSERT INTO "helmert_transformation" VALUES('EPSG','4827','S-JTSK to ETRS89 (4)','Derived at approximately 700 points. Scale difference incorporated into rotation matrix. Replaces S-JTSK to ETRS89 (3) (code 4829) to use more common method. May be taken as approximate transformation S-JTSK to WGS 84 - see code 4836.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4258','EPSG','1211',1.0,485.0,169.5,483.8,'EPSG','9001',7.786,4.398,4.103,'EPSG','9104',0.0,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'UGKK-Svk',0);
696: INSERT INTO "helmert_transformation" VALUES('EPSG','4828','S-JTSK to WGS 84 (4)','Parameter values from S-JTSK to ETRS89 (4) (code 4827). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1211',1.0,485.0,169.5,483.5,'EPSG','9001',7.786,4.398,4.103,'EPSG','9104',0.0,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EPSG-Svk',1);
704: INSERT INTO "helmert_transformation" VALUES('EPSG','4836','S-JTSK to WGS 84 (4)','Parameter values from S-JTSK to ETRS89 (4) (code 4827). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation.','For applications to an accuracy of 1 metre.','EPSG','9606','Position Vector transformation (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1211',1.0,485.0,169.5,483.8,'EPSG','9001',7.786,4.398,4.103,'EPSG','9104',0.0,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'EPSG-Svk',0);
752: INSERT INTO "helmert_transformation" VALUES('EPSG','5226','S-JTSK/05 to ETRS89 (1)','Derived through the relationship between the R05 realisation of ETRS89 and the astrogeodetic S-JTSK network. Replaces tfm code 1622. May be taken as approximate transformation S-JTSK to WGS 84 - see code 5227.','Defined as exact for S-JTSK/05 (Ferro) / Modified Krovak projCRSs (CRS codes 5224-25).','EPSG','9607','Coordinate Frame rotation (geog2D domain)','EPSG','5228','EPSG','4258','EPSG','1079',0.0,572.213,85.334,461.94,'EPSG','9001',-4.9732,-1.529,-5.2484,'EPSG','9104',3.5378,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'CUZK-Cze 05',0);
755: INSERT INTO "helmert_transformation" VALUES('EPSG','5239','S-JTSK to WGS 84 (5)','Parameter values from S-JTSK/05 to WGS 84 (1) (code 5227). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation. Replaces tfm code 1622.','For applications to an accuracy of 1 metre.','EPSG','9607','Coordinate Frame rotation (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1079',1.0,572.213,85.334,461.94,'EPSG','9001',-4.9732,-1.529,-5.2484,'EPSG','9104',3.5378,'EPSG','9202',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'OGP-Cze 05',0);
1379: INSERT INTO "helmert_transformation" VALUES('EPSG','15965','S-JTSK to WGS 84 (3)','Derived at 6 stations.','For military purposes. Accuracy 4m, 2m and 3m in X, Y and Z axes.','EPSG','9603','Geocentric translations (geog2D domain)','EPSG','4156','EPSG','4326','EPSG','1306',6.0,589.0,76.0,480.0,'EPSG','9001',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'NIMA-Cze',0); </pre>

As a user in Czechia I would use 1623 or newer 5239. How is the Mapper selecting +towgs84 parameters? 
I am wondering if it would be worth implementing +towgs84 parameter separately from EPSG definition into submenu. Most of the users I think will not understand the background, but still can decide between 1 meter (EPSG 5239) and 4 meter (EPSG 15965) precision.

**Comment by dg0yt** [comment]
Mapper does nothing in particular with regard to choosing +towgs84 parameters in the legacy PROJ definition. In the WKT2 definition, I don't even see equivalents:

~~~
PROJCRS["S-JTSK / Krovak East North",
    BASEGEOGCRS["S-JTSK",
        DATUM["System of the Unified Trigonometrical Cadastral Network",
            ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4156]],
    CONVERSION["Krovak East North (Greenwich)",
        METHOD["Krovak (North Orientated)",
            ID["EPSG",1041]],
        PARAMETER["Latitude of projection centre",49.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8811]],
        PARAMETER["Longitude of origin",24.8333333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8833]],
        PARAMETER["Co-latitude of cone axis",30.2881397527778,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",1036]],
        PARAMETER["Latitude of pseudo standard parallel",78.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8818]],
        PARAMETER["Scale factor on pseudo standard parallel",0.9999,
            SCALEUNIT["unity",1],
            ID["EPSG",8819]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - Czechoslovakia"],
        BBOX[47.73,12.09,51.06,22.56]],
    ID["EPSG",5514]]
~~~

I have no idea if the +towgs84 issue simply  becomes obsolete once we move away from legacy PROJ definitions.

**Comment by dg0yt** [comment]
PROJ 6.2.1 is scheduled for November 1st.

**Comment by dg0yt** [comment]
Fixed in master pre-release.
