### ISSUE TITLE
PDF Manual for Mapper 0.9.0

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1394]
### Actual behaviour

Currently there are no download links to PDF version of manual for `v0.9.0`.

Previously, PDF versions of manual located here:

- https://download.opensuse.org/repositories/home:/dg0yt/Windows/

### Expected behaviour

Add `OpenOrienteering-Mapper-0.9.0-Manual.pdf` file in `v0.9.0` release assets

- https://github.com/OpenOrienteering/mapper/releases/tag/v0.9.0

### Configuration

Mapper Version: `v0.9.0`

**Comment by dg0yt** [comment]
The "old" manual is still available from https://github.com/OpenOrienteering/mapper/releases/tag/v0.8.4. However there was practially no *update* to the manual.

**Comment by dg0yt** [comment]
Will be published from CI in v0.9.1.
