### ISSUE TITLE
Cannot open OSM template with Mapper 0.9.0 on openSUSE 15.1

### ISSUE THREAD

**Issue by huirad** [OpenOrienteering/mapper#1397]
### Steps to reproduce
0. Fresh installation of openSUSE 15.1 with KDE Desktop. Nothing else.
1. Install OpenOrienteering Mapper (OOM) 0.9.0 from OBS via 1-click install (https://software.opensuse.org/ymp/home:dg0yt/openSUSE_Leap_15.1/openorienteering-mapper.ymp)
2. From openstreetmap.org, export an area of the map (about 500mx500m - file size ca 1.3 MB) as file map.osm
3. Start OOM and create a new project
4. Template -> Open -> select map.osm

### Actual behaviour
First of all, *.osm files are not in the default filter for template files. 
So I filter for "all files" and then select map.osm.
A dialog box appears telling me: error - file format not detected

### Expected behaviour
Opening a map.osm as template works flawlessly on the Windows build.
I expect the same successful handling also on openSUSE 15.1

### Configuration
Mapper Version: 0.9.0
Operating System: openSUSE 15.1

**Comment by dg0yt** [comment]
Thanks for reporting. The build log says that GDAL was disabled on openSUSE 15.x, probably because it was mistaken for SUSE Linux Enterprise (SLW). I'm working on a fix.

**Comment by dg0yt** [comment]
New Linux builds of 0.9.0 are running and should be published in a few minutes.

You may verify the absence or presence of GDAL support via the mention of gdal in the legal notices:
Help > About OpenOrienteering Mapper > All about licenses, copyright notices, conditions and disclaimers > Third-party components.

**Comment by huirad** [comment]
Unfortunately I don't see any improvement. See my comment on #1398 
Are you sure that the new build is already available for installation?

**Comment by dg0yt** [comment]
https://build.opensuse.org/package/show/home:dg0yt/openorienteering-mapper says that build is in state **finished** but not yet **published**. The resulting version is openorienteering-mapper-0.9.0-lp151.20.1.x86_64.rpm.
I don't have much influence on when the publishing takes place. I'm sorry if it takes longer than expected.
