### ISSUE TITLE
Cannot open geotiff template without world file with Mapper 0.9.0 on openSUSE 15.1

### ISSUE THREAD

**Issue by huirad** [OpenOrienteering/mapper#1398]
### Steps to reproduce
0. Fresh installation of openSUSE 15.1 with KDE Desktop. Nothing else.
1. Install OpenOrienteering Mapper (OOM) 0.9.0 from OBS via 1-click install (https://software.opensuse.org/ymp/home:dg0yt/openSUSE_Leap_15.1/openorienteering-mapper.ymp)
2. Start OOM and create a new project
3. Template -> Open -> select a geotiff file which has georeferencing information included 

### Actual behaviour
The dialog box for positioning/scaling the template appears. 
However "gereferenced" cannot be selected, if there is no related .tfw file available.
If there is a related .tfw file available. then I can select "georeferenced (world file)".
If I open the same geotiff without tfw file with OOM 0.9.0 on the Windows, then  "georeferenced (GeoTIFF)".
I tried with geotiff files using 2 different projections: Gauss-Krueger, Zone 4 (epsg 31468) and Mercator_1SP (epsg 9001) - no difference. 

### Expected behaviour
OOM on OpenSUSE should offer the same functionality as on Windows.
I.e. it should be possible to open a geotiff file containing georeferencing information even if no related .tfw file is available

### Configuration
Mapper Version: 0.9.0
Operating System: openSUSE 15.1

### Note
In YaST, I had a look at the list of installed files for OOM and also in the list of dependencies. I expected to find gdal there as it is explicitly mentioned in the 0.9.0 announcement. But I did not find gdal. Maybe that is related to the root cause.

**Comment by dg0yt** [comment]
Same cause as #1397: GDAL support not included in build.

**Comment by dg0yt** [comment]
I think this is also solved, but I would like to get a confirmation.

**Comment by huirad** [comment]
Thank you for your quick reaction.
Unfortunately I do not see any improvement. Neither for this issue nor for #1397 
Also there is no sign of GDAL being installed (not mentioned in list of 3rd party components, no increase in the size of the package).

Maybe I just need some assistance to installed the right package?
- I tried first to update (including remove and then install again) the openorienteering-mapper package. 
- But then I saw on https://download.opensuse.org/repositories/home:/dg0yt/openSUSE_Leap_15.1/x86_64/ that the rpm has not been changed. 
- So then I uninstalled openorienteering-mapper  and installed openorienteering-mapper-master for which the rpm has been updated today at 10:10 (not sure how to translate this time to CEST). But also with this, there is no change.


I am attaching some screenshots. Maybe this helps
![image](https://user-images.githubusercontent.com/4027039/67622138-8755e380-f817-11e9-9dc2-7659d3ffefa9.png)
![image](https://user-images.githubusercontent.com/4027039/67622160-bd936300-f817-11e9-9203-8c0d9ddcb1a9.png)
![image](https://user-images.githubusercontent.com/4027039/67622167-d439ba00-f817-11e9-8828-208c170b0bff.png)
![image](https://user-images.githubusercontent.com/4027039/67622184-15ca6500-f818-11e9-8297-6af394e139b1.png)

**Comment by dg0yt** [comment]
https://build.opensuse.org/package/show/home:dg0yt/openorienteering-mapper says that build is in state **finished** but not yet **published**. The resulting version is openorienteering-mapper-0.9.0-lp151.20.1.x86_64.rpm.
I don't have much influence on when the publishing takes place. I'm sorry if it takes longer than expected.

openorienteering-mapper-master will receive the same fix when it is confirmed to work, or when I release other changes which I am investigation at the moment.

**Comment by dg0yt** [comment]
Transition from **finished** to **published** seems to have completed.

**Comment by dg0yt** [comment]
The GeoTIFF unit test is working now, so the issue with the first build must be solved.
