### ISSUE TITLE
Files with mixed letters case in extensions names not shown in «Open template...» browser

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1402]
### Steps to reproduce

1. Run *Mapper*;
2. Create new map;
3. Try to «Open template...»;
4. Navigate to folder where stored template files with mixed letters case in extension names.

### Actual behaviour

When navigate to directory where stored template files with mixed letters case (`.Png`, `.tiF`, `.jPG`) in extension names are not visible in «Open template...» browser.

In same time, files with fully lower-cased (`.png`, `.tif`, `.jpg`) or fully upper-cased (`.PNG`, `.TIF`, `.JPG`) are visible in «Open template...» browser.

### Expected behaviour

*Mapper* should recognize files with mixed letters case in extensions names.

### Configuration

- **Mapper Version:** `0.9.0`
- **Operating System:** Debian 9.x (x86_64)

**Comment by dg0yt** [comment]
[QTBUG-51712](https://bugreports.qt.io/browse/QTBUG-51712), see GH-765.
And I start to think that if GTK is designed to not support such filters more easily, than it is not even Qt's fault, but a GTK misfeature.

**Comment by Symbian9** [comment]
Strange fact, that if set «All files» in file types filter field files with mixed letters case in extensions names SHOWN, so it could be dirty trick/tip for users at least.
