### ISSUE TITLE
GetTickCount64 procedure not found in KERNEL32.dll on Windows

### ISSUE THREAD

**Issue by jmacura** [OpenOrienteering/mapper#1404]
### Steps to reproduce
1. Download "OpenOrienteering-Mapper-0.9.0-Windows-x86.exe" from the releases page
2. Install that file on 32-bit Windows XP
3. Run the program

### Actual behaviour
![oomapper_kernel32_error_on_winxp](https://user-images.githubusercontent.com/5598693/68090741-9e2fb200-fe77-11e9-975e-0d83fc5aa2e5.gif)

The error is a translation of "The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll"

### Expected behaviour
I know that Win XP is long unsupported by Microsoft, so I won't complain if the issue will receive a "won't fix" label. But if there is a change to fix, I will be glad.
A friend of mine tried the above mentioned steps and ended with the above mentioned error. The 0.8.4 version worked on the very same machine without any problem. I don't have enough knowledge to say if this problem only occurs on Win XP or on every 32-bit version of Windows.

### Configuration
Mapper Version: 0.9.0
Operating System: Windows XP (32bit)

**Comment by dg0yt** [comment]
Windows XP is unsupported. You may use older versions of Mapper.

**Comment by dg0yt** [comment]
PS: You may still try to build your own binaries with Qt 5.6. But even that is unsupported, and once you see how much time it takes, you will understand that this cannot be supported by me. I'm glad to have a homogenous set of 3rd-party components for Windows, macOS and Android.

**Comment by jmacura** [comment]
Well, that was a bloody quick close of an issue...
I completely understand that supporting 18 years old versions of at least 3 different operating systems is out of scope for a project run by a little team of voluntary enthusiasts, but I recall once again the note that this might perhaps affect other 32bit Win systems as well. If you are sure that this is Win XP issue only, than OK and I am fine with closing the issue in 60 seconds.

**Comment by jmacura** [comment]
P.S. Maybe it might be worth the mention in the release notes for 0.9.0 that this version no longer supports Win XP (32bit) and that 0.8.4 is the last known version of Mapper running there?

**Comment by dg0yt** [comment]
I do not even have 32 bit Windows for testing. But we have continuous integration running 32 bit unit tests which will link to 32 bit libraries even on 64 bit Windows. And we had a long series of dev snapshots based on Qt 5.12.

**Comment by dg0yt** [comment]
Updated the release notes to match the Qt 5.12 requirements. But still cannot test it all.

**Comment by lpechacek** [comment]
For the record, Windows XP was dropped from the list of supported platforms with [Qt 5.7](https://doc.qt.io/archives/qt-5.7/supported-platforms.html). It remained only on Qt 5.6 LTS list but support for that release expired in [March 2019](https://www.qt.io/blog/2018/11/29/support-qt-5-6-lts-ends-march-2019).
