### ISSUE TITLE
Swapped coordinates when initializing georeferencing from geographic template

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#1407]
### Steps to reproduce
1. Créate a new map
2. Open an osm export as template
3. Use it to georeferencing the map

### Actual behaviour
Latitude and Longitude are reversed
=>The reference point is wrong

### Configuration
Mapper Version: 9.0
Operating System: Windows

**Comment by dg0yt** [comment]
Thanks for reporting! This is another side-effect of the transition to PROJ 6, no longer letting us get away with (too) simple assumptions...

**Comment by dg0yt** [comment]
Actually, it is GDAL 3, not PROJ, in this case.
 https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order
