### ISSUE TITLE
No georeferencing setup  when importing OSM data

### ISSUE THREAD

**Issue by valentin5007** [OpenOrienteering/mapper#1420]
### Steps to reproduce
1. Export OSM file from open street map
2. Import these file in OOM
3. Assign news symbol box--->OK

### Actual behaviour
Before version 0.9, its wat automatically georeferenced. Now, there is a bug, the projection is wrong after the step of "Assign news symbol " .

### Expected behaviour
Still have an automatically georeferencing when we import an OSM file.

### Configuration
Mapper Version: 0.9.0
Operating System: Windows x64
![Sans titre 1](https://user-images.githubusercontent.com/36935547/68803744-9f739280-0660-11ea-8daa-ecaba06bf2ab.jpg)

**Comment by dg0yt** [comment]
Did you set up the map's georeferencing before importing the data? (IIRC Mapper used to ask for the map's georeferencing but it doesn't do so now when you call File > Import.)

**Comment by valentin5007** [comment]
No i've not set up the georeferencing before the importation. Import an OSM file was an easier way to set up the georeferencing fastly.

**Comment by dg0yt** [comment]
As a workaround, you may start with loading the OSM file as a template.

**Comment by valentin5007** [comment]
Ok with this way in template, its good !

**Comment by dg0yt** [comment]
Duplicated GH-1007.
