### ISSUE TITLE
OCD export turns area setting to clip mode 

### ISSUE THREAD

**Issue by ehakki** [OpenOrienteering/mapper#1424]
### Steps to reproduce
1. Create Isom2017 map
2. Create area object Stony area, all 3 levels has the same problem
3. select area setting which shows objects which have center point isnside boundary
4. export ocd 12 
5. open in purple pen

### Actual behaviour
Tell us what happens
stony area objects (dots) are cut in the edge

### Expected behaviour
Tell us what should happen instead
stony area should have full dots if their center point is inside border
actually ocad 12 has similar type if strange behaviour

### Configuration
Mapper Version:0.9.0 windows deskyop
Operating System: windowz 10

**Comment by dg0yt** [comment]
Please test today's master release.
