### ISSUE TITLE
"ISOM 2017-2_*.xmap" -> "ISOM_*.xmap"

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1427]
### Steps to reproduce

1. Launch *Mapper*;
2. Start creating new map from menu «File > New»;

### Actual behaviour

Here  is how symbol set chooser dialog look like in *Mapper* latest dev build

![pic.1](https://i.imgur.com/lkimr5w.png)

### Expected behaviour

As *Mapper* dev builds already provide latest versions of specifications no need anymore show "ISOM 2017-2_*" as it latest version of ISOM spec.

So just use `ISOM_*.xmap` (but `ISOM 2017-2` should be stored in symbol set ID)

### Configuration

Mapper Version: `master v20191118.1`
Operating System: Debian 9.x

**Comment by dg0yt** [comment]
1. `master` is not `dev`.
2. I may drop the scale, but I won't drop the version here.

**Comment by jmacura** [comment]
For the record, I disagree here with @Symbian9 , as it is quite useful to know with which symbol set is the mapper working. It is not otherwise evident at the first glance.

**Comment by Symbian9** [comment]
> as it is quite useful to know with which symbol set is the mapper working.

For that in *Mapper* exists «Symbol set ID» feature.

**Comment by jmacura** [comment]
Well, I might be just blind, but I can't see «Symbol set ID» anywhere when picking a new blank map symbol set... Where can it be seen?

**Comment by Symbian9** [comment]
> but I can't see «Symbol set ID» anywhere when picking a new blank map symbol set.

And this is issue of «Create new map» window

**Comment by dg0yt** [comment]
At the moment, there is **no issue**. IDs and file names of our symbol sets are in sync. And this is not by accident, but ensured by the SymbolSetTool which is also run as a test.
(And that's why you immediately know "ISSkiOM 2019" is missing when it isn't visible.)
