### ISSUE TITLE
Add note with Linux builds info into releases description on GitHub

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1440]
### Steps to reproduce

1. Visit - https://github.com/OpenOrienteering/mapper/releases/tag/master-v20191203.4

### Actual behaviour

There are no info about Linux builds in release/pre-release description on GitHub.

### Expected behaviour

Add next note into each release/pre-release description on GitHub

```
> **NOTE:** For download Linux packages visit *Mapper* [homepage](https://www.openorienteering.org/apps/mapper). 
```

### Configuration

Mapper Version:
Operating System: Linux

**Comment by dg0yt** [comment]
The Linux information is part of the release notes of official releases (e.g. v0.9.0), and it is on www.openorienteering.org/apps/mapper. I don't want to put more details to the release notes of master and dev builds. Anyway, Linux users will receive updates automatically if they add the repository from OBS.
