### ISSUE TITLE
Crash on OSM Import

### ISSUE THREAD

**Issue by leopold2410** [OpenOrienteering/mapper#1448]
### Steps to reproduce
[crash.zip](https://github.com/OpenOrienteering/mapper/files/3936647/crash.zip)

1. Open Mapper 0.9.1
2. Create new map (1:4000 ISSOM)
3. Import osm file (see attached zip file: fliegerviertel.osm)
4. Georeference Settings is displayed (setting see attached zip file: georef.jpg)
5. **First bug:** nothing happens after confiming georef settings with OK
6. Calling import again (no georef dialog displayed this time)

### Actual behaviour
Program crashes

### Expected behaviour
Import working and displaying map

### Configuration
Mapper Version: 0.9.1
Operating System: Windows

**Comment by dg0yt** [comment]
I get an immediate crash, after georeferencing + symbol assignment.

**Comment by dg0yt** [comment]
This is triggered by a particular data constellation in the OSM file. Some object creates an unexpected state during the rendering of the symbol of the object.

**Comment by dg0yt** [comment]
BTW, if you want to start a new sprint map, you may be interested in the ISSprOM symbol set which I am preparing at the moment, including CRT files (#1348).

**Comment by dg0yt** [comment]
This fix is now included in https://github.com/OpenOrienteering/mapper/releases/tag/master-v20191211.4.
