### ISSUE TITLE
Crash in Find's query editor

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1451]
### Steps to reproduce
1. in 'Edit -> Find...' press button Query editor
2. Don't enter something, just create a new line via '+' button
3. Press Move-up button => Mapper crashes

### Configuration
Mapper Version: 0.91 (x64)
Operating System: Win7x64

**Comment by dg0yt** [comment]
AFAICT you cannot move rows at all without crash, with Qt 5.12. Mapper with older versions of Qt are not affected (0.8.4 for Windows, 0.9.1 for Ubuntu 18.04).

**Comment by dl3sdo** [comment]
The crash no longer occurs for master v20191211.4.
However the fix has some quirks:
- it is possible to be in the first line and have the up button enabled (you get there by deleting the seconds line).
- it's also possible to be in the first line and have the down button enabled
- it's sometimes not possible to enter text in cells (the focus is locked at another cell).

**Comment by dg0yt** [comment]
> However the fix has some quirks:
> 
>  * it is possible to be in the first line and have the up button enabled (you get there by deleting the seconds line).
> * it's also possible to be in the first line and have the down button enabled

Yes, I can see this, at least with Qt 5.12.

>  * it's sometimes not possible to enter text in cells (the focus is locked at another cell).

I wasn't able to reproduce this on Linux.
