### ISSUE TITLE
Empty map display in CONDES course design software

### ISSUE THREAD

**Issue by JHuberman** [OpenOrienteering/mapper#1452]
Files saved in OOM 0.9.0 as ocd files appear empty when opened in CONDES course design software.  Previous editions of OOM  ocd files displayed correctly.
The CONDES developer (Finn Arildsen, finn@arildsen.com) says that the color pointer index is at 0 so no colors are drawn. 

### Steps to reproduce
1. Create a file in OOM 0.9.0 or open a map file
2. Save the file as a ocd file (I have been using v10 to test but it is the same for the others)
3.Open the file in CONDES software. (Download at https://condes.net/download/)

### Actual behaviour
The file opens but nothing is drawn in CONDES
(It worked properly in previous OOM versions)

### Expected behaviour
The map should display in CONDES

### Configuration
Mapper Version: 0.9.0
Operating System: Windows 10, version 1903

**Comment by JHuberman** [comment]
I just re-installed OOM 0.8.4.  opened the test file and saved it again and the file opened properly in CONDES.

[TestMaps.zip](https://github.com/OpenOrienteering/mapper/files/3947028/TestMaps.zip)

The file v0-8-4 opens and displays properly
The file v0-9-0 opens but does not draw any symbols

**Comment by dg0yt** [comment]
- Did you also try with v8? Both new and old implementation are available for Save-as.
- I'm not quite sure what is meant by "color pointer index is at 0". OCD files saved from Mapper are displayed properly in OCAD viewer and in Purple Pen. And I don't have CONDES available for testing. So it is difficult to do anything which is not a shoot in the dark.

**Comment by dg0yt** [comment]
... however, there is a colors bitmask per symbol, which may be left unset from the new exporter.

**Comment by JHuberman** [comment]
Yes, I installed 0.8.4 and the map saved with that version had no problems.
If you look at my comment I have included maps saved from both versions.
The 0.9.0 does not work, while the 0.8.4 does work.
Here is the screenshot from v8
[image: image.png]
Here is the screenshot from v9
You can see that the map boundaries are there, but no map is displayed.
[image: image.png]

I hope this helps.

Here is the text from Fin, the CONDES developer.

> I had a look at the files. They open fine, but they look very empty.   It
> seems that there is an error in the file.  In the file, for each map
> symbol, there is a list of colors used by that symbol. However, the
> indicator that counts the colors is always 0, so when Condes reads the
> file, it is led to believe that the symbol has no colors and therefore
> nothing is to be drawn.
> This is not due to any changes in Condes, it must be a change in OOM that
> has caused this to happen.
> I’ll see if I can do something to circumvent the problem, but I also think
> you should report it to the OOM people.

Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788

**Comment by dg0yt** [comment]
Dear Joseph, I fully understood what you tried.

Mapper v0.9.x has a completely new implementation of OCD export. This where the support for new versions of this format comes from.  What I wanted to point out is that ATM you can still access the old export in v0.9.1 by choosing the "OCAD version 8, legacy implementation".

It is a pity that the long period of dev snapshots before v0.9.0 wasn't used more for testing such use cases.

I will try to deal with the color bitmask. It is redundant IMO, and I don't think it is a counter or a pointer, but documentation is thin. You will have to try the next master snapshots and verify that the changes actually fix the problem in CONDES.

**Comment by JHuberman** [comment]
Thanks so much for your very quick and through replies.
I re installed v8.4 so I can keep working on course designs and field
checking and will upgrade to v9 when this is fixed.
I tried saving in ocd v8 and that only partially worked.  As you can see
below only the brown in streets was drawn when saved in ocd v8. (The purple
course is in CONDES.)
[image: image.png]
I'm not sure what "master snapshot" means.  I have only done
software installations using the windows installer.
I am attaching the map saved in ocd v8 using OOM 9.0 that is shown in the
above screenshot.

Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788

**Comment by dg0yt** [comment]
"Master snapshots" are packages made available for testing bug fixes and minor improvements, cf.  https://www.openorienteering.org/apps/mapper/.
This fix is now included in https://github.com/OpenOrienteering/mapper/releases/tag/master-v20191211.4.

**Comment by JHuberman** [comment]
I tested OpenOrienteering-Mapper-master_v20191211.4-Windows-x64.exe
<https://github.com/OpenOrienteering/mapper/releases/download/master-v20191211.4/OpenOrienteering-Mapper-master_v20191211.4-Windows-x64.exe>
and  Condes only displayed the brown in road symbols.  I tested both save
as ocad v10 and ocad v8 old implementation.

Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788

**Comment by lpechacek** [comment]
Yesterday I installed Condes and opened one of my maps exported to v10 .ocd format with Condes. The map display was correct, as far as I can tell.

**Comment by JHuberman** [comment]
Yes Finn updated Condes and it works great.


Joseph Huberman
919-610-1788

**Comment by dg0yt** [comment]
For the record, I didn't just close the issue: I verified myself with the Condes software on Dec 15 and again today that this is fixed *in Mapper*, to the best of my knowledge.

**Comment by JHuberman** [comment]
Yes, thanks so much for helping with this.  OOM is so important to our
club.  We have standardized on it for our club along with Condes -
excellent for designing courses.

Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788
