### ISSUE TITLE
"Import and remove" changes OMAP template position

### ISSUE THREAD

**Issue by pinnabilli** [OpenOrienteering/mapper#1467]
### Steps to reproduce
The following is the simplest scenario I found in which the issue occurs (no georeferencing needed).
1. Add an OMAP template to a map.
2. If necessary, change the template's rotation attribute to a nonzero value.
3. Apply the "Import and remove" function.

### Actual behaviour
The template's objects are placed in wrong position; it looks like an unwanted shear transformation occurs.

### Expected behaviour
The template's objects should be placed as displayed before the "Import and remove" function is applied.

### Configuration
Mapper Version: 0.9.1
Operating System: Manjaro Linux 18.1.4

**Comment by dg0yt** [comment]
Thanks for reporting the issue. I observed something similar a few days ago.

**Comment by pkturner** [comment]
The bug is in Object::rotate(qreal angle). In one place where sin_angle is used, it needs to be subtracted.

**Comment by dg0yt** [comment]
@pkturner Do you want to prepare a PR?
