### ISSUE TITLE
Sporadic crashes when using vectoriser

### ISSUE THREAD

**Issue by mpickering** [OpenOrienteering/mapper#1470]
I am using an artifact from the most recent master commit to test the vectoriser code. (MacOS - https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=1310&view=artifacts&type=publishedArtifacts)

From time to time, mapper crashes without any error message, I haven't managed to work out how to reproduce the crash yet. All map state is completely lost. 

Any tips on how to provide some more information so we can debug this issue?

**Comment by lpechacek** [comment]
Thanks for the bug report, Matthew! Of course, the best thing to get from a crash is a core dump or at least a stack trace. However, I know nothing about Mac OS and debugging possibilities on that platform for I cannot give guidance at the moment.
On a more generic level, any piece of information might be important. If you can describe if Mapper crashes in the CoVe dialog, after closing CoVe or even without starting CoVe at all, these are all important data points. Also if you can share data files with which Mapper crashes, I can try playing with the same setup to see if I spot something.

**Comment by dg0yt** [comment]
Assumed to be fixed with GH-1487. Re-open otherwise.
