### ISSUE TITLE
Some vector formats missing when GDAL/OGR GPX support is disabled

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1476]
### Steps to reproduce

There are 3 ways how OSM data could be opened in previous *Mapper* builds:

- *"File > Open... > All maps"* (or *"File > Open... > Geospatial vector data"*)
- *"File > Import > Importable files"*
- *"Templates > Open template... > Template files"*

### Actual behaviour

In all mentioned dialogs files with `*.osm` extension NOT shown with latest *Mapper* build.

### Expected behaviour

OSM (`*.osm`) files should be shown/recognized as supported file format in such dialogs as *"File > Open... > All maps"*, *"File > Open... > Geospatial vector data"*, *"File > Import > Importable files"* and *"Templates > Open template... > Template files"*.

### Configuration

- **Mapper Version:** `master 0.9.20191221` (tagged as `master v20191221.17` on GitHub)
- **Operating System:** Debian 9.x, x86_64 (OBS build)

**Comment by lpechacek** [comment]
I've just tested **openSUSE Tumbleweed** packages from https://download.opensuse.org/repositories/home:/dg0yt:/staging/openSUSE_Tumbleweed/x86_64/ and both v0.9.1 and the latest snapshot (0.9.20191221) accept `.osm` files. I suspect this might be connected with the configuration of GDAL package on Debian where OSM support might be switched off. This is, however, a mere guess.

**Comment by Symbian9** [comment]
> and both v0.9.1 and the latest snapshot (0.9.20191221) accept .osm files.

I just checked *Mapper* `v0.9.1` release - it accept `.osm` files for "Open" & "Import" on my Debian PC.

![pic.1](https://i.imgur.com/n8RC83I.png)

![pic.2](https://i.imgur.com/AOR37Jk.png)

So it's NOT related to GDAL package on Debian 9.x.

Look like *Mapper* `master v20191221.17` has some regression here.

**Comment by lpechacek** [comment]
Ack. `mapper-gdal-info` does list OSM driver on Debian 9. The culprit seems to be in Mapper integration bits.

**Comment by Symbian9** [comment]
> changed the title ~~OSM files not recognized as supported~~ **OSM files not recognized as supported on Debian 9**

On Facebook user also reported same issue under *Windows 10*, so it is not only *Debian 9.x* build affected.

**Comment by dg0yt** [comment]
Not reproducible on macOS.

**Comment by dg0yt** [comment]
We also have a unit test which loads the georeferencing, i.e. reads data via GDAL, from an OSM file.

What about other vector formats (DXF, SHP, GML, KML)?

**Comment by Symbian9** [comment]
> What about other vector formats (DXF, SHP, GML, KML)?

- *Mapper* `v0.9.1` - recognized;
- *Mapper* `master v20191221.17` - NOT recognized.

System info:

- Debian `9.x` 
- GDAL `2.1.2+dfsg-5`

**Comment by dg0yt** [comment]
The bug is in the (optional) disabling of GPX support via GDAL/OGR, introduced in 38ef4c8.
Workaround: Check the GPX box in the GDAL/OGR settings page.

**Comment by Symbian9** [comment]
> Workaround: Check the GPX box in the GDAL/OGR settings page.

Yes, workaround solve this regression.
