### ISSUE TITLE
.omap file georeferencing inconsistent, should be detected

### ISSUE THREAD

**Issue by pkturner** [OpenOrienteering/mapper#1480]
### Steps to reproduce
1. Start with a georeferenced .omap file.
2. With a text editor, modify the `lat` and `lon` properties of the `ref_point_deg` element, both to "0".
3. Open the map.
4. Open the georeferencing dialog.
5. Make a small modification to the declination.

### Actual behaviour
The map opens and Mapper appears to function normally, until the georeferencing dialog is used. Then the geographic coordinates of the reference point show up as 0.0. When the declination is modified, the Grivation swings wildly.

### Expected behaviour
When the map is opened, Mapper warns the user that its georeferencing is incorrect, that the projected coordinates do not agree with the geographic coordinates, and "Please go to Map > Georeferencing to fix the problem." The user would not find this straightforward to fix, but at least the user is informed that the problem is with the map, rather than with the way Mapper displays it to the user.

### Configuration
Mapper Version: 0.9.0 to master-v20191221.17
Operating System: MacOS, Linux, Android

### Discussion
Unfortunately, I don't have details of the history whereby this problem got into my map. The oldest version of the map where the problem appears is from October 11, and in that map there is no `<geographic_crs/>` element at all. So my guess is that some stable or pre-release version of Mapper did not write the `<geographic_crs/>` element. It is also possible that the version could have been my transitory development build. 

Since then in the process of field work, the map was transferred back and forth between Android and Linux several times. It wasn't until I revisited some ideas for #1277 that I noticed that the latitude and longitude were showing up as 0.

**Comment by dg0yt** [comment]
While added with different intentions, https://github.com/OpenOrienteering/mapper/pull/1532/commits/ecf1704ac31eca3cd3b5a838b3d338c67bd4ffa0 will add a warning when the calculated projection of the geographich reference point is more than 1 meter away from the user-defined projected reference point. This catches the manual editing of lat/lon.

In addition, we added automatic adjustment of declination in case of inconsistencies. So after all, this should be resolved in v0.9.2.
