### ISSUE TITLE
when clicking CLOSE on POSITIONING window, OOM closes with error

### ISSUE THREAD

**Issue by valdisj** [OpenOrienteering/mapper#1494]
Running OOM on Mac OS 10.15.2 (19C57) Catalina
### Steps to reproduce
1. Open Map
2. Open Templates
3.Click on Template and Choose "EDIT" => Positioning
4. Do or not do any edits in numers in Positioning window
5. Click "CLOSE" button in positioning window

### Actual behaviour
All OOM exits with error

### Expected behaviour
Window should just close

### Configuration
Mapper Version: 0.9.1
Operating System: Mac OS 10.15.2 (19C57) Catalina

**Comment by dg0yt** [comment]
Confirmed on macOS.
