### ISSUE TITLE
Unused symbols and colors are deleted when loading CRT file directly

### ISSUE THREAD

**Issue by boletbo** [OpenOrienteering/mapper#1500]
### Steps to reproduce
1. Open an existing map or open a new one.
2. Go to Symbols Menu -> Load CRT file…
3. Choose attached CRT file (rename to 'test.crt' instead of 'test.crt.txt') and apply changes.
[Test.crt.txt](https://github.com/OpenOrienteering/mapper/files/4081755/Test.crt.txt)

### Actual behaviour
All unused symbols in map disappear from "Symbol pane".
All unused  colors in map disappear from "Color window".

Before:
![Before](https://user-images.githubusercontent.com/17615064/72670665-56650380-3a40-11ea-9867-04117f0f23e6.png)

After:
![After](https://user-images.githubusercontent.com/17615064/72670664-55cc6d00-3a40-11ea-882c-40ea8fd49e25.png)

### Expected behaviour
"Symbol pane" and "Color window" should remain unchanged.

### Configuration
Mapper Version: 20191221.17.r0.gb4466b07
Operating System: Arch Linux (Manjaro)

**Comment by dg0yt** [comment]
Thanks for you report. 

There are checkboxes to control this behaviour when replacing symbol sets, but not when loading CRT files only. Hiding the checkboxes seems okay but the assumed state seems wrong indeed.

(So for now this might be a workaround: load your map files as replacement symbol set, and load the CRT file from the dialog. Uncheck the boxes for remove of unused colors and symbols.)

**Comment by boletbo** [comment]
Thank you for the fast answer.
I've made some testing:
If you load the CRT file when replacing symbol set or when importing data (file->import...), the symbols and colors are preserved. The symbols only disappear when loading CRT from "Symbols->Load CRT file...".

**Comment by dg0yt** [comment]
I can confirm all what was written before. I started working on the correction, but there are some more use cases of the same source code, especially loading geospatial data such as OSM. So I need to do a number of manual test, and I found another bug. Anyway, bug fix will come soon.
