### ISSUE TITLE
Manual: how to extend a path object

### ISSUE THREAD

**Issue by huirad** [OpenOrienteering/mapper#1501]
Background: I am trying how to use best the drawing tools

### Steps to reproduce
1. Create a path object, finish by double-click or right-click
2. Want to extend it at one end 
3. Don't know how to do this best

### Actual behaviour
If I have been interrupted in completing a path object, I can add an extra node within an existing line or curve by Ctrl-click on an empty spot of a path. This is described in the manual at https://www.openorienteering.org/mapper-manual/pages/toolbars.html#drawing-toolbar. 
But I see no natural way to continue drawing the path at its end.

### Expected behaviour
I would like to have a description in the manual how continue drawing an existing path at one of its ends. Is it by creating a new path and joining both? Or is there an easier way?

### Configuration
Mapper Version: 0.9.1
Operating System: Windows

**Comment by dg0yt** [comment]
Press Shift when clicking at the end point of the path which you want to extend.

Watch the status bar for more hints how to interact with the current tool.

**Comment by dg0yt** [comment]
In the manual, the tool's description is already quite long, but this particular use case is not very explicit:

> To snap to existing objects when starting to draw or while drawing a path, hold Shift. To follow the shape of existing objects while drawing, click at the existing object while holding Shift and drag the mouse along it. Depending on the direction in which you drag the mouse, the object will be followed along this direction

https://www.openorienteering.org/mapper-manual/pages/toolbars.html#drawing-toolbar,
"Draw Lines"

**Comment by huirad** [comment]
Thank you very much for your fast reply!
Holding Shift indeed works, if the mouse cursor is captured by the path endpoint which is highlighted by the X.

My particular case was probably too complicated - see attached picture.
For whatever reason the end point overlapped with last intermediate point.
And there is a OSM line below (although in another map part).
Apparently, this is confusing the selection algorithm ;-).
![grafik](https://user-images.githubusercontent.com/4027039/72755989-319d9700-3bcc-11ea-93b9-17d5268645f1.png)

I now tried several times with less complex examples and it practically always works.

**Comment by dg0yt** [comment]
Ideas how to improve the manual or how to handle the complicated case are welcome.

**Comment by dg0yt** [comment]
Concerning the overlapping points at the end: Note that there are different behaviours for finishing a path (double click, right click, Return key). For the right click, there is an Editor setting controlling whether it creates another point or not.

**Comment by ollesmaps** [comment]
On Android the extension of a line is tricky as well.
There you have to push the Snap button and then draw.
However the snapping/connecting in my experience works in 50% times.

What about clicking on the line you want to extend first and then pushing the Snap button?

**Comment by ollesmaps** [comment]
#471

**Comment by mlerjen** [comment]
#1142
