### ISSUE TITLE
CoVe: Corrupted B/W image

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1503]
Please note that this misbehavior has been observed on a development build.

### Steps to reproduce
1. Attempt to vectorize attached example template ([fb-orienteering-mappers-mom-2020.zip](https://github.com/OpenOrienteering/mapper/files/4108436/fb-orienteering-mappers-mom-2020.zip))
2. Classify colors into 20 buckets, choose the brown ones
3. Switch to Thinning tab

### Actual behaviour
Corrupted B/W image. The machine is a two-core notebook with (Intel) hyperthreading off. Processing was split into two chunks.

![image](https://user-images.githubusercontent.com/5584406/73068954-cd6d2280-3eac-11ea-940f-a2c5b701bf29.png)

Going back to the color classification tab and retrying classification gave another interesting result.

![image](https://user-images.githubusercontent.com/5584406/73069421-fe9a2280-3ead-11ea-9318-b3a1a6899b46.png)

It seems that data for the bottom part of the picture come from uninitialized memory. Interestingly enough, the address sanitizer didn't complain so my guess is that the allocated memory was merely not populated with new data.

### Configuration
Mapper Version: master-v20191221.17-77-g43c0cb2b056a (debug build)
Operating System: openSUSE Tumbleweed 20200121

**Comment by dg0yt** [comment]
I saw similar issues with some stripes being weird, but not in all the manual testing I did in the end.

> Mapper Version: master-v20191221.17-77-g43c0cb2b056a (debug build)

So this is the master v20191221.17 source code? Or a later build which includes my concurrency changes?

**Comment by lpechacek** [comment]
> So this is the master v20191221.17 source code? Or a later build which includes my concurrency changes?

It is a build that contains the concurrency changes. The string in Mapper version field is an output of `git describe --tags`. It says that `HEAD` is v20191221.17 plus 77 additional commits. Behind the final `-g` there is SHA of the actual `HEAD`, i.e. 43c0cb2b056a. Git can parse the string as is and check out the corresponding tree state. I hope that this way of identifying development builds is fine for you.
