### ISSUE TITLE
ISSOM_4000/ISSOM_5000 Symbol sets: wrong "black" color for filling pattern in symbols 211/415

### ISSUE THREAD

**Issue by huirad** [OpenOrienteering/mapper#1504]
### Steps to reproduce
1. Create a new map based on ISSOM_5000 or ISSOM_4000
2. Draw a path "paved road outside settlements" (529.0.11)
3. Draw an area "sandy ground" (211) or "cultivated land" (415) partly over the path

### Actual behaviour
The filling dots are also visible where the path intersects the area

### Expected behaviour
The filling dots are NOT visible where the path intersects the area. This is how it looks for maps created with ISOM 2017-2_10000.

### Assumed root cause

The root cause is that in ISOM 2017-2_10000, a special t of "black for open land" is used for the filling pattern. That black has higher drawing priority than yellow but less than brown. I suggest to adapt the ISSOM symbols 211 and 415 accordingly.

### Configuration
Mapper Version: 0.9.1
Operating System: Both Windows and OpenSuSE 15.1

### Screenshots

ISSOM_5000: 211 Open sand area- using "black" for the filling pattern
![grafik](https://user-images.githubusercontent.com/4027039/73118050-c26ace80-3f4e-11ea-859d-312dc4ab1196.png)

ISOM 2017-2_10000: 213 Sandy ground using "black for open land" for the filling pattern
![grafik](https://user-images.githubusercontent.com/4027039/73118068-f47c3080-3f4e-11ea-8dba-2649560b3673.png)

**Comment by dg0yt** [comment]
Thanks for reporting this issue. However, ISSOM is about to be replaced with ISSprOM in the next official release, and our ISSprOM symbol set does not have this issue.

The ISSprOM is already included in the latest master builds. There are still some correction to be made.
