### ISSUE TITLE
Enhancement Request - Add button for Template setup window (like in mobile version)

### ISSUE THREAD

**Issue by rem-maps** [OpenOrienteering/mapper#1511]
It would be very nice to have in the desktop version a button for Template setup window (like in mobile version)

For instance in this position:
![template](https://user-images.githubusercontent.com/59602742/73556629-15152080-4450-11ea-9b8f-e60f889f03cf.png)

Mapper Version:
v20191221.17
Operating System:
Windows 7 PRO

**Comment by lpechacek** [comment]
@rem-maps: At this point, I'm wondering what would the toolbar button good for. Please note that there is a hotkey combination for activating the Template Setup window (Ctrl+Shift+9).

**Comment by rem-maps** [comment]
@lpechacek yes I know about the hotkey combination,
This feature - very low priority I know - will just improve my OOM experience: 
Now every time I need Template Window my brain looks for a button. Of course I can train myself to use the hotkey but there's lot of empty space in the toolbar and if it is not big deal adding this button will just make me work happier.
And most of buttons have hotkey combinations anyway - like ZOOMs for instance... there's a button and I just don't need it (other options are with the mouse or hotkey).
As I'm becoming a very heavy OOM user I'm  just trying to see if the features I need could be useful for the whole community - for me Template setup window button would be a lot more important than Zoom buttons.
