### ISSUE TITLE
See all objects with selected symbol one after the other

### ISSUE THREAD

**Issue by rem-maps** [OpenOrienteering/mapper#1512]
I cannot find it in the manual or in the issues, so thanks a lot if you can help me and sorry if it is already explained somewhere:

-is there a way to count objects with a selected symbol?
-is there a way to see all objects with selected symbol one after the other? (click a command and show object in the middle of the screen - click again and show the 'next' until the end of selected objects)

I tried the 'find' tool but :
- I am not able to see all the objects because with 'find next' it doesn't put the object in the middle of the screen
- I am able to count objects with a query but I am not able to differentiate between similar objects
 ( for instance I am not able to select 'Passable fence or railing' ONLY - I get to select 'Passable fence or railing' AND 'Impassable fence or railing' with a simple query with text 'fence' )

**Comment by Symbian9** [comment]
> is there a way to count objects with a selected symbol?

Yes. Just open «Measure» widget & select objects.

![pic.1](https://i.imgur.com/o3lK9j1.png)

**Comment by rem-maps** [comment]
cool @Symbian9 thank you so much :-)

still hoping for a way to view selected objects one after the other in the middle of the screen clicking next

**Comment by Symbian9** [comment]
> still hoping for a way to view selected objects one after the other in the middle of the screen clicking next

Try *«Find objects»* dialog:

1. Open map;
2. Go to menu *"Edit > Find..."*
3. Input symbol name of needed objects without number (for example for toggle between objects with *"`401` Index contour"* symbol input query as `Index contour`);
4. Use button <kbd>Find next</kbd> to select each next object with defined symbol.

FTR, You could also use one or two words that included in few symbols names, e.g. `Forest` query could be used to toggle between all objects which symbol names include *"forest"* word.

![pic.2](https://i.imgur.com/ZoBLKI6.png)

**Comment by Symbian9** [comment]
> I am not able to see all the objects because with 'find next' it doesn't put the object in the middle of the screen

As addition to all above, think, *Mapper* only missed feature here is «Zoom to fit/selected».

@dg0yt is it possible add «Zoom to fit/selected» feature/shortcut?

**Comment by rem-maps** [comment]
exactly @Symbian9 thanks, with the additions:
- that I would need 'zoom to fit' to be used associated with 'find next'
- as I previously said, with the query now I am not able to select 'Passable fence or railing' objects ONLY because with the query 'Passable fence or railing' I also get 'Impassable fence or railing' objects

**Comment by dg0yt** [comment]
> for instance I am not able to select 'Passable fence or railing' ONLY - I get to select 'Passable fence or railing' AND 'Impassable fence or railing' with a simple query with text 'fence' 

In fact, we miss negation in our object queries. You could already ask for

~~~
"Passable fence or railing" AND "Major road"
~~~

but not yet for

~~~
"Passable fence or railing" AND NOT "Impassable"
~~~

**Comment by Symbian9** [comment]
@dg0yt Is it possible to add also symbol number (something like: `"symbol:<id>"`) as query?

```
"symbol:201" AND "symbol:502.1"
```

**Comment by dg0yt** [comment]
@symbian9 We are talking about designing a formal language. It is quite trivial to add the missing `NOT` operator. (We already have operators AND + OR, and this part of the language is formally complete with `NOT`added.) But it needs much more thought if you want to add special predicates. (We don't have predicates yet.) You start with "symbol" now, but then there will be "color" and "size" and "position" and so on. And still you want to also catch data having any tag with value "symbol:201"...

**Comment by dg0yt** [comment]
Side note: we have an implementation for the symbol predicate (used with CRT files), but it is not part of the query language.
