### ISSUE TITLE
Inconsistent beahaviour on object selection

### ISSUE THREAD

**Issue by jmacura** [OpenOrienteering/mapper#1518]
I have encountered a strange inconsistency when selecting multiple objects by mouse. I am not sure whether it is a bug or a feature 😄 

### Steps to reproduce
1. Select some objects in the map by dragging a mouse over them
2. Select again and select few more

### Actual behaviour
Sometimes, the nodes of selected objects are highlighted by blue squares, but sometimes not. It seems like it depends on a number of nodes, which are currently visible on the screen or the overall complexity of selected objects. Can't tell for sure...

### Expected behaviour
If this is a feature, than wow and it is good to know about it
If not, than the behaviour should be consistent or at least predictable

### Configuration
Mapper Version: 0.9.1 & last master (20191221.17)
Operating System: Win 10 Pro v1903

**Comment by dg0yt** [comment]
>If this is a feature, than wow  ...

In various tools, the cut is at 10 objects, intentionally (`max_objects_for_handle_display`).

**Comment by lpechacek** [comment]
I noticed this too and as to my understanding, this is a reasonable design decision. I'm all for keeping the behavior as is and closing this ticket. If there are no objections, I'll do so in a few days.

**Comment by jmacura** [comment]
> (...) the cut is at 10 objects

That didn't crossed my mind..

> I noticed this too and as to my understanding, this is a reasonable design decision. I'm all for keeping the behavior as is and closing this ticket. If there are no objections, I'll do so in a few days.

There are no objections. The behaviour just seemed too random at the first glance to be a feature :-)
