### ISSUE TITLE
Cut section from symbol

### ISSUE THREAD

**Issue by stevogray** [OpenOrienteering/mapper#1527]
A question, or perhaps enhancement request:
I've only just started using OOM (amazed at the program by the way!) so I might be missing how to achieve this.
Point symbols, especially control circles, occasionally obscure important terrain details. I can't find a way to to cut a segment out of a point symbol without impacting the rest of the symbol. I can draw a circle and cut a segment from this, but can't do this with point symbols.
It would be great if there was a way to hide/make non visible/delete a section of a symbol, that moved with the symbol. Could also be used as an alternative way to make a hole in an area?

**Comment by dg0yt** [comment]
Do you really need this feature for point symbols other than "course planning symbols"? Mapper offers only limited course planning capabilities.
- You might use another software.
- With older IOF standards, you might use overprinting simulation.
- With latest IOF standards, some course planning symbols (such as control circles) are meant to use a special color level, below selected other colors.

Each solution has it is own issues, unfortunately.

For actually hiding some parts of a control circle, we already have #1100.
Real course planning capabilities are requested in #242.

If you do see another use case, please make an explicit example.

**Comment by stevogray** [comment]
No, you're right, the only point symbol I've found that needs this is control circles. And despite my search, I didn't see issue #1100. 
Thanks for your time on this program, brilliant software!
