### ISSUE TITLE
File causes oomap to crash after language change

### ISSUE THREAD

**Issue by benoitrauturier** [OpenOrienteering/mapper#1528]
### Steps to reproduce
1. Switched language from English to French while editing a map
2. Closes Oomap window
3. The file cannot be open (only on my OS) and causes oomap to crash

### Configuration
Mapper Version: 0.9.1
Operating System: Ubuntu 18.04
logs while trying to open the file : 
- corrupted double-linked list
- GtkDialog mapped without a transient parent, this is discouraged

### Steps for a quick and dirty solve of the issue
I "solved" the issue following these steps : 
1. Open the corrupt map file on Windows machine (Windows 10, oomap 0.6.6)
2. Saved the file in .ocd
3. Open .ocd  file on the Ubuntu machine and convert it back to .omap

I tried unsucellfully the following things : 
- Reboot the machine
- Reinstall oomap
- Switching langage configuration back and forth

I attached to the issue the corrupt file in question : 
[stavros_niarxos.zip](https://github.com/OpenOrienteering/mapper/files/4271014/stavros_niarxos.zip)

Last but not least : thanks a lot for making orienteering mapping free and open, you're amazing !

**Comment by dg0yt** [comment]
Hm, I wonder if this is really connected to Mapper. 
- The attached file is not corrupted. It looks complete, and it loads without problems here.
- The user interface language has no influence on the data saved to the OMAP file. 
  Can you really exclude other issues, such as a corrupt hard disk? For example, can you really reproduce the issue when saving to another location, e.g. some flash drive?
- "corrupted double-linked list" is harmful, but not an error message from Mapper or Qt. 
- "GtkDialog mapped without a transient parent, this is discouraged" is a (probably harmless) warning which I see only when running with the "gtk3" platform theme. To explicitly try an alternative, you may run
~~~
Mapper -platformtheme gtk2
~~~

**Comment by benoitrauturier** [comment]
Hi @dg0yt ,
Thanks for your reply, it helped me a lot to narrow the problem down. 
It is indeed not linked to language change. 
It has to do with the fact that I ran system updates while working on the map : 
- The map add a openstreetmap template (.osm)
- The  system updated the geographical dependencies
- Then I have the following errors trying to run the program : 
"ERROR 6: Failed to initialize PROJ pipeline from `+proj=longlat +datum=WGS84 +no_defs' to `+proj=utm +datum=WGS84 +zone=34 +wktext': unknown projection id"

Here are my proj and gdal versions (I am on ubuntu 18.04LTS): 
- proj : 6.2.1
- gdal: 3.0.2

**Comment by dg0yt** [comment]
Well, these are not the Ubuntu 18.04 versions of PROJ and GDAL (4.9.3/2.2.3). If you install 3rd-party versions of Ubuntu packages, you can't use the openorienteering-mapper packages we provide. It is surprising enough that Mapper is not failing with linker errors on start.

**Comment by benoitrauturier** [comment]
Ok I got it. I had a concurrent install of qgis which add for some reason installed 
"deb-src http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic main" in my /etc/apt/sources.list I removed it and it seems fine now. 
Thanks for the time and help and sorry if I've been a bit nooby.

**Comment by dg0yt** [comment]
It is okay to ask. I'm glad we could sort it out quickly.
