### ISSUE TITLE
Some line symbols make it difficult to select other objects

### ISSUE THREAD

**Issue by valdisj** [OpenOrienteering/mapper#1529]
HW: Samsung Active Tab 2
OS: Android
OOM version: 0.9.1.
### Steps to reproduce
1. Open OOM on Android, open any OOM map file 
2. Try selecting any "area", where an 416 Distinct Vegetation Boundary is around it.

### Actual behaviour
It selects closest 416 Distinct vegetation boundary, and does not select anything else. Only when clicking at least 3cm away, it diselects it. Then trying again, and may be with some luck and persistance over multiple tries it will select "area".

### Expected behaviour
Clicking on "area" should select it. Of course, there should be some "marginal" error treshold, if you want to select "boundary", but not so big.

### Configuration
Mapper Version: OOM 0.9.1. on Android
Operating System: Android

**Comment by eolmapper** [comment]
It's not specific to the android apply. It's only a symbol set problem.
Edit the symbol an put the line thickness to 0. 
Problem solved!

**Comment by dg0yt** [comment]
I'm unable to reproduce it, with a simple combination of open land and 416, on PC. Maybe you could attach a minimal demo file, in a ZIP folder.

**Comment by eolmapper** [comment]
Make a small area. 
The 416 default symbol have thickness line 3,75mm.

**Comment by dg0yt** [comment]
@eolmapper I want a test file.

I'm unable to reproduce it with the forest sample map on Android.

**Comment by valdisj** [comment]
Indeed.

This explains.
I will correct it manually, but it would be good to correct in 0.9.2 release

This is how any other typical line item looks lie

**Comment by dg0yt** [comment]
> Indeed
>
> This explains.
> I will correct it manually, but it would be good to correct in 0.9.2 release

???

I  don't see a reproducible case, nor an explanation for the bug. So there is nothing that can be expected to be fixed.

**Comment by valdisj** [comment]
I will try to explain. 
Since the “width” of the 416 line in ISOM2017-2 symbol sett 1:15000 is 2.5mm, then in the large close-ups (like zooming in a lot), makes it hard or nearly impossible to select area behind this symbol, even when clicking “outside” of the symbol. When clicking it almost always jumps to select 416, not the area. 
What I did to correct, is that I manually made symbol “width” smaller, down to 0.5mm, and this solved problem. But template still stays the same in OO Mapper distributed symbol setts. Therefore suggestion is to correct this in symbol sett comming with OO Mapper 0.9.2
From:

To:

**Comment by dg0yt** [comment]
The original report was: 

> It selects closest 416 Distinct vegetation boundary, and does not select anything else. Only when clicking at least 3cm away, it diselects it.

If I understand correctly now, "3 cm" is not to be taken literally but an observation at ~8x zoom.

> Then trying again, and may be with some luck and persistance over multiple tries it will select "area".

The expected behaviour is that the next touch at the same region selects the next available object. So this is not working as expected?

> The 416 line in ISOM2017-2 symbol set

Now we are talking about a particular test file! Indeed, the line width of 416 in that particular symbol set is not zero. This can be changed. However, the line has no color and no border, so it should not have any effects at all. So apart from changing the symbol, we should also check the selection behaviour.

**Comment by dg0yt** [comment]
The situation is as follows:
- The region of interactively selecting line object depends on the symbol's line width, plus border width and offset. 
  - This works as expected for regular lines.
- For line symbol with added point symbols (start/end/dash/mid), the point symbol size is *not* taken into account. Only the line width defines the region of interaction.
   - If such line symbols have a visible line (e.g. fence, power line), this may work as expected. But it also means that the region of interaction does not reliably cover the point symbols along the line.
   - If such line symbol do not have a visible line (e.g. disting vegetation boundary, small erosion gully), the region of interaction does not depend at all on a visible property, but only on the arbitrary line width value.

We may choose from these alternatives:
1. Leave code as is. Adjust line widths in our symbol sets.
   - This only affects new maps based on our symbol sets. 
     The region of interactivity will not be fixed for other map files.
   - We need to decide which value to choose for line width. 
     We are free to intentionally choose a sensible non-zero value.
   - We may automatically check the property in our symbol set tool.
     This would catch broken cases like "416 line in ISOM2017-2 symbol set".
   - It is computationally cheap at runtime.

2. Explicitly ignore line width of invisible lines.
    - This affects all maps, broken or not.
    - We are not able to explicitly define a sensible width to define the region of interaction.
    - It is computationally cheap at runtime.

3. Explicitly ignore line width of invisible lines, but consider point symbol sizes.
    - This affects all maps, broken or not.
    - We are not able to explicitly define a sensible width to define the region of interaction.
    - However, we don't have to take the point symbol size literally. We could ignore start/end symbol, and we could reduce the extent for very distant mid symbols.
    - It is computationally more expensive at runtime (but probaly not relevant).

**Comment by valdisj** [comment]
I am for solution #1.
Its simple, sensible and does not require to rewrite. 

This activitiy "• We may automatically check the property in our symbol set tool. This would catch broken cases like "416 line in ISOM2017-2 symbol set".” is important not only for ISOM2017-2 by may be for some other sybolsets.

**Comment by eolmapper** [comment]
+1 for solution #1.
