### ISSUE TITLE
Crash when using GDAL on linux

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#1530]
### Steps to reproduce
1. Open OOM 9.1 on linux Xubuntu
2. open any template using GDAL (osm, shp...)

### Actual behaviour
OOM crash

No problem on OOM 8.2 with GDAL disabled.  But it also crashes when GDAL is enable.
GDAL appear in Third-party components.
The gdal-data and gdal-bin packages are installed.

### Configuration
Mapper Version:0.9.1
Operating System:Xubuntu 18.04

**Comment by dg0yt** [comment]
You will need to report more details.
- Which version of proj and gdal? (cf. #1528...)
- Any output when running Mapper from the command line?

**Comment by eolmapper** [comment]
Thanks a lot.
It's the same problem to #1528 (interference with QGIS unstable)
I hadent find this issue when i was surching a similar problem.
