### ISSUE TITLE
Help with Open Orienteering mapper

### ISSUE THREAD

**Issue by Fredriksporteducation** [OpenOrienteering/mapper#1546]
Fredrik is my name and I use the Open Orienteering Mapper program andI´am very pleased with this program. I have learned many functions myself and can draw maps in a good way today and make this in a PDF. I have searched around to find any support but I cannot find anyone to contact. It is so that I can draw the map clearly but cannot paste map signs that I used for the map in a list. I can not find templates to clearly edit the map with name, equidistance, etc. (look at the picture) When I searched the internet, I found a picture from the program that I did not reach. Hope you can help me. Thanks for now! 
Fredrik

<img width="622" alt="Skärmklipp 2020-03-18 09 07 22" src="https://user-images.githubusercontent.com/62327787/76939064-04354700-68f8-11ea-9689-831651cef438.png">

**Comment by mlerjen** [comment]
Contact me. Find my mail in my profile.

**Comment by Symbian9** [comment]
@Fredriksporteducation there also *«Orienteering Mappers Int.»* Facebook-group, where you could ask for help with *Mapper* and orienteering mapping in general

- https://www.facebook.com/groups/485564718218028

FTR, There is one more help request posted on old forum few month ago (with no replies):

- https://sourceforge.net/p/oorienteering/discussion/mapper/thread/50be529dfd/

We should add more info in the readme, user manual & official website with info for those users who need additional help and useful links (on Attackpoint, Facebook, etc.)

@dg0yt, what you think about realizing idea of recreating "forum" in some way?

 - https://github.com/OpenOrienteering/mapper/issues/528#issuecomment-168205951

> There was a proposal in #528 to have a separate repositiory here, e.g. "forum" or "mapper-users", and use the issues for discussion.

**Comment by lpechacek** [comment]
I'm assuming the inquiry has been addressed. Feel free to reopen should you disagree with my assesment. Thanks!
