### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1547]
Is there an e-mail I can reach for promotion?

**Comment by lpechacek** [comment]
@AhmetPolat43, what kind of promotion do you mean?

**Comment by AhmetPolat43** [comment]
Open orienteering mapper turkey I would like to introduce you want to take from one place do I need a permit for this instructive videos Windows 10 için Posta ile gönderildi Kimden: Libor PecháčekGönderilme: 20 Mart 2020 Cuma 00:35Kime: OpenOrienteering/mapperBilgi: AhmetPolat43; MentionKonu: Re: [OpenOrienteering/mapper] Contact (#1547) @AhmetPolat43, what kind of promotion do you mean?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AhmetPolat43** [comment]
Open orienteering mapper turkey I would like to introduce you want to take from one place do I need a permit for this instructive videos

**Comment by lpechacek** [comment]
In my opinion, there is no permission needed to make a tutorial video. However, make sure that the video presents your knowledge and your persona rather than a trade-mark.

@dg0yt, what is you stance on this matter, please?

**Comment by dg0yt** [comment]
I don't exactly understand what is desired here. What I can say is the following:

In general there is no problem in using the terms "OpenOrienteering", "Mapper", "OpenOrienteering Mapper", and the related graphics, when referring to our project and software. However, you should not give the impression that you are representing the OpenOrienteering project or acting on behalf of the project.
This can be summarized as "fair use".

**Comment by lpechacek** [comment]
Thanks, Kai, for the explanation.

I would say that the question has been answered at this point. I'm closing the issue. Feel free to reopen should you disagree. Thanks!
