### ISSUE TITLE
UX: Inform user about the supported GeoTIFF types

### ISSUE THREAD

**Issue by jmacura** [OpenOrienteering/mapper#1550]
### Steps to reproduce
1. open GeoTIFF which is not supported by Mapper as a template file (e.g. file with floating-point values)
2. see the error message

### Actual behaviour
The error message is not very helpful to understand why the template won't load:
![image](https://user-images.githubusercontent.com/5598693/76805264-a95bfc80-67de-11ea-8c97-0080771af616.png)

### Expected behaviour
The message should be complemented with the information about supported (Geo)TIFF types, like:
"Unable to read image data. Only the following types of TIFF images can be loaded as templates:
* 8 bit grayscale (256 levels), optionally plus 8 bit alpha
* 8 bit indexed (256 colors palette)
* 24-bit RGB
* 32-bit RGBA"

### Configuration
Mapper Version: 0.9.2 & MASTER (v20200214.2)
Operating System: Win10Pro  v1903

**Comment by jmacura** [comment]
This is a "spin-off" of issue #1515.

**Comment by dg0yt** [comment]
Note that we actually talk about our GDAL raster image reader. It may load GeoTIFF but also other raster file formats. So error reporting probably won't be as accurate as my comment in #1515. 
However, the basic idea is fine.

**Comment by dg0yt** [comment]
While we don't explicitly report the supported raster variants, the image reader should already report the unsupported raster bands it finds:

https://github.com/OpenOrienteering/mapper/blob/e7f434ff22b97528006dc656ba80cc558a967716/src/gdal/gdal_image_reader.cpp#L108-L115

Looks like the message doesn't find its way to the UI.

**Comment by dg0yt** [comment]
And this is the reason. For TIFF, we do another attempt with Qt's TIFF reader:

https://github.com/OpenOrienteering/mapper/blob/e7f434ff22b97528006dc656ba80cc558a967716/src/gdal/gdal_template.cpp#L68-L82

**Comment by dg0yt** [comment]
Test with trmm.tiff  from https://github.com/OSGeo/gdal/tree/master/autotest/gdrivers/data

Mappper user interface: "Unable to read image data".
GdalImageReader reports to console:  "Unsupported raster data: GrayFloat32".
Qt's libtiff reports to console: "ERROR 1: foo:Sorry, can not handle images with 32-bit samples" 
(where "foo" is a constant string passed from Qt to TIFF).

**Comment by dg0yt** [comment]
So this is what will close this ticket:
![issue-1550](https://user-images.githubusercontent.com/13567791/78025569-8f7ff500-735a-11ea-9657-88dcd868ddb5.png)
