### ISSUE TITLE
Geopackage as template format

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1551]
[BT raster.zip](https://github.com/OpenOrienteering/mapper/files/4364842/BT.raster.zip)

### Steps to reproduce
1. Create Geopackage File from Raster Map in QGIS
2. (Naming convention xx_raster.gpkg)
3. (Reference systerm EPSG 2056)
4. Load as Template in Mapper

### Actual behaviour
Nothing. No error message neither.

### Expected behaviour
The template should be loaded.

### Configuration
Mapper Version: 0.9.2
Operating System: Windows 7

**Comment by dg0yt** [comment]
Did you also try `.raster.gpkg`? `_raster.gpkg` will use the vector data loader.

**Comment by mlerjen** [comment]
OMG. ;-)  .raster.gpkg is loading the template... I double-checked the GDAL manual page and realized that the point preceding  "raster" is always implicit, never explicit. If it is okay with you, I would adapt the page changing the list of extensions to their explicit form e,g, ".raster.gpkg" even if this might not be 100% in terms of  the definition of extension (as behind the dot).

Now I only have to deal with the problem, that the loaded raster still is displayed as empty...

**Comment by dg0yt** [comment]
Well, I added the raster/vector for removing ambiguity. We are not yet able to handle hybrid files well (There is also XML, KML etc.). And we don't handle tiles, which may be an issue here. Just leave this issue open.
(Note that this is why we need volunteers to test the snapshots: If we find limitations, we can at least put it to the release notes of official releases.)

**Comment by dg0yt** [comment]
>  I would adapt the page changing the list of extensions to their explicit form e,g, ".raster.gpkg" even if this might not be 100% in terms of the definition of extension (as behind the dot).wq

The tables are generated, so we need to change the generator (mapper-gdal-info).

**Comment by mlerjen** [comment]
It works for geopackages, if 
1) you comply with the naming conventinon Map.raster.gpkg
2) you opt for "rendered image" and no pyramids for the export from QGIS
