### ISSUE TITLE
Unexpected declination adjustment

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1552]
### Steps to reproduce
1. import ocd (OCAD10) file
2. save as omap
3. open omap

### Actual behaviour
Mapper shows a warning message:
"Inconsistent declination/grivation detected. Declination adjusted from 0° to 0,01°."
Note: although the declination gets changed the map is not marked as having unsaved changes.

### Expected behaviour
I'm not sure whether this adjustment really needs to be done.

### Configuration
Mapper Version: 0.92 (x64)
Operating System: Win7x64

**Comment by dg0yt** [comment]
Well, most likely it needs to be done earlier in this context. 0.01° sounds like a rounding issue.

**Comment by dg0yt** [comment]
That map file is close to the central meridian of UTM Zone 32 (9°), in SW Germany. At this location, grid convergence is 0.01° indeed. So the declination must be different from the grivation.

Assuming that the map is drawn with regard to the current alignment of the templates and that the templates have stable rotation against true north (= grivation), it is reasonable to leave the map's grivation unchanged, and adjust the value of the declination instead, based on the calculated grid convergence, to establish consistency.
(If the calculated declination does not match real declination, the user may adjust that from the georeferencing dialog, rotating the map as needed.)

However, this adjustment is implemented for loading .OMAP files only, not for loading .OCD files. This may need work. However, I would still not trigger the flag for unsaved changes. Either you do other changes, or we leave the file unmodified.

**Comment by dl3sdo** [comment]
Thank you for the explanation Kai.

**Comment by dg0yt** [comment]
Need to verify the OCD import/export case. (Don't unnecessarily change the OCD file, but always write a valid OMAP file.)
