### ISSUE TITLE
Enhancement Request - add little gap between the moving frame and the ends points.

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#1555]
### Actual behaviour
When i edit ends points of objects, very often and particularly with a stylus on android, the moving frame is selected instead of the point.
It's annoying because I move the object what I don't want.

### Expected behaviour
Tell us what should happen instead
Add little gap between the moving frame and the ends points to avoid mis selected éléments.

**Comment by ollesmaps** [comment]
I believe this is the same issue as #980.

**Comment by eolmapper** [comment]
> I believe this is the same issue as  #980.
Yes

**Comment by dg0yt** [comment]
Please subscribe to and/or "like" the other issue than.
