### ISSUE TITLE
Enhancement request - Help me smooth my curves

### ISSUE THREAD

**Issue by kjetilk** [OpenOrienteering/mapper#1556]
As the manual says:
> Note: While this way of drawing curves may seem to be difficult at first, it is important to get used to it. Drawing "smooth" curves with many small straight segments instead is not an alternative, as these will look ugly when viewed closely. Just practice Bézier curve drawing until you get used to it. Less nodes are often better than too many.

As a casual map drawer, I just don't get enough practice. I have tried, but I'm still awful at just this problem. I've tried the simplification tool, but that makes my curves look even sharper...

Thus, my enhancement request is a tool to help me smooth my curves, possibly using a smoothing spline or something. I'm so bad, a computer should do better :-)

**Comment by dg0yt** [comment]
Could you provide screenshots, screencasts, or at least map example of what you are trying to achieve?

**Comment by otoomet** [comment]
@kjetilk , have you tried "convert to curves" and "simplify" tools?  I am regularly using those and usually happy with the result.

**Comment by kjetilk** [comment]
On tirsdag 24. mars 2020 16:50:00 CET Kai Pastor wrote:
> Could you provide screenshots, screencasts, or at least map example of what
> you are trying to achieve?

Yes, here's a screenshot attached (my home is in the lower left :-) ). The 
contours follow the 1 meter equidistant traces closely, but they are drawn by 
me using the Paths tool. And as you can see, they are not pretty. 

Indeed, this is a PEBKAC problem, so I am asking for tools that are better 
than me. Yes, I have tried the simplification tool, but what I see then is 
that the sharp edges become even more pointed, as in the second screenshot.

Kjetil

**Comment by dg0yt** [comment]
> Yes, here's a screenshot attached (my home is in the lower left :-) )

No, there isn't...

**Comment by kjetilk** [comment]
Huh? Oh well, how about now:

![Screenshot_20200325_103047](https://user-images.githubusercontent.com/154068/77593701-e8800100-6ef4-11ea-8b20-025ce59567d8.png)
![Screenshot_20200325_102306](https://user-images.githubusercontent.com/154068/77593702-e9189780-6ef4-11ea-80ed-e2784cb682f8.png)

**Comment by dg0yt** [comment]
Do I understand correctly that you talk about the contours, and that your starting point is a set of generated lines which have straight segments?

Could you perhaps add two more screenshots of the first (small) example:
a) What is created by tool "Convert to curves"?
b) What is your expected outcome? (manually...)

You might also copy and paste the example path to a new map which you could share with us more easily (attached in ZIP file, or via direct e-mail).

**Comment by mlerjen** [comment]
@kjetilk: You can not leave this to an algorithm. 
https://youtu.be/rq7mzkhXoKk

**Comment by kjetilk** [comment]
So, after drawing a more, I have found that what has mostly been happening is that I haven't done curves, I have done straight segments. So, thank you, @mlerjen, that helped me train, but how about the possibility of having a tool that would convert an object from straight to curved, rather than using the edit lines tool and click every segment separately?

**Comment by kjetilk** [comment]
After having made more drawings, I have found that the "convert to curves" tool does address what I need. I'll start using that now, thanks!
