### ISSUE TITLE
Add parallel curve movement function

### ISSUE THREAD

**Issue by xianchb** [OpenOrienteering/mapper#1560]
Optimization suggestion: I hope to add the parallel movement function. This will be more convenient when dealing with the other boundary of the road, special parallel curves and circular fields.

**Comment by dg0yt** [comment]
Do you mean the feaure requested in #273, i.e. work-in-progress in #1539, or something else?

**Comment by mlerjen** [comment]
Might be #650. It is a concentric shift, but the result is a pair of parallel lines.

**Comment by xianchb** [comment]
> Might be #650. It is a concentric shift, but the result is a pair of parallel lines.
#650 is  what I mean，thanks.

**Comment by xianchb** [comment]
> Might be #650. It is a concentric shift, but the result is a pair of parallel lines.

#650 is what I mean，thanks.

**Comment by dg0yt** [comment]
Allright. You can subscibe to #650 then.
