### ISSUE TITLE
Question: OpenOrienteering Mapper in F-Droid repository

### ISSUE THREAD

**Issue by jmacura** [OpenOrienteering/mapper#1572]
### Context

I have yet another (#1447) question about package managers :-) I've started to use F-Droid recently. For my own surprise, I have found OpenOrienteering Mapper in its repository: https://f-droid.org/en/packages/org.openorienteering.mapper/ but the last version available there seems to be 0.6.8.
I was just about to propose publishing Mapper there, instead of Google Play (#607), as it seems more feasible for now (no Android target API limitations). But then I've found it is already listed.

### Question

Is the Mapper metadata file (https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.openorienteering.mapper.yml) in F-Droid database an official release maintained by OpenOrienteering? What blocks updating the package with new releases?

### Configuration
Mapper Version: latest stable builds
Operating System: Android

**Comment by sikmir** [comment]
See #517

**Comment by jmacura** [comment]
Obvious duplicate, sorry...
