### ISSUE TITLE
How to make transparent corridor-o symbol? (to be cut out of a white area symbol)

### ISSUE THREAD

**Issue by Freemapper** [OpenOrienteering/mapper#1574]
### Steps to reproduce
1.
2.
3.

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by mlerjen** [comment]
If I got you right, you just draw the corridors with any area symbol. Then make the cut-out from the white area and finish with deleting the area symbol used for the corridors. Right?

**Comment by Symbian9** [comment]
> transparent corridor-o symbol (cut out of a white area symbol)

Its really depend on expected result: should be "temporary cutout" or "permanent cutout"?

@Freemapper, could you provide more info? (some pictures/map examples)

**Comment by Freemapper** [comment]
Yes I tried for long time to make a new area symbol 20m wide and transparent, but have failed so far in OOM. Se "Corridor" in this Ocad-link:
 https://www.ocad.com/wiki/ocad/en/index.php?title=O-training_with_OCAD#Corridor

After creating this symbol it would be easy to use the "Cut out" function on a white overlay.

**Comment by Symbian9** [comment]
> Se "Corridor" in this Ocad-link:

As a workaround, create top-level printing knockout area and cut "hole" along corridor borders, as I explained here:

- https://github.com/OpenOrienteering/mapper/issues/1102#issuecomment-412242879

Sadly, Mapper has no *"eraser color"* feature (yet?) that would be much more better way to cut corridors throw top level color area.

**Comment by Freemapper** [comment]
I svan a map and use it as background. Them I cover it with a White area but later diselect the map in the layers box. Them I would like to use an area symbol wich is for ed as a 20m wide line in transparent colour. Ocad can do it but I dont think Mapper can do this symbol. I tried to modify the Road symbol but since its a line symbol, the cut tool cuts it right in the middle of The corridor and not aling its edge.  Found 20m corridor-o to be The most challenging training Ive done the last 40 years of o-running. Hate to be forced to do this maps in Ocad just of principle.

**Comment by Symbian9** [comment]
> Them I would like to use an area symbol wich is for ed as a 20m wide line in transparent colour.

There is no "transparent color" feature in actual Mapper colors implementation.

Sadly, Mapper also has no *"eraser color"* feature (yet?) that would be much more better way to cut corridors throw top level color area.

- https://github.com/OpenOrienteering/mapper/issues/151#issuecomment-231145643

So, if you want keep map as  template (without cutting map objects directly), use workaround from my comment above and manually draw hole around corridor. That is the only solution as for now (until Mapper would got "eraser color" feature)

**Comment by dg0yt** [comment]
Note that a follow-border-line feature will be in the next master build (cf. #273), so you use the border line of a corridor symbol.

**Comment by Freemapper** [comment]
Thanks. A follow-border-line feature is exactly what´s needed when making a corridor with many narrow 180 degrees turns. The line-symbol I created is 3 mm wide and non-coloured. The outer edge is 6 mm wide and has white overprint. The 180 degree turns I can create quickly is 60-100 m wide but narrower turns create strange intrusions in the middle visible corridor. Later I manualy follow the white edge when covering the rest of of the map with white colour. It would be far easier to be able to just use the cutaway tool.  Many thanks to the creators of OOM by the way... I love it.

**Comment by dg0yt** [comment]
For the record, I also checked if you couldn't just use the "Fill" tool - this would be much easier than following lines. However, this tool also only uses the base line, not the border. Maybe we could use Shift or Control keys as modifiers...

**Comment by dg0yt** [comment]
https://github.com/OpenOrienteering/mapper/releases/tag/master-v20200411.3
