### ISSUE TITLE
Crash if Cut hole mask spans complete object

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1578]
### Steps to reproduce
1. draw an area object
2. select it and choose any of the three 'Cut hole' operations
3. draw a circle, rectangle or free form that contains the selected area completely

### Actual behaviour
Mapper crashes

### Configuration
Mapper Version: v20200411.3
Operating System: Win7x64

**Comment by dg0yt** [comment]
Happens in v0.9.2, too.
