### ISSUE TITLE
Tool to move a line parallel to an existing line.

### ISSUE THREAD

**Issue by MartinHore** [OpenOrienteering/mapper#1588]
### Steps to reproduce
1. I have a line (curved or straight line segments) eg a ditch. 
2. I want to produce a feature exactly parallel to this eg a fence
3. In OCAD I can fill the first feature with the second, then drag it parallel to the first using the move parallel tool. Can this be done in OOM? It would be useful. 

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dl3sdo** [comment]
This feature was just recently discussed (again), see #650

**Comment by dg0yt** [comment]
The general case is requested in #650. Just following the border reached the master build (#273).

**Comment by MartinHore** [comment]
Many thanks

I have tried to follow the links but it's a bit complicated for a newbie. Am I right that contributors are working on this but it's not yet enabled in OOM 9.2? One link I followed led to a mention of a possible temporary workaround, but I've not been able to find that again. 

In the meantime I've been solving the issue myself by copying the feature to follow into a new OOM file, saving that in OCAD, performing the parallel (ie concentric) shift in OCAD, re-opening in OOM and copying back to my map file. Only worth doing if I have a long feature to follow parallel. Apart from occasional work-arounds like this I'm working exclusively in OOM now and generally find it more user-friendly than OCAD (which our club has not updated since OCAD 9). So many thanks to all the OOM developers.

I don't have the level of programming knowledge required to contribute myself I'm afraid.

Regards

Martin

**Comment by ryan-mooore** [comment]
As far as I'm aware, the code for this feature still needs to be written but the issue is very much active.

The comment you mentioned about the temporary workaround I assume is here: https://github.com/OpenOrienteering/mapper/issues/650#issuecomment-612637604.

The video mentioned in the comment demonstrates that by using the new follow-border functionality, you can create a temporary wider symbol in place of the main symbol you want to use to draw a new symbol parallel to and use the border of it to draw a parallel line.

Hope this makes sense.

**Comment by dg0yt** [comment]
> a possible temporary workaround

Note that the follow-line feature is only [in the current "master" release](https://github.com/OpenOrienteering/mapper/releases/tag/master-v20200411.3), not yet in v0.9.2.

**Comment by MartinHore** [comment]
Thanks for everyone's help  with this. The follow border-line feature will be very useful in its own right, as well as for a temporary workaround for concentric shifts . I'll see if I can pick it up from the "master" release - otherwise I'll wait (I presume) for version 9.3.  

Having recently joined the GitHub group it's great to see how much work is being done to improve OOM. Many thanks everyone. I'm sorry I don't have the programming expertise to contribute myself. 

Martin

**Comment by dg0yt** [comment]
Thank you Martin. I would like to use the opportunity to invite 
- feedback on issues and feature requests,
- testing the master builds, 
- feedback and contributions to documentation, translations or English wording etc. 

This doesn't require programming expertise, and the master builds normally shouldn't need more backups than you would do anyway ;-)

**Comment by MartinHore** [comment]
Yep - just succeeded in downloading the master release and experimented with following borderlines, and using this as a workaround for concentric shifts. All works perfectly. 

Mostly I need concentric shifts for drawing two features parallel (eg ditch and fence) when in reality they are, at map scale, virtually on top of one another (eg one or two metres apart). So I just need one throw-away symbol with borderlines at minimum separation for legibility - draw that where the ditch and fence should be, follow the borderlines with the ditch and fence symbols, then delete the throw-away. Not a big problem as a temporary workaround at all. Thanks everyone.

Martin

**Comment by MartinHore** [comment]
> Thank you Martin. I would like to use the opportunity to invite
> 
> feedback on issues and feature requests,
> testing the master builds,
> feedback and contributions to documentation, translations or English wording etc.
> 
> This doesn't require programming expertise, and the master builds normally shouldn't need more backups than you would do anyway ;-)

Thanks - will do.  I noted that you would appreciate translating expertise. My wife is Russian and a qualified and experienced English/Russian translator. Let me know if that would be of use anytime.

Martin

**Comment by mlerjen** [comment]
@MartinHore: You/your wife might check https://hosted.weblate.org/projects/openorienteering/mapper/ once in a while.

**Comment by MartinHore** [comment]
> @MartinHore: You/your wife might check https://hosted.weblate.org/projects/openorienteering/mapper/ once in a while.

Thanks - just checked your link. My wife and I can get the Russian version back up to 100% I expect. (It's close already - just a few recent updates as far as I can see.)  Can I get a full Russian version of OOM to download for context? I can't see how to do that on the download page on the OOM website - perhaps because the site knows I speak English.

Martin

**Comment by mlerjen** [comment]
Just switch to Russian in your Mapper>File>Settings ...
![image](https://user-images.githubusercontent.com/15611653/80276613-3b162e00-86ea-11ea-80df-2ff6165912a8.png)

**Comment by mlerjen** [comment]
btw. Another work-around for features mostly drawn as straigt lines... (a distance holder 0.15mm integrated into the symbol)
![image](https://user-images.githubusercontent.com/15611653/80276724-c98aaf80-86ea-11ea-9616-74c43a33101b.png)
![image](https://user-images.githubusercontent.com/15611653/80276775-18d0e000-86eb-11ea-9846-6dcbbf6f9591.png)

**Comment by MartinHore** [comment]
Thanks, that's great. We'll look at the missing Russian words/phrases this weekend. In lockdown here as I expect you are too. 
Martin
