### ISSUE TITLE
Rotation error with non-georeferenced DXF template

### ISSUE THREAD

**Issue by pkturner** [OpenOrienteering/mapper#1591]
### Steps to reproduce
1. Map with open but invisible, non-georeferenced DXF template
2. Open map in Mapper.
3. Use the Georeferencing dialog to change declination.
4. Accept offer to rotate the map.
5. Make the template visible.

### Actual behaviour
The template appears, rotated twice as much as needed.

### Expected behaviour
The template should appear aligned with the map.

### Configuration
Mapper Version:0.9.2
Operating System:Linux

This is a case in which the template has or will have an `explicit_georef`. Perhaps it needs to be handled the same as a georeferenced template by `Map::rotateMap`.

**Comment by pkturner** [comment]
I should add that in the original .omap file, the template config has an empty `<crs_spec>` element. If the map is saved after the performing the listed 5 steps, then it gets a `<georeferencing>` element in place of the `<crs_spec>`.

**Comment by dg0yt** [comment]
Thanks for reporting. I have an idea what it is happening, and why. I'm working on this template class in order to deal with geographic coordinates in DXF files.

**Comment by pkturner** [comment]
That sounds reasonable, thank you. This is not a priority for me.

**Comment by dg0yt** [comment]
Apart from other changes in my pipeline, this may be benefit from our recent PRs.

**Comment by pkturner** [comment]
I checked with your latest commit related to #1604, namely [4d8729c](https://github.com/OpenOrienteering/mapper/pull/1604/commits/4d8729c60f5f50a19af3b401f003ab2eb43b8014) ([GeoreferencingDialog: Unify geographic reference point updates](https://github.com/OpenOrienteering/mapper/pull/1604/commits/4d8729c60f5f50a19af3b401f003ab2eb43b8014)). I also tried my variation on that, and it still shows the issue.

**Comment by dg0yt** [comment]
Okay, I will look at this for 0.9.4.

**Comment by pkturner** [comment]
@dg0yt 
For what it's worth, here's an analysis which presumably agrees with your "idea of what is happening".

The relevant concepts interfere with one another. Because the template is non-georeferenced, it has a `TemplateTransform` which is an adjustment applied to its `TemplateMap` map coordinates. At the same time, the `TemplateMap` adjusts the DXF coordinates according to the grivation of the main `Map`. The problem occurs when the user rotates the map. This rotation is applied both to the map's grivation and to the `TemplateTransform` of every non-georeferenced template. Thus the template, when made visible, shows double the desired rotation.

To fix this, I think the template needs to be identified when its XML is read, as a third category. It is not georeferenced, nor is it a basic non-georeferenced case that uses its own paper coordinates directly. Perhaps this should be implemented by assigning an `explicit_georef` within `loadTemplateConfiguration`, rather than waiting until `mapTransformationChanged` is called. I'm uncertain about that approach, because it would interact with the `template_track_compatibility` flag, which I don't understand.
