### ISSUE TITLE
add Android app on Mapper manual

### ISSUE THREAD

**Issue by rem-maps** [OpenOrienteering/mapper#1596]
I've playing a bit with bluetooth GPS on Android and I found out that the app needed for Mapper (called 'Bluetooth GPS' ) has some users on Google Play stating it is not working with Android 10. 

Maybe it is not the case (some others users say it is fine) but I have found another one working properly (also providing mock location) so maybe it is worth to add this
called 'Bluetooth GNSS'
https://play.google.com/store/apps/details?id=com.clearevo.bluetooth_gnss&hl=en
to the manual page as an alternative
https://www.openorienteering.org/mapper-manual/pages/android-requirements.html

and the name GNSS is more appropriate than GPS :-)

**Comment by dg0yt** [comment]
Thanks for your proposal. It is not just an interesting app, but the developer/company also seems to offer an experimental receiver, https://www.clearevo.com/ecodroidgps/. 

The play store description claims that the app is open source. I tried to check this, and what I found is https://github.com/ykasidit/libbluetooth_gnss, by @ykasidit. Not sure if it is the complete app, but it is licensed GPL2+ which is compatible with Mapper. Maybe it helps to (learn how to) manage the link from Android Bluetooth to the NMEA parser which is already in Qt directly within the Mapper app.

And yes, I would like to use the term "GNSS" more frequently, too.

**Comment by ykasidit** [comment]
Thanks for using the Bluetooth GNSS app! Yes it's open source, this repo is the java engine part which does all the connection and parsing nmea and some ubx/pubx from bt dev, rtk ntrip relay to bt dev, the UI part (flutter dart + java glue to this engine) is at: https://gitlab.com/ykasidit/bluetooth_gnss - I plan to move it to GitHub and add links in the readme so they can be more easily found together... Yes, the app have Android 10 support as well as Galileo counts and RTK too - thanks again for your interest in this humble project ;-)

**Comment by Symbian9** [comment]
> And yes, I would like to use the term "GNSS" more frequently, too.

What about @lpechacek's DIY/open-hardware *Bluetooth GNSS receiver*?

- https://github.com/lpechacek/u-blox-gnss-receiver

**Comment by ollesmaps** [comment]
Thank you @ykasidit for your work. 
Just to let you know - if there was an option to power the EcoDroidGPS with battery - the orienteering mapping community would definetely consider it worth buying.

**Comment by lpechacek** [comment]
FWIW, I've spent a few hours in the forest with Bluetooth GNSS. The things I like
* Works just fine. Choose Bluetooth receiver, connect, and enjoy.
* Has a built-in NTRIP client. Cool!
* Is stable. The connection froze once and I don't think it was the application problem but rather something with the Bluetooth connection.
* The app seems to parse u-blox PUBX,01 message for accuracy estimates. That would lead to a longer discussion but it's matter of fact that HDOP says essentially nothing about accuracy in multi-constellation settings. NME GST sentence gives a better clue about what is going on in the receiver and the proprietary PUBX,01 is perhaps the best indicator of receiver's error estimate.
* Does exactly what I need. I was on the verge of reviving bluegnss4droid project to get the additional functionality which is already in Bluetooth GNSS.
* The license is a clear benefit in my eyes.

Suggestions for enhancement
* List signal C/N0. I sometimes check whether SBAS satellites are available and what is the signal strength.
* Separate NTRIP client controls. I do not want to feed RTCM corrections stream all the time into the receiver. Instead, I'd like to use it as a sort of "afterburner" - switch it on only as needed and save the costs of data transfer.
* The receiver connect and disconnect functions should be co-located. :)
* Support for u-blox Bluetooth Low Energy (BLE) Serial Port Service or another BLE serial port service implementation.

Overall, I like the direction in which the application is evolving. Keep up the good work, @ykasidit!

**Comment by ykasidit** [comment]
Thanks for your kind comments! Very happy to see that it meets your needs!
@ollesmaps - thanks for your suggestion - will try see how this can be implemented easily/modularly - right now users use it with a battery pack - maybe we'll try add a mount or straps in the kit...
@lpechacek - thanks for your review and suggestions - will definitely put them in the TODO list...

**Comment by rem-maps** [comment]
and FYI guys @ollesmaps  @dg0yt @lpechacek @Symbian9 I want to share with you that I bought C099-F9P application board from ublox
https://www.u-blox.com/en/product/c099-f9p-application-board

I'm no GNSS expert so I'm afraid to say stupid things (and also I don't understand every single word of Libor's amazing document on his GNSS tests) but as far as I know ZED-F9P looked the best accuracy-price option for orienteering mappers and this could be helpful for you all.

I configured everything and it's working smooth with android and Mapper (with Bluetooth GNSS app) and now I'm just waiting for the lithium battery (arriving from China) to test it outdoor.

I plan to use it without RTK corrections but I'm open to that if I understand how to do it  (I don't know if that is possible like buying a second unit and leave it in the forest as a base while mapping?)

I don't know anything in electronics so I'm doing everything with the assistance of an Italian friend also active in orienteering that already assembled  his unit and fully working with a lithium battery  18650 3000mAh 3.7V (but he's not 'professsional' mapper so he never used it in a forest with valleys or pine trees)

this is his unit assembled:
![WIN_20200308_14_41_15_Pro](https://user-images.githubusercontent.com/59602742/81193434-af3eb480-8fbb-11ea-8e30-130ef2d58236.jpg)

**Comment by joffhk** [comment]
Hi all. I'm new to this thread and haven't used openorienteeringmaps yet, but I have been using the ardusimple Ublox F9 for orienteering mapping (still using OCAD for drawing). I have also been using Kasidit's excellent Bluetooth GNSS app, and I can personally vouch for his expertise and continued support. I find both the F9 and BTGNSS app both stable and reliable, and the F9 accuracy (using Galileo) is perfect for orienteering mapping. Even without RTK, I can reliably get 1-2m accuracy even under tree cover (important to mount the aerial on top of your hat with reasonable ground plane underneath - I use 140mm diameter thin metal plate -  to cut down on multi-path effects) and the RTK option is easy to use when there is mobile data coverage and close to a base station. Like someone mentioned above, I usually turn on RTK before I start mapping - confidence check - then turn off to save data, but sometimes turn on briefly during a survey day when have mobile coverage. So far I have never seen a significant shift in position (always less than 1m!) when turning on RTK so I am getting more and more confident that the F9 can manage alone. I looked at post-processing but it was a lot more work and no significant accuracy improvement. I power the ardusimple F9 from a USB phone power pack, I think more reliable than wiring up a lithium battery inside the box.
