### ISSUE TITLE
No longer able to specify template image coordinate system

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#1597]
### Steps to reproduce
1. Open template with world file
2. Select (keep) "Georeferenced (World file)" option and click "Open"

### Actual behaviour
There is no longer a way to tell OOM that the template is using lat/lon instead of UTM coordinates.
### Expected behaviour
Have a way to specify the template coordinate system.

### Configuration
Mapper Version: 0.9.2 and v20200411.3
Operating System: Mac OS 10.15.5

**Comment by dg0yt** [comment]
Thanks for reporting. I noticed this bug, too, and it is taken care of in bd88058 (part of GH-1595, pending).

The idea is not to generally skip template CRS selection, but only immediately after setting up the map georeferencing, assuming that the template will (intentionally) use the same CRS in this particular case.
