### ISSUE TITLE
Crash in Symbol Editor's Combination settings

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1600]
### Steps to reproduce
1. Edit a symbol consisting of combined symbols, e.g. 501.0 Motorway
2. In 'Combination settings' increase Number of parts from 2 to 4 or to 5
3. For Symbol 4 or 5 choose any symbol (for private line or area symbol: just cancel it)
4. Press Reset button => Mapper always crashes

### Actual behaviour
Mapper always crashes

### Configuration
Mapper Version: v20200411.3 or v0.92
Operating System: Win7x64

**Comment by dg0yt** [comment]
Extra step required to reproduce the crash:

5. Click 'Cancel'

**Comment by dl3sdo** [comment]
Of course, sorry, I forgot to mention the 'Cancel' operation.

**Comment by dg0yt** [comment]
Well, memory corruption happens on 'Reset' indeed... my setup just doesn't crash before 'Cancel'.
