### ISSUE TITLE
Some area symbol objects trigger a crash

### ISSUE THREAD

**Issue by valdisj** [OpenOrienteering/mapper#1608]
### Steps to reproduce
1. Opening OCAD12 file in Mapper

This happens with this OCAD file in attach. Other OCAD files are opening normal. But its worth to check, if something special is making MAPPER to totally crash, since this could be indication of wider problem.

### Actual behaviour
Mapper totally crashes. 

### Expected behaviour
OCAD file is opened.

### Configuration
Mapper Version: 0.9.2
Operating System: MacOS
[Bargupite_SIkompass-2019.ocd.zip](https://github.com/OpenOrienteering/mapper/files/4609190/Bargupite_SIkompass-2019.ocd.zip)

**Comment by lpechacek** [comment]
Possible fix.

```
diff --git a/src/core/symbols/line_symbol.cpp b/src/core/symbols/line_symbol.cpp
index d0c8ed207a8a..e28f99198972 100644
--- a/src/core/symbols/line_symbol.cpp
+++ b/src/core/symbols/line_symbol.cpp
@@ -403,7 +403,7 @@ void LineSymbol::createSinglePathRenderables(const VirtualPath& path, bool path_
        if ((create_line || create_border) && processed_coords.size() > 1)
        {
                VirtualPath processed_path = { processed_flags, processed_coords };
-               processed_path.path_coords.update(path.first_index);
+               processed_path.path_coords.update(0);
                if (create_line)
                {
                        output.insertRenderable(new LineRenderable(this, processed_path, path_closed));
```

**Comment by dg0yt** [comment]
@lpechacek Yes, this argument should always be zero, or rather `processed_path.first_index`. Broken since 7c26d51e, when I renamed the local variable `path` (shadowing a parameter with same name) to `processed_path`.

**Comment by lpechacek** [comment]
Minimal reproducer. The key points are - combined symbol (area+dashed line), line dash longer than the hole in the area, and the hole must have at least one Bézier segment.

[crasher.omap.gz](https://github.com/OpenOrienteering/mapper/files/4611581/crasher.omap.gz)
