### ISSUE TITLE
Templates window show wrong information after adding Draft template

### ISSUE THREAD

**Issue by andzs** [OpenOrienteering/mapper#1613]
### Steps to reproduce
1. Open Forest map sample
2. Make Template setup window visible CTRL+SHIFT+9
3. Click "Paint on template tool", choose "Add template..." and press Draw

### Actual behaviour
Now Templates window show 2 items: "Draft..." (upper one) and "- Map -" lower one.
Actually this is  incorrect because  -Map- is upper one. Try clicking show/hide check boxes
and see what happens.

### Expected behaviour
Templates window should display correct information right after adding new Draft template.

### Configuration
Mapper Version: 0.9.2
Operating System: OS Name: Microsoft Windows 10 Enterprise OS Version 10.0.17763
![Template](https://user-images.githubusercontent.com/7015947/81694272-cec95780-9469-11ea-896c-435205fc748f.png)

**Comment by dg0yt** [comment]
Thanks for reporting. I'm working on cleaning up this code, and similar issues are going away soon.
