### ISSUE TITLE
In 0.9.2 addition of georeferenced Ocad template places it incorrectly.

### ISSUE THREAD

**Issue by andzs** [OpenOrienteering/mapper#1620]
### Steps to reproduce
1. Open Map.omap in 0.9.2 from attached archive. It shows georeferenced map with one TIF template in background.
2. Press CTRL+SHIFT+9 to open Template setup window
3. Add new template 4311-44-34_Contours.ocd (georeferenced Ocad file) from attached archive above TIF template.

### Actual behaviour
Loaded Ocad template does not match TIF template. There is some offset. Both are for the same tile, the same coordinate system. Version 0.9.1 does not have this behaviour and works correctly.

### Expected behaviour
Both templates should match.

### Configuration
Mapper Version: 0.9.2
Operating System: Microsoft Windows 10 Pro 10.0.18362
[OcadTemplateBug.zip](https://github.com/OpenOrienteering/mapper/files/4620472/OcadTemplateBug.zip)

**Comment by dg0yt** [comment]
Thank you very much reporting. 

I see different scale factors in template positioning. @pkturner: git bisect points to 34bb323.

**Comment by pkturner** [comment]
@dg0yt I'm looking into it.

**Comment by pkturner** [comment]
[GH-1621](https://github.com/OpenOrienteering/mapper/pull/1621) fixes this.

It's funny how one day some of the code looks a little wrongish, and then the next day you spend a few hours tracking down a problem to the same few lines of code.

I think it would be even better to combine `grivation_locked` with `scale_factor locked`, and consolidate on a single parameter to `setProjectedRefPoint` that controls updating both grivation and scale factor. Similarly for `setGeographicRefPoint`.
