### ISSUE TITLE
Wrong default GPS source on Android app 0.9.3

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#1629]
### Steps to reproduce
1. Start Android mapper app
2. Set up app to use GPS
3. Tap the move to location icon

### Actual behaviour
Nothing
### Expected behaviour
Map should pan so that current location is in the middle of the screen. The red GPS symbol should display.
### Configuration
Mapper Version: 0.9.3
Operating System: Android 10 and Android 7

This works perfectly on 0.9.3 and on v20200411.3

**Comment by dg0yt** [comment]
Thanks for reporting. Looks like the default sensor changed. Please go to Setting > Sensors, and choose Android.

**Comment by sfroyen** [comment]
That did the trick. Thanks for the quick response!

**Comment by pekko** [comment]
Hey, I'm seeing similar behavior now on 0.9.5 with Android 13, Samsung Tab S6 Lite. Mapper asked for location permissions but doesn't display anything, also compass doesn't move anywhere. I've tried to force sensor to "android", no difference. Happy to provide any debug info that would be helpful.

**Comment by sfroyen** [comment]
Hi Pekko,

I have a couple of Samsung Galaxy Tab tablets (Active 3 and Active 5). I usually use an external GPS and employ the mock GPS setting in order receive the GPS data over Bluetooth.

The Active 3 is using UI Version 5.1.1 and 5 is on UI Version 6.1 (Android 14)

I just tested what would happen if I did not connect the an external Bluetooth GPS. After starting OOM, and after waiting a while (several seconds), Mapper displays the correct location, presumably using the internal tablet GPS. (I did not turn off the mock GOS setting for this test).

Note that you have to tap the GPS on button and the double circle button with the red GPS icon in order for the location to show. But I suspect you did this.

I suggest installing the barbeauDev gpstest app for Android from the Google Play store. It provides a lot of information about your tablet’s GPS status.

Regards,
Sverre

**Comment by dg0yt** [comment]
@pekko If your issue isn't resolved with @sfroyen's hints, please open a new issue.
