### ISSUE TITLE
Linux OBS builds of v0.9.3 still unavailable for some distro

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1632]
### Steps to reproduce

1. Try install 0.9.3 under Debian 10 via OBS 

### Actual behaviour

OBS builds not available for Debian 10, but already available for Debian 9 and Debian Testing.

- https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper

![pic.1](https://i.imgur.com/zxaDIEN.png)

### Expected behaviour

Builds should be available for all supported Linux distros, including Debian 10.

### Configuration

- Mapper Version: `0.9.3`
- Operating System: Linux (Debian 10)

**Comment by dg0yt** [comment]
I'm aware of that, but I didn't want to have the other distributions wait just because there is a bug in the default version of GCC on Debian 10. Feel free to quickly provide a patch to the OBS package. Probably there is an alternative compiler package such as clang.

**Comment by dg0yt** [comment]
References: 
https://build.opensuse.org/package/live_build_log/home:dg0yt/openorienteering-mapper/Debian_10/x86_64 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89050

**Comment by Symbian9** [comment]
Is there bug report on OBS?

- https://github.com/openSUSE/open-build-service/issues

**Comment by Symbian9** [comment]
Just tried to install Debian 9 package under Debian 10: while `libpolyclipping16` and `libproj12` dependency could be installed from Stretch repo, `qtbase-abi-5-7-1` dependency is fully not satisfiable.

Is there a reason to keep both `libqt5core5a (>= 5.7.0)` and `qtbase-abi-5-7-1` (which provided by by `libqt5core5a (>= 5.7.0)`) instead of just single `libqt5core5a (>= 5.7.0)` dependency?

**Comment by dg0yt** [comment]
> Is there bug report on OBS?

It is not a bug in OBS. It is a bug in gcc 8.3. It is now solved in our OBS package by switching back to `g++-7` for Debian 10, and removing Fedora 29.

**Comment by dg0yt** [comment]
> Is there a reason to keep both libqt5core5a (>= 5.7.0) and qtbase-abi-5-7-1 [...]

Yes. Only `libqt5core5a` versions that provide `qtbase-abi-5-7-1` are binary compatible with our package: We need to use some "private" interfaces of Qt, and these can be changed in binary incompatible ways in new versions of Qt.
