### ISSUE TITLE
"More specific rules need to follow more general rules" in CRT files actually works reverse

### ISSUE THREAD

**Issue by reinisberzins** [OpenOrienteering/mapper#1640]
### Steps to reproduce
1. I wrote a test.crt file with these 3 lines following the advice "more specific rules need to follow more general rules" in the manual (https://www.openorienteering.org/mapper-manual/pages/crt_files.html):
406 natural = wood
408 natural = wood AND wood:age = young
404 wood:density = sparse
2. I loaded this CRT file in my OMAP file with 3 different woodland objects:
- 1st woodland tags: natural = wood
- 2st woodland tags: natural = wood ; wood:age = young
- 3rd woodland tags: natural = wood ; wood:age = young

### Actual behaviour
All 3 different woodlands converted to the same symbol 406 (the same happened with test.crt and with the built-in OSM-ISOM 2017-2.crt).
When I reordered the 3 lines in my CRT file in reverse order, then every woodland converted to a different symbol (as they should).

### Expected behaviour
Reading the manual page I assumed that every next line re-assigns symbols to all matching objects (including those which were already assigned symbols by previous lines), but it's the reverse.
This current behaviour is acceptable too, but it contradicts with manuals and built-in CRT files and creates confusion.

### Configuration
Mapper Version: 0.9.3
Operating System: Windows 10 x64

**Comment by dg0yt** [comment]
Thanks for reporting!

I think we should change the behaviour to match documentation.
- The order in the files (first general, than special) seems more natural.
- The order in the files also determines the order in the symbol replacement dialog.
- There should be no side effects on CRT files which use unique code numbers only.

In the end, it might be enough to reverse the list of rules before applying them on the objects, still short-cutting after the first match, for performance.

**Comment by dg0yt** [comment]
Extra note: `wood:age` becomes `wood_age` unless we explicitly set `attribute_laundering=no`.

**Comment by dg0yt** [comment]
> Extra note: `wood:age` becomes `wood_age` unless we explicitly set `attribute_laundering=no` in mapper-osmconf.ini.

https://github.com/OSGeo/gdal/pull/2610
