### ISSUE TITLE
Toolbars gone every time I start OOM

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#1647]
### Steps to reproduce
1. Select all toolbars via the View | Toolbars menu.
2. Close OOM.
3. Open OOM and open a map.
4. Observe that all toolbars are deselected again.

### Actual behaviour
All Toolbars except the Advanced Editing toolbar are gone every time I restart OOM.

### Expected behaviour
The toolbars selected the previous time should be visible when OOM is restarted.

### Configuration
Mapper Version: 0.9.3.
Operating System: Window10 10 x64

**Comment by Symbian9** [comment]
> ### Expected behaviour
>
> The toolbars selected the previous time should be visible when OOM is restarted.

As addition, think, there should be options to "store actual" & "restore to default" UI layout.

**Comment by jan-gerard** [comment]
This is what I have as options "General"
![image](https://user-images.githubusercontent.com/7569832/83263956-b1adbc00-a1bf-11ea-9387-e8eb18a7d9bb.png)
and "Editor"
![image](https://user-images.githubusercontent.com/7569832/83264070-dc981000-a1bf-11ea-99c1-2a27059990ca.png)
but I cannot find where to (re)store the UI.

**Comment by Symbian9** [comment]
> but I cannot find where to (re)store the UI.

To be clear: this is "feature request" in my comment above.

**Comment by dg0yt** [comment]
@jan-gerard For now, delete all OpenOrienteering.org/Mapper settings in the WIndows registry.
The settings path is `HKEY_CURRENT_USER\Software\OpenOrienteering.org\Mapper`.
You may do that either in `regedit`, or at a Command Prompt using
~~~
reg delete HKEY_CURRENT_USER\Software\OpenOrienteering.org\Mapper
~~~

**Comment by jan-gerard** [comment]
Solved! Thanks. I thought it was a bug, but this probably happened since I upgraded from an older version.

**Comment by dg0yt** [comment]
It is a bug, but is extremely rare, is not yet possible to reproduce it, and probably the cause is located in a 3rd-party component. In the past we even had crashes, but I was able to prevent this (https://github.com/OpenOrienteering/mapper/issues/1366). Now, if I add a button to reset UI, I can't verify that it helps in this particular situation.

**Comment by Symbian9** [comment]
I also has such issue. As I understand something going wrong with `[OpenOrienteering%3A%3AMapEditorController]` value in `Mapper.conf`

Here is "default" (clean install) value:

```
[OpenOrienteering%3A%3AMapEditorController]
state="@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\xfc\x2\0\0\0\x1\xfb\0\0\0\"\0\x43\0o\0l\0o\0r\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xad\0\xff\xff\xff\0\0\0\x1\0\0\0\xbc\0\0\x2l\xfc\x2\0\0\0\x3\xfb\0\0\0$\0S\0y\0m\0\x62\0o\0l\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\x1\0\0\0j\0\0\x2l\0\0\0m\0\xff\xff\xff\xfb\0\0\0*\0T\0\x65\0m\0p\0l\0\x61\0t\0\x65\0s\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xb6\0\xff\xff\xff\xfb\0\0\0,\0T\0\x61\0g\0 \0\x65\0\x64\0i\0t\0o\0r\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\x9b\0\xff\xff\xff\0\0\x4>\0\0\x2l\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x3\0\0\0\x1e\0G\0\x65\0n\0\x65\0r\0\x61\0l\0 \0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x18\0V\0i\0\x65\0w\0 \0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x1g\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\"\0M\0\x61\0p\0 \0p\0\x61\0r\0t\0s\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x3\0\0\0\x1e\0\x44\0r\0\x61\0w\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1e\0\x45\0\x64\0i\0t\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x1\x94\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x30\0\x41\0\x64\0v\0\x61\0n\0\x63\0\x65\0\x64\0 \0\x65\0\x64\0i\0t\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\x3\x89\xff\xff\xff\xff\0\0\0\0\0\0\0\0)"
```

Here is "no toolbars value" (affected after toggling some toolbars, can't remember all steps to reproduce):

```
[OpenOrienteering%3A%3AMapEditorController]
state="@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\xfc\x2\0\0\0\x1\xfb\0\0\0\"\0\x43\0o\0l\0o\0r\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\xad\0\xff\xff\xff\0\0\0\x1\0\0\x1Y\0\0\x2\xbc\xfc\x2\0\0\0\x3\xfc\0\0\0\x1a\0\0\x2\xbc\0\0\0m\0\xff\xff\xff\xfa\0\0\0\x1\x1\0\0\0\x2\xfb\0\0\0&\0M\0\x65\0\x61\0s\0u\0r\0\x65\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\xfb\0\0\0$\0S\0y\0m\0\x62\0o\0l\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\x1\0\0\x3\xb3\0\0\x1M\0\0\0R\0\xff\xff\xff\xfb\0\0\0*\0T\0\x65\0m\0p\0l\0\x61\0t\0\x65\0s\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\x2\x1b\0\0\0\xbb\0\0\0\xb6\0\xff\xff\xff\xfb\0\0\0,\0T\0\x61\0g\0 \0\x65\0\x64\0i\0t\0o\0r\0 \0\x64\0o\0\x63\0k\0 \0w\0i\0\x64\0g\0\x65\0t\0\0\0\x1(\0\0\x1\xaf\0\0\0\x9b\0\xff\xff\xff\0\0\x3\xa1\0\0\x2\xbc\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x3\0\0\0\x1e\0G\0\x65\0n\0\x65\0r\0\x61\0l\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x18\0V\0i\0\x65\0w\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\"\0M\0\x61\0p\0 \0p\0\x61\0r\0t\0s\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x3\0\0\0\x1e\0\x44\0r\0\x61\0w\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1e\0\x45\0\x64\0i\0t\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x30\0\x41\0\x64\0v\0\x61\0n\0\x63\0\x65\0\x64\0 \0\x65\0\x64\0i\0t\0i\0n\0g\0 \0t\0o\0o\0l\0\x62\0\x61\0r\0\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)"
```

I saved both configs if you need it.

**Comment by dg0yt** [comment]
> I also has such issue. As I understand something going wrong with `[OpenOrienteering%3A%3AMapEditorController]` value in `Mapper.conf`

Basically yes. However, on Windows, the registry is used instead of a file. And the data comes from and goes to Qt.

Which version of Qt do these values refer to?

**Comment by Symbian9** [comment]
> Which version of Qt do these values refer to?

I use Mapper under Debian 10

> ### About Qt — OpenOrienteering Mapper 0.9.3
>
> This program uses Qt version 5.11.3.

**Comment by dg0yt** [comment]
Okay, I can reproduce the issue with the given data.
