### ISSUE TITLE
Crash when opening .ocd with templates

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1656]
### Steps to reproduce
1. save .omap as .ocd (V12), some warnings appear ("Unable to export template: file type of "Luftbild_Stitch1.png" is not supported yet")
2. open that .ocd file

### Actual behaviour
Mapper crashes (this happens only with v20200612.4, not with 0.93)
"Unable to export template: file type of "Luftbild_Stitch1.png" is not supported yet" messages only show up in v20200612.4, not in 0.93.

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: v20200612.4
Operating System: Win7x64

**Comment by dl3sdo** [comment]
I think it is caused by trying to open a .jpg template.

**Comment by dg0yt** [comment]
You hit two bugs, the minor one hiding the major one from the automated tests:
- Handling of PNG templates was lost in a change to OCD export.
- Switching to smart-pointers for handling Template object lifecycles unintentionally left a now-obsolete `delete` statement in the generic map loading code.
