### ISSUE TITLE
Unsaved changes are ignored after loading a template

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1672]
### Steps to reproduce
1. start a new map by selecting a symbol set
2. open a template
3. start drawing
4. close the map (or Mapper)

### Actual behaviour
The map (or Mapper) is being closed without asking.
Note: if step 2 (opening a template) is skipped Mapper asks before closing

I know that template handling has been changed a lot since v20200613.1, thus this issue
may be obsolete.

### Configuration
Mapper Version: v20200613.1
Operating System: Win7x64

**Comment by dg0yt** [comment]
Fixed June 27: https://github.com/OpenOrienteering/mapper/commit/36c3877a9c4c482f9137306feb9cdf52d9defdf4
