### ISSUE TITLE
Mapper loses gaps in borders imported from OCAD

### ISSUE THREAD

**Issue by PeteSNelson** [OpenOrienteering/mapper#1679]
### Steps to reproduce
1. Create feature with border in OCAD 9 or 11
2. Cut border line in OCAD.  Save.
3. Open file in OOM 0.9.3

### Actual behaviour
Gaps made in OCAD do not appear in OOM.
This is stopping us transferring .OCD maps, epsecially urban, to OOM

### Expected behaviour
OOM should reproduce the appearance in OCAD.
Further, OOM should allow cutting of borders (eg black line along road)

### Configuration
Mapper Version: 0.9.3
Operating System: Windows 10
![cut borders](https://user-images.githubusercontent.com/57093406/87430399-150f7400-c5dd-11ea-8c2a-2945c644f19b.png)

**Comment by dg0yt** [comment]
https://github.com/OpenOrienteering/mapper/issues/150
