### ISSUE TITLE
error: aggregate ‘QPainterPath outside_path’ has incomplete type and cannot be defined

### ISSUE THREAD

**Issue by liborw** [OpenOrienteering/mapper#1687]
### Steps to reproduce
1. Building from source on ArchLinux using aur package (https://aur.archlinux.org/packages/openorienteering-mapper/#news)

### Actual behaviour
It failed to build with the following error:
```
/home/wagnelib/.cache/yay/openorienteering-mapper/src/mapper-0.9.3/src/gui/print_tool.cpp: In member function ‘virtual void OpenOrienteering::PrintTool::draw(QPainter*, OpenOrienteering::MapWidget*)’:
/home/wagnelib/.cache/yay/openorienteering-mapper/src/mapper-0.9.3/src/gui/print_tool.cpp:144:15: error: aggregate ‘QPainterPath outside_path’ has incomplete type and cannot be defined
  144 |  QPainterPath outside_path;
      |               ^~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/Mapper_Common.dir/build.make:976: src/CMakeFiles/Mapper_Common.dir/gui/print_tool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3176: src/CMakeFiles/Mapper_Common.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

### Expected behaviour
It should build without errors.

### Configuration
Mapper Version: 0.9.3 and also master branch on git
Operating System: ArchLinux

**Comment by lpechacek** [comment]
Thanks for the report, Libor. The bug was induced by a change in Qt and there is a fix in Mapper. Either apply https://github.com/OpenOrienteering/mapper/commit/af650a5300d79077568fe239ec2c6df0c067fe27 to your copy of v0.9.3 or check out the latest code from the repository.

**Comment by sikmir** [comment]
@liborw there is the latest [openorienteering-mapper-git](https://aur.archlinux.org/packages/openorienteering-mapper-git/) available as well. Use it for now. I'll add the patch to openorienteering-mapper package a bit later.
