### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by Tiekku** [OpenOrienteering/mapper#1689]
### Steps to reproduce
1. File saved in mobile mapper, OK I think.  Open File with desktop application
2. Open File with desktop application --> error message Cannot open file
/Users/jukka/Documents/kartat/Rukavaara/kartoitus/Rukavaara-kartoitus-2020-07-18.omap:
Error at line 80840 column 10502: Premature end of document.
3. I can still open it with mobile application and work with it

### Actual behaviour
Cannot open file
(path sensured)...Rukavaara-kartoitus-2020-07-18.omap:
Error at line 80840 column 10502: Premature end of document.

### Configuration
Mapper Version: 0.92 & 0.93
Operating System: Android in mobile mapper and MAC OS 10.14.6  in desktop

**Comment by Tiekku** [comment]
Problem was in android file trasfer application.

**Comment by dg0yt** [comment]
This used to be a more frequent issue: Android is not immediately updating cached meta data which is used by Android's Media Transfer Protocol (MTP) implementation to determine file size. Then the file transfer to the PC is incomplete.

We mostly eliminated the issue by explicitly triggering running the media scanner whenever updating the file. But I suppose the media scanner process is running asynchronously, so you may still get into trouble if going to fast.

**Comment by dg0yt** [comment]
(In the past, users restarted the phone to workaround this issue.)

**Comment by jmacura** [comment]
Sounds very similar to #1115 .
