### ISSUE TITLE
Crashing when canceling template adjusting by x-button

### ISSUE THREAD

**Issue by Tiekku** [OpenOrienteering/mapper#1690]
### Steps to reproduce
1. Open template for adjusting
2. Press new button to set template position for adjusting and press the point
3. Now, cancel adjusting by press x-button on upperleft corner of dialog without set the map point

### Actual behaviour
Application crashing

### Configuration
Mapper Version: 0.9.2 and 0.9.3
Operating System: Mac OS, Mojave 10.14.6

**Comment by dg0yt** [comment]
> Mapper Version: newest

Could you be more explicit, please? The version is in the "About OpenOrienteering Mapper" dialog.

**Comment by Tiekku** [comment]
The Android version(s):
- At first I used version 0.9.2
- And same thing with the version 0.9.3

**Comment by dg0yt** [comment]
>The Android version(s):

On Android, we don't have the template adjustment feature. Your initial report is:

> Operating System: Mac OS, Mojave 10.14.6

**Comment by Tiekku** [comment]
Of course!  There is not also Adjustment feature!  Sorry, I mentioned all the time DeskTop SW which run on MAC OS.

**Comment by dg0yt** [comment]
I can trigger the crash on macOS, but not Linux or Windows.
