### ISSUE TITLE
Outer width in point symbol does not form a perfect circle

### ISSUE THREAD

**Issue by tobbywilson** [OpenOrienteering/mapper#1693]
### Steps to reproduce
Create point symbol with a high ratio between outer and inner radii at midpoint (e.g. 4:1, as in image below)

### Actual behaviour
The shape formed by the outer radius is not a perfect circle on wither the inside or the outside.
<img src="https://user-images.githubusercontent.com/2275540/89375963-2c500600-d732-11ea-947d-d5c4e3969c8e.png" alt="point symbol with gaps between outer and inner colours" width="300"/>
The grey area is a point symbol with the same total radius as the black symbol.

### Expected behaviour
The outer radius should form a perfect circle.

### Configuration
Mapper Version: master v20200613.1 and 0.9.3
Operating System: Windows 10

**Comment by dg0yt** [comment]
A known limitation, #51.

**Comment by dg0yt** [comment]
Note that this does not necessarily affect printing, at least not PDF export in vector mode.
