### ISSUE TITLE
Create georeferenced map at 1:1000 scale

### ISSUE THREAD

**Issue by pedalwood** [OpenOrienteering/mapper#1695]
### Steps to reproduce
1. Create new map at scale 1:1000 (for a school campus map)
2. Import a georeferenced template file (jpg, tif, geotif...)

### Actual behaviour
The template file imports at a location that is a long way from the reference point. The declination is also wrong.
Any attempt to draw on the map creates a line from the reference point to where the map is located.
Importing the same template at a scale of 1:10000 works properly.

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: 0.9.3
Operating System: Windows 10

**Comment by dg0yt** [comment]
Works for me.

Please provide more details which help to find out the real problem. Test files, georeferencing screen shot, etc.

**Comment by pedalwood** [comment]
Attached files are –

*	Blank map file, before loading the template
*	Georeferenced TIF files
*	Screen shots during process of loading the template
*	Map file after loading template.

At this point, on any attempt to draw on the map file, the line disappears as you draw it.

 

Peter Dalwood

Dandenong Ranges Orienteering Club

**Comment by dg0yt** [comment]
I guess e-mail attachments are not passed through. Either attach to the issue on the public Github website, or send a personal e-mail.

**Comment by pedalwood** [comment]
[Wombat OMAP.zip](https://github.com/OpenOrienteering/mapper/files/5039894/Wombat.OMAP.zip)

**Comment by pedalwood** [comment]
I’ve uploaded a zip file to the issue comments

**Comment by dg0yt** [comment]
The map is georeferenced as UTM (Zone 55, southern hemisphere), reference point at (UTM E/N): 
373232.00 5800841.00

The TIFF's world file says the center of the top left pixel is at (X/Y): 
2540231.45683785 2397082.1250772
(cf. text editor)

If this is the same region then the world file does not use UTM. The TIFF is not a GeoTIFF, so we don't know the actual CRS.

**Comment by dg0yt** [comment]
Maybe we should issue a warning when users try to add templates more than 10 km away  from the reference point?

**Comment by pedalwood** [comment]
Kai,

 

Thank you for your investigative work. I think the problem is in the code behind site from which I obtained the georeferenced data, which is here: https://mapshare.vic.gov.au/MapShareVic/index.html?viewer=MapShareVic.PublicSite <https://mapshare.vic.gov.au/MapShareVic/index.html?viewer=MapShareVic.PublicSite&locale=en-AU> &locale=en-AU

 

I’ve had similar issues in the past, where it sometimes generates georeferenced data with a reference point that is a very long way from the actual map. I’m not sure how to force it to use a more local origin. I’ll follow up with the government department that is responsible for the website.

 

Regards,

Peter

**Comment by dg0yt** [comment]
Perhaps you should just choose GeoTIFF export then? A test export reveals "GDA_1994_VICGRID94".

For this example, the area of interest is still quite far away from the map reference point. 
When you create a new map, you can immediately add a georeferenced template: Mapper will present the map georeferencing dialog, initializing geographic coordinates from the template. You may still choose to use UTM for the map.

**Comment by pedalwood** [comment]
I've done just as you suggest. The catch is I want to save the map to Ocad9, which cannot open a tif template. But I've solved that problem by overlaying a jpg copy of the base map and then discarding the tif.

Regards,
Peter Dalwood
________________________________

**Comment by dg0yt** [comment]
I see. Looks like older version of OCAD were picky about TIFF features:
http://www.attackpoint.org/discussionthread.jsp/message_1339220

I'm closing this issue now. Don't hesitate to report new issues. Thanks!
