### ISSUE TITLE
Crash when trying to continue a line

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1708]
### Steps to reproduce
1. Create a map with two parts.
2. Create a line object in the first part.
3. Switch parts.
4. Try to continue the original object with the draw path tool's snap function. Make sure the end vertex of othe first object is highlighted with the cross sign.

### Actual behaviour
Kaboom:
```
1   raise                                                                                                                                                             0x7ffff426c4b1 
2   abort                                                                                                                                                             0x7ffff4255539 
3   QMessageLogger::fatal(const char *, ...) const                                                                                                                    0x7ffff513bc27 
4   qt_assert(const char *, const char *, int)                                                                                                                        0x7ffff513b074 
5   OpenOrienteering::MapPart::findObjectIndex                                                                                       map_part.cpp                136  0x5f9386       
6   OpenOrienteering::DrawLineAndAreaTool::finishDrawing                                                                             draw_line_and_area_tool.cpp 269  0xf910db       
7   OpenOrienteering::DrawPathTool::finishDrawing                                                                                    draw_path_tool.cpp          893  0xfe0b2c       
8   OpenOrienteering::DrawPathTool::mousePressEvent                                                                                  draw_path_tool.cpp          135  0xfbf724       
9   OpenOrienteering::MapWidget::_mousePressEvent                                                                                    map_widget.cpp              1014 0xbb1abc       
10  OpenOrienteering::MapWidget::mousePressEvent                                                                                     map_widget.cpp              1003 0xbb0e53       
11  QWidget::event(QEvent *)                                                                                                                                          0x7ffff7ae40de 
12  OpenOrienteering::MapWidget::event                                                                                               map_widget.cpp              803  0xba70af       
... <Qt event loop>
```

### Expected behaviour
The progran should not crash for sure. However, what would be the correct behavior I'm not sure.
Options:
1) Don't allow snapping to object end vertices that reside in a different part.
2) Keep the snapping behavior as is (the cross mark) but do not merge the objects.
3) Bring the object from the other part into the current one.

For the record, I'm using parts as map "layers" - the drawing and contour lines. It helps with object selection during edits.

### Configuration
Mapper Version: master-v20200613.1-134-g70359b027045
Operating System: openSUSE Tumbleweed

**Comment by dl3sdo** [comment]
I can reproduce the crash only in a slightly different scenario:
After drawing the 2nd line on the other map part Mapper crashes when I press 'Undo'.
OS: Win7x64, master-v20200613.1

**Comment by dg0yt** [comment]
@dl3sdo In release builds, assertions are disabled. In development builds, they are meant to fire early.

@lpechacek I think only the first option is consistent with general map parts / snapping behaviour in Mapper, i.e. 
> Don't allow snapping to object end vertices that reside in a different part.
