### ISSUE TITLE
Import of shapefiles

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#171]
**Somebody reported on Sourceforge [[tickets:#171](https://sourceforge.net/p/oorienteering/tickets/171)]:**

It would be Nice if it was possible to import shapefiles, and to Cut them.

**Comment by dg0yt** [comment]
The unstable snapshots have GDAL/OGR now.

To import a .shp file without accompanying .shx, add parameter SHAPE_RESTORE_SHX with value YES to the GDAL configuration in Mapper's settings.

**Comment by Zerbembasqwibo** [comment]
OpenOrienteering Mapper unstable 0.6.20160802
I can import shp but scale is totally messed up. There is also shx-file in same folder. I import, can't see if objects are imported. The symbol is however imported.

Imported dxf on map where in know it should fit. See almost nohing. Scale is very strange. 

Maybe I don't do correct with the coordinate system, but I made what I think i s correct with the OOmap: UTM 33N and the coordinates on map origo.

**Comment by dg0yt** [comment]
I will not be able to reproduce this problem with that information.

**Comment by Zerbembasqwibo** [comment]
I have prepared a "basemap" in another map tool, converted it to "Basemap.omap". Import Leder.DXF (it's open material from the Swedish Land Survey). 

Expected: It should end up on the violet lines as they are the same lines. 
Happens: I (think I) end up in one corner of the DXF-file. (That file is 1000 of km big or so...)

Improvement: import only those part of the DXF that are covered by the map you import it to.

[Basemap_Leder.zip](https://github.com/OpenOrienteering/mapper/files/407610/Basemap_Leder.zip)
