### ISSUE TITLE
polyclipping dependency missing in rpm .spec file

### ISSUE THREAD

**Issue by enpontus** [OpenOrienteering/mapper#1715]
### Steps to reproduce
1.trying to rebuild openorienteering-mapper on fedora 32 after installing all dependencies
2.get error about missing polyclipping library 
3.

### Actual behaviour
compilation stopped

### Expected behaviour
the spec file should (likely) declare polyclipping-devel a dependency

### Configuration
Mapper Version: 0.93
Operating System: fedora 32 (x86_64)

notably the compilation stops a bit later due to missing key but that i guess is a completely different issue....

**Comment by dg0yt** [comment]
Please be more specific about the error, and what you tried to do.

---

Our spec file on build.opensuse.org includes:

~~~
%if 0%{?fedora_version}
BuildRequires:  polyclipping-devel
...
%endif
~~~

And even the "rawhide" build finds the lib:

~~~
-- Found Polyclipping: /usr/include/polyclipping (found version "6.4.2") 
~~~

This build (rawhide, in contrast to fedora 31) fails due to some other changes in that distro.

~~~
-- Build files have been written to: /home/abuild/rpmbuild/BUILD/openorienteering-mapper-0.9.3/x86_64-redhat-linux-gnu
+ make -j16
make: *** No targets specified and no makefile found.  Stop.
~~~

If you want to build RPMs outside of OBS, you probably better start with a more specifc SRPM instead of the generic spec file. Apart from the OBS macros, there are also package name substitutions etc. being applied during an OBS build.

**Comment by enpontus** [comment]
with openorienteering-mapper-0.9.3-29.16.src.rpm - i get this without polyclipping & polyclipping-devel installed

rpmbuild --rebuild Downloads/openorienteering-mapper-0.9.3-29.16.src.rpm 

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Polyclipping (missing: POLYCLIPPING_INCLUDE_DIR
  POLYCLIPPING_LIBRARY) (Required is at least version "6.1.3")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPolyclipping.cmake:117 (find_package_handle_standard_args)
  CMakeLists.txt:182 (find_package)

whereas the build continues a bit longer with them installed ending with this:
-- Configuring incomplete, errors occurred!
See also "/home/pontus/rpmbuild/BUILD/openorienteering-mapper-0.9.3/CMakeFiles/CMakeOutput.log".
error: Bad exit status from /var/tmp/rpm-tmp.u6pbeB (%build)


RPM build errors:
    Downloads/openorienteering-mapper-0.9.3-29.16.src.rpm: Header V3 RSA/SHA256 Signature, key ID 7ce0ae6a: NOKEY
    Bad exit status from /var/tmp/rpm-tmp.u6pbeB (%build)

**Comment by enpontus** [comment]
may i add that i am not very good at building packages so pardon any mistakes from my side looking through the logs - with them installed it complains on 

-- The following OPTIONAL packages have not been found:
 * IWYU (required version >= 0.12)
and before that a lot of missing license files.

**Comment by dg0yt** [comment]
Don't expect me to be an RPM expert. I guess "without polyclipping & polyclipping-devel installed", you must run into an error. There are command for dealing with the build dependencies for local SRPM packages.

But maybe you don't want to build yourself, but just use another download from our OBS service?

**Comment by enpontus** [comment]
i am sorry but "OBS sevice" ?  (i most likely have missed something substantial.
i cannot get F31 nor Rawhide version to install from here https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper
theres no F32 version/repo that i can find, and no flatpacks nor binary tarballs that i can find anywhere else.

**Comment by dg0yt** [comment]
What you see at software.opensuse.org is what is built on build.opensuse.org, the major installation of OBS. My home project is: https://build.opensuse.org/project/show/home:dg0yt 

Anyway, now that (I learned that) Fedora 32 is available, I just enabled that repository. The build succeeded without error, no missing dependencies. The RPM is ready for download.

**Comment by enpontus** [comment]
Thanks a lot!

**Comment by enpontus** [comment]
t seems that the openorienteering-mapper is built against an earlier
version of the the qtlibrary (5.13.2) than is the current (and updated)
version in F32(5.14.2)  causing a quite a few conflicts - can this be
remedied ?

brg Pontus

**Comment by dg0yt** [comment]
I added an "update" repository on top of the standard f32 repository now, and triggered a rebuild. This seems to pull in Qt 5.14 instead of 5.13. There is still a delay in publishing the build result, which is:
openorienteering-mapper-0.9.3-29.3.x86_64.rpm

**Comment by enpontus** [comment]
and again - a big thank you for the efforts - ill install & tester later
when available!

brg Pontus

**Comment by enpontus** [comment]
Hello Kai

fedora 33 was apparently released today - will you add that to the builds
as well  ?

best regards Pontus

ps - thanks for the good work - it has worked fine for me after you got the
repos to work the last time!

**Comment by dg0yt** [comment]
> fedora 33 was apparently released today - will you add that to the builds as well ?

Thanks for the hint. I managed to add this configuration, too.

**Comment by enpontus** [comment]
Thanks a lot i might be updating by the weekend then

have a nice day!
brg Pontus
