### ISSUE TITLE
Template not visible in Android

### ISSUE THREAD

**Issue by samlaminilepre** [OpenOrienteering/mapper#1730]
### Steps to reproduce
1.Open a raster template (exported from qgis) with is world file
2.Everything is ok
3.Close mapper
4.Reopen the saved file or open it on a different device (where you have copied all templates as usual)
5. (it doesn't happen all the time but i was not able to find a pattern for when it happens)

### Actual behaviour
Template is not shown. In the templates list the file is there, with or without check nothing happen, no warning what so ever, template name NOT in red. Other templates are ok.
If you try to reenter the georeferencing data nothing happen.
If you delete the template and you reopen the same file it work, but just until you close mapper.

### Expected behaviour
Template should be shown
### Configuration
Mapper Version: 0.9.3
Operating System: windows 10

**Comment by dg0yt** [comment]
This must be made reproducible, at least with two particular devices on your side.

**Comment by dg0yt** [comment]
Without more information, this cannot be handled. Please reopen when you have more information.
