### ISSUE TITLE
TemplateTest::ogrTemplateTest is flaky

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#1752]
### Steps to reproduce
Run `template_t`.

### Actual behaviour
`TemplateTest::ogrTemplateTest` *sometimes* fails with:

~~~
FAIL!  : TemplateTest::ogrTemplateTest(TemplateTrack georef) Compared strings are not the same
   Actual   (temp->getTemplateType()): TemplateTrack
   Expected ("OgrTemplate")          : OgrTemplate
   Loc: [/<<PKGBUILDDIR>>/test/template_t.cpp(339)]
FAIL!  : TemplateTest::ogrTemplateTest(TemplateTrack non-georef) Compared strings are not the same
   Actual   (temp->getTemplateType()): TemplateTrack
   Expected ("OgrTemplate")          : OgrTemplate
   Loc: [/<<PKGBUILDDIR>>/test/template_t.cpp(339)]
FAIL!  : TemplateTest::ogrTemplateTest(TemplateTrack OGR georef) Compared strings are not the same
   Actual   (temp->getTemplateType()): TemplateTrack
   Expected ("OgrTemplate")          : OgrTemplate
   Loc: [/<<PKGBUILDDIR>>/test/template_t.cpp(339)]
FAIL!  : TemplateTest::ogrTemplateTest(TemplateTrack OGR non-georef) Compared strings are not the same
   Actual   (temp->getTemplateType()): TemplateTrack
   Expected ("OgrTemplate")          : OgrTemplate
   Loc: [/<<PKGBUILDDIR>>/test/template_t.cpp(339)]
~~~

This happened in five differents builds of v0.9.4 for Ubuntu: 
https://launchpad.net/~ginggs/+archive/ubuntu/testing/+packages > openorienteering-mapper (0.9.4-1~ppa1) groovy

One single FAIL was observed locally during debugging (v0.9.4, GDAL and PROJ from v0.9.4 superbuild config, Qt 5.15.1, Linux)

### Expected behaviour

In all cases, ogrTemplate shoud find the expected template type.

### Configuration
Mapper Version: 0.9.4
Operating System: Linux

**Comment by pkturner** [comment]
For what it's worth, with a local post-0.9.4 build, I ran `template_t` 10 times with 100% passes.   
master branch with commit dde0c70b2cd1e6db84ab6f2f38061f139bcab921     
Gentoo Linux, gdal-3.0.4, proj-7.0.1, qt-5.14.2

**Comment by pkturner** [comment]
I guess the problem is that `QCOMPARE(temp->getTemplateType(), "OgrTemplate");` is comparing pointers (`const char *`) when it needs to compare the strings.

**Comment by dg0yt** [comment]
I think I just found the trigger in Ubuntu's build environment:

~~~
HOME=/sbuild-nonexistent
~~~

When I run the test locally with `HOME` set to a non-existent directory, the test fails here, too.
However, I don't know the mechanism. Maybe `QSettings` doesn't work if it can't write to a file.

**Comment by ginggs** [comment]
Yes, this is it, thank you.  I added the following in **debian/rules** and the test passes.
```
export HOME=$(CURDIR)/tmphome
```
