### ISSUE TITLE
Reset map extent to actual extent (on saving or OCAD export)

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1784]
### Steps to reproduce
1. Working on a map in EPSG 2056 
2. Import an older map part only available in paper coordinates
3. The imported part is placed around the Zero of the reference system about 1500km apart from the rest of the map
4. Cut the imported map part -> Zoom to map extent (Jumps to the actual map) ->Paste and place manually
5. Save as .ocd
6. Open in OCAD

### Actual behaviour
7. OCAD alerts, that the map size is more than 4mx4m (a restriction under certain licences e.g. OCAD Orienteering) and then centers somewhere in between the two map parts and thus is empty. Even though the "Zoom to map extent" in Mapper works fine and jumps to the actual map only after cutting out the misplaced parts, the map extent saved is not adjusted but remains on "Megamap". 

### Expected behaviour
7.  Map extent should be adjusted to the extent the actual map features.

### Configuration
Mapper Version: 0.9.4
Operating System: Windows 7

**Comment by lpechacek** [comment]
Thanks for the report, Martin. Would you mind sharing a sample map exhibiting this behavior for a faster analysis on our side, please?

**Comment by krticka** [comment]
See also #956

**Comment by mlerjen** [comment]
[Samples issue #1784.zip](https://github.com/OpenOrienteering/mapper/files/5601827/Samples.issue.1784.zip)
There is the Mapper file I save as OCAD and the resulting  OCAD file.
Also here the two OCAD dialogs. 
![image](https://user-images.githubusercontent.com/15611653/100333082-75beac80-2fd2-11eb-9d41-bb4472bfe4e7.png)
![image](https://user-images.githubusercontent.com/15611653/100333185-925ae480-2fd2-11eb-9cd4-6448814e2eea.png)

**Comment by lpechacek** [comment]
> [Samples issue #1784.zip](https://github.com/OpenOrienteering/mapper/files/5601827/Samples.issue.1784.zip)
> There is the Mapper file I save as OCAD and the resulting OCAD file.

I've opened the sample map and I can see three objects there. Some outline at -6,873.77 -29,390.36 (mm), small marsh and a rocky pit at -0.00 -0.00 (mm) and a tiny map cutout at 429.80 -211.16 (mm). I don't know how the sample was created but it does not look like a simple import unless the imported map already contained objects that are that far apart. The OCD map truthfully reflects the Mapper original.

It would help me to have files with which I can reproduce the procedure described in the initial comment.

**Comment by mlerjen** [comment]
Ouch. Painful.  
![image](https://user-images.githubusercontent.com/15611653/100371594-52aeef80-3008-11eb-9443-df8a66441c7e.png)
There was an line feature  in the imported map whichs symbol was set to "hidden". It though remained at the imported position close to the CRS origin while the visible features where cut & pasted & dragged to the actual position.  The "show whole map" function does though rather show the "whole visible map". That tricked me into this error report, which I hereby withdraw.

What is left, is the somehow odd placement of imports lacking a CRS as described in #956

I am sorry.

**Comment by dg0yt** [comment]
>  The "show whole map" function does though rather show the "whole visible map".

Yes, this is useful also with misplaced templates ;-)

We still need to solve #956 (thanks for reminder). But there is the alternative method of adding data as a template, adjust positioning, and then import and remove this template.

Mapper tries to actively move the map into the limited area 4x4 area when saving as OCD. But this won't help if the area is too large.
