### ISSUE TITLE
Scribble template saving not atomic

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#1785]
`TemplateImage::saveTemplateFile()` uses `QImage::save()`. This function may leave corrupted files when interrupted by Android. 
*Solution:* explicitly use `QSaveFile`.

> I experienced a peculiar crash with the above mentioned test build.
> 
>- All information in worked upon template _Draft @ 46...png_  got lost.
> - This png file got corrupt.
> - You could still see it in template list, however OOM could not open it.
> - This oom file was saved short time before the crash - vectors, gpx were all fine, the rest of the templates were fine as well
> -  This png was saved even before this mapping session, previous day.
> - The trigger was perhaps a multitouch  - I was receiving a phone call and clumsily handled the tablet (but could be also something else).
> - I later inspected this file and it was 0 kB, when opened in Notepad - no information inside

_Originally posted by @ollesmaps in https://github.com/OpenOrienteering/mapper/issues/945#issuecomment-735051950_

**Comment by ollesmaps** [comment]
One more thing maybe worth mentioning:
The crash was not total - OOM closed itself partly, the first window "Map choice, Settings" remained open.

**Comment by dg0yt** [comment]
> One more thing maybe worth mentioning:
> The crash was not total - OOM closed itself partly, the first window "Map choice, Settings" remained open.

Hm, it is just one activity, with different windows. If there is a crash, it is *total*. But if Android would restart the application (after a crash, or after forceful termination), you will see with the welcome screen again (if you did not change the setting for re-opening the most recently used file).

**Comment by dg0yt** [comment]
Once again, this is harder to fix than expected due to Qt shortcomings: https://bugreports.qt.io/browse/QTBUG-89022
