### ISSUE TITLE
Dxf city plans

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1799]
I have difficulty in drafting a city plan with Mapper (dxf). An improvement should come, I think most perceive the lines the same.

**Comment by Symbian9** [comment]
> An improvement should come, I think most perceive the lines the same

Can you provide more details & screenshots?

Also it would cool if you may attach sample of city plan as DXF file.

**Comment by dg0yt** [comment]
@AhmetPolat43 Is this what is presented in more details in #1800? If yes, please close this issue.

**Comment by AhmetPolat43** [comment]
Sorry ı missed
