### ISSUE TITLE
When DXF imports city plans, it directly converts all information from lines to undefined lines.

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1800]
When importing city plans, DXF directly converts all the information lines to undefined lines and I cannot separate the layers as I wish. In my plan, the building and canopy lines are different, but oom directly makes the same line. Instead of turning it into lines, if he conveys it as it is, if we turn it into lines
![Adsız](https://user-images.githubusercontent.com/62382116/102113830-91d3a200-3e4a-11eb-8a09-e721d411c115.jpg)
 or symbols, according to his definitions.

**Comment by Symbian9** [comment]
> DXF directly converts all the information lines to undefined lines and I cannot separate the layers as I wish.

May you provide this DXF file for testing?

Seems like for solve this task you just need create custom "CRT file" (instead of Mapper default/built-in CRT files):

- https://www.openorienteering.org/mapper-manual/pages/crt_files.html

You may also select various entities via "Find Object" feature:

- https://www.openorienteering.org/mapper-manual/pages/find_objects.html

**Comment by dg0yt** [comment]
> When importing city plans, DXF directly converts all the information lines to undefined lines and I cannot separate the layers as I wish.

We do the best what we can to use the style information and the properties which we get. Please select View > Tag editor, and check if the properties of the imported objects carry the information you are looking for. If yes, you can use these properties via Edit > Find..., and as in CRT files  during import. Symbian9 already posted the links to the documentation.

**Comment by AhmetPolat43** [comment]
I'll share more information about this dxf with you tomorrow. Because we want to draw our maps directly from Mapper without using any other alternative program

**Comment by AhmetPolat43** [comment]
I've also tried with different dxf files, but mapper converts my dxf defined lines to automatically undefined lines and doesn't tell me which line they are. In the other program for example, it tells me what line the line is, and I can turn that line into the line I want. I don't know if I could explain it exactly.
![1](https://user-images.githubusercontent.com/62382116/102182292-1101be00-3ebd-11eb-94ad-285bcbbfa015.jpg)
![2](https://user-images.githubusercontent.com/62382116/102182318-1a8b2600-3ebd-11eb-87a9-b79a6c4b6613.jpg)
![3](https://user-images.githubusercontent.com/62382116/102182329-1fe87080-3ebd-11eb-94ee-867093bf4027.jpg)
![4](https://user-images.githubusercontent.com/62382116/102182337-2545bb00-3ebd-11eb-84fb-981f7ffbbd3f.jpg)
![5](https://user-images.githubusercontent.com/62382116/102182351-2a0a6f00-3ebd-11eb-9c81-108152d0a53c.jpg)

**Comment by dg0yt** [comment]
Please do what I told:
> Please select View > Tag editor, and check if the properties of the imported objects carry the information you are looking for.

**Comment by AhmetPolat43** [comment]
I can't assign the dxf file from here, can you give me an e-mail address?

**Comment by AhmetPolat43** [comment]
![image](https://user-images.githubusercontent.com/62382116/102182805-ee23d980-3ebd-11eb-84b9-145a3406512a.png)

**Comment by dg0yt** [comment]
... you need to select an object in order to see object properties ...
![Unbenannt](https://user-images.githubusercontent.com/13567791/102183034-7cdc2a80-3ead-11eb-9250-091a77f51366.png)

**Comment by dg0yt** [comment]
> I can't assign the dxf file from here, can you give me an e-mail address?

Please look at my Github profile. Just click one of the dg0yt user name mentions.

**Comment by AhmetPolat43** [comment]
Yes, it is now, but I put two different objects that I need to separate on the same line and I cannot change them.
![image](https://user-images.githubusercontent.com/62382116/102183127-668a9a80-3ebe-11eb-81b4-1cbd984161af.png)
![image](https://user-images.githubusercontent.com/62382116/102183264-989bfc80-3ebe-11eb-9f13-3097de3f8596.png)

**Comment by AhmetPolat43** [comment]
> > I can't assign the dxf file from here, can you give me an e-mail address?
> 
> Please look at my Github profile. Just click one of the dg0yt user name mentions.

I sent it to your e-mail

**Comment by dg0yt** [comment]
Well, you could now use _Edit > Find objects_, enter something like `Layer = "B_MESKEN"`, let it select the objects, and assign symbols.

If you want to do this repeatedly, you can write the rules to a CRT file, like this (assuming ISSPROM):
~~~
# Example for GH-1800, ISSprOM 2019

# Building
521   Layer = "B_MESKEN"

# Canopy
522   Layer = "B_SUNDURMA"
~~~

If you now start with our ISSprOM 2019 symbol set, and import the data, you can load the CRT file during symbol assignment:
![1](https://user-images.githubusercontent.com/13567791/102184699-28867a00-3eb0-11eb-8719-4fe11a8bdfa2.png)

Then you will get much nicer map:
![2](https://user-images.githubusercontent.com/13567791/102184737-376d2c80-3eb0-11eb-9a88-c71571bffb41.png)

**Comment by AhmetPolat43** [comment]
Can you send me the crt file you made? I don't understand how to do it?

**Comment by AhmetPolat43** [comment]
> Can you send me the crt file you made? I don't understand how to do it?
Frankly I don't know how to edit the crt file

**Comment by dg0yt** [comment]
> > Can you send me the crt file you made? I don't understand how to do it?

Done.

> Frankly I don't know how to edit the crt file

https://www.openorienteering.org/mapper-manual/pages/crt_files.html, section "CRT file editing". Basically, just open it in a text editor.

**Comment by AhmetPolat43** [comment]
Thank you very much. We had to use a different program to prepare the base because of this problem. Now I learned and I will share it with others. Good work.

**Comment by AhmetPolat43** [comment]
Finally, I open a text file, but I cannot save it as a crt. When I save it as a text book, it does not open because the mapper is not CRT, I looked at the link you gave, but I did not.

**Comment by AhmetPolat43** [comment]
Do I need another program to edit

**Comment by AhmetPolat43** [comment]
I solved the problem, thank you very much.
