### ISSUE TITLE
I can't get that dxf fit

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1803]
Hello, I have a question again. I have a dxf file in my hand but it has no coordinates. I can't get that dxf fit on my coordinate satellite image.
![Adsız](https://user-images.githubusercontent.com/62382116/102363334-5fe74a80-3fc6-11eb-8fdf-7a3136ae984b.jpg)

**Comment by dg0yt** [comment]
There is no tool to fit your **- Map -** on your satellite image. These tools are meant to fit templates like TIFF images or DXF data on your map.

The DXF file is not in your list of templates. This means you do not currently use the DXF file as a template. I guess you opened like a regular (map) file, or you imported into a new map.

Try something like this:
1. Create a new, empty map with the desired scale and symbol set.
2. Add some properly georeferenced template. This will guide you into a step where you define the map's georeferencing. Change the coordinate reference systems (CRS) to your preferred local standard, or choose UTM, or just leave the default. 
  If you don't have any other properly georeferenced template, you may just export the desired region from www.openstreetmap.org, giving you a `map.osm` file.
3. Add more templates (images etc.) as you like.
4. Now add the DXF file as a template. It won't be georeferenced, so you can adjust its scaling and position with the buttons you already tried.
5. Once satisfied, you can turn the objects from the template into map objects by clicking the template's Edit button and selecting "Import and remove". This does similar things like File > Import..., however Mapper knows the desired positioning.

**Comment by dg0yt** [comment]
Converting this issue to a discussion, category "Question and answers"...
