### ISSUE TITLE
Area symbols not behaving properly when rotating map.

### ISSUE THREAD

**Issue by MartinHore** [OpenOrienteering/mapper#1812]
### Steps to reproduce
1. I have area symbols on my map such as 406.1, 408.1 (ISOM 2017) which show direction of easier running. Area setting "adjustable per object" is switched on and I've rotated the pattern to give the correct orientation as measured in the field.
2. I rotate the whole map (eg to switch alignment from Grid North (OSGB36) to magnetic north - just 2 degrees - , but larger rotations show the problem more obviously).
3. Area symbol patterns as above should rotate to remain correctly oriented.

### Actual behaviour
The above area symbol patterns fail to rotate and are no longer correctly oriented. (As opposed to point symbols such as 110 - elongated small knoll - with "always oriented to north" switched off which do rotate correctly).

### Expected behaviour
The area symbol patterns should rotate with the map when "adjustable per object" is switched on.

### Configuration
Mapper Version: 9.4
Operating System: Windows 10

Sorry. This seems so simple there must be an obvious solution, or it must have been reported before, but I can't find it. Many thanks. Martin

**Comment by dg0yt** [comment]
Confirmed with overprinting example. THis is a bug.

**Comment by MartinHore** [comment]
Thanks Kai. I'm glad I wasn't troubling you for no reason.

I've just found a temporary work around. Re-set the fill rotation angle in area settings to compensate for the map rotation. You have to do it for each affected symbol so it's a bit messy, but quicker than re-orienting every affected feature on the map.

Martin
