### ISSUE TITLE
Cannot change resolution for KMZ and PDF export

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1815]
### Steps to reproduce
1. export map as KMZ
2. try to change resolution

### Actual behaviour
While export as image offers for example 150, 300, 600 and 1200dpi as resolution, export as KMZ offers only
600dpi.

### Configuration
Mapper Version: v20201220.7 (x64)
Operating System: Win7x64

**Comment by dg0yt** [comment]
Bonus question: What about PDF export on Windows?

**Comment by dl3sdo** [comment]
Same behaviour for PDF export, only 600dpi is offered as possible resolution(s)

**Comment by dg0yt** [comment]
Okay, this is what I expected from looking at the source code.
