### ISSUE TITLE
fill pattern rotation not reset for cloned objects

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1828]
### Steps to reproduce
1. open forest sample.omap
2. edit the 409 symbol and make the fill rotation 'adjustable per object'
3. select one of the existing 409 objects and clone it
4. rotate the pattern in both the objects, the original and the cloned one
5. create a new pattern object and rotate its pattern as well
5. edit the 409 symbol and uncheck 'adjustable per object'

### Actual behaviour
The pattern rotation for the original object is reset to north as well as for the newly created one, while the pattern rotation for the cloned object stays the same.

### Configuration
Mapper Version: master v20201227.4
Operating System: Win7x64

**Comment by lpechacek** [comment]
Thanks, Matthias, for the report. I've tried the procedure on my Linux test system and all area objects (cloned/duplicated and new ones) changed the pattern orientation to north after the last step. I'll try on Windows next.

**Comment by dg0yt** [comment]
Hm, duplicating the object by Copy-and-Paste created a new symbol. That's why changing the property of the original symbol doesn't make a difference...

**Comment by dg0yt** [comment]
... and it doesn't happen for "Duplicate" tool. @dlsdo I found bugs in the bug report :smile:

**Comment by dl3sdo** [comment]
Actually I didn't use the Duplicate tool, as I was not aware of it. I used copy and paste, and only there it is reproducible.
I should have mentioned that 'cloning' didn't involve using the Duplicate tool.

**Comment by dg0yt** [comment]
The Duplicate tool is cheap (no clipboard involved). 
Copy-and-Paste means saving (exporting) the selected features into XML format, putting the result into the clipboard, and importing from clipboard again - with all difficulties related to import, such as identifying identical symbols and colors. Now the question is why the symbol is different now. The last release modified two related properties: fill pattern rotation and object tags.

**Comment by dl3sdo** [comment]
If you copy and paste an object where the pattern can be rotated and disable this symbol property afterwards, the pattern can still be rotated for exactly this 'copy&paste' symbol.

**Comment by dl3sdo** [comment]
1.) open forest sample.omap
2.) edit the 409 symbol and make the fill rotation 'adjustable per object'
3.) select one of the existing 409 objects and clone it via copy and paste
=> a new symbol is added to the symbol set

**Comment by dg0yt** [comment]
Reproducible also in v0.9.4.

**Comment by dg0yt** [comment]
`AreaSymbol::FillPattern::equal` compares the `name` which is a transient property, set and used by the symbol editor. Editing a symbol creates a name. Copy-and-paste doesn't carry it. Now `equal` claims that the symbols are different...
