### ISSUE TITLE
Cannot add scribble template

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1830]
Affects the pre-release build. v0.9.4 is fine.

### Steps to reproduce
1. Open a georeferenced map.
2. Tap-and-hold Paint on template button.
3. Select Add template.

### Actual behaviour
Mapper says that it cannot open the new scribble template.

### Expected behaviour
In v0.9.4 the template gets added and opened.

### Configuration
Mapper Version: master v20201227.4
Operating System: Android and openSUSE Tumbleweed

**Comment by dg0yt** [comment]
Confirmed.

**Comment by dg0yt** [comment]
Reproducible on the desktop.
