### ISSUE TITLE
Duplicate line symbol after editing properties, copy, paste

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1837]
Note: this is similar to #1828 
### Steps to reproduce
1. draw an object
2. edit symbol
3. copy and paste object

Some affected symbols/properties:
- 517: check 'Line is dashed' or change Line color or change Line width in Line settings
- ~402: change 'Minimum size' or 'Pattern interval' in Area settings~ (GH-1828)

It seems that a lot of properties in line and area symbols are subject to this behaviour.

### Actual behaviour
A new symbol is created

### Configuration
Mapper Version: master v20201227.4
Operating System: Win7x64

**Comment by dg0yt** [comment]
> It seems that a lot of properties in line and area symbols are subject to this behaviour.

This claim is too broad. 402 is an area symbol, so you just observe #1828 again. And the trigger for 1828 is not a particular property which you change: The trigger is the fact that you change a property in the symbol editor, before copy-and-paste. This explains why nobody noticed this before: a) The symbol editor isn't used so much. b) Without changes, nothing goes wrong. x) For serious work on symbol sets, you will do a copy of the symbol first, not copy-and-paste objects after changing the symbol.

For line symbols (517), the symbol editor creates named PointSymbol for start, mid, dash and end symbol. So it is probably the same bug pattern.
