### ISSUE TITLE
Object becomes invisible after color correction

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1842]
### Steps to reproduce 
1. Open attached minimal example [broken-colors.omap.zip](https://github.com/OpenOrienteering/mapper/files/5761983/broken-colors.omap.zip)
2. Open Color Window
3. Edit 'Yellow 50%'
4. In tab 'Professional printing' change spot color 'YELLOW' to '-none-'. Let Mapper calculate this color from custom CMYK.

### Actual behaviour
The object drawn by this color is invisible now.

### Expected behaviour
Mapper calculates such colors from custom settings in desired color scheme. All objects are visible.

### Configuration
Mapper Version: current master, 0.9.3
Operating System: Windows, Linux. Not reproduced on Android

Not reproduced with default symbol sets. Reproduced after export symbols from OCD file and in some other cases.

**Comment by krticka** [comment]
Color is not visible when color is defined in CMYK mode only and overprinting simulation is active (F4). Is this the case?

**Comment by dg0yt** [comment]
Overprinting simulation: Works as intended.

**Comment by yevhenmazur** [comment]
Well, it works in my minimal example, but not in my original map. 
![2021-01-03-222006_1366x768_scrot](https://user-images.githubusercontent.com/10380431/103488064-8274c280-4e12-11eb-96de-856127487001.png)
The Overprinting simulation switch is not available...

**Comment by yevhenmazur** [comment]
Just figured out. The workaround is:
1. Create at least one spot color
2. Turn on Overprinting emulation
3. Turn off Overprinting emulation
4. Remove spot color
