### ISSUE TITLE
I click on the paint on template tool to draw, but what could be the reason for such an error?

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1847]
I click on the paint on template tool to draw, but what could be the reason for such an error?
![WhatsApp Image 2021-01-16 at 19 09 33](https://user-images.githubusercontent.com/62382116/104816937-52c0b400-582f-11eb-83c4-0fcf21cb1296.jpeg)

### Configuration
Mapper Version:
Operating System:Android

**Comment by dg0yt** [comment]
Hm, could you also report the Mapper version (See "About OpenOrienteering Mapper")? I remember that I had such an issue in a manual test. But I don't think it is in v0.9.4.

**Comment by AhmetPolat43** [comment]
> Hm, could you also report the Mapper version (See "About OpenOrienteering Mapper")? I remember that I had such an issue in a manual test. But I don't think it is in v0.9.4.

OpenOrienteeringMapper master v20201220.7

**Comment by AhmetPolat43** [comment]
I'll try the main version then

**Comment by lpechacek** [comment]
Known problem in the pre-release version (#1830). Install v0.9.4 or wait for the next pre-release snapshot.
