### ISSUE TITLE
Enhancement request: Line continuation

### ISSUE THREAD

**Issue by Andreasox** [OpenOrienteering/mapper#1850]
New tool to continue line editing, i.e. add new coordinates to the selected end of a line

**Comment by krticka** [comment]
If I understand well, you want to make like longer to add some part. This is already working with holding SHIFT and starting drawing at the end of line.

**Comment by ollesmaps** [comment]
For Android this is a copy of issue Fluent drawing enhancement #988.

**Comment by Andreasox** [comment]
> If I understand well, you want to make like longer to add some part. This is already working with holding SHIFT and starting drawing at the end of line.

Thanks I had missed that. And #988 should cover the case in field with Android device.

**Comment by Andreasox** [comment]
Reading #988 more closely it does not fully cover this request. Therefor it is reopened as:
New tool for Touch UI to continue line editing, i.e. add new coordinates to the selected end of a line, mimicking the desktop functionality when pressing SHIFT and start drawing a new line

**Comment by dg0yt** [comment]
In a way, it is already possible. The "Shift" modifier key maps to the button labeled "Snap".

**Comment by lpechacek** [comment]
@Andreasox do you mean this functionality?

https://user-images.githubusercontent.com/5584406/105055159-154c6880-5a73-11eb-85f0-aece5ab03dd1.mp4

**Comment by Andreasox** [comment]
Yes, thanks.
