### ISSUE TITLE
CMake configure error "Unknown CMake command mapper_translations_sources"

### ISSUE THREAD

**Issue by mpickering** [OpenOrienteering/mapper#1866]
I am trying to build the project from source. To that end I cloned a fresh checkout and then ran

```
cmake .
```

which leads to the following CMake error. 

```
CMake Error at CMakeLists.txt:327 (mapper_translations_sources):
  Unknown CMake command "mapper_translations_sources".
```

I couldn't work out at all why this was happening, or the otherwise correct way to build the project.

**Comment by dg0yt** [comment]
Hm. Which version of CMake do you use? And please use a  separate build directory, really.

**Comment by mpickering** [comment]
Same thing happens with a separate build directory. 

```
[nix-shell:~/mapper]$ cmake --version
cmake version 3.18.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by mpickering** [comment]
I cleaned the source directory and then did a build from a separate build directory and it worked..

Sorry for the noise - hopefully this issue with help anyone else with this problem in future. 

Thank you for the quick response.

**Comment by dg0yt** [comment]
I'm glad you could resolve it. With CI builds on macOS, Windows and Linux, and more builds for various Linux distributions, it should really work out of the box.
Cf. https://github.com/OpenOrienteering/mapper/wiki/Target-systems#unstable-builds-v09 and https://github.com/OpenOrienteering/mapper/wiki/Continuous-Integration#ci-configurations for the current spectrum of configurations.
