### ISSUE TITLE
Point symbols with an outer ring are not rendered circular

### ISSUE THREAD

**Issue by tdobra** [OpenOrienteering/mapper#1878]
### Steps to reproduce
1. Draw a prominent large tree (417) in the ISSprOM 2019 symbol set.
2. For reference, draw a black dot inside with point symbol diameter a = 0.5 mm to match the inner diameter of 417. Also draw a purple dot with diameter a = 1.0 mm to match the outer diameter of 417.
3. Export this "map" as a high resolution PNG without simulating overprinting, or print to PDF, or just look at it on screen with exporting.

### Actual behaviour
The green ring is a bit square on both its inner and outer edges. You can see purple. The purple and black are perfectly circular, as expected. See attached image.

![MapperFault3](https://user-images.githubusercontent.com/37083402/108848493-f6dd0e00-75d8-11eb-87e8-bdf94376a35c.png)

### Expected behaviour
The green ring should be circular with its inner edge matching the black dot and its outer edge matching the purple dot. With overprinting disabled, you should not be able to see any purple.

### Further information
This also applies to symbols 418 and 526, so I believe it is an issue with point symbols with a nonzero outer width b.

Purple Pen reading an OMAP file renders these symbols correctly, so it is an issue with rendering in Mapper.

### Configuration
Mapper Version: 0.9.4
Operating System: Windows x64

**Comment by dl3sdo** [comment]
Issue seems to be a duplicate of #1693

**Comment by dg0yt** [comment]
And #1693 says: "A known limitation, #51."

**Comment by tdobra** [comment]
Sorry, I thought I had tried searching for all the sensible keywords, but obviously not.

**Comment by dg0yt** [comment]
Well, I removed wont-fix from 51, and will re-open 51 with a comment.
