### ISSUE TITLE
Vikazimut compatibility

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#1883]
_Originally posted by @Eric-P-Kmz in https://github.com/OpenOrienteering/mapper/issues/1793#issuecomment-782428545 :_
> Hi,
>
> I participate in the development of the free Vikazimut application. Is it possible to do a kmz export of the same format as that of OCAD in OOM (with a single image in the export)?
> We use the OCAD export format to georeference the maps to import into the app. The division into several images of the map is not compatible with our import.

- [x] Export KMZ with single raster image file
- [x] Export single course in IOF format

**Comment by dg0yt** [comment]
@eric-p-kmz Here is another ZIP file with a simple course in IOF Data Standard 3.0 format.
[course.zip](https://github.com/OpenOrienteering/mapper/files/6047683/course.zip)

**Comment by Eric-P-Kmz** [comment]
Hi,

We have continued to improve the link between OOM and Vikazimut for creating routes from OOM.
We've managed the differences between the IOF and OOM formats in the XML file, but the map scale is missing from your XML.
Is it possible to add this tag to the XML?
<RaceCourseData>
  <Map>
      <Scale>10000</Scale>
  </Map>
...
</RaceCourseData>

- Second request, would it be possible to create multiple races in one XML?

- If you can make it easier to create the definition table, it would remove a big drawback to creating courses under OOM.

**Comment by dl3sdo** [comment]
Hi @Eric-P-Kmz,
thank you for your ideas to improve XML export. I will analyze them and eventually create a PR.
Since this issue is closed I propose to continue discussion in a new issue, so please open a new one with your input above.
Thank you and Best Regards, Matthias
