### ISSUE TITLE
Only prints the overlay, not the background map

### ISSUE THREAD

**Issue by MEdelenbosch** [OpenOrienteering/mapper#1890]
### Steps to reproduce
1. Chose print
2. At print preview only the overlay of control points for the course is shown, and not the background map

### Actual behaviour
I would like to print a map made by the mapper on my macbook. I uploaded a template background map, and manually added control points. After adding all the control points, i wanted to print the map. 
When i pressed print, the example showed only the control points, but not the background map. 

### Expected behaviour
I expected that also the background map would be printable, with the overlay of control points as was shown in the interface. 
<img width="1383" alt="Interface with background map and overlay of checkpoints" src="https://user-images.githubusercontent.com/80007454/109873634-4e7d1880-7c6e-11eb-8c23-354bebf61b06.png">
<img width="791" alt="Printpreview" src="https://user-images.githubusercontent.com/80007454/109873648-550b9000-7c6e-11eb-97e8-8a33d8eaf05d.png">

### Configuration
Mapper Version: 0.9.4
Operating System: MAC OS Big Sur 11.2.1

**Comment by dg0yt** [comment]
Did you select the "Show templates" option?

**Comment by MEdelenbosch** [comment]
> Did you select the "Show templates" option?

Where should i select this option? After i select print? I don't see that option there.

**Comment by mlerjen** [comment]
![image](https://user-images.githubusercontent.com/15611653/109940473-66868380-7cd2-11eb-95cb-39044ded2f3b.png)

**Comment by dg0yt** [comment]
Similar on macOS, with a small layout quirk.

**Comment by MEdelenbosch** [comment]
Thanks. I didn't notice that i could scroll down in there. Found it.
