### ISSUE TITLE
Manual installed in a wrong place

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#1906]
### Steps to reproduce
```sh
$ cmake \
    -DMapper_MANUAL_QTHELP:BOOL=OFF \
    -DCMAKE_INSTALL_DOCDIR=/home/sikmir/test/share/doc/Mapper \
    -DCMAKE_INSTALL_MANDIR=/home/sikmir/test/share/man \
    -DCMAKE_INSTALL_PREFIX=/home/sikmir/test ..
$ make
$ make install
```

### Actual behaviour
```sh
$ tree /home/sikmir/test
/home/sikmir/test
├── bin
│   └── Mapper
├── home
│   └── sikmir
│       └── test
│           └── share
│               └── doc
│                   └── openorienteering-mapper
│                       └── manual
...
└── share
...
    ├── man
    │   └── man1
    │       └── Mapper.1
...
```

### Expected behaviour
It works properly with Mapper 0.9.4:
```sh
$ tree /home/sikmir/test
/home/sikmir/test
├── bin
│   └── Mapper
└── share
...
    ├── doc
    │   └── openorienteering-mapper
...
    │       └── manual
...
    ├── man
    │   └── man1
    │       └── Mapper.1
...
```

### RCA

I guess `${CMAKE_INSTALL_PREFIX}` not needed here:
https://github.com/OpenOrienteering/mapper/blob/9e874fe7d9d1b19e7560a2ed63be9a5da5cd0908/doc/manual/install-html.cmake.in#L26

### Configuration
Mapper Version: 0.9.5
Operating System: Linux

**Comment by dg0yt** [comment]
There was a change to properly use the `GNUInstallDirs` module from CMake.

IIUC, `install-html.cmake.in` is only used when building with `Mapper_MANUAL_QTHELP:BOOL=OFF`. However, it didn't break the Android build. Hm...

**Comment by sikmir** [comment]
Yes, I use `Mapper_MANUAL_QTHELP:BOOL=OFF`.
