### ISSUE TITLE
Export as .ocd with wrong ID for EPSG 25831, 25832 and 25833

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1912]
### Steps to reproduce
1. create .omap with EPSG 25832
2. export map as .ocd12 (tested also for .ocd10)
3. import .ocd12 into Mapper

### Actual behaviour
Mapper shows a warning "Could not load the coordinate reference system '8007'." and sets a local CRS.
OCAD does open the map and shows the ID 8007 but does not complain.
BTW: OCAD creates ID 63005 for EPSG 25832 which is correctly imported by Mapper.

### Reason
In file ocd_georef_fields.cpp EPSG 25831...25833 are declared twice in grid_zone_epsg_codes[]
243:    { OcdGrid::Germany, 6, 25831 }, // ETRS89 / UTM zone 31N
244:    { OcdGrid::Germany, 7, 25832 }, // ETRS89 / UTM zone 32N
245:    { OcdGrid::Germany, 8, 25833 }, // ETRS89 / UTM zone 33N
637:    { OcdGrid::UtmEtrs89, 4, 25831 }, // ETRS89 / UTM zone 31N
638:    { OcdGrid::UtmEtrs89, 5, 25832 }, // ETRS89 / UTM zone 32N
639:    { OcdGrid::UtmEtrs89, 6, 25833 }, // ETRS89 / UTM zone 33N

Mapper should select the line  { OcdGrid::UtmEtrs89, 5, 25832 } which results in ID 63005.
However, the function int toOcd(const MapperCrs crs_unique_id,...
will iterate over grid_zone_epsg_codes[] and the first match for EPSG 25832 will be the wrong one ({ OcdGrid::Germany, 7, 25832 }).

The import of ID 8007 fails because there is a gap/mismatch:
695:	case OcdGrid::Germany:
		// DHDN, Gauss-Krüger, Zone 2-5
		if (ocd_zone_id >= 2 && ocd_zone_id <= 5)
			return { MapperCrs::GaussKrueger, ocd_zone_id };
		break;
The OcdGrid::Germany case is entered due to 8007 / 1000 = 8 == OcdGrid::Germany.
However, the (ocd_zone_id >= 2 && ocd_zone_id <= 5) does not match ocd_zone_id 7 and thus the function exits
with return { MapperCrs::Invalid, 0 };

### Configuration
Mapper Version: 0.95 x64
Operating System: Win7

**Comment by dl3sdo** [comment]
I notice that even if 
244: { OcdGrid::Germany, 7, 25832 }, // ETRS89 / UTM zone 32N
245: { OcdGrid::Germany, 8, 25833 }, // ETRS89 / UTM zone 33N
are removed there are still duplicate definitions of EPSG 25832 prior to the desired one, e.g.:
    { OcdGrid::Italy, 7, 25832 }, // ETRS89 / UTM zone 32N
    { OcdGrid::Italy, 8, 25833 }, // ETRS89 / UTM zone 33N

**Comment by lpechacek** [comment]
Thanks for the report, Matthias! Can you please verify if the patch from PR#1916 fixes your issue?

**Comment by lpechacek** [comment]
> Mapper shows a warning "Could not load the coordinate reference system '8007'." and sets a local CRS.
> OCAD does open the map and shows the ID 8007 but does not complain.
> BTW: OCAD creates ID 63005 for EPSG 25832, which is correctly imported by Mapper.

A remark on how to read the `grid_zone_epsg_codes` table and how the translation works.

`grid_zone_epsg_codes` is indeed used for two-way translation between EPSG codes and OCD zone ids. However, Mapper has a few datums built-in and does not use EPSG codes for everything. There is a translation from/to the built-in datums to OCD codes in `toOcd()` and `fromOcd()`. Code for EPSG:25832 was correctly translated to `OcdGrid::Germany, 7` (8007) on the export, but on the way back, it fell into a gap in the code that handles translation of 8002-8005 to `MapperCrs::GaussKrueger`. That code part should let the other 8xxx codes fall through to the EPSG code lookup. The patch in #1916 establishes the fall-through to the EPSG lookup section.

OCAD ids 63xxx correspond to `OcdGrid::UtmEtrs89, xxx` that use EPSG codes in Mapper. That part seems to work flawlessly.

**Comment by dl3sdo** [comment]
Thank you for the fix and explanation Libor. The question remains whether we should apply ID 8007 for EPS 25832 as it still would be with your patch or if we change it to export ID 63005 like OCAD does. This could easily be achieved by moving the OcdGrid::UtmEtrs89, xxx section to the start of the array which still would allow to decode IDs 8007 & 63005.
What do you think?

**Comment by lpechacek** [comment]
> What do you think?

TBH, I don't intend to make Mapper bug-to-bug compatible with OCAD. I don't see Mapper as a **replacement** for the commercial software but rather as software for orienteering map-making.

OCAD engineers decided to assign two different internal codes for ETRS89 / UTM zone 31-33N their software. The user can first choose location "Germany" and then select the ETRS89 / UTM zone there, or select "ETRS89" location and the specific zone. I don't know the exact workflow and location names, but that would outline the steps. That is, when someone says that they are mapping in "ETRS89 / UTM zone 32N", it cannot be determined how they arrived at that selection in the OCAD georeferencing dialog.

That said, when we change the order of the entries, we will receive bug reports from those who chose location "Germany", and now they get "ETRS89" on export from Mapper. The solution would be to keep the OCAD code in Mapper's .omap. I don't plan to implement that without a compelling reason, however.

**Comment by lpechacek** [comment]
On an afterthought, it may make sense to move **all** the `OcdGrid::Utm*` zones in front of the "national" entries. Imagine someone who chooses "Italy"/ "ETRS89 / UTM zone 32N" and get "Germany" / "ETRS89 / UTM zone 32N" back on Mapper export. They might feel offended. The generic "ETRS89" location might feel more appropriate at this point. Opinions?

**Comment by dl3sdo** [comment]
Indeed, for OCAD, selecting the country first was probably intended to help the user select only known CRS that make sense for his country. Without preserving the imported ID, moving the zones at least changes the ID to the 'superset'.
While still changing something (which is most probably neither noticed nor needed) this would be an acceptable change with the least effort.

**Comment by dg0yt** [comment]
> The generic "ETRS89" location might feel more appropriate at this point. Opinions?

I would prefer the more generic solution.
 
I see a potential caveat of changing the CRS ID: There might be different transformations selected when looking them up from different pairs of CRS IDs. But I have no idea if this has relevance for the OCAD software.

**Comment by lpechacek** [comment]
I can see that there is agreement about the direction. Something tells me to be cautious before we make the change, however.

OCAD is said to be picky about what can become a background map. I.e. the grivation must agree (cf https://github.com/OpenOrienteering/mapper/issues/1896#issuecomment-798870687) and I think also the projection must be the same. That is, we should check that map with Germany / ETRS89 UTM 32N can have Italy / ETRS89 UTM 32N and ETRS89 / ETRS89 UTM 32N maps as templates. @dl3sdo, can you please carry out the test and let us know the results?

**Comment by dl3sdo** [comment]
@lpechacek: you had the right suspicion.
I used OCAD12 to test your proposed setup: foreground map with Germany / ETRS89 UTM 32N (ID 8007, EPSG25832), import of (same) background map with same EPSG but different ID fails (neither Italy / ETRS89 UTM 32N nor ETRS89 / ETRS89 UTM 32N). The same is true for foreground map ETRS89 / ETRS89 UTM 32N.
Error reported is: Internal error: Background map has a different coordinate system from this map.

**Comment by lpechacek** [comment]
> Error reported is: Internal error: Background map has a different coordinate system from this map.

Thanks for performing the test, Matthias! So, we should maintain the grid id parameter on re-export if possible. I can see the following options:
1) Add an element attribute in .omap to store the imported value. Re-use the value on export.
2) Stick the value in an existing .omap element or attribute. E.g., add a special line to the map notes or extend CRS parameters with the .ocd grid id.
3) Establish a new `MapperCrs::OCD` and use the number in a similar way to how we use EPSG numbers.
4) Leave things as they are and tell users to change their map's CRS in OCAD so that it matches what Mapper produces.

@dg0yt, what would be your advice here, please?

**Comment by dg0yt** [comment]
Thanks for looking into this issue.

> Error reported is: Internal error: Background map has a different coordinate system from this map.

Oh, the worst-case result for "different transformations".

> what would be your advice here, please?

I prefer to improve preserving of information in OCD files. In my opinion, the least volatile approach is (3) "establish a new MapperCrs::OCD", internally mapped to EPSG codes (for optimal usage of PROJ).
(4) is bad user experience. (1) and (2) are volatile when changing map georeferencing, which makes them worse alternatives for (3).

**Comment by lpechacek** [comment]
Thanks, Kai, for your feedback. I've isolated the creation of `MapperCrs::OCD` into a new issue (#1921). This one will be closed with the pull request merge.
