### ISSUE TITLE
Cannot export map as vector graphics PDF

### ISSUE THREAD

**Issue by jjojala** [OpenOrienteering/mapper#1914]
### Steps to reproduce
1. Open "forest sample.omap" (part of the distribution)
2. From the menu: File->Export as...->PDF
3. PDF export dialog appears for setting export options

### Actual behaviour
Mode "Raster graphics" is on. Mode "Vector graphis" is disabled and cannot be chosen. PDF is generated in raster graphics mode.

### Expected behaviour
Mode "Vector graphics" should be available (as it used to be in 0.9.4).

### Configuration
Mapper Version: 0.9.5
Operating System: Windows 10 Pro

**Comment by jjojala** [comment]
My C++ skills are already a bit rusty after so many years, but does it seem be in
https://github.com/OpenOrienteering/mapper/blob/v0.9.5/src/gui/print_widget.cpp#L658
that invokes method kmzTarget() in https://github.com/OpenOrienteering/mapper/blob/v0.9.5/src/core/map_printer.cpp#L401
that returns always non-NULL, i.e. TRUE.

**Comment by dl3sdo** [comment]
@jjojala: Yes, I agree.
bool is_raster_target = target == MapPrinter::imageTarget() || target == MapPrinter::kmzTarget();
does solve the issue and offers Vector graphics again.

**Comment by Symbian9** [comment]
@dg0yt, please, update `master` and `unstable` builds on OBS.

**Comment by Symbian9** [comment]
JFTR, @jjojala, latest `unstable 0.9.20211224` builds already include fix for this issue — vector PDF works as expected now!

So, till next release (0.9.6 or `1.0.0`) would be released it you may install and use `unstable` builds of OpenOrienteering Mapper ***under Linux***:

- https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper-unstable
  - https://download.opensuse.org/repositories/home:/dg0yt/

**Comment by app4soft** [comment]
There was no release & unstable builds for a while and existing builds on OBS are not suitable for latest **Debian 12** & **Ubuntu 22.04**.

(On Azure nightly only for Ubuntu 20.04)

@dg0yt, Could be fresh `unstable`/`master` compiled and packaged for latest Ubuntu 22.04 & Debian 12 on OBS?
