### ISSUE TITLE
New cutout and cut away icon

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1919]
### Steps to reproduce
Personally I struggle a lot with the iconography of the cutout and the cut away buttons.
![image](https://user-images.githubusercontent.com/15611653/111975790-4859b980-8b01-11eb-89b5-b77404b807ba.png)
I mean, yes, rationally I see it. Purple marks the area you get rid of, but at the same time purple is usually used to mark what is important. Neither do I want do get rid of OOB areas, as these are crucial for orienteering. Thus having to choose between cutout and cut-away (yes, I am not that well in English neither) I end up just confused and usually carry on to a "just try one of them"- bingo.
### Expected behaviour
I propose that we just leave away the purple hatch.
![image](https://user-images.githubusercontent.com/15611653/111976855-6378f900-8b02-11eb-952a-59f67f799603.png)
or to make it even clearer even the grayed out content.
![image](https://user-images.githubusercontent.com/15611653/111976949-80adc780-8b02-11eb-917f-1a55cb54656b.png)
or to make it even clearer try to avoid the control point association...
![image](https://user-images.githubusercontent.com/15611653/111977820-7b04b180-8b03-11eb-8438-3beddeb44c6e.png)

What do you think?

[Buttons.zip](https://github.com/OpenOrienteering/mapper/files/6181465/Buttons.zip)

### Configuration
Mapper Version: 0.9.5.
Operating System: Windows 7

**Comment by krticka** [comment]
I think that confusion can come also from wording used Cut out / Cut away. In GIS these tools are usually called Clip and Erase.
https://pro.arcgis.com/en/pro-app/latest/tool-reference/analysis/clip.htm
https://pro.arcgis.com/en/pro-app/latest/tool-reference/analysis/erase.htm

**Comment by dl3sdo** [comment]
@mlerjen: if the icons would be changed I would favour the ones with the red circle. I'm in slight favour for the variant without the light gray. For the variant with the light gray I would propose to use a darker green to better contrast with the light gray.

**Comment by lpechacek** [comment]
I think that this change is very much needed and I'll take care of the logistics.

The plan:
* Rename **Cutout** to **Clip (formerly Cutout)** and **Cut away** to **Erase (formerly Cut away)**. The old names tool will be kept for a year-long transition period.
* The icons would be those from the second row of ![image](https://user-images.githubusercontent.com/15611653/111977820-7b04b180-8b03-11eb-8438-3beddeb44c6e.png), i.e. red circle, white erased area for maximum contrast.

Agree?

**Comment by mlerjen** [comment]
![image](https://user-images.githubusercontent.com/15611653/112142979-8d501f80-8bd7-11eb-964c-9671b7cc77ca.png)
The clip and erase border does not have to be a perfect circle... (just playing with a tooth-line :-)

**Comment by krticka** [comment]
I am OK with red circle, white erased area for maximum contrast

**Comment by lpechacek** [comment]
This is the implementation. It is good that we have abandoned the gray icons. They would become indistinguishable from each other when they are deactivated. I've also added "area" to the tool descriptions to align them with the "verb noun" pattern in the menu.

![image](https://user-images.githubusercontent.com/5584406/112293572-93ef9d00-8c92-11eb-97a8-74e813f93f79.png)
