### ISSUE TITLE
530 Prominent man-made feature – ring 1.2 mm instead of 1.0

### ISSUE THREAD

**Issue by rem-maps** [OpenOrienteering/mapper#1920]
I am using version 0.9.4
and I just realized symbol 530 Prominent man-made feature – in the Mapper default  ISSPROM symbol set is 1.2 mm and it should be 1.0 mm (like cairn or tree - see pictures: black circle is bigger now in Mapper)

![manmade](https://user-images.githubusercontent.com/59602742/112101319-b7d5b480-8ba6-11eb-8b13-a6c9117d3eba.png)

![man2](https://user-images.githubusercontent.com/59602742/112101558-26b30d80-8ba7-11eb-8126-cb0969065624.png)

I can't believe no-one ever noticed it, so maybe I am doing something wrong?
please someone else check!
thank you

**Comment by eolmapper** [comment]
Yes, there is a mistake. The "a" diameter should be 0,56mm insted of 0,76mm.

**Comment by mlerjen** [comment]
... comparing ISOM and ISSPROM they were pretty free-style in scaling these point symbols inbetween. :-P
