### ISSUE TITLE
Problem with printing: vector graphics mode (it doesn't work)

### ISSUE THREAD

**Issue by biker2s** [OpenOrienteering/mapper#1927]
The two modes of printing do not work (graphic vector and color separation)
I don't know if it is problem from hardware or software.
On the previous version (0.9.4)  it works.

Device name	--------
Processor	Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz   2.53 GHz
Installed RAM	6,00 GB
Device ID	-----
Product ID	--------
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

![capture-20210330-100043](https://user-images.githubusercontent.com/36484895/112948025-32bb4400-9140-11eb-9edb-1b14fcc92c53.jpg)

**Comment by dl3sdo** [comment]
@biker2s: thank you for reporting this issue. This has already been reported as #1914, #1917, #1924 which are marked as closed.

**Comment by dg0yt** [comment]
I'm really sorry for the inconvenience.

Listed in "Known issues" linked in the release notes, and pinned on top of the issues list.
