### ISSUE TITLE
Font names invisible due to excessive font icon size

### ISSUE THREAD

**Issue by biker2s** [OpenOrienteering/mapper#1928]
I found this minor issue in previous versions as well. I solve it by opening the file with 0.9.2 version to change it and then I work again with the latest one. The problem exists from 0.9.3 version in my computer. I didn't try it in other device.

![text](https://user-images.githubusercontent.com/36484895/112949150-93974c00-9141-11eb-942e-ce51c0b889d0.jpg)

Thumbs up for 0.9.5!!!
It sounds really interesting.....

**Comment by dl3sdo** [comment]
Thank you for reporting this issue, indeed that is really weird behaviour. I confirm it for Windows10 and will check it on Linux.

**Comment by dg0yt** [comment]
Could you please double-check that the problem exists in v0.9.3?   
v0.9.4 added 'freetype' for PDF template support. This is the change most likely to have font-related side effects.

**Comment by dl3sdo** [comment]
Reproducible on Ubuntu and Windows7.
Problem exists in 0.93 as well but not in 0.92.

**Comment by lpechacek** [comment]
WTH? Replicated on openSUSE Tumbleweed.

**Comment by lpechacek** [comment]
Bisected down to 3f11710594c1. Disabling the `ScalingIconEnginePlugin` in `src/main.cpp` makes the problem go away. The connection to icon scaling also explains the fancy pattern from the screenshot. We are seeing the TrueType icon (red T + black T) scaled to the width of the drop-down container. :)

**Comment by Symbian9** [comment]
@dg0yt, May you force OBS to refresh `openorienterring-mapper-master`/`openorienterring-mapper-unstable` builds with latest `master` branch as actually all available builds for Linux (i.e. Debian 10) are affected by this issue.
