### ISSUE TITLE
Vectoring background maps

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1935]
When I license a background map to vectorize, and add it to the map by thinning the time lines, the program constantly closes itself. I also showed the video .

OpenOrienteering Mapper master v20201227.4
Windows 10

https://user-images.githubusercontent.com/62382116/113474041-ff492400-9475-11eb-8f4e-4fa379bf28de.mp4

**Comment by krticka** [comment]
Probably good idea to update to the latest stable version 0.9.5, works fine for me. Then I would try if this behaviour persist.
https://github.com/OpenOrienteering/mapper/releases

**Comment by dl3sdo** [comment]
I can easily reproduce the crash with master v20201227.4, while I can not reproduce it (up to now) with 0.95.
@AhmetPolat43: can you reproduce the crash with 0.95 and your map/template?

**Comment by AhmetPolat43** [comment]
> I can easily reproduce the crash with master v20201227.4, while I can not reproduce it (up to now) with 0.95.
> @AhmetPolat43: can you reproduce the crash with 0.95 and your map/template?

I do not understand exactly what you say, which version should I try?

**Comment by dl3sdo** [comment]
Version 0.95, the latest official release:
https://github.com/OpenOrienteering/mapper/releases
