### ISSUE TITLE
Not installable on "Ubuntu 20.10"

### ISSUE THREAD

**Issue by piiskop** [OpenOrienteering/mapper#1941]
### Steps to reproduce
1. Follow the [instructions](https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper)!
2. Start the installation process and see the unmet depencies problem!

### Actual behaviour
```
peacecop@peacecop-HP-ProBook-4520s:~/mapper-0.9.5/src$ sudo apt install openorienteering-mapper
[sudo] password for peacecop: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openorienteering-mapper : Depends: libgdal26 (>= 3.0.0) but it is not installable
                           Depends: libproj15 (>= 6.1.0) but it is not installable
                           Depends: qtbase-abi-5-12-8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Expected behaviour
The installation goes fine without dependency problems.

### Configuration
Mapper Version: The one you offer in your repository.
Operating System: "Ubuntu 20.10"

**Comment by dg0yt** [comment]
Note that there are different packages/instructions  for  different versions of Ubuntu. Ubuntu 20.10 is not there yet, except for the unstable package. I will see if I can enable easily.

**Comment by piiskop** [comment]
Well, _Ubuntu 21.04_ is about to knock at the door soon already.

I've tried to compile, too, but _cmake_ just did this:
```
peacecop@peacecop-HP-ProBook-4520s:~/mapper-0.9.5/src$ cmake .
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:332 (mapper_translations_sources):
  Unknown CMake command "mapper_translations_sources".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/peacecop/mapper-0.9.5/src/CMakeFiles/CMakeOutput.log".
```

**Comment by dg0yt** [comment]
> Well, _Ubuntu 21.04_ is about to knock at the door soon already.

Sure, that's covered by the "Ubuntu Next" configuration. However, I do not always notice new releases of distributions. So if 20.10 is missing, just ask for it. Usually its just a matter of a few click, plus a few minutes of build time.

I cannot comment about the cmake issues. There is something wrong, unrelated to pristine Mapper source code.
If you just want a nice package for your Ubuntu you might also try to build a .deb from the .dsc/.orig.tar.gz/.diff.gz at https://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_20.04/. (I don't have a link to these instructions ATM.)

**Comment by dg0yt** [comment]
Ubuntu 20.10 packages are ready now. I assume they are installable, as they were built in Ubuntu 20.10.

If you already added a repository for another version of Ubuntu, it needs to be removed and replaced with the 20.10 one.

**Comment by piiskop** [comment]
I was curious what _Ubuntu Next_ meant as there's no such thing as _Ubuntu Next_.

Installation for _Ubuntu 20.10_ went just fine after replacing the repository.

**Comment by dg0yt** [comment]
"Ubuntu Next" is a term used in the Open Build Service only, to name the coming distribution.
