### ISSUE TITLE
All files saved with OOM not accesible externaly

### ISSUE THREAD

**Issue by gianvigalta** [OpenOrienteering/mapper#1942]
### Steps to reproduce
1. saving maps in .omap, as pdf, printing and saving as pdf create the files but ehey are only visible inside OOM 
2. no way to find them on Windows File Explorer or other Explorer
3.

### Actual behaviour
i have a problem because the OMAP files created by OOM arent' shown in my file explorer.
I downloaded also other file explorer (Explorer++, FreeCommander) but no way that omap files appears.
They are regular listed if, from OOM, i click on open project.
Same Happens if i save file as pdf.
I have open same report in Question and Answer, @dg0yt tried to help me but no result at the end
I added .omap in the file indexing, i tried a lot of thing but no result.
I have Comodo Antivirus installed, correctly ask me during the installing the permissions to give to OOM, i click full.
I tried installing with Comodo not working,  on other PC but still same problem.

![file1](https://user-images.githubusercontent.com/15347218/115890128-e6200b80-a454-11eb-926e-e32c9b5630da.png)
![file2](https://user-images.githubusercontent.com/15347218/115890122-e5877500-a454-11eb-98b5-4b0f01c90f87.png)

### Expected behaviour
I have to see the files in Explorer

### Configuration
Mapper Version: 0.9.5
Operating System: windows 10 and windows 7

**Comment by dg0yt** [comment]
> I have to see the files in Explorer

Continuing the discussion from https://github.com/OpenOrienteering/mapper/discussions/1940:
I assume you run Mapper in an isolated sandbox. Either start it without sandbox, or start explorer in that sandbox, too.

**Comment by dg0yt** [comment]
Related: https://help.comodo.com/topic-72-1-451-4768-Configure-the-Sandbox.html

**Comment by gianvigalta** [comment]
tks dg0yt
i tried also to install and run without Comodo Antivirus/firewall ON, but files are missing the same.
I tried also to save on an USB key, but OOM say that USB is not available for writing because is write protected (but isn't true)

**Comment by dg0yt** [comment]
I still assume sandbox, because it is only known from your setup, and it is a consistent explanation. The USB device may be protected by the firewall, too. (Maybe a network share could work).

Please check the link I posted. There are settings for particular programs, or for shared space.

**Comment by gianvigalta** [comment]
@dg0yt 
you are right about th eissue in Comodo. But strange was that in sandbox i have no issue about OOM.
I disinstalled Comodo, reinstalled OOM and now i can see files. I  will use Avast from now on.
Hope that this will not happens anymore.
Many tks for your help

**Comment by dg0yt** [comment]
To be honest, I like what I learned about this sandbox. It is just the kind of thing what you need with random downloads from the Internet. The problem seems to be that it doesn't seem to sufficiently interact with the user: explain, what is blocked and how the user can change this.

Apps on Android, iOS, macOS and in some Linux bundles are restricted, too. However there are explicit and implicit ways to ask for certain permissions to be granted.
