### ISSUE TITLE
fedora 34 is out  - will you make openorienteering-mapper for that as well

### ISSUE THREAD

**Issue by enpontus** [OpenOrienteering/mapper#1943]
### Steps to reproduce
1.fedora 34 is out
2.
3.

### Actual behaviour
no openorienteering-mapper packages for f34 - yet

### Expected behaviour
f34 packages availagle

### Configuration
Mapper Version:
Operating System: fedora 34

**Comment by dg0yt** [comment]
Thanks for the hint!
Repository activated, packages ready.

**Comment by enpontus** [comment]
Thank you a lot!
brg Pontus

**Comment by enpontus** [comment]
Hello again - fedora is now apparently at #35 will there be a repo for that
as well ?

brg Pontus
