### ISSUE TITLE
Simple course exported as IOF-XML does not comply with IOF XML schema

### ISSUE THREAD

**Issue by arashipl** [OpenOrienteering/mapper#1947]
### Steps to reproduce
1. Select a course and export as Simple Course to IOF Data Standard 3.0 (xml)
2. Validate resulting file against IOF Data Standard 3.0 XSD ( https://github.com/international-orienteering-federation/datastandard-v3/blob/master/IOF.xsd ) with use of any validation tool (i.e. https://www.freeformatter.com/xml-validator-xsd.html )

### Actual behaviour
Validation fails - at first due to basic mistake - CourseDate tag is used instead fo CourseData.
After easy fix it throws a lot of absent but required attributes:
```
Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'CourseControl'. One Of '{"http://www.orienteering.org/datastandard/3.0":PunchingUnitId, "http://www.orienteering.org/datastandard/3.0":Name, "http://www.orienteering.org/datastandard/3.0":Position, "http://www.orienteering.org/datastandard/3.0":MapPosition, "http://www.orienteering.org/datastandard/3.0":Extensions}' Is Expected., Line '8', Column '63'.
(...)
```

### Expected behaviour
Exported data should pass the validation or Mapper should not claim to export valid IOF XML course files.

### Configuration
Mapper Version: 0.9.5
Operating System: Windows

**Comment by dl3sdo** [comment]
@dg0yt: I fixed two issues. Besides the typo in CourseData the CourseControl inside the Control elements needs to be replaced by Position. Now the XML validation tool as proposed by @arashipl passes.

**Comment by arashipl** [comment]
@dl3sdo I checked those changes by manual search&replace and resulting file uploaded fine to livelox.com. This was quick, I even thought about making a fix myself but it was done before I even started to set up the toolchain. Looking forward to 0.9.6
