### ISSUE TITLE
Scan result on computer

### ISSUE THREAD

**Issue by bjeuph6** [OpenOrienteering/mapper#1949]
### Steps to reproduce
1. see results of scan below
2.App is blocked from opening
3.

### Actual behaviour
Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 09/05/2021
Scan Time: 11:26
Log File: 0adb78d4-b0b1-11eb-b6c7-bc5ff4e101ad.json

-Software Information-
Version: 4.3.0.98
Components Version: 1.0.1273
Update Package Version: 1.0.40250
Licence: Premium

-System Information-
OS: Windows 10 (Build 19041.928)
CPU: x64
File System: NTFS
User: System

-Scan Summary-
Scan Type: Threat Scan
Scan Initiated By: Scheduler
Result: Completed
Objects Scanned: 458461
Threats Detected: 1
Threats Quarantined: 0
Time Elapsed: 6 min, 25 sec

-Scan Options-
Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 1
Malware.AI.1120729248, C:\PROGRAM FILES\OPENORIENTEERING MAPPER 0.7.0\LIBEXPAT-1.DLL, No Action By User, 1000000, 0, 1.0.40250, BF9F17521CB27F3842CCF8A0, dds, 01237523, D25780335348F5BEA9079B5206ECE95C, FF67F6D2AC6D3422244BACC6793A448832ED9B33213E7C7B9FC36D2D8C57151B

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

(end)

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:0.7.0
Operating System:Win 10 64 bit

**Comment by dg0yt** [comment]
> Mapper Version:0.7.0

0.7.0, seriously? 

- I don't see a sound evidence of malware here. 
  Malware.**AI** may mean Artificial Intelligence, i.e. some heuristics which can generate false positives.
- [0.7.0](https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.0) is from  5 Jun 2017. Even if there is no malware, there must be vulnerabilities. Some vulnerabilites may be based on behaviour which is flagged as potentially malicious by modern malware heuristics.

Scan with other services to be sure.
