### ISSUE TITLE
Strange behaviour on Symbol modification

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1954]
### Steps to reproduce
Inspired by @ollesmaps I modified the ISSprOM symbol for impassable fence such as the drawing-line is situated at the outline of the symbol. 
### Actual behaviour
As far as fun... until I just noticed that as soon as I bend a line feature with the new symbolisation it gets apparent that for the modified symbol the tags get drawn twice in a slightly differing angles.
![image](https://user-images.githubusercontent.com/15611653/118301767-bc9e5100-b4e3-11eb-88f3-c5805e5bb753.png)

### Sample
[Sample Tagged Fence.zip](https://github.com/OpenOrienteering/mapper/files/6480006/Sample.Tagged.Fence.zip)

### Expected behaviour
The tags should just be drawn once each

### Configuration
Mapper Version: 0.9.5
Operating System: Windows 7

**Comment by ollesmaps** [comment]
I imported the definition from Ocad and it seems correct.
![plot](https://user-images.githubusercontent.com/20535899/118350829-0d9c5c80-b559-11eb-92cc-817ff5d7cf96.jpg)
[shifted_fence.zip](https://github.com/OpenOrienteering/mapper/files/6483304/shifted_fence.zip)

**Comment by dg0yt** [comment]
>  it gets apparent that for the modified symbol the tags get drawn twice in a slightly differing angles.

Actually it is not twice but *three times*. It is expected behaviour here. Your symbol definition says "3 mid symbols per spot, with 0 mm distance.

:smile:

**Comment by mlerjen** [comment]
🤦‍♂️
