### ISSUE TITLE
Error when compiling OOMapper on Debian 10 Linux

### ISSUE THREAD

**Issue by akom5224** [OpenOrienteering/mapper#1957]
### Actual behaviour
When trying to compile mapper (0.9.5, the same error appears also with 0.9.4) on Debian 10 Linux machine, the following error is reported around 1/3 of the process:

[ 34%] Building CXX object src/CMakeFiles/Mapper_Common.dir/core/symbols/combined_symbol.cpp.o
/home/komarek/DownloadAK/Lib_SRC/mapper-0.9.5/src/core/symbols/combined_symbol.cpp: In lambda function:
/home/komarek/DownloadAK/Lib_SRC/mapper-0.9.5/src/core/symbols/combined_symbol.cpp:64:56: error: ‘this’ was not captured for this lambda function
   return (part && is_private) ? Symbol::duplicate(*part).release() : part;
                                                        ^
make[2]: *** [src/CMakeFiles/Mapper_Common.dir/build.make:579: src/CMakeFiles/Mapper_Common.dir/core/symbols/combined_symbol.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3418: src/CMakeFiles/Mapper_Common.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

This looks like some error in the C++ code? In case of need, I am appending (at the end of the message) also output from 'cmake' that preceded 'make' leading to above error.

### Expected behaviour
Compilation should run without errors.

### Configuration
Mapper Version: 0.9.5 (the same problem appears also with 0.9.4 version)
Operating System: Linux, Debian 10

### OUTPUT FROM cmake:
Make Warning (dev) at CMakeLists.txt:50 (message):
  In-source builds are discouraged for development.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Polyclipping: /usr/include/polyclipping (found suitable version "6.4.2", minimum required is "6.1.3") 
-- Found GDAL: /usr/lib/libgdal.so (Required is at least version "2") 
-- Could NOT find ClangTidy: Found unsuitable version "7.0.1", but required is at least "8" (found /usr/bin/clang-tidy)
CMake Warning (dev) at CMakeLists.txt:262 (message):
  Install clang-tidy >= 8 for code checks during build
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find IWYU (missing: IWYU_EXECUTABLE) (Required is at least version "0.12")
CMake Warning (dev) at CMakeLists.txt:272 (message):
  Install include-what-you-use >= 0.12 for code checks during build
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring Mapper user manual
-- Conditional manual sections: LINUX
-- Configuring Mapper translations
-- Found GDAL: /usr/lib/libgdal.so  
-- Configuring Mapper packaging
-- Configuring Mapper licensing documentation
-- Direct third-party components: libpolyclipping;proj;qtbase;qtimageformats;qttranslations;qtlocation;qtsensors;qtserialport;qtsingleapplication;gdal;potrace
-- Licensing information provided by: debian
-- Found Polyclipping: /usr/include/polyclipping (found version "6.4.2") 
-- Configuring Mapper API documentation
-- Configuring Mapper source packaging
-- The following features have been enabled:

 * Mapper_WITH_COVE, Contour line vectorization

-- The following OPTIONAL packages have been found:

 * Qt5SerialPort
 * Qt5Positioning
 * Qt5Sensors

-- The following REQUIRED packages have been found:

 * Qt5Sql
 * Qt5Help
 * Qt5LinguistTools
 * Qt5Concurrent
 * GDAL
 * Polyclipping
 * PROJ4
 * Qt5Core
 * ZLIB
 * Qt5Network
 * Qt5Gui (required version >= 5.11.3)
 * Qt5PrintSupport
 * Qt5Test
 * Qt5Widgets

-- The following OPTIONAL packages have not been found:

 * ClangTidy (required version >= 8)
 * IWYU (required version >= 0.12)

-- CMAKE_CXX_FLAGS:  -Wall -Wpedantic -Wextra
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG
-- CMAKE_C_FLAGS:  -std=c99 -Wall -Wpedantic
-- CMAKE_C_FLAGS_RELWITHDEBINFO: -O2 -g -DNDEBUG
-- Configuring done
-- Generating done
-- Build files have been written to: /home/komarek/DownloadAK/Lib_SRC/mapper-0.9.5

**Comment by lpechacek** [comment]
FTR, the Debian variant of Mapper builds in OBS just fine: https://build.opensuse.org/package/binaries/home:dg0yt/openorienteering-mapper/Debian_10

Another remark, in-tree builds may cause interesting effects (https://github.com/OpenOrienteering/mapper/issues/1866#issuecomment-770382669). I wouldn't suspect the in-tree build to be the culprit here. I think that it's rather a version of Clang that is reporting this error. However, I don't see which compiler is in effect from the output. In case it's Clang, can you retry an out-of-tree compilation with GCC, please?

**Comment by dg0yt** [comment]
This is a bug in g++-8, as provided in Debian 10. References:
https://github.com/OpenOrienteering/mapper/issues/1632 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89050 
No bug reported in Debian, unfortunately.

The workaround is to use g++-7. Our Debian 10 build logs: 
https://build.opensuse.org/public/build/home:dg0yt/Debian_10/x86_64/openorienteering-mapper/_log

**Comment by akom5224** [comment]
Thanks for quick replies. Kai is right. The problem was in g++-8. Once I changed it to g++-7 everything went fine.

**Comment by lpechacek** [comment]
Marking as resolved then. Thanks!
