### ISSUE TITLE
Could not load the coordinate reference system '20023'

### ISSUE THREAD

**Issue by Schmackster** [OpenOrienteering/mapper#1976]
### Steps to reproduce
1. Open an OCAD map referenced to coordinate system EPSG 7856 (id 20023) in OOMapper
2. 
3. 

### Actual behaviour
Gives error message "Could not load the coordinate reference system '20023' "
It brings in the grid magnetic angle from OCAD rather then changing it to the magnetic declination from true north

### Expected behaviour
It should change the grid magnetic angle from OCAD to the magnetic declination from true north

### Configuration
Mapper Version: 0.9.4
Operating System: Windows 10 Pro (20H2, build 19042.1110)

**Comment by dg0yt** [comment]
Thanks for reporting the issue. 
IIUC, OCD ID 20023 and [EPSG 7856 / GDA2020 / MGA zone 56](https://epsg.org/crs_7856/GDA2020-MGA-zone-56.html) are not in our list of known OCD IDs. It would be good to add it, given the rapid movement of Australia. But this is just one zone of GDA2020 / MGA. Can you help us find the OCD IDs of other relevant zones as well?

|OCD| EPSG| Name|
|------|-----|-----------|
|20023|7856|GDA2020 / MGA zone 56|
|...|...|GDA2020 / MGA zone ...|

**Comment by Schmackster** [comment]
Mainland Australia spans UTM zones 49 to 56. Below are the OCD IDs and EPSG codes for the latest reference datum

OCD | EPSG | Name

20023 | 7856 | GDA2020 / MGA zone 56
20022 | 7855 | GDA2020 / MGA zone 55
20021 | 7854 | GDA2020 / MGA zone 54
20020 | 7853 | GDA2020 / MGA zone 53
20019 | 7852 | GDA2020 / MGA zone 52
20018 | 7851 | GDA2020 / MGA zone 51
20017 | 7850 | GDA2020 / MGA zone 50
20016 | 7849 | GDA2020 / MGA zone 49

**Comment by dl3sdo** [comment]
@Schmackster: can you provide an OCAD sample map?

**Comment by Schmackster** [comment]
[Nth Turramurra 2021-07-25.zip](https://github.com/OpenOrienteering/mapper/files/6884871/Nth.Turramurra.2021-07-25.zip)

**Comment by dl3sdo** [comment]
@Schmackster: thank you for the file. Opening now works fine, please find attached the resulting omap file.
Looking up the reference point in OpenStreetMap results in a plausible location too.
[Nth Turramurra 2021-07-25 omap.zip](https://github.com/OpenOrienteering/mapper/files/6885769/Nth.Turramurra.2021-07-25.omap.zip)

**Comment by Schmackster** [comment]
Looks good to me too. Thanks for fixing.
