### ISSUE TITLE
Symbol locking ?

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1986]
Hello, is there a symbol lock feature in the android version? I couldn't find it.
@dg0yt

**Comment by mlerjen** [comment]
![Screenshot_20210816-105029_OpenOrienteering Mapper](https://user-images.githubusercontent.com/15611653/129537283-59a9108d-9649-411c-b8e1-f94cdcc16a6a.jpg)
A long press on the symbol icon on the main view opens up the dialog to hide/lock the active symbol.

**Comment by AhmetPolat43** [comment]
@mlerjen thank you very much.
