### ISSUE TITLE
File save error in Ocad12 format

### ISSUE THREAD

**Issue by Guus55** [OpenOrienteering/mapper#2015]
![Knipsel](https://user-images.githubusercontent.com/96693269/147413121-3dc41d66-5846-44c6-8831-ddef33f61a44.JPG)
Error is there in all Ocad formats, Ocad8 - Ocad12

The map is pretty large, about 22Mb

**Comment by lpechacek** [comment]
Thanks for the report. The issue has already been reported and analyzed in issue #2012.

As a workaround, delete all undefined text objects from the map before exporting or assign a real symbol to them. You can find all objects with undefined symbols by hiding all symbols. Then Select all objects function (Ctrl-A) chooses those with an undefined symbol.
