### ISSUE TITLE
ISMTBOM2022 Symbol set

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#2033]
Create ISMTBOM2022 Symbol set.
[PDF ISMTBOM2022](https://onedrive.live.com/?authkey=%21AE8iquTM1ZY3UDM&cid=663580750D0C0BCE&id=663580750D0C0BCE%2147463&parId=663580750D0C0BCE%2118039&o=OneUp)

**Comment by Symbian9** [comment]
Duplicate of https://github.com/OpenOrienteering/mapper/issues/1107
