### ISSUE TITLE
Can't select any Line Tools

### ISSUE THREAD

**Issue by psathalo** [OpenOrienteering/mapper#2037]
### Steps to reproduce
1. Open OOM
2. Try to select a line tool, eg "Road" not available. eg, try to draw a freehand line...it treats it as a point object and all I get is a short line set at a bearing of 45 degrees. All point objects are working correctly. "Edit Lines" makes no difference....it's greyed out too.
3.

### Actual behaviour
All line tools are being dealt with as Point Tools, line tools greyed out. Not had this before.

### Expected behaviour
Should be able to select Line tools correctly, what am I doing wrong?

### Configuration
Mapper Version: 0.94 and 9.95
Operating System: Desktop computer, android.

**Comment by mlerjen** [comment]
Could you share screenshots?

**Comment by psathalo** [comment]
Hi
I am a recently new user to OOM. I believe I am stuck on Course Planner
mode and not the map drawing mode. How do I get back to map drawing?
Paul

**Comment by psathalo** [comment]
Paul

**Comment by jmacura** [comment]
Dear Paul,

it seems like your last message was malformed. If you could, it would be better, if you can reply directly via GitHub ([here](https://github.com/OpenOrienteering/mapper/issues/2037)) and not via email.

Regards
 Jan

**Comment by psathalo** [comment]
![Current display](https://user-images.githubusercontent.com/99027425/152610279-1fd68704-a167-4604-9208-622709f7a52d.JPG)

[Current Display as a Word File.docx](https://github.com/OpenOrienteering/mapper/files/8006550/Current.Display.as.a.Word.File.docx)

Hi File(s) attached
Paul

**Comment by dg0yt** [comment]
Thanks for sharing your question and screenshot @psathalo.

In the course planning symbol set, the actual map is just a template and can't be edited. 

With "symbols", we usually refer to the (abstract) symbols as found on the right side of your screenshot. 
The features in the actual map are refered to as "objects".

By the way, you can import OSM data (i.e. `.osm` files as exported by openstreetmap.org) directly into a map. For our foot-O symbol sets, we automatically assign many symbols from OSM tags. The remaining objects can be reviewed manually, and finally the remaining OSM symbols can be hidden.

Hope this helps,
Kai

**Comment by psathalo** [comment]
Hi again, Thanks for the clarification of the various points. I shall have
a play round with the osm files see if I can how it works. Should save me a
load of time.
As I say, I am just a beginner so much of what I am doing is new to me.
😊
Paul
