### ISSUE TITLE
Bluetooth GPS

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#2050]
I can not see the app "Bluetooth GPS" in Google Play anymore. Same at you? - (that might concern only the manual)
(Android 9 and 12)

I installed "Bluetooth GNSS - GPS, Galileo, GLONASS and BeiDou", connected to Garmin **GLO** and strangely I can not see **Glo**nass satellites in the menu, see picture:

![no_glonass2](https://user-images.githubusercontent.com/20535899/158138300-dd933940-2b01-49d9-a5a5-1de86f6e3448.jpg)

I checked with my phone built in GNSS and there I can see Glonass satellites.

So the question is:
a) Is Garmin Glo malfunctioning or?
b) Is "Bluetooth GNSS" malfunctioning?

**Comment by lpechacek** [comment]
Ad Bluetooth GPS, I can see it [in Google Play](https://play.google.com/store/apps/details?id=googoo.android.btgps). It is not featured in the search but the direct link works. The last update is from 2015.

Regarding the compatibility of Bluetooth GNSS with Garmin, you got to talk to the Bluetooth GNSS developers at https://github.com/ykasidit/bluetooth_gnss/issues . From my POV, Bluetooth GNSS is a perfect fit for U-blox receivers, including the ClearEvo products. I'll list the benefits below. Garmin products tend to be unknown technology wrapped in marketing words. You never know exactly what is inside. A possible reason for GLONASS not being listed in the in use/in view section might be the incompatible numbering of satellites in the NMEA message.

The benefits of Bluetooth GNSS with U-blox receivers:
1) it does report the U-blox accuracy estimate the same way the receivers in Android-based devices do (mind that the accuracy estimate is not HDOP, residuals, or the convolution matrices; the accuracy estimate is a proprietary synthetic value)
2) it's not confused by the dual-frequency readings coming out of ZED F9P
3) it includes an NTRIP client, perfect for RTK and DGPS
4) it sends the rover location over the NTRIP connection, so it's compatible with VRS
5) it's reliable, at least in my deployment
6) it's open source

In any case, the connection between Android device and the receiver is not in OO Mapper's scope. I'm closing the ticket as off topic.

**Comment by ollesmaps** [comment]
Thank you Libor! The direct link works.
