### ISSUE TITLE
Unify Areas tool error !

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#2076]
![Ekran görüntüsü 2022-06-29 181222](https://user-images.githubusercontent.com/62382116/176473874-6dadfb76-dbbc-481a-88c9-a0064c163d3a.jpg)
![Ekran görüntüsü 2022-06-29 181250](https://user-images.githubusercontent.com/62382116/176473881-6b7589f0-f937-44b6-b1b8-3f54f5119f3b.jpg)
![Ekran görüntüsü 2022-06-29 181337](https://user-images.githubusercontent.com/62382116/176473885-0581648f-bf7a-431c-9603-b37e0cb03368.jpg)
![Ekran görüntüsü 2022-06-29 181401](https://user-images.githubusercontent.com/62382116/176473891-61e519d3-db72-4962-8611-107b8c576720.jpg)
![Ekran görüntüsü 2022-06-29 181437](https://user-images.githubusercontent.com/62382116/176473896-a147c980-0805-467e-8d77-bab421e4504d.jpg)
### Steps to reproduce
1.I imported a building plan into OOMapper.
2.When I want to combine adjacent buildings and get a single building image, it becomes a building that goes into infinity.
3.What is causing this? I tried with 6-7 different data but still the same result.
the file is in the link
https://dosya.co/twkh16fbqdbo/1.dxf.html

### Configuration
Mapper Version:0.9.5
Operating System:Windows 10

**Comment by dg0yt** [comment]
Does the problem also occur when you close the map after import, open it again, and the call the operation?
(When loading your demo map, I get: 
"Some coordinates were out of bounds for printing. Map content was adjusted."
And I cannot reproduce the issue yet.)

**Comment by AhmetPolat43** [comment]
I saved the imported data without converting it to building. I then turned it off and on after turning it into a building. There was no problem when I did the merge

**Comment by AhmetPolat43** [comment]
Thanks, problem solved

**Comment by dg0yt** [comment]
Thank you for the feedback. We know a workaround now, and some approximate conditions which can trigger the issue. I know we have seen this before...

**Comment by dl3sdo** [comment]
For reproducing the issue with the 1.dxf file as provided above it is important to select a map scale of 1:4000 or less. Then the issue can be reproduced for different symbol sets and for different symbols.
When creating an empty map or changing the map scale after import the issue does occur for e.g., 1:3000, 1:4000 but not for 1:4500, 1:5000, 1:10000.
Example:
- new map with 1:10000, ISOM 2017-2
- import 1.dxf and change objects to symbol 522
- try to unify some buildings as shown above -> ok
- undo and change map scale to 1:4000
- try to unify some buildings as shown above -> fail

**Comment by dg0yt** [comment]
The DXF import creates paper coodinates 1 million millimeters aways from the origin. This is app. 1 billion internal units (2E30), really close to the numeric limits of signed 32 bit integers.
