### ISSUE TITLE
Using File from Mobile App in Desktop App

### ISSUE THREAD

**Issue by GyDomonkos** [OpenOrienteering/mapper#2081]
Steps to reproduce
1. Create map in Desktop App
2. Copy it onto Mobile phone and open it in Mobile App and add modifications.
3. Try opening it in the the Desktop App again

Actual behaviour
When opening the file in Step 3., the Program returns error

Expected behaviour
Opening the file normally.

Configuration
Mapper Version: 9.5
Operating System: Windows 10

**Comment by jmacura** [comment]
I would suspect an incomplete transfer of data from your mobile device to your desktop device. I have experienced this in the past. See  #1115
Could you retry?

**Comment by GyDomonkos** [comment]
I retryed after restarting the Computer and Phone, and it worked again.
