### ISSUE TITLE
Install Error on Arch Linux

### ISSUE THREAD

**Issue by pkturner** [OpenOrienteering/mapper#2130]
### Steps to reproduce
1. On web page for Mapper app, click on button "Download v0.9.5 for Linux".
2. On OpenSuse openorienteering-mapper web page, click on "Arch".
3. Click on "Add repository and install manually".
4. Follow the directions that are displayed. The final command is
`pacman -Sy home_dg0yt_Arch_Community/openorienteering-mapper`

### Actual behaviour
Error messages are displayed.
`error: home_dg0yt_Arch_Community: signature from "home:dg0yt OBS Project <home:dg0yt@build.opensuse.org>" is unknown trust`
`error: failed to synchronize all databases (invalid or corrupted database (PGP signature))`

Checking pacman-key indicates the signature is expired.

### Expected behaviour
The openorienteering-mapper package is installed.

### Configuration
Mapper Version: 0.9.5
Operating System: Arch Linux

**Comment by dg0yt** [comment]
Today I updated the the 0.9.5 packages, backporting two changes to fix build errors.
Now that it builds again, it should pick up an updated signing key.
HTH

**Comment by pkturner** [comment]
Thank you @dg0yt.

It did not "just work". However, it did work after I followed the directions on the openSUSE installation page, to add and locally sign the new key.
