### ISSUE TITLE
Update Actions runner image

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#2140]
Due to https://github.com/actions/runner-images/issues/6002 Ubuntu 18.04 will no longer be supported by 2023/04/01.
Recommendation is that
> Workflows using the ubuntu-18.04 image label should be updated to ubuntu-latest, ubuntu-20.04, or ubuntu-22.04

[azure-pipelines.yml](https://github.com/OpenOrienteering/mapper/blob/master/ci/azure-pipelines.yml) currently references 'ubuntu-18.04' five times.

**Comment by dg0yt** [comment]
This needs to be solved in https://github.com/OpenOrienteering/superbuild first.

**Comment by dg0yt** [comment]
Fixed by #2146.
