### ISSUE TITLE
Find object by code number

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#2183]
### Steps to reproduce
1.Draw some object with symbol 123
2. Find Object with the expression SYMBOL 123 (Like it's describe in the user manual)

### Actual behaviour
Nothing happens. the objects are not find

Its work fine with the name of the symbol but it will be easily if it worked with the symbol code.
I have tried different syntax variations but without success

**Comment by dg0yt** [comment]
There is only the workaround to search all objects with a particular symbol (via right click on the symbol).

**Comment by eolmapper** [comment]
When you select all object it is very difficult to see what is selected.
**So what is interesting is the "search next" function** which allows you to inspect the objects one by one. (like with the binoculars in ocad) This allows for example to inspect each black cross to see what it represents or Each object of the same type individualy which potentially has the same drawing problem.
