### ISSUE TITLE
Not able to download to phone

### ISSUE THREAD

**Issue by MarshaGF** [OpenOrienteering/mapper#2210]
### Steps to reproduce
1.Got a new phone, Samsung S24
2.App was not working after data transfer (wouldn't open)
3.Tried to download. Phone says 1. app is dangerous but tried to download anyway, 2. app is not compatible 

### Actual behaviour
Can't download app to phone which I need to finish a map I am working on.
### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dg0yt** [comment]
Please make sure to try the "arm64-v8a.apk" from https://github.com/OpenOrienteering/mapper/releases/tag/v0.9.5.

**Comment by MarshaGF** [comment]
Thank you! That seems to have worked.

**Comment by dg0yt** [comment]
Thanks for your feedback. I took this as a reminder to change the default Android download link to arm64,
