### ISSUE TITLE
Build pipeline: macOS-11 image is deprecated

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#2248]
The build of #2027 was aborted due to
"This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024."

According to
https://learn.microsoft.com/en-us/azure/devops/release-notes/2024/sprint-238-update
"The macOS-11 image is deprecated and will be retired June 2024."

**Comment by dg0yt** [comment]
Needs https://github.com/OpenOrienteering/superbuild/pull/96.

- [ ] PR CR in superbuild
- [ ] master CI in superbuild
- [ ] Retain master CI run
- [ ] Switch mapper CI

**Comment by dl3sdo** [comment]
Tnx Kai.
