### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Sonka-a** [OpenOrienteering/mapper#2260]
![Screenshot 2024-07-19 110315](https://github.com/user-attachments/assets/6f0e8eae-f8f8-4b8b-8b4a-3c0294ddab1e)
Help me please! I have this issue in Open Orienteering Mapper: Error while loading an object of type 1 at 2540:161966: Could not parse coordinates. Is it possible to revive the file, I was working many hours with it. The only thing left from it is a PDF, but of course I can't work on that. Thanks!

**Comment by dl3sdo** [comment]
@Sonka-a: Please send me the file via email and I will try fixing it.
Regards, Matthias

**Comment by dl3sdo** [comment]
BTW: if you open the map with a text editor, the error message tells you in which line the problem occurs, in this case it's line 2540.
