### ISSUE TITLE
Build pipeline: macOS-12 image is deprecated

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#2284]
See
[Notice of upcoming deprecations and breaking changes in GitHub Actions runners](https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/)
and
https://github.com/actions/runner-images/issues/10721

**Comment by dg0yt** [comment]
The macOS 12 image "will be fully retired by the December 3rd, 2024".  
IIUC the macOS 13 image is still available for x64.  
But our key challenge might be ensuring the lowest deployment target, cf. https://github.com/OpenOrienteering/mapper/discussions/2288.

**Comment by dg0yt** [comment]
Resolved with GH-2291
