### ISSUE TITLE
Tag selector not there?

### ISSUE THREAD

**Issue by eliska161** [OpenOrienteering/mapper#2294]
Hello, where is my tag selector? I have the tag editor but i cant find the tag selector.

![Bilde_2024-11-08_082356863](https://github.com/user-attachments/assets/0d835fdb-744d-483d-b344-35d8094eb9ab)
![Bilde_2024-11-08_082409279](https://github.com/user-attachments/assets/afb71bb8-0aba-4c51-bbcb-10ccd44af107)

**Comment by dg0yt** [comment]
Manual pages:
https://www.openorienteering.org/mapper-manual/pages/object_tags.html
https://www.openorienteering.org/mapper-manual/pages/find_objects.html

**Comment by eliska161** [comment]
Thanks
