### ISSUE TITLE
Problems exporting PDF

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#269]
**oskarlin reported on Sourceforge [[tickets:#269](https://sourceforge.net/p/oorienteering/tickets/269)]:**

I'm using 0.5.3 and having problems with the PDF export. I'm making a ISSOM 4000 map and when I make PDF:s for field work I'm trying to export in A5 format with templates but the PDF end up really weird. The PDF is A5 but it looks like the attached image (the map is up in the left corner).

When I export without the templates turned on, it comes out fine. 

It doesn't matter if the template is an other OMAP file or if it's a raster image, it goes wrong either way.

![image](https://cloud.githubusercontent.com/assets/13567791/25794540/9f40b20c-33d1-11e7-8871-f944eacf3d54.jpg)

**Comment by dg0yt** [comment]
@oskarlin Is this still an issue?

**Comment by oskarlin** [comment]
Yes. And I have noticed why it behave like this. I think the default resolution is 1200 dpi. So if I export in 1200 dpi the template image end up the same as the map. But in 600 dpi it comes out smaller, like the screen shot above. Etc. But my quick fix for this has been opening the PDF in Illustrator and scale the template to the same size as the artboard, and then print it.

**Comment by dg0yt** [comment]
Hm. Even today, I wasn't immediately succesful in reproducing the issue (using 0.7.0-RC2 and [the world file test map](https://github.com/OpenOrienteering/mapper/tree/master/test/data/templates)) ... until I changed from vector graphics mode to raster graphics mode. There is no difference whether I decide to include or exclude templates, the scaling is wrong, the output is in the top left corner.

**Comment by oskarlin** [comment]
![nybohov_obj_ochdens](https://cloud.githubusercontent.com/assets/2736990/25826109/d28f6d82-3445-11e7-91d0-8fc1612c4ec3.png)
[nybohov_obj_ochdens.pgw.txt](https://github.com/OpenOrienteering/mapper/files/984896/nybohov_obj_ochdens.pgw.txt)

Here are my background file. It's in EPSG 3006 (Sweref 99TM).

**Comment by dg0yt** [comment]
As stated in my last comment, the issue is reproducible only in raster graphics mode, and not on Linux (i.e. probably only on Mac).

**Comment by dg0yt** [comment]
Update: not only in raster graphics mode, but also in vector mode when template opacity is different from 100 % and therefore printed/exported in raster graphics mode. And the scaling is not if it would be always using 1200 dpi internally, but 2x the selected resolution. "x2", the "Retina factor"?

**Comment by dg0yt** [comment]
No, 1200 dpi is a correct reference here, but changes in the dpi entered in the dialog are sometimes not forwarded to the export process...

**Comment by dg0yt** [comment]
Seems to be related to the second change in f7739fa.
In addition, there is an issue with changes in resolution field not being used when immediately clicking export after editing this field.

**Comment by dg0yt** [comment]
You can test v0.7.0-RC3 now (printing, PDF export, image export).
