### ISSUE TITLE
Follow a path's outline

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#273]
**oskarlin reported on Sourceforge [[tickets:#273](https://sourceforge.net/p/oorienteering/tickets/273)]:**

If I have a road and want to follow the outer border of that line (the black outline) this is not possible right now. Instead I can only follow the center of the road line. Following the border-line like in OCAD would be very useful.

**Comment by dg0yt** [comment]
Related to #650

**Comment by mlerjen** [comment]
Thats a nice improvement!

**Comment by dg0yt** [comment]
Note how the feature works:
- It is enabled by the *Shift* key, like following the path object itself.
- It only works with visible border lines, e.g. for the Road symbol.
- If the border line is continuous (or if the main line is invisible), it follows the center of the border line.
- If the border line is dashed, it follows the outline of the main line instead, so that no white gap remains between the dashes.

**Comment by lpechacek** [comment]
Thanks for the explanation, Kai. I first started with a highway symbol, because it's so broad and has three distinct lines, but that attempt failed. Now I can see that the highway is a combination symbol. Oon a normal road, the cursor snaps just fine.

**Comment by dg0yt** [comment]
Yeah, Highway may not work if it is a combined symbol. This will need extra work.
