### ISSUE TITLE
GeoTIFF support

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#284]
**Somebody reported on Sourceforge [[tickets:#284](https://sourceforge.net/p/oorienteering/tickets/284)]:**

I took a geotiff file (extension .tif) I got from the State of Indiana (156MB or so), clipped it using QGIS and created a 3MB tif file. It opens correctly in QGIS.  But neither the original 156MB file or the smaller file works in OOM. When I try to load it as a template, OOM doesn't have the "georeferenced" options lit up. See attached tif image.

**Attachments (on Sourceforge):**
- [nvms.tif](http://sourceforge.net/p/oorienteering/tickets/284/attachment/nvms.tif) (3504224 bytes)

**Comment by Symbian9** [comment]
Any news on GeoTIFF support addding? As it many times requested by users:

- http://www.attackpoint.org/discussionthread.jsp/message_1333242#message1334420
- http://www.attackpoint.org/discussionthread.jsp/message_1339220#message1339250

**Comment by dg0yt** [comment]
I was always happy with `listgeo -tfw` on Linux. But given the simplicity of [what listgeo does](https://github.com/OSGeo/libgeotiff/blob/master/libgeotiff/bin/listgeo.c#L252) on top of libtiff, it could be feasible to add the same on top of GDAL with minimal effort.
