### ISSUE TITLE
keyboard shortcuts for Symbol and Fill tools 

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#294]
**justask4 reported on Sourceforge [[tickets:#294](https://sourceforge.net/p/oorienteering/tickets/294)]:**

Need to set keyboard shortcuts for tools that are used in multiple sequences, namely
Tools > Switch symbol       [S]  and
Tools > Fill/Create border  [F]

Once you have multiple objects and you go through them manually to change their symbols, there is a lot of mouse clicking to do.  One shortcut would eliminate this.

Actually, the File>Setting could allow setting shortcuts for any item on the Menu or Symbol set.

**Comment by mlerjen** [comment]
Must the shortcuts keys be fixed? One might think of a concept where the user can customize them the way it suits him/her best.

**Comment by dg0yt** [comment]
- Having them fixed enforces consistency with documentation.
- Many users would probably never change the defaults.
- Developers will have write (a little bit) more code every time they deal with a keyboard action.

I would be more willing to deal with this if we could re-use some established open source code for it. But I'm unaware of a cross platform solution.

**Comment by florianlang** [comment]
I understand the reasoning for not making the hotkeys customizable, but the placement of some hotkeys is imho quite unfavourable, e.g. when I am editing lines/bezier curves I want to switch between "Edit objects" E to "Edit lines" L regularly. Unfortunately the L is far from my left hand, which needs to be on the left side of the keyboard to operate ctrl, shift, space. The same for the hotkey P for "Draw paths". 

Could the keys be customizable by some hidden config file for power users on their own risk?

Tooltips with the hotkeys would be much appreciated for learning the hotkeys - even though it does not matter so much for myself anymore.
