### ISSUE TITLE
Drawing Impasable wall gives strang look 

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#309]
**@Zerbembasqwibo reported on Sourceforge [[tickets:#309](https://sourceforge.net/p/oorienteering/tickets/309)]:**

I use symbol 521.1.1 in ISSOM .

When drawing a line I see different result when doing 

1) left click on point of start, left click on point of finish, and click enter
2) left click on point of start, right click on point of finish

1) gives a line that is longer than what i clicked. The box marking the object when selected is as big as I expect
2) no problems

1) When I marked the two lines together to take screenshot the misdisplay was gone!

![impass_wall_bug](https://cloud.githubusercontent.com/assets/13567791/9568200/f93dcce2-4f42-11e5-8540-bbc41c772ddd.JPG)

**Comment by dg0yt** [comment]
@Zerbembasqwibo Is this still an issue?

**Comment by Zerbembasqwibo** [comment]
I cannot reproduce it, right click doesn't have the same function today.

Close it.

2018-03-10 6:05 GMT+01:00 Kai Pastor <notifications@github.com>:
