### ISSUE TITLE
Portugese_BR translation

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#317]
**dg0yt reported on Sourceforge [[tickets:#317](https://sourceforge.net/p/oorienteering/tickets/317)]:**

c/o creonte38, see project reviews.

**Comment by francojmf** [comment]
You said: Hello, there is an old ticket for a Portugese translation, but I don't think 
anyone is working on it. However, it would be good to leave a note there 
when you start working on a (variant of) Portugese translation: 
https://github.com/OpenOrienteering/mapper/issues/317

How could I start a Portuguese translate project?

**Comment by dg0yt** [comment]
There is a wiki page about [Translation](https://github.com/OpenOrienteering/mapper/wiki/Translation). It provides a link to the Qt Linguist software which will be needed to properly edit the translation file. The translation file for Portugese (Brazil) probably needs to be named OpenOrienteering_pt_BR.ts.

If you want to see the source code context of strings during translation, you will need to work with a local checkout (a fork of) of our code repository. But it is also possible now to work with the translation file without any context, and create the pull request by uploading the file directly. (I didn't try the latter.)

**Comment by francojmf** [comment]
Good afternoon:
I finished the Portuguese-Br translation. I made some tests in my OOMapper, fixed some words, and now it is working very well. You may put on the site or ask someome to test.
Best regards,Joao Franco

Date: Fri, 18 Mar 2016 22:48:37 -0700

**Comment by francojmf** [comment]
I'm not able to upload files of Portuguese-BR translations. Request for email francojmf@hotmail.com

**Comment by francojmf** [comment]
Terminei minha tradução para Português-BR, mas não estou habilitado a fazer uploads neste fórum. Os interessados em testar podem pedir pelo email francojmf@hotmail.com até que o arquivo traduzido  esteja aprovado e seja disponibilizado com o programa. Ele funciona muito bem, ajude a testar e mande sugestões para melhorar.

**Comment by dg0yt** [comment]
You may attach ZIP files here. However for contributing the new file to Mapper it would be best if you fork the mapper repository, upload (only!) the OpenOrienteering_pt_BR.ts to the translation subdirectory, and create a pull request.

**Comment by dg0yt** [comment]
How about giving it another try? Either on Github, or on [Weblate](https://hosted.weblate.org/projects/openorienteering/mapper/) (after registration with your Github account, and creating pt_BR), or via e-mail to me (then I will commit with your name and e-mail as the author).

**Comment by dg0yt** [comment]
I just saw you did some upload in your fork, but the pull request didn't go to our main repository. I will see if I can handle this.

**Comment by francojmf** [comment]
Yes, I added the file via upload into my fork,  I tried to follow the instructions, but I was not sure about what to do.Then I sent a note to the forum, because I only had access to that part.
Franco
Date: Wed, 20 Jul 2016 10:08:11 -0700

**Comment by dg0yt** [comment]
It is now merged. You can now edit the translation on https://hosted.weblate.org/projects/openorienteering/mapper/pt_BR/. Just register/login with your Github account.
