### ISSUE TITLE
Crash when import map in other scale and rescale it

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#351]
**@Zerbembasqwibo reported on Sourceforge [[tickets:#351](https://sourceforge.net/p/oorienteering/tickets/351)]:**

When importing a file in 1:10 000 to one with 1:15 000 and choosing to rescale it crashed.

If I choose not to rescale it doesn't crash.

**Comment by dg0yt** [comment]
@Zerbembasqwibo Can I close this old bug?

**Comment by Zerbembasqwibo** [comment]
Yes close it, it did not crash now.

2018-03-10 6:03 GMT+01:00 Kai Pastor <notifications@github.com>:
