### ISSUE TITLE
Improved following existing line function.

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#362]
**Somebody reported on Sourceforge [[tickets:#362](https://sourceforge.net/p/oorienteering/tickets/362)]:**

Like in OCAD, the follow existing line feature should be able to follow the border line (casing) of an existing line, not just the centre line.

When I draw sprint maps, I am generally concerned about getting casings on either side of the roads exactly parallel - the maps become much more legible then. I do this by creating a set of helper symbols: line symbols with no fill but with a border line on either side at various distances.   I then use the follow existing line feature to draw individual road casings on either side of the road.

**Comment by jan-gerard** [comment]
I agree. This is something that would at least speed-up drawing that sort of map features, and at best make a neater map.

**Comment by dg0yt** [comment]
Duplicate of #273.
