### ISSUE TITLE
DXF import produces mirrored object

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#413]
**Somebody reported on Sourceforge [[tickets:#413](https://sourceforge.net/p/oorienteering/tickets/413)]:**

Imported dxf-file ends up being rotated 180 degrees or mirror image (not sure which). 

Worked ok when tested with same file in 0.5.3.

**Comment by Zerbembasqwibo** [comment]
Is there some workaround for the mirror thing? It still occurs in 0.6.20161212 Unstable Windows x64.

**Comment by dg0yt** [comment]
This is probably not exactly the same bug which was closed in v0.6.0: In unstable, the GDAL-based DXF import might be enabled by default. You can change this in the settings. This didn't exist in August 2015.
