### ISSUE TITLE
Use GPS location with windows version

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#422]
**Somebody reported on Sourceforge [[tickets:#422](https://sourceforge.net/p/oorienteering/tickets/422)]:**

It would be great to be able to use the geolocation with the windows version, not only the android one. In this way, we users of Windows 8 tablets could use them the same way as android ones.

Ideally, we could choose between built-in location system or an external GPS (connected through bluetooth serial port). Much like OCAD 11 does.

**Comment by dg0yt** [comment]
Tracked upstream at [QTBUG-48082](https://bugreports.qt.io/browse/QTBUG-48082) - see there for API documentation links.

**Comment by dg0yt** [comment]
Qt 5.6 will bring support for reading NMEA GPS data from devices which provide a serial port style interface. We need to see how many other dependencies this adds (QtSerialport at least).

**Comment by Zerbembasqwibo** [comment]
I see that this question is alive, and I also want it to happen.

Is it still in the plan to include live GPS-support for the Windows version? When might it then be possible to find it in some unstable version? Best regards

**Comment by dg0yt** [comment]
Current short term plan is to release Mapper 0.6.2 (important bug fixes) with the Qt version we have (5.5.1). After this, I will try out Qt 5.6.1. This changes a lot for the support of high resolution screens. If it works, we could look into Qt's GPS support on Windows.

**Comment by dg0yt** [comment]
Depends on #673.

**Comment by Zerbembasqwibo** [comment]
A curious question since my mapping season is coming closer: GPS on Windows depends on Qt 5.7, and it was not under consideration at the moment 17 June 2016. And now? It says milestone 0.7.0 but also 0.x.x.

Have anyone found out some workaround to use OOM (maby using i.e. Windroy or something) on W 8.1 with GPS? Where is such question discussed? Am I alone with this interest?

**Comment by dg0yt** [comment]
I took the issue out of 0.7.0 because I didn't find neither enough time nor a proper testing setup. However, if you want to help with testing, we may get started with the unstable build. Limitation: For Windows, only NMEA data from a serial port can be used. If your device doesn't provide this directly, you should find out if there is some kind of adapter tool which can provide such a service.

**Comment by Zerbembasqwibo** [comment]
I have found a program that simulate com-ports, Franson gate, so I guess it
might work. At least I got the live gps into QGIS that way.

I can test when there is something to test.

måndag 15 maj 2017 skrev Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
So take the unstable build for Windows, and test GPS in the "mobile UI" of Mapper by setting two environment variables, for example in a .cmd file put in the Mapper directory:

~~~
set MAPPER_MOBILE_GUI=1
set QT_NMEA_SERIAL_PORT=COM3
.\Mapper.exe
~~~

(You will have to give the correct serial port, of course. This GPS support is completely untested.)

**Comment by Zerbembasqwibo** [comment]
I will test it.

2017-05-16 9:39 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
The positioning feature was disabled even in the unstable builds. New packages available now.

However, I really don't know if it works. At least, I learned that I can use Franson gate to simulate a GPS device on COM port in Windows, so I can work on this as soon as time permits.

**Comment by Zerbembasqwibo** [comment]
I tried both unstable, I got no one to work as expected.

I tried "Virtual COM9", "COM1" and "COM2" as output from Franson, I changed
environmental variables manually 'cause the CMD-file didn't do it (aha,
maybe needed to run as admin I realise now...). Well anyway those two
GPS-buttons were grey. I couldn't verify that Franson was connected because
OOM stole my window with some kind of Fullscreen mode, maknig Franson not
available while running OOM (maybe my lack of knowledge of W8.1, which
indeed is strange).

OOM crashed when closing it too fast. I closed with X right upper corner
twice.

2017-05-17 8:54 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
Confirmed. 

Remarks:
- You get other Windows etc. by pressing the "Windows" key.
- I put my test files in the examples folder.

**Comment by Zerbembasqwibo** [comment]
I also put it there. and no, Window button doesn't give chans to look at Franson, only that "8.1- window", not "old-style-desktop" since that one is filled with the full screen mode of OOM. Maybe I am just old.

Can I test something else?

**Comment by dg0yt** [comment]
I will look into this again soon. I have no idea why it does not work. So I have to trace and debug.

**Comment by hel3** [comment]
I'm also interested in this. Any development the last year?

**Comment by dg0yt** [comment]
Nobody is actively working on it. IIRC I once tested the Franson gate stuff without success, but I couldn't take the time to track down if the trouble was within Mapper or more general.

I guess our current Windows packages don't include the positioning plugins. I can try to change this in order to allow for experimentation.

**Comment by hel3** [comment]
OK. Has anyone tried to use Remix OS on a PC to be able to use the OOM Android app and get i t working that way?

**Comment by dg0yt** [comment]
Please don't discuss Remix OS questions in this issue. Thanks

**Comment by dg0yt** [comment]
Which Windows position interface do you expect to be support nowadays? I never had success with the serial port NMEA part, but I'm studing `System.Device.Location` access via Powershell. This should be possible from Windows 7 up to Windows 10.

**Comment by Zerbembasqwibo** [comment]
Sorry I cannot give input in this question. I can maybe do some testing in Windows 8.1...

**Comment by dg0yt** [comment]
If you get your exact position in the web browser, it will probably also work for Mapper. Otherwise you may need software which cross-links the various providers.

**Comment by dg0yt** [comment]
I would appreciate feedback based on the latest dev pre-release.

**Comment by dg0yt** [comment]
> you may need software which cross-links the various providers.

GPSDirect (https://www.gpssensordrivers.com/) is confirmed to work (forwarding from a GPS Bluetooth receiver to the Windows location service).

**Comment by dg0yt** [comment]
> set QT_NMEA_SERIAL_PORT=COM3
> .\Mapper.exe

This is also confirmed to work, for devices providing NMEA via COM3.

**Comment by lpechacek** [comment]
> This is also confirmed to work, for devices providing NMEA via COM3.

Please note that the COM port number may vary in your setup. Have a look at the below video made by Meowsbox for instructions on how to pair a Bluetooth Serial Port Profile (SPP) enabled receiver (often called "GPS data logger" or "GPS mouse") with your Windows box.

https://youtu.be/5ITtBxsZ-wA?t=14

**Comment by dg0yt** [comment]
The actual port is already meant to be chosen in the settings, not via externally providing `QT_NMEA_SERIAL_PORT`.

**Comment by Jocke-G** [comment]
I dont understand if this is supposed to work or not, but issue is closed and it seems to not work yet.
I have OOM 0.9.5 installed on Windows 10.
I have a NMEA GPS connected to COM4. No bluetooth, just COM port. It did work perfect in OCAD.
I have tried all settings: Standard/Windows/NMEA(qt).
Am I doing wrong, or is this still not working?

**Comment by dg0yt** [comment]
The "Windows" sensor just works when Windows provides an accurate location, usually from internal GPS sensons. This is what I can test.

The Windows "sensor" can be made work with external receivers using bridging software such GPSdirect, as noted a few comments earlier.
