### ISSUE TITLE
App icon needed!

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#43]
**russellporter reported on Sourceforge [[tickets:#43](https://sourceforge.net/p/oorienteering/tickets/43)]:**

Need to find someone good with artwork.. I think something inspired by the default Mac icon might work:

![App icon](http://www.bentleydrummer.nl/software/software/Other%20Software_files/GenericApplicationIcon.png)

The paper could have a little orienteering map made by the app on it.

**Comment by ollesmaps** [comment]
I converted the app / program icon into into an .oom symbol. It does not glitter that much, but still looks quite good. Free to use :)

[OOM_icon.zip](https://github.com/OpenOrienteering/mapper/files/2016481/OOM_icon.zip)
