### ISSUE TITLE
Ubuntu 14.04: No main menu

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#438]
**Somebody reported on Sourceforge [[tickets:#438](https://sourceforge.net/p/oorienteering/tickets/438)]:**

In Ubuntu Gnome Classic (not in Unity), the menus isn't visible.
But the shortcuts are active (like Ctrl + O, or Ctrl + S)...
OpenOrienteering Mapper Version is 0.5.96

Thanks.

![oom-not-menus](https://cloud.githubusercontent.com/assets/13567791/13346642/ecda20ec-dc67-11e5-89cb-f951151500ae.png)

**Comment by kolesar-andras** [comment]
I have switched Ubuntu to Xubuntu by installing xubuntu-desktop. OpenOrienteering Mapper does not have menu, all other apps have. Tried to move the mouse pointer to the window title bar, nothing happened. Can I show menu somehow?

**Comment by kolesar-andras** [comment]
I have removed package `appmenu-qt5` and menu become visible. I hope it will help others, too.

**Comment by dg0yt** [comment]
Yes, that is the answer. We even have an unfinished pull request for the manual on this issue.
I suggest I reopen this issue here and mark it as known issue.

Please add the version of Ubuntu to your comments.

**Comment by kolesar-andras** [comment]
Ubuntu 14.04.4 LTS with xubuntu-desktop. Regular Ubuntu has installed Unity with appmenu packages, that hide local menu in favor of global menu. Later I have switched to Xfce that does not have a global menu but appmenu packages were not removed automatically.

**Comment by dg0yt** [comment]
I found that I had ```appmenu-qt``` installed, but not ```appmenu-qt5```. With ```appmenu-qt5```, the menu is in the global menu bar at the top of the screen with the standard Ubuntu desktop.

The ```appmenu-qt5``` package sets an environment variable named ```QT_QPA_PLATFORMTHEME``` for enabling this "feature". By unsetting the variable, you get a normal menu. 

If no other Ubuntu version is affected, I might add unsetting this variable to the Ubuntu 14.04 package.

**Comment by kolesar-andras** [comment]
First I have removed `appmenu-qt` package but it was not enough, then removed `appmenu-qt5` that solved my problem. This coincides with your observations.

I think it could affect more (even all) Ubuntu versions where global menu is available.

**Comment by dg0yt** [comment]
I rebuilt 0.6.1 and unstable packages with a fix for this issue.
