### ISSUE TITLE
CRT & DXF

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#443]
**Somebody reported on Sourceforge [[tickets:#443](https://sourceforge.net/p/oorienteering/tickets/443)]:**

Would it be possible to import DXF files with CRT as in OCAD?

**Comment by jvtm** [comment]
This would be useful. I have such mapping for free-to-use data from National Land Survey of Finland. Might write a short howto + improve the existing tooling (eg. shp-to-dxf converter, coordinate system stuff, ...) for using that data with OOM. All the related DXF import improvements will help on that.

About the CRT file I have:
- it has two columns, apparently ISOM code and the second value is the DXF code
- some lines are missing the first value: maybe this means "ignore", or maybe it's a mistake in the file
- not sure where I actually got this file, need to figure out...:)

**Comment by dg0yt** [comment]
Note: There is no file-open dialog. Mapper looks for a CRT file with the same base name as the DXF file while doing the import.

**Comment by dg0yt** [comment]
![crt-import](https://cloud.githubusercontent.com/assets/13567791/22399444/02892804-e59d-11e6-8060-1ffb86e8a237.png)

**Comment by Symbian9** [comment]
@dg0yt, is it possible create functionality for use tags info for first column (as on this screenshot) when import DXF/OSM? (without need CRT)

Currently using only Tag Selector method its need much time for converting objects with each tags to needed symbols.

**Comment by dg0yt** [comment]
@Symbian9 It is possible to implement but noone is working on it. And is out-of-scope for this issue here.  Your request seems to belong #606.

**Comment by TerjeWiigMathisen** [comment]
New 1:10K ISOM map
Import rotnes contours, skip CRT mapping the negative contours
Map georeferencing:
    UTM 32 N coordinate, keep geographic coordinates
    Show UTM coordinates in lower right status field
Save as rotnes.omap
Import rotnes vegetation, keep suggest CRT mappings
  -- CRASH --
[OpenOrienteering Mapper 0.6.20170128 has stopped working]

When I then click [Debug] and go into VS2015 I get more detail:
Unhandled exception at 0x000000000052FA31 in Mapper.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

I.e. from the low address this seems like a NULL pointer being passed to a library routine somewhere.

**Comment by TerjeWiigMathisen** [comment]
OK, getting closer possibly:

Opening the attached vegetation file crashes immediately:
[rotnes_vegetation.zip](https://github.com/OpenOrienteering/mapper/files/737472/rotnes_vegetation.zip)

**Comment by dg0yt** [comment]
True. It is trying to render an object which has got a null symbol.

**Comment by dg0yt** [comment]
New unstable binaries are now available.

**Comment by bwa** [comment]
Using windows 0.6.20170130 I was trying to import a DXF with a corresponding CRT file in same directory. But nothing happened. Just 'normal' imports, no popup to map symbols. I also tried Terjes rotnes_vegetation.zip. Here I get a message about an empty folder, nothing to import.

**Comment by dg0yt** [comment]
Maybe you don't have the GDAL/OGR importer enabled in the settings?

**Comment by bwa** [comment]
Correct, I wasn't aware of that. After setting that, it seems to work OK
