### ISSUE TITLE
Unable to load huge image template with 64bit windows install

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#449]
**havatv reported on Sourceforge [[tickets:#449](https://sourceforge.net/p/oorienteering/tickets/449)]:**

Loading a huge (22288x29875) template (JPEG ortho photo) fails with 64bit 0.5.96 on Windows 7 (openorienteering-mapper_0.5.96-Windows-x64-Installer).
The error message is:

```
Cannot open template
<...>.jpg:
Not enough free memory (image size: 22288x29875 pixels)
```

Having 16GB of memory installed, I had expected the image to load.
Loading a 20000x15000 image and several 12000x12000 images works fine, and reported memory usage is still at only 4GB.

**Comment by dominikzalewski** [comment]
This happens on Android tablets as well and for much smaller templates. It would be great if you could fix that as well. By fix I mean that the application does not crash, but recovers and simply gives a message to the user that the template is too big for existing memory in the system.

**Comment by dg0yt** [comment]
@dominikzalewski: Your comment is unrelated to Windows where the crash from the OP is already fixed. Open a separate issue.

**Comment by dominikzalewski** [comment]
Separate issue opened: https://github.com/OpenOrienteering/mapper/issues/598

**Comment by dg0yt** [comment]
Maybe better with GDAL raster import, #864.

**Comment by dg0yt** [comment]
Actually, it is the QImage class which has a 2 GB limitation, even in 64bit builds. It won't be fixed before Qt 5.10: [QTBUG-50912](https://bugreports.qt.io/browse/QTBUG-50912).

**Comment by dg0yt** [comment]
@havatv Huge images should work in the recent `dev` snapshots (based on Qt 5.12), if there is enough RAM.

**Comment by havatv** [comment]
Sounds good!  Thanks for following up.
