### ISSUE TITLE
Manual: Wrong shortcut keys for windows

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#458]
**Somebody reported on Sourceforge [[tickets:#458](https://sourceforge.net/p/oorienteering/tickets/458)]:**

The shortcut keys for opening and closing the Symbol, Color and Template setup windows do not work for me. Ctrl+Shift+7-9 or in the documentation it says Ctrl+Shift+F7-F9 but neither works. I am using Linux Mint 13 MATE 32-bit.

**Comment by Abbe98** [comment]
Is this issue just something that differs from the manual?

**Comment by dg0yt** [comment]
The manual is wrong here, that's why the issue is still open. Well, the manual update is scheduled for 0.6.0... (#347).

OS X would probably need a variation, too, but I haven't thought yet about how to do this in the manual. It should be doable by some kind of doxygen macro. (In the program, we run the modifier keys through `QKeySequence::toString()` before displaying them in the status bar.)

**Comment by Abbe98** [comment]
Where is the manual located? It should be easy for any contributor to
update.

Is it inline somewhere? Think I saw it as HTML in some other project...?

**Comment by dg0yt** [comment]
Its somewhere in https://github.com/OpenOrienteering/mapper/tree/master/doc/manual/docs.

**Comment by dg0yt** [comment]
Fixed in  8342eaf.
