### ISSUE TITLE
Export image with worldfile

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#463]
**Somebody reported on Sourceforge [[tickets:#463](https://sourceforge.net/p/oorienteering/tickets/463)]:**

It would be very useful to be able to export raster images with georeferencing information. A checkbox in the image export-dialog such as 'include worldfile' would be a nice way to do it.

**Comment by oskarlin** [comment]
The relatively new website Livelox.com for GPS-tracks uses images with world files so this feature would probably bli much appreciated by all the swedish users/mappers!

**Comment by mpickering** [comment]
I am interested to implement this feature. 

It seems like it would be quite straightforward? Could someone give me some direction about where the correct places in the code to modify are and any potential pitfalls I should look out for?

**Comment by dg0yt** [comment]
It should be straightforward indeed. The key function is MapWidget::exportToImage:

https://github.com/OpenOrienteering/mapper/blob/daa52dd8ba71f5b38453274ea03a0d2500ec6d4f/src/gui/print_widget.cpp#L1150

You will need to access the map's georeferencing for converting the print area's corner to (projected) real word coordinates, and also for rotation. Beware of the flipped sign of the Mapper's coordinates.

There is also a small class `WorldFile` which is used for template loading. As you can see there, world file parameters are equivalent to certain parameters in a `QTransform`:
https://github.com/OpenOrienteering/mapper/blob/daa52dd8ba71f5b38453274ea03a0d2500ec6d4f/src/templates/world_file.cpp#L67-L71

And there is even a little bit of test code related to world files for templates:
https://github.com/OpenOrienteering/mapper/blob/daa52dd8ba71f5b38453274ea03a0d2500ec6d4f/test/template_t.cpp#L65-L74

**Comment by mpickering** [comment]
Thanks Kai, I have got this working roughly. 

I'm encountering two problems which I will note here for myself.

1. The world file points to the georeferenced point in the image rather than the top left.
2. The scale is completely wrong, roughly 2-3x bigger than it should be. 

My branch is here, https://github.com/mpickering/mapper/tree/wld-file

**Comment by mpickering** [comment]
I fixed (1) but the scaling and rotation is still wrong.

**Comment by dg0yt** [comment]
If you create a pull request (PR), I could review/comment more easily and even add commits. You could still update the PR by just pushing to your branch.

Maybe you can even squash the commits? At least I wouldn't merge without editing. If you are new to git and need more help, let me know.

Normally I would ask to develop new features against dev branch (v0.9 ATM). But given that this is small and straightforward change, I'm fine with adding it to master (v0.8.1 ATM).

**Comment by lpechacek** [comment]
> The scale is completely wrong, roughly 100x bigger than it should be.

After quick glance at your code changes, my first thought was that scale depends on DPI setting, provided by the user in export dialog.

**Comment by mpickering** [comment]
I have fixed the scaling problem now as well. 

I'll squash everything and make a PR tonight once I have cleaned the code up. I didn't realise that there was a 0.9 branch, I'll make sure to rebase onto that before making the PR.

Thanks for your help so far!
