### ISSUE TITLE
Error while loading an object

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#507]
**Somebody reported on Sourceforge [[tickets:#507](https://sourceforge.net/p/oorienteering/tickets/507)]:**

Can not open an exiting file dialog says
"Error while loading an object of type 1 at 1:8388606: Could not parse the data.

**Comment by Tiekku** [comment]
I got same error.  Now the Map is corrupted, how to rescue it? The map has been edited with MAC, Windows and Android.  The location of file is in network-drive and it includes about 30 MB-image.

The file size is more than 10MB --> I can't load it with this comment. Also earlier map is available, I can send those if needed.

**Comment by dg0yt** [comment]
Note that I never got more information from the original report.

What do you mean by the "same error"? Do you literally receive "Error while loading an object of type 1 at 1:8388606: Could not parse the data."?

You could put the file in a "secret" Github Gist and send me the URL via personal e-mail.
