### ISSUE TITLE
Too easy to move symbols in symbol window

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#510]
**Somebody reported on Sourceforge [[tickets:#510](https://sourceforge.net/p/oorienteering/tickets/510)]:**

It gets messy in my symbol window, it's so easy to accidently move the symbols when being too quick to click on them and moving mouse at same time. 

It's so seldom you want to move them within that window, would be better to have move "hidden" under right click menu.

//Zerbembasqwibo

**Comment by gandym** [comment]
I too would like to see this changed:
http://sourceforge.net/p/oorienteering/tickets/352

gandym

**Comment by dg0yt** [comment]
So this is a duplicate of #352.
