### ISSUE TITLE
Crash while following another symbol

### ISSUE THREAD

**Issue by xc-racer99** [OpenOrienteering/mapper#525]
In unstable builds (both from the openSUSE build service and my own) Mapper crashes when following the edge of another symbol.  Doesn't matter whether these are line or area symbols.  Isn't always instantaneous and happens on all map files.

Doing a git bisect, it appears to have been introduced in 200e3e93fd2ef454cf9ca98159fa82f730266191

Command line output on openSUSE unstable:
'Segmentation fault'

During the git-bisect, I also got the output:

'ASSERT: "last_index < coords.size()" in file /home/user/oomapper/mapper/src/core/virtual_path.cpp, line 329
Aborted'

and

'ASSERT: "base_index >= first_index" in file /home/user/oomapper/mapper/src/core/virtual_path.cpp, line 435
Aborted'

Running Debian Jessie with QT 5.3.2

**Comment by dl3sdo** [comment]
When doing the operation you described I also got crashes at various locations:
ASSERT: "false" in file ../../oorienteering-code/src/object.cpp, line 1072
(when following straight lines)
ASSERT: "pos < part->last_index" in file ../../oorienteering-code/src/object.cpp, line 2920
(when following curves)

**Comment by dg0yt** [comment]
This is probably one of the few left follow-ups from that particular change. Thanks for reporting.
