### ISSUE TITLE
Crash at ocd Import

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#533]
Mapper crashes when importing a special ocd file (all other ocd files work well):
ASSERT: "part_start == 0 || !flags[part_start].isHolePoint()" in file ../../oorienteering-code/src/core/virtual_path.cpp, line 87

Tested with latest Mapper version and QT 5.5.1

**Comment by dg0yt** [comment]
An assert is not really a crash but indicates a broken contract. Asserts are not in release builds but the broken contract may lead to other errors (real crashes) there. The test file has an area object with a hole which consists of a single point. This doesn't make sense.
