### ISSUE TITLE
Crash when aborting print operation

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#538]
With latest x64 build (unstable-0.5.20151104-x64) on Win7 Mapper crashes when doing the following:
- open a map
- enter Print dialog
- Microsoft XPS Document Writer is selected as printer
- Press Print Button
- When the file dialog for the storing the .xps file shows up press the Abbrechen (Cancel) button
=> Mapper crashes
I'll test whether this happens also for other printers (which are not installed on this computer).

**Comment by dl3sdo** [comment]
It happens when the print operation fails or is cancelled, because either:
- the save dialog is aborted
- a generic printer dialog (HP) shows up that can be cancelled
- the printer driver exits with an error

**Comment by dg0yt** [comment]
https://bugreports.qt.io/browse/QTBUG-48203. (Affects Qt Assistant, too.) Fixed after Qt 5.5.1. We need to merge this in our mingw Qt 5.5.1 packages on OBS, or switch to pre-release 5.6.
