### ISSUE TITLE
EPSG 5514 is broken

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#542]
Most used coordinate system for Czech and Slovak Republic in GIS and cartographic applications is missing in OO Mapper EPSG database. Please add EPSG 5514: S-JTSK (Greenwich) / Krovak East North. Definition is bellow, thank you.

~~~
+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=542.5,89.2,456.9,5.517,2.275,5.516,6.96 +pm=greenwich +units=m +no_defs
~~~

**Comment by dg0yt** [comment]
We use the [EPSG list from the Proj.4 library](https://github.com/OSGeo/proj.4/blob/master/nad/epsg#L5497). It has its own bug report for EPSG 5514 here: OSGeo/proj.4#233. Summary:
 - version 4.8.0: EPSG 5514 undefined
 - version 4.9.2: EPSG 5514 defined equally to 5513, possibly wrong, and different from yours in +towgs84 and +pm:
~~~
+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs 
~~~
We now have 4.9.2 for Windows, OS X and Android, but [some Linux distribution lag behind](https://github.com/OpenOrienteering/mapper/wiki/Target-systems#component-version-matrix).

**Comment by dg0yt** [comment]
Note: If you give some reference points in WGS84 and Czech EPSG 5514, I can add it to the test code.

**Comment by krticka** [comment]
I updated bug report at Proj.4 library: https://github.com/OSGeo/proj.4/issues/233

**Comment by dg0yt** [comment]
I'm going to use these two test points:

	// Selected from http://geoportal.cuzk.cz/geoprohlizec/?lng=EN, source Bodová pole, layer Bod ZPBP určený v ETRS
	// http://dataz.cuzk.cz/gu.php?1=25&2=08&3=024&4=a&stamp=7oexTQLNPE8ri5SXY04ARS7vIMnJu3N2
	QTest::newRow("ČÚZK Dolní Temenice EPSG 5514") << epsg5514   << -563714.79 << -1076943.54 << degFromDMS(49, 58, 37.5577) << degFromDMS(16, 57, 35.5493);
	// http://dataz.cuzk.cz/gu.php?1=11&2=01&3=034&4=a&stamp=jFLV7GCCmybIhb9A8mQA598C7UgjsxhZ
	QTest::newRow("ČÚZK Stará Role EPSG 5514")     << epsg5514   << -852886.39 << -1008120.76 << 50.2523994861 << 12.8252755861;

Doufam ze to je v poradku...

**Comment by dg0yt** [comment]
@krticka Did the fix work for you?

**Comment by lpechacek** [comment]
I worked with two maps in S-JTSK / Krovak East North reference system, diligently checked a few coordinates on them and all was fine.

These are the CRS parameters in one of them:
`<georeferencing scale="10000" declination="3.87" grivation="11.47"><projected_crs id="EPSG"><spec language="PROJ.4">+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=542.5,89.2,456.9,5.517,2.275,5.516,6.96 +pm=greenwich +units=m +no_defs</spec><parameter>5514</parameter><ref_point x="-723120.805826" y="-1063311.059815"/></projected_crs><geographic_crs id="Geographic coordinates"><spec language="PROJ.4">+proj=latlong +datum=WGS84</spec><ref_point_deg lat="49.93038066" lon="14.73148234"/></geographic_crs></georeferencing>`

Just my two cents.

**Comment by dg0yt** [comment]
Mapper is still overriding the `+towgs84` parameter for EPSG 5514. PROJ.4 continues to have
[the same definitions for 5513 and 5514](https://github.com/OSGeo/proj.4/blob/7d0f1db924210fc69ba0408cb562de47b243d831/nad/epsg#L5572-L5575), despite the closing of OSGeo/proj.4#233. 

Someone with more expertise should clarify if PROJ.4 needs an updated definition, or if we should drop our (working!) override.

**Comment by krticka** [comment]
I will try to discuss it again. 
5513 is not relevant for us as this is special case. 
The true is, that there are several transformation keys available. The one which is now using Mapper is not the official transformation key used by State Administration of Land Surveying and Cadastre for area of Czechia (+towgs84=570.8,85.7,462.8,4.998,1.587,5.261,3.56) but alternative transformation key which is suitable for whole territory of Czechia and Slovakia. This is not problem as the maximum difference in position deviation is < 1 m between these two transformation keys. Proj4 now contains transformation key +towgs84=589,76,480,0,0,0,0 and I will try to find what are the position deviations.
More about S-JTSK (in Czech) at [http://freegis.fsv.cvut.cz/gwiki/S-JTSK](url)

**Comment by krticka** [comment]
OK, some notes for +towgs84=589,76,480,0,0,0,0.
It should be old U.S. NIMA transformation key from 1993 with average accuracy 6 m. [http://georepository.com/transformation_15965/S-JTSK-to-WGS-84-3.html](url) 
Test on 26 CZEPOS permanent stations shoved maximum position deviation 13.6 m and median deviation 7.6 m. [http://freegis.fsv.cvut.cz/gwiki/S-JTSK_/_%C4%8Ceskoslovensk%C3%BD_transforma%C4%8Dn%C3%AD_kl%C3%AD%C4%8D](url)
This means that this transformation key is obsolete and inadequate in terms of current precision requirements.
