### ISSUE TITLE
Can't get this program to work at all.

### ISSUE THREAD

**Issue by srocdocs** [OpenOrienteering/mapper#546]
I installed the windows 64 bit version. Started it up and clicked on "help files" - program froze. So I closed it and tried opening an OCAD file. Program froze again. Not having a lot of luck here.

**Comment by dg0yt** [comment]
I cannot reproduce freezes with the Mapper 0.5.97 64 bit Installer, neither when clicking on "Help" in the "home screen", nor when choosing Help > Open Manual from the menu, nor when opening an OCD file.

Which version are of Mapper are you referring to? Which download did you use? Can you create a new map, or open one of the included examples?

**Comment by srocdocs** [comment]
I have had a bit more luck this evening. I have now found some exiting 
OCAD maps which will open ok. I still can not access any help 
information, the program always just freezes when I do that.

**Comment by dg0yt** [comment]
Please keep reporting your findings. And don't forget to answer my questions.

Q: The manual is displayed by a separate program, assistant.exe. Can you start it directly directly from the program's directory?

I wonder if anti-virus software could play a role here, or if your computer's PATH contains incompatible versions of some libraries. (Version 0.5.96 was packaged in a different way, if you want to try that one.)

**Comment by dl3sdo** [comment]
Like Kai, I cannot reproduce any freezes with the Mapper 0.5.97 64 bit Installer on Win7.
Which OS are you using?

**Comment by srocdocs** [comment]
I have tried running assistant.exe and it does nothing. I found in 
taskmanager that I have several instances of it, and they can not be 
killed either! They do not appear to have got very far. 0 I/O listed.

Alex

**Comment by srocdocs** [comment]
64 bit windows 7 professional

**Comment by dg0yt** [comment]
Any news for 0.6.0, 0.6.1? Otherwise I will close the ticket.

**Comment by dg0yt** [comment]
No response, closing.
