### ISSUE TITLE
Crash when pushing backspace

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#548]
Using 0.5.97 on Windows Vista (!).

Drawing sandy area in sprint map, one start point, and by mistake I made a curved line to the second point. Wanted to delete the last point as usual by pushing backspace, program crashed.

Can be repeated. 

In 0.5.96 this does not cause the program to crash.

**Comment by krticka** [comment]
I can confirm (win8.1, x64). Crashes when you want to go back from 2nd point to start point.
