### ISSUE TITLE
Deleting a line may delete all selected objects

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#550]
If a line and other objects are selected and the ctrl button is pressed to delete points within that line, then deleting the second to last point will not just delete the remaining last segment of the line and thus the line, but all selected objects as well.

**Comment by dg0yt** [comment]
Cannot reproduce. Test file, please.

**Comment by dl3sdo** [comment]
Tested with x32 and x64 versions of Mapper 0.5.97. Happens also with 0.5.96.
[Uploading DeleteAll.zip…]()

Select all objects and then delete one of the two remaining line points of the motorway by pressing Ctrl and clicking on the point -> all objects will be deleted.
