### ISSUE TITLE
Adjust border behaviour (clipping) for area symbols of point objects

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#555]
According to the new ISOM201X there are some new area symbols built up from point objects, for example 209 Dense boulderfield according to 

http://www.orientering.no/media/filer_public/d9/f6/d9f61f1d-62b8-498d-9033-b4c9a4d2415f/isom201x_symbols_201512.pdf

When you create such symbol and use it point symbols will be cut at the border of the drawn area. Let there be a possibilty to choose whether the point symbol at the border will be 
1) cut (as now) 
2) complete if any part is outside the border
3) only the objects that are completely inside the area will be drawn

![skarmklipp](https://cloud.githubusercontent.com/assets/16168975/11776830/7b30c2cc-a24a-11e5-9b03-28de5197c26d.JPG)

**Comment by dg0yt** [comment]
So far we don't have randomly distributed patterns. In order to maintain stability of the individual positions, we should only to deal with the border when the area is created ("filled") or changed. A relaxed variant of 3 should be good solution.

Do you want to discuss this also for non-random patterns (412 Orchard, 413 Vineyard etc.)?

**Comment by Zerbembasqwibo** [comment]
(First, I dislike "semirandom" patterns. Will look ugly if big and will give problem when some objects will be covered.)

As to your question, I think no. For all those metioned patterns (412, 413, semi/open with white/green dots, marshes etc) I think it's OK if they are cut since they are not made from "objects", they are just a pattern. 

Boulder fields are made from several point objects, also written it the norm (same with stony ground symbols) therefore these kind of patterns need another way of behaviour. 

The boulder field's minimum area is defined as "a minimum of two triangles" and stony ground of three, but the other area symbols are limited by area size.

There is actually one area symbol that is somewhere in between, if you read ISOM201X, it's the 310 Indistinct marsh. Look at the way the example is drawn, made from four lines and no cutted lines. It mau be a mistake, but maybe that symbol should be added to the stony symbols if not.

**Comment by dg0yt** [comment]
Duplicated in #863, and implemented in v0.8.0.
