### ISSUE TITLE
Ubuntu 14.04: there is no main menu

### ISSUE THREAD

**Issue by sembruk** [OpenOrienteering/mapper#556]
There is no main menu in Ubuntu 14.04 (as with Mapper 0.5.96).
Tested with openorienteering-mapper-prerelease deb package and the own build from the source (Qt 5.2.1).

In Windows 7 it's OK.

**Comment by dg0yt** [comment]
Sorry, this is the result of a Ubuntu "feature" called "global menu". I'm tired of explaining that...

**Comment by dg0yt** [comment]
Cf. #438.
