### ISSUE TITLE
Strange behaviour drawing bezier

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#558]
![bug](https://cloud.githubusercontent.com/assets/15611653/11915325/a6742810-a6a1-11e5-816e-f9dc4b10f948.jpg)
With the 0.5.97  desktop version, while drawing bezier-curves I sometimes have these "jumps" where the opposite handle than the one I am just about to draw suddenly gets v(10*e)ry long. See screenshot.

**Comment by dg0yt** [comment]
I need more information...

 - [ ] steps how to reproduce this behaviors?
 - [ ] a sample map file with some markers?
 - [ ] which operating system?
 - [ ] touch screen?

**Comment by mlerjen** [comment]
1) I can not reproduce it, but it happens regularly while drawing lines.
2) Sample by mail to dg0yt
3) Windows 7 Pro
4) No. Desktop.

**Comment by mlerjen** [comment]
I am now able to reproduce it:
1) I start drawing a line with the bezier tool (start point)
2) When drawing the second point, I drag out the handle first, but  I do not release the left mouse button but move the mouse tip back right over the place I started drawing the second point. Here the jump happens.
3) It is only at drawing of the second point of a curve this happens.

**Comment by dg0yt** [comment]
Thanks for the file and the steps. I can reproduce the issue in 0.5.97, but it seems to be already fixed or mitigated by a later change (14d7daa5e4b05d8362e9ba42bc84004eca38eb11). Can you check if this happens with "unstable" build? I cannot reproduce the behaviour described in the original post there.

The test file uncovers at least one more rough edge in my development builds. It is good to know this doesn't affect the release builds :-)

**Comment by dg0yt** [comment]
I guess the reported bug resulted in a line with bogus (out-of-bounds) coordinates/dimensions in the test file. This could explain follow-up problems such as printing difficulties and the stop (failed assertion) in the development build. 

While we do have code for handling maps which were originally drawn outside the printable range, this case ist different: I don't think we will ever support printing maps larger than 1000 m... 

Dropping objects with width or height larger than 1000 m (on paper) seems to be the only reasonable approach.

**Comment by mlerjen** [comment]
Thank you. Where can I get the "unstable" build? :-/

**Comment by dg0yt** [comment]
The blog post on the unstable builds is a little bit older, but the unstable builds are triggered whenever I push changes to GitHub:
http://download.opensuse.org/repositories/home:/dg0yt/Windows/

**Comment by mlerjen** [comment]
Yes. I cannot reproduce the error with the 20151216 build.

**Comment by dg0yt** [comment]
"Show whole map" suffered from the irregular coordinates, too. We now drop objects which have either first or last coordinate out-of-bounds.
