### ISSUE TITLE
Adding a set of training course symbols

### ISSUE THREAD

**Issue by Abbe98** [OpenOrienteering/mapper#567]
:santa: :christmas_tree: :gift: 
![screenshot](https://cloud.githubusercontent.com/assets/2631719/11987788/c4151220-a9e5-11e5-90f8-fb1f605e867f.png)

I think that adding a symbol set with useful training course symbols could help people to get started with using Mapper for course setting. Mapper is actually much better then Purple Pen(for example) for course setting and once you got the symbols it's easy to get started.

I propose such a set get bundled with Mapper. I could make a Pull request for review(as I have such a set).

If its gets added should it go into the symbol sets folder? The alternative is the example folder, buts that's even more wrong.

Note that this isn't about ISOM symbols only.

**Comment by dg0yt** [comment]
Course setting is aweak point in Mapper, unfortunately. If you want to contribute another symbol set, it must be put in the symbol sets/src folder, with a .xmap extension. The distribution files (compact .omap, different scales) are generated by test/symbolset_t.

For a quick start, you may copy and paste the existing course setting symbols into an empty map.

There is a fork (https://github.com/aivarszo/mapper) which adds more course setting features to the code. I might add a build for it to build.opensuse.org.

**Comment by Abbe98** [comment]
#568
