### ISSUE TITLE
Android: Georeference with EPSG Code

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#572]
On Android, while a map is georeferenced by EPSG Code the GPS functionality is not available/grayed out. 

[georeferenced by .proj4 code works as ever]

In my example it is 
+init=epsg:3006
vs.
+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs

**Comment by dg0yt** [comment]
I'm not convinced that there this a general issue with EPSG on Android. 
 - The `epsg` file is in the APKs (`/assets/proj/`), and it has an <3006> entry.
 - On my Android device, Mapper 0.6.0 opens the test map I got from you for #558 (EPSG 3043), and GPS is available for this map. 
 - GPS is available with this file when I manually modify the EPSG code to 3006.

On the other hand if the EPSG code is unknown (e.g. 1000), there is NO warning, and GPS is not available, just as reported.

**Comment by mlerjen** [comment]
Ouch. Now it works.

-> What I did now was uninstall and reinstall.
-> I did not uninstall 0.5.97 properly before
