### ISSUE TITLE
Build and use GDAL for extended vector file format support

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#574]
[GDAL](http://www.gdal.org/) opens access to a variety of raster and vector geospatial data formats. The head of development is version 2.0, but most Linux distributions still are on 1.11 (or even 1.10). The use of GDAL should be optional during the build.
- [x] Document available versions of GDAL for all [target systems](https://github.com/OpenOrienteering/mapper/wiki/Target-systems)
- [X] Build GDAL 2.0 as 3rd-party component (for development and packaging)
  - [X] Linux
  - [X] OS X
  - [X] Android
- [X] Build GDAL on openSUSE build service (for packaging)
  - [X] [Windows](https://build.opensuse.org/project/show/home:dg0yt:3rd-party:gdal-2) (2.0.1)
  - [X] Linux packages provided by the distributions, but not available on OBS:
       Rebuild with reduced dependencies (not for redistribution)
- [X] Implement a FileFormat class for _vector_ formats based on OGR
- [X] Implement a Template class for _vector_ formats based on OGR
- [X] Provide GDAL configuration and information

This feature will be required or beneficial for the following issues:
- #138 KMZ export
- #144 Track template import
- #171 Shape files
- #228 PDF as template
- #276 SVG import
- [DXF-related issues](https://github.com/OpenOrienteering/mapper/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dxf)
- #601 GPX/KML export

**Comment by dg0yt** [comment]
For now, use GDAL 1.11. No success yet with building GDAL 2.0 for Android, and too much work for all those Linux distributions.

First promising experiments with DXF import via GDAL/OGR.

**Comment by dg0yt** [comment]
Building GDAL 2.0.1 for Android succeeds with standalone toolchain only, and some minimal patches. Coming GDAL 2.1.0 might work without patches. However, the resulting libgdal.so is ~10 MB, plus data. Getting rid of unneccessary OGR formats seems to need patching.

**Comment by Symbian9** [comment]
Give a list of needed packages to run unstable builds on Ubuntu Trusty 14.04

**Comment by dg0yt** [comment]
The .deb packages carry that information... but since you ask:
~~~
$ dpkg-query -s openorienteering-mapper-unstable
Package: openorienteering-mapper-unstable
[...]
Version: 0.6.20160222
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libgdal1h (>= 1.10.1), libpolyclipping16, libproj0 (>= 4.8.0-1), libqt5core5a (>= 5.2.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libstdc++6 (>= 4.1.1), qtbase-abi-5-2-1, zlib1g (>= 1:1.1.4)
Pre-Depends: dpkg (>= 1.15.6~)
Recommends: qttools5-dev-tools, qttranslations5-l10n, qt5-image-formats-plugins
[...]

**Comment by dg0yt** [comment]
Or look here: https://build.opensuse.org/package/binary/home:dg0yt/openorienteering-mapper-unstable?arch=x86_64&filename=openorienteering-mapper-unstable_0.6.20160319-205.1_amd64.deb&repository=xUbuntu_14.04

**Comment by kjetilk** [comment]
Could this possibly also enable users to keep their maps in a PostGIS database? I don't have any concrete use for it, but it would be kinda neat if it could... :-)

**Comment by dg0yt** [comment]
Keeping (i.e. editing) map data in PostGIS is a different story. This would mean implementing writing to GDAL (or directly PostGIS). It might not be too difficult for typical map objects and some parts of the symbols, but getting read access right is of much more importance. There is little (or no) feedback on the GDAL features in the unstable builds.

**Comment by dg0yt** [comment]
Considered done for 0.7.0, even if there is a lot of opportunities (read: work) left.

**Comment by legrostdg** [comment]
Now I can't wait to see #864 fixed :-). Thanks a lot for this continuous effort!
