### ISSUE TITLE
Track recording when screen is turned off

### ISSUE THREAD

**Issue by rugk** [OpenOrienteering/mapper#576]
[In your doc](https://github.com/OpenOrienteering/mapper-manual/blob/gh-pages/pages/android-app.md#the-mobile-map-editor) (part 3) you say:

> Note that track recording is interrupted while the screen is off or the app is in the background to save battery. If you want to record a track, you need to keep the app active.

However as far as I remember the app also recorded when the screen is off (which also makes sense IMO).
And if this is not true then I would recommend to add this feature.

**Comment by dg0yt** [comment]
Maybe you test and report the current state?

Note that "screen off" is different from "in the background". The app will be in the background when another app is active. It will need a different approach to make recordings while the app is in the background (i.e. stopped).

**Comment by rugk** [comment]
If it is stopped (swiped out of the "recent apps" list) you can of course not track. But if you leave the app in the foreground and just turn the device off it works AFAIK. So maybe the documentation is wrong here.

**Comment by yevhenmazur** [comment]
I've changed my work device to Mi 9 powered by Android Pie (MIUI 10.2) with internal dual-band GNSS receiver. In this setup track is recorded only when the screen is on. Unfortunately this behavior makes the dual-band GNSS receiver almost useless. Looking for a solution or workaround, I found a [similar issue with Osmand](https://github.com/osmandapp/Osmand/issues/5587) (resolved). I would be very grateful if track recording when the screen is off will be possible on new devices with internal GNSS reciver.

**Comment by dg0yt** [comment]
@yevhenmazur Thanks for pointing this out.  Which OOMapper version were you refering to?
FTR I would like to add the link to https://github.com/osmandapp/Osmand/issues/5632.

**Comment by yevhenmazur** [comment]
Tested on OOMapper 0.8.4 and dev-20190609.3
Tomorrow I going to test it with external Bluetooth GNSS receiver.

**Comment by dg0yt** [comment]
dev-20190609.3 has target API level 28 so it will probably significantly increase our "obligations" on newer devices. This could be hard to solve. (We can move GPX tracking to a service, but I'm more concerned about the app being killed while you are taking photos.) At least, I do have an 8.1 test device.

**Comment by dg0yt** [comment]
Android 9 (API level 28) uses a rigid [power management](API level 28). With a foreground service, an app is considered to be in the *active bucket*.

In Android 8 (API level 26), [background apps receive location updates less frequently](https://developer.android.com/about/versions/oreo/android-8.0-changes), [only a few times each hour](https://developer.android.com/about/versions/oreo/background-location-limits.html). With a foreground service, an app is considered to be in the foreground.

Android 6 (API level 23) introduced [Doze and App Standby modes](https://developer.android.com/training/monitoring-device-state/doze-standby.html) which are activated (in some situations) when the screen is turned off. Again, a foreground service would be taken into consideration by Android when deciding if an app is idle. In addition, there is a configurable whitelist for apps which are allowed to ignore Android's battery optimizations.

**So for Android 6 and later, you may already test if disabling Android's battery optimization for OpenOrienteering Mapper mitigates the issue. Just go to: 
Settings > Battery > Battery Optimization.**

TODO:
- [ ] Add a foreground service
- [ ] Guide the user to the battery optimization setting.

This deserves extra attention with regard to Google Play policies.

**Comment by yevhenmazur** [comment]
I did not notice the difference with the battery optimization turned off. This was one of the first things I did to find a solution or workaround.

**Comment by dg0yt** [comment]
@yevhenmazur Thanks for reporting. Sorry that this didn't help. I'll try to add the foreground service soon.

**Comment by ollesmaps** [comment]
I have Samsung Galaxy Tab Active 2 (Android 8.1.0) for a month now. And it originaly also stopped recording when screen went asleep (Mapper 0.8.4). I did some adjustments and it now works also in the sleep mode. I assume the trick was. Screen lock type. None.
I also switched off: Floating icon. Pointer.

**Comment by lpechacek** [comment]
> Android 9 (API level 28)

FWIW, I can help with testing as I have a Google smartphone with said Android version.

**Comment by ollesmaps** [comment]
My assumptions were wrong. The real culprit, at least for me, seems to be internal x external GNSS receiver. If external OK.  If internal bad - measurement each cca 10 minutes (will inspect gpx later).
Will try the Battery Optimization.

**Comment by yevhenmazur** [comment]
Happy to inform you that I've found a workaround by using this app - [ActiveGPS](https://play.google.com/store/apps/details?id=tisinadev.activegps&hl=en). To make it workable you should disable power saving for ActiveGPS.

**Comment by yevhenmazur** [comment]
Where can I get new apk for testing?

**Comment by dg0yt** [comment]
I will create a new unstable release APK when #1296 is merged.

**Comment by dg0yt** [comment]
> Guide the user to the battery optimization setting.

The app may even ask to ignore battery optimizations:  
https://developer.android.com/reference/android/provider/Settings.html#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS  
https://stackoverflow.com/questions/39256501/check-if-battery-optimization-is-enabled-or-not-for-an-app
