### ISSUE TITLE
Incorrect shape when using "Cut away from area" tool 

### ISSUE THREAD

**Issue by wanacode** [OpenOrienteering/mapper#577]
I am noticing when I cut away shapes sometimes the result is not correct and there is a strange angle like in the example below.

![image](https://cloud.githubusercontent.com/assets/2317149/12069793/b2952e18-b0b1-11e5-8d66-13d3fd40351d.png)

The problem only occurs sometimes and I'm not sure what situations is causing it. In this example omap file it is occurring every time though, when I try to cut the open land away from the green. The result is the above image. 

[example.omap.zip](https://github.com/OpenOrienteering/mapper/files/75859/example.omap.zip)

**Comment by dg0yt** [comment]
Happy new year! The fix is available in the unstable builds now. Thanks for reporting, the test file was a good help to track down the issue.

**Comment by wanacode** [comment]
Great. Thanks very much!
