### ISSUE TITLE
cmake fails to find Clipper on second run

### ISSUE THREAD

**Issue by gaudenz** [OpenOrienteering/mapper#579]
I'm trying to create a Debian package for openorienteering-mapper to include into the official Debian repositories. The Debian tools (debhelper) create a build directory obj-x86_64-linux-gnu and call cmake with the following command to configure the build:

```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=x86_64-linux-gnu -DMapper_BUILD_QT=OFF -DMapper_BUILD_CLIPPER=OFF -DMapper_BUILD_PROJ=OFF -DMapper_BUILD_PACKAGE=OFF -DMapper_AUTORUN_UNIT_TESTS=OFF -DMapper_AUTORUN_SYSTEM_TESTS=OFF
```

This works fine the first time, but if the command is rerun with CMakeCache.txt already present it fails to find the Clipper library. This is the error message shown:
```
CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Clipper (missing: POLYCLIPPING_LIBDIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindClipper.cmake:32 (find_package_handle_standard_args)
  CMakeLists.txt:195 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/openorienteering-mapper-DqeW19/openorienteering-mapper-0.6.0/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
```

The log does not contain any hints.

I'm running into this problem because after the successful build the "make install" command reruns cmake and fails:
```
make -j1 install DESTDIR=/build/openorienteering-mapper-DqeW19/openorienteering-mapper-0.6.0/debian/openorienteering-mapper AM_UPDATE_INFO_DIR=no
make[2]: Entering directory '/build/openorienteering-mapper-DqeW19/openorienteering-mapper-0.6.0/obj-x86_64-linux-gnu'
/usr/bin/cmake -H/build/openorienteering-mapper-DqeW19/openorienteering-mapper-0.6.0 -B/build/openorienteering-mapper-DqeW19/openorienteering-mapper-0.6.0/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
```

My best guess until now is that the logic in cmake/FindClipper.cmake is somehow broken. This used to work with 0.5.96, but does not work since 0.5.97.

**Comment by dg0yt** [comment]
Which version of Debian are you packaging for? Could the problem be related to cmake 3.4? Packaging in/for Debian 8.0 (cmake 3.0.2) is working without tricks on [openSUSE build service](https://build.opensuse.org/package/live_build_log/home:dg0yt:staging/openorienteering-mapper/Debian_8.0/x86_64). But cmake 3.4 is used for none of our [target systems](https://github.com/OpenOrienteering/mapper/wiki/Target-systems).

**Comment by gaudenz** [comment]
Kai Pastor <notifications@github.com> writes:

> Which version of Debian are you packaging for? Could the problem be
> related to cmake 3.4? Packaging in/for Debian 8.0 (cmake 3.0.2) is
> working without tricks on [openSUSE build
> service](https://build.opensuse.org/package/live_build_log/home:dg0yt:staging/openorienteering-mapper/Debian_8.0/x86_64).
> But cmake 3.4 is used for none of our [target
> systems](https://github.com/OpenOrienteering/mapper/wiki/Target-systems).

I'm targetting this at Debian unstable to be included in testing and
later the next stable release. This has indeed cmake 3.4.1

I just tried running cmake twice on Debian 8.0 (jessie) which has cmake
3.0.2 and it indeed does not fail there. But reverting to an older cmake
for the official Debian build is not really an option as the unstable
and testing distributions no longer contain cmake 3.0.X.

Gaudenz

**Comment by gaudenz** [comment]
I did some more investigation and found out why make install causes cmake to rerun. The problem is that I'm running the tests after a successful build and the tests modify the sample maps in the example directory. CMake then detects that these files have newer modification dates than the Makefile it generated and tries to rerun.

IMO running the tests should not write to any source files.

Fixing the testruns will not fix the problem that cmake is unable to run twice but will avoid this bug because cmake will not rerun during the make install phase.

**Comment by gaudenz** [comment]
I found the offending test. It's symbol_set_t. I reported a separate issue about this: #580

**Comment by dg0yt** [comment]
Repeating my comment from #580: Generally, it is not a problem to re-run CMake. IMHO you observe a problem because during the CMake re-run, the environment is different from the initial run - clipper cannot be found via pkgconfig.
