### ISSUE TITLE
Provide arm64 android package.

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper#581]
Please provide an apk for arm64 based android devices.

**Comment by txt-file** [comment]
actually this is only a minor issue. The armv7a apk installed and is running.

**Comment by dg0yt** [comment]
Required for #607.
CI builds for arm64 and x86_64 now work (https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=707). However, I want to do a few more updates before publishing another snapshot.

**Comment by dg0yt** [comment]
Pre-release published:  
https://github.com/OpenOrienteering/mapper/releases/tag/v20190622.5
