### ISSUE TITLE
Possibility to remove template with broken path

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#586]
My map is ready and I moving omap file in new location. Paths to template are broken now. When I click to template, Mapper offer me to specify the path to the template and reattach it, but I want just to remove all templates. Remove button is inactive in this case.
It should be implemented in some other way, for example as a context menu where user can choose remove or attach template he want.

**Comment by dg0yt** [comment]
As a workaround until the stable release, maybe just put an image named REMOVE_THIS_TEMPLATE.jpg in the map folder, so you easily select that image and then remove the template.
