### ISSUE TITLE
Official symbol sets for MTBO and SkiO

### ISSUE THREAD

**Issue by lorrieq** [OpenOrienteering/mapper#588]
I am starting work on creating these now.

**Comment by 999999333** [comment]
In what stage are you now? I have done MTBO so make only SkiO :+1:

**Comment by dg0yt** [comment]
MTBO from @999999333 is now merged (#619). Testing and Review welcome.

**Comment by dg0yt** [comment]
ISMTBOM and ISSkiOM symbol set are now in unstable, waiting for tests.
