### ISSUE TITLE
High Resolution Monitor Problem

### ISSUE THREAD

**Issue by JHuberman** [OpenOrienteering/mapper#592]
I have a 3840 x 2160 pixel 15.5" laptop screen, and 
 * [x] the boxes for zoom level and map location are very short and the information is unreadable. 
 * [x] The selection pointer is also very small and difficult to see.

 Are there any suggestions for correcting this?

![image](https://cloud.githubusercontent.com/assets/17171179/12968737/ee371628-d043-11e5-9e52-ad44d1d39fca.png)

**Comment by dg0yt** [comment]
Thanks for reporting. I see that these labels are created with fixed screen pixel size. This needs to be changed to screen independant pixels or some dynamic size.

Are you using Windows (and if yes, which version)? Are there any other artifacts? I see a tiny lens icon in the screenshot.

High-resolution is work-progress in the Qt framework used by Mapper, and it depends on the operating system and even version. It is going to receive major changes with upcoming release 5.6 of Qt.

For Windows, you may experiment with the [```dpiawareness``` option](http://doc-snapshots.qt.io/qt5-5.5/highdpi.html#operating-system-support) which can take the value 0, 1, or 2. It can be given either at the command line:

    Mapper.exe  -platform windows:dpiawareness=0

or [in the qt.conf file](http://doc-snapshots.qt.io/qt5-5.5/qt-conf.html#configuring-arguments-to-the-platform-plugins):

    [Platforms]
    WindowsArguments = dpiawareness=0

Please report your result (screenshots welcome). I lack a machine for real testing of these options, and that is the reason why there is no mentioning in the documentation or FAQ.

**Comment by JHuberman** [comment]
Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788

On Thu, Feb 11, 2016 at 2:18 AM, Kai Pastor <notifications@github.com>
wrote:

> Thanks for reporting. I see that these labels are created with fixed
> screen pixel size. This needs to be changed to screen independent pixels or
> some dynamic size.
>
> Are you using Windows (and if yes, which version)?
>
Windows 10 Home
Version 1511
OS Build 10586.104


> Are there any other artifacts? I see a tiny lens icon in the screenshot.
>
That is the icon for the zoom level.  It is about the same size as the
selection triangle which is tiny and difficult to see.

Windows has a magnification setting.  In order to see stuff on the screen I
keep it at 300%.  (250% is the recommended level.)  When I set it to 100% I
can see the map location and zoom numbers but they are unreadably tiny.  I
have included a full screenshot at my standard 300% as well as 100%.  The
image of the map and tool icon does not seem to change with the
magnification level.[image: Inline image 1][image: Inline image 2]

...
>
> For Windows, you may experiment with the dpiawareness option
> <http://doc-snapshots.qt.io/qt5-5.5/highdpi.html#operating-system-support>
> which can take the value 0, 1, or 2. It can be given either at the command
> line:
>
> Mapper.exe  -platform windows:dpiawareness=0
>
>
I tried the command line and got this response:

C:\Users\Josep>Mapper.exe  -platform windows:dpiawareness=0

'Mapper.exe' is not recognized as an internal or external command,
operable program or batch file.

>  or in the qt.conf file
> <http://doc-snapshots.qt.io/qt5-5.5/qt-conf.html#configuring-arguments-to-the-platform-plugins>
> :
>
> [Platforms]
> WindowsArguments = dpiawareness=0
>
> I updated the qt.conf file and OOM would not start. I got this result:
[image: Inline image 3]

**Comment by dg0yt** [comment]
The pictures from the image were dropped by Github.

In a Windows 7 environment, I could now test the dpiawareness setting. It doesn't really give an improvement. With dpiawareness=1 and environment variable ```QT_DEVICE_PIXEL_RATIO=2``` I got wider labels, but lost the high resolution of the map and of other images. So only for the record:
 * The command line needs the full path to Mapper.exe (if it is not the current directory).
 * The qt.conf issue is quite surprising. I guess you get a message about the windows platform plugin not being found. This could be fixed by more entries:

        [Paths]
        Plugins = ./plugins

**So high resolution is already working quite well with the defaults.**
A proper fix for the label width issue and magnifying glass icon size is now in the source code and will appear in the development snapshot builds soon.

I still don't understand what you mean by "selection pointer". The normal mouse pointer?

**Comment by dg0yt** [comment]
- The map symbol icons need to be larger.
 - The relative map scale is incorrect, i.e. 1x is not 100% of printed size.

The following screenshot show a standard 0.6.1 Linux window on top of a 200% Windows window (with latest changes). I removed the ugly label frames from the Windows version of Mapper.

![dpiawareness](https://cloud.githubusercontent.com/assets/13567791/13000925/c9cde352-d160-11e5-9be7-9a8c53eb4197.png)

**Comment by dg0yt** [comment]
The map symbol icons, the relative map scale, and the size of handles of selected objects change with the screen pixel per inch setting of mapper. Setting this to 192 instead of 96 gives properly sized map symbol icons and object handles. However the map is displayed with 200% size at 1x zoom. To be done...

**Comment by JHuberman** [comment]
Yes, the selection pointer I am referring to is the little triangle mouse
pointer.  It seems to have only one pixel line width and is really tiny and
difficult to see.

Thanks for working on this.  Our club (BackwoodsOK.org) is considering
standardizing our map editing on OOM so several of us are using it now.  We
will be migrating from ocad if there is general agreement.  One really big
draw is being able to do some fieldchecking on an android phone in the
field.  Another big thing is using SHAPE files, since we can get those from
the county GIS office.  We use CONDES by Finn Arildsen <finn@arildsen.com>
for our course design software, and he is considering including the OOM map
format if there is enough demand for it.  For now we export into OCAD 8
format for use in CONDES. (condes is really an excellent course design
program, especially when multiple people are setting an event and checking
control sites.)

I'll look forward to the next release that includes the fix.  Until then
I'll set the display to 100% and use the little magnifying app to read the
map location when we are trying to geolocate the map.

Thanks again for all your work.

Joseph

================================
Joseph Huberman
904 Dorothea Drive
Raleigh, NC 27603

m. (919)610-1788

**Comment by dg0yt** [comment]
The cursors are scaled now. It is not beautiful but don't expect someone working on high-dpi images soon. I noticed the right click menu using fixed sizes, so I adjusted that too.

The development snapshot (aka unstable) now has binaries with these changes. I don't know if the new template code has unwanted side effects, but it will give you SHAPE file support.
