### ISSUE TITLE
OCD export should save georeferencing

### ISSUE THREAD

**Issue by dominikzalewski** [OpenOrienteering/mapper#596]
Use case 1: I'm using OO Mapper for drawing, but when the day of the competition on this map comes, I have to switch to Purple Pen to setup some routes/courses for competitors. Purple Pen has an option to export GPX files of designed courses. You can import them to your watch to be 100% sure that controls you're setting in the woods are exactly in the places where they need to be. Sometimes there's just too much stress, not enough time and you can make silly errors without GPS support. Sometimes you just want to outsource this action (setting up control points) or part of it to some other person, when you face time issues. That person may be less experienced.

Use case 2: Prepare an empty map with templates (from LIDAR) and imported iso-lines for my friends that are 45+ map makers, hence are so used to OCAD, that I cannot get them convinced to OO Mapper. I have to do a lot of this, since they also don't know how to handle LIDAR data.

Request: Keep georeferencing in an OCD file exported from OO Mapper not as 'local', but as exactly the coordinate system that was chosen (using say EPSG codes) in OO Mapper.

This way for use case #1 I could use Purple Pen's GPX export functionality. Currently as a workaround I have to input the same course in OO Mapper as I put into Purple Pen, then use my custom extension code to download a KML file from Simple Course in OO Mapper to have it finally loaded on my watch. If I have 4 courses in a competition it's a lot of work and a lot of room for errors.

For use case #2 I wouldn't need to instruct my colleagues that they need to setup georeferencing correctly in the OCD file I give them. Also, when we do teamwork and they come back with the file to me in order for me to put my changes in, I would have less trouble merging two files.

Both use cases have workarounds so please consider this issue more of a wishlist addon for this great software that OO Mapper already is!

**Comment by dg0yt** [comment]
There is a insufficient information on the details of storing georeferencing in OCD files.

**Comment by dominikzalewski** [comment]
Do I understand correctly that it's technically not possible?

Or do you want me to provide more details because my description could not be understood?

**Comment by dg0yt** [comment]
The problem is that the available documentation on the OCD format is not very detailed. Someone needs to spend time on research and experimenting. Any extra pointers are welcome.

The issue is (at least partially) covered by #373.

Preserving the georeferencing of existing OCD files is a separate story, similar to preserving other information in these files.

**Comment by dg0yt** [comment]
The offset is properly saved since https://github.com/OpenOrienteering/mapper/commit/82daa6fcbb0e8cbbfabca0b22f6f75eee051af26 (only in unstable builds at the moment).

**Comment by Zerbembasqwibo** [comment]
When exporting to different OCAD-versions, and different users receive files, almost all of them complain about lost georeferencing. 

Any news about it? I have very difficult to give aid since I don't have those OCAD version-programs that handle georefecering. Maybe I delete this question since it give nothing to others. But I just have some feeling that things happens differently and I cannot understand the pattern. This is to unstable 20180913.

**Comment by dg0yt** [comment]
a) Unstable 20180913 is not the latest build.
b) There is a (certainly incomplete) mapping of OCD grid/zones to EPSG code at https://github.com/OpenOrienteering/mapper/blob/7c821e2d8324dfd0e9675a23c026fccd66bb5456/src/fileformats/ocd_georef_fields.cpp#L135-L669

So if something isn't working, it may help to prepare a small test case.

**Comment by lpechacek** [comment]
FWIW, I'm happily using -unstable to deliver OCD maps to my club. I can only recommend updating to the latest build and re-testing. If there is something broken, be so kind as to file a new issue report.

From my point of view, this enhancement request can be closed.
