### ISSUE TITLE
Explain why OCD export has different symbols then a file created directly in OCAD

### ISSUE THREAD

**Issue by dominikzalewski** [OpenOrienteering/mapper#597]
Use case: Prepare an empty map with templates (from LIDAR) and imported iso-lines for my friends that are 45+ map makers, hence are so used to OCAD, that I cannot get them convinced to OO Mapper. I have to do a lot of this, since they also don't know how to handle LIDAR data.

After I execute the use case above, they often complain that the symbols list that is available in OCAD's patch, is not visually the same as if they had the file created in OCAD originally.

This is more of a question, rather than the issue. It also has very low priority.

**Comment by dg0yt** [comment]
Are you talking about the symbol icons, typically on the right side of the window? 

If I remember correctly, OCD files explicitly store icon bitmaps which are independant of the actual symbol definition, while Mapper creates an icon on the fly. On OCD export, Mapper generates an icon in the same way. This is also true for editing OCD files in Mapper. I would love to preserve more information from the original OCD files, but this left for the future. Mapper is an editor for OMAP files in the first place, OCD files is just a bonus.

**Comment by dominikzalewski** [comment]
Yes, I was referring to that exact window. I really appreciate you've made an effort to answer my question. I'm satisfied with the answer.

**Comment by dg0yt** [comment]
When working on OCD files round-trip with OCAD and Mapper, it may make sense to keep a backup of the original OCD file, and to occassionaly replace the symbols in OCAD from this backup in order to restore properties which are not preserved when editing the file in Mapper.

**Comment by dominikzalewski** [comment]
Thanks again for a valuable hint. The problem I'm also facing is that I use only Linux and Mac (ocasionally launch something on a Virtual Box Windows installation). For personal/professional reasons I am trying not to use OCAD at all - it's only my friends that use it. What you suggested would probably require me to do this 'symbol replacement', but in order to do that I'd need to run OCAD (the thing I'm trying to get rid of from my workflows). My older friends are having a hard time understanding how to do simple things on a computer. Replacing a symbol set could be just too much for them ;)
