### ISSUE TITLE
Crash on Android tablet if too many too big templates

### ISSUE THREAD

**Issue by dominikzalewski** [OpenOrienteering/mapper#598]
Problem: 
If the templates that I use are too big (or there are too many medium-sized), starting OO Mapper on Android Tablet crashes.

Possible reason:
There is not enough memory on the device to put everything into RAM.

Proposed solution:
Application should not crash, but recover and give a message to the user saying which template causes a problem with loading it into memory. The application should try to load all visible templates and report a list of templates that could not be loaded, rather than just the first one that caused the problem. After successfully loading some of them, it should be possible to work with OO Mapper without the templates that could not be loaded.

I would also much appreciate is template loading could be optimized and only visible templates are loaded into memory. My guess is that currently OO Mapper tries to load all templates (visible and hidden) into memory. This really slows down startup time on mobile device. If OO Mapper was working in the following way:
- initially load into memory only templates that are visible
- if the user sets visibility flag to TRUE of a template, load it into memory
- if the user sets visibility flag to FALSE of a template, unload it from memory
  Then I could work with big templates if that is my wish, but only turning them on and off (one at a time) on a mobile device.

Current workaround:
Currently what I need to do is to delete almost all templates on the desktop from the map, load onto device and check if it works. If it is, add another template on the desktop, transfer to tablet, check. And so on. It's really painful and time consuming to figure out which template causes a problem.
After realizing which one causes the problem, I have to lower its resolution and this forces me to loose meaningful details while doing fieldwork.

**Comment by dg0yt** [comment]
I will rewrite some parts of the template code in the course of adding the GDAL. I know some rough spots, including initial template loading.

However, it may be impossible to completely avoid some "crashes", depending on how Android handles memory. On standard Linux systems, there is memory overcommitment. Processes get any memory they *ask* for, but processes get killed when they start to *use* more than actually can be provided. The experience I have from servers is that this may finally hit a random process - even the single remote login service... If Android reliably kills the active app, that's already an improvement.

**Comment by dominikzalewski** [comment]
After a week of thinking I come to the conclusion that maybe what I suggested is not such a great idea in all the details. I mean in general it's OK, but I think we need small adjustments.

When doing fieldwork I frequently change the visibility of layers. This is the operation that already is a bit user-unfriendly, as each time I need to wait about 1-2 seconds for the layer to appear/disappear. Right now the image is already loaded in memory, so I think we cannot do it any faster.

Now, if you code exactly what I proposed then each change in layer visibility will have a penalty of loading the image to memory, which will probably add around 10 seconds to the loading time, at least for the template sizes I'm using.

Therefore, I suggest that everything stays as I stated previously, with a minor change that once the template is made visible, it is never 'unloaded' and stays in memory until the program is closed. This way the loading time and loading crash will be fixed, but current operations will not be harmed.

Sorry for all the confusion I caused not thinking it through right from the start.

**Comment by dg0yt** [comment]
It is allright. Unloading would be the last thing I would implement ;-) But I will need to review the the raster file formats anyway, taking into consideration the features provided by GDAL. It could mean loading only small pieces of a larger file becomes feasible. Another thing to be done is decoupling the user interface from the loading.
