### ISSUE TITLE
Kubuntu install fail

### ISSUE THREAD

**Issue by nicknn** [OpenOrienteering/mapper#602]
OpenOrienteering Mapper fails to install due to unmet dependencies with apt-get install:

The following packages have unmet dependencies.
 openorienteering-mapper-unstable : Depends: qtbase-abi-5-2-1
E: Unable to correct problems, you have held broken packages.

The error occurs on both stable and unstable releases because qtbase-abi-5-2-1 is a legacy package and has been superseded. All other dependency demands (five in total for me) were met without issue.

Synaptic and apt cannot find broken packages to fix.

Aptitude will offer to downgrade and mess about with 18 packages to attempt to correct this dependency; I am not willing to take the risk that it will work.

Kubuntu 14.04, 64-bit, AMD, 8Gb RAM
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
kernel 3.19.0-49-generic

**Comment by dg0yt** [comment]
On standard Ubuntu 14.04, ```qtbase-abi-5-2-1``` is a *virtual* package provided by ```libqt5core5a```. As far as I can tell, even newer releases of Debian and Ubuntu let ```libqt5core5a``` provide such a virtual package. It seems to me that your system has non-standard Qt packages.

For reference, on my standard Ubuntu 14.04 (with all updates), i have got this information about the installed libqt5core5a (note the ```Provides:``` line):

~~~
dg0yt@ubuntu:~$ dpkg-query -s libqt5core5a
Package: libqt5core5a
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 5118
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: qtbase-opensource-src
Version: 5.2.1+dfsg-1ubuntu14.3
Replaces: libqt5core5 (<< 5.2.0+dfsg~)
Provides: qtbase-abi-5-2-1
Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), libglib2.0-0 (>= 2.22.0), libicu52 (>= 52~m1-1~), libstdc++6 (>= 4.1.1), zlib1g (>= 1:1.1.4)
Pre-Depends: dpkg (>= 1.15.6~), multiarch-support
Suggests: libthai0
Breaks: libqt5core5 (<< 5.2.0+dfsg~)
Description: Qt 5 core module
 Qt is a cross-platform C++ application framework. Qt's primary feature
 is its rich set of widgets that provide standard GUI functionality.
 .
 The QtCore module contains core non-GUI functionality.
Homepage: http://qt-project.org/
Original-Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
~~~

How does the output differ on your system?

**Comment by nicknn** [comment]
Thanks. OK, so a slight difference can be seen in 'Provides':

$ dpkg-query -s libqt5core5a
Package: libqt5core5a
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 5622
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: qtbase-opensource-src
Version: 5.3.0+dfsg-2ubuntu9~trusty1
Replaces: libqt5core5 (<< 5.2.0+dfsg~)
Provides: qtbase-abi-5-3-0
Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), libglib2.0-0 (>= 2.22.0), libicu52 (>= 52~m1-1~), libstdc++6 (>= 4.1.1), zlib1g (>= 1:1.1.4)
Pre-Depends: multiarch-support
Suggests: libthai0
Breaks: libqt5core5 (<< 5.2.0+dfsg~)
Description: Qt 5 core module
 Qt is a cross-platform C++ application framework. Qt's primary feature
 is its rich set of widgets that provide standard GUI functionality.
 .
 The QtCore module contains core non-GUI functionality.
Homepage: http://qt-project.org/
Original-Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>

I perform regular updates and upgrades, and I probably have a couple of non-standard Repositories to keep QGIS up-to-date. Not sure where this takes me with Mapper.

**Comment by dg0yt** [comment]
That's not just a different provides, it is a different version: 5.3.0+dfsg-2ubuntu9~trusty1. And QGIS doesn't even officially support Qt5 (https://github.com/qgis/QGIS/blob/master/INSTALL item 3.9). I couldn't identify where your Qt build comes from.

Mapper uses some private API of Qt where the ABI may change between releases. That's why there is the particular versioned ABI dependeny.

Your options are:
- use the Windows version via Wine. It may have drawbacks such as printing not working.
- rebuild Mapper from source in your non-standard system. It should not be too difficult if the development packages for that Qt version are available. You need the openorienteering-mapper .dsc, .orig.tar.gz and .diff.gz files from http://download.opensuse.org/repositories/home:/dg0yt./xUbuntu_14.04/. Using ```debuild```, it could be as easy as:

        dpkg-source -x openorienteering-mapper_0.6.1-3.1.dsc
        cd openorienteering-mapper-0.6.1
        debuild

  In practice, you might need to manually install the build dependencies (see dsc) first, and I just discovered that these .tar.gz downloads are gzipped twice - they need to be gunzipped once and renamed to there original .tar.gz name. (I need to get this fixed on openSUSE build service.)

**Comment by nicknn** [comment]
Thanks again.
Mapper in Wine fails because of another error: 'Failed to load platform plugin "windows".'
Not going to risk compiling from source. 
Giving up -- I'll stick with Inkscape.

**Comment by dg0yt** [comment]
The Windows version has become somewhat sensitive. It will probably work when you put the following in ```qt.conf```:

    [Paths]
    Plugins=./plugins
    Translations=./translations

I will probably add that again for the next release.

IMHO compiling from source is more tedious but much less risky than adding alien repositories. It is not just about breaking dependencies: Unless you use APT pinning carefully, these repositories may replace any package, comprising your system's security.
