### ISSUE TITLE
Import OpenStreetMap data with styles

### ISSUE THREAD

**Issue by kolesar-andras** [OpenOrienteering/mapper#606]
Imported .osm files become gray lines. Points are not imported at all. Do you plan to extend OSM importer to read tags and apply styles to objects during import? Or will you accept a pull request that implements this feature?

If not, I should find or create a converter that creates .omap files from OSM data. Do you know such a converter? I don't want to reinvent the wheel if not necessary.

**Comment by dg0yt** [comment]
In the stable releases, I would expect OSM vectors to become purple line, and tags are imported, too. However, there is nothing yet what would assign styles. 

In the unstable snapshots, OSM import might already use GDAL/OGR, and formatting would be according to the GDAL defaults (black, gray). Tags are partially imported, depending on [the configuration](http://gdal.org/drv_osm.html). This is work in progress. I'm about to add GDAL configuration options to the settings. In the end, I will probably remove Mapper's native support for DXF, GPX and OSM in favour of GDAL based support. This code directly creates first class Mapper objects (Map, Symbol, Object).

I gladly accept pull requests, but I'm unlikely to accept ad-hoc solutions which will be difficult to maintain or extend in the long run. When you want to work on assigning styles, we need to discuss the features and design:
 - Which type of style definition will we (re-)use?
   - Is it common?
   - Are the existing definitions for orienteering-style maps?
 - Can this feature be generalized for other vector formats?

My ideas include to expose the map objects to a Javascript environment where arbitrary user scripts could do what they want.

**Comment by wanacode** [comment]
Someone wrote a basic bash script which may be a starting point for a converter https://github.com/OpenOrienteering/mapper/issues/178#issuecomment-135996873

**Comment by dg0yt** [comment]
That script doesn't do much more than splitting osm files. It does neither assign existing symbols nor create new ones.

**Comment by kolesar-andras** [comment]
Thank you for you answer. Planned JavaScript API is an interesting feature that would allow users to automate tasks. Howewer, a beginner user would rather need a one-step (builtin) solution for importing OSM data. Either by opening an .osm file downloaded from OpenStreetMap website or by selecting a bounding box of target area on a slippy map, just [like in JOSM](http://learnosm.org/images/josm/josm_download-dialog.png).

Styling could happen by a builtin but configurable JavaScript solution or a json/xml/etc configuration file. This solution can be even more general:

* not for only .osm files but any OGR data source that has OSM tags
* not only for OSM tags but mapping any combination of values in data source to styles

I'm going to create a conversion method from OSM tags to ISOM codes. This will be a command line tool that converts OGR data including .osm files to .omap file format. I will publish this on GitHub where anyone can contribute. Main starting points:

* [IOF mapping page](http://wiki.openstreetmap.org/wiki/IOF_mapping) at OpenStreetMap wiki
* [OpenOrienteeringMap](http://oomap.co.uk/) styles available at [GitHub](https://github.com/oobrien/oomap)

When this converter produces usable results you can build the method in mapper. Is this way viable?

**Comment by dg0yt** [comment]
I wasn't aware that the OpenOrienteeringMap styles are available on Github. It illustrates the complex combinations of tags that are needed to determine the symbol.

We can port or merge what is compatible with Mapper's license (GPL3). The file format is not documented, subject to change, and the implementation details are somewhat littered over different classes. If you don't reuse Mapper' file format classes, use an .xmap file as an example, .omap is compressed for size and speed in various ways.

**Comment by kolesar-andras** [comment]
I see no structural differences between .omap and .xmap format. Saved a file in both formats and pretty-printed them using http://xmlprettyprint.com/ online service. Results were identical.

**Comment by kolesar-andras** [comment]
I have published first version of converter: https://github.com/kolesar-andras/osm-omap

I have chosen PHP to be used as an online service, hopefully integrated to OpenOrienteeringMap. For testing I use it from command line.

**Comment by Symbian9** [comment]
Is this project included in Mapper? 
https://github.com/sembruk/osm2xmap

**Comment by kolesar-andras** [comment]
Thank you for mentioning, this project seems to do the same job. It uses C++ that can be included directly into mapper. I have just contacted author.

**Comment by 999999333** [comment]
I think that for now, will be better to add tag based selection pls :+1:

**Comment by Symbian9** [comment]
Need CRT support for OSM import

**Comment by dg0yt** [comment]
Done with #892.
