### ISSUE TITLE
Unstable build with GDAL support NOT include libgdal-20.dll

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#609]
I try run "openorienteering-mapper-unstable_0.6.20160222-Windows-x86.exe" from http://download.opensuse.org/repositories/home:/dg0yt/Windows/ but have an error on start:

err:module:import_dll Library libgdal-20.dll (which is needed by L"C:\\Program Files\\OpenOrienteering Mapper\\Mapper.exe") not found
err:module:LdrInitializeThunk Main fwd initialization for L"C:\\Program Files\\OpenOrienteering Mapper\\Mapper.exe" failed, status c0000135

I try get GDAL from this link:
http://download.opensuse.org/repositories/home:/dg0yt:/3rd-party:/gdal-2/Windows
But this not have any files. Where get libgdal-20.dll and why this lib not distributed with unstable windows binary?

**Comment by dg0yt** [comment]
This was a packaging error. It is now fixed. Note that at the moment, GDAL might not be working so well on Windows out of the box. It would need to be told the path the gdal directory by setting the ```GDAL_DATA``` environment variable. I'm going to add this soon (as time permits).
