### ISSUE TITLE
OpenOrienteering - Czech localization file update

### ISSUE THREAD

**Issue by pafri** [OpenOrienteering/mapper#615]
OpenOrienteering - Czech localization update.
[OpenOrienteering_cs.ts.tar.gz](https://github.com/OpenOrienteering/mapper/files/160004/OpenOrienteering_cs.ts.tar.gz)

**Comment by dg0yt** [comment]
The translation looks good. Which name and e-mail should be used as the autor/for contributor credits?

(You might also fork Mapper on Github, upload the file to the translations folder, and send a pull request, all on the Github website.)

**Comment by pafri** [comment]
Use Pavel Fric
pavelfric AT yahoo dot com
