### ISSUE TITLE
Unable to load valid file, internal format version 5

### ISSUE THREAD

**Issue by banak84** [OpenOrienteering/mapper#618]
Hello

I have some problem to open back omap file, after one year i decided to go back to some map project.

Unfortunately the file is not working, during the time i changed the system form linux to windows.

If there is some way to restore the file, i will be very grateful for your help.

[FosséA.zip](https://github.com/OpenOrienteering/mapper/files/167883/FosseA.zip)

**Comment by dg0yt** [comment]
Okay, it was plain bug. A fixed unstable build will be available later this night. 

Background: We automatically move coordinates the whole data towards the origin (0;0) at loading when the coordinates are out of (reasonable) bounds for printing. I even wrote a unit test for map objects, but this bug was in template loading - templates need to be adjusted accordingly, of course. Please let me know if you find the templates to be misaligned.

**Comment by banak84** [comment]
Thank you, I just have one silly question, how can I load and save my map, there is some link or place where i can find a fixed file or i need to edit the code ?
Thank you for help

**Comment by dg0yt** [comment]
What I meant is that you can install the so-called "unstable" development snapshot (cf. http://www.openorienteering.org/apps/mapper/) 20160307 (or later), run Mapper-unstable, and load and save the map on your computer.

I can also attach the updated file if I get the copyright holders' consent. I cannot see the indidual e-mail address on Github.

**Comment by banak84** [comment]
Ok, i try to run the file on the "unstable" development snapshot but the
error is still repeats. Installation

openorienteering-mapper-unstable_0.6.20160307-Windows-x86.exe
<http://download.opensuse.org/repositories/home:/dg0yt/Windows/openorienteering-mapper-unstable_0.6.20160307-Windows-x86.exe>
    07-Mar-2016 02:50


You can attach the file, I give you the copyright holders consent, I'm a
individual mapper and you can send the file on my individual e-mail adders.


2016-03-11 7:31 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
[FosseA-fixed.omap.zip](https://github.com/OpenOrienteering/mapper/files/168712/FosseA-fixed.omap.zip)

**Comment by banak84** [comment]
Thanks its working.

2016-03-11 9:50 GMT+01:00 Kai Pastor <notifications@github.com>:
