### ISSUE TITLE
Printer properties missing in Print window

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#622]
If I want to print a map, and open the Print window, there is no entry for the Printer properties dialog. And the printer prints using its default options.
Therefore, if I print by default on A4, in B/W, my map will be printed on A4, despite the A3 settings in the OpenOrienteeringMapper dialog.
To change the printer output, I have to go to Devices and Printers (Win7), select the printer, and change the default print settings, to achieve what I want.
I think it would be nice to have a button in the OOM Print Dialog to go to Printer properties and make the changes there.

**Comment by dg0yt** [comment]
I'm aware that the standard Windows printer properties dialog is not available. The application is developed in a cross-platform way, and features like this are more difficult to implement and maintain.

Mapper does give you the choice to print B/W, but you can select the page format and orientation. Didn't this work for you?

**Comment by jan-gerard** [comment]
Unfortunately, this doesn't work. The printer settings overrule other settings. My printer profile prints by default 2 pages on am A4 sheet, double sided, with a staple. Changing it in OOM affects the printed selection size, but it still gets printed according to the default settings of the driver. Same in other applications, unless I change the settings in via a print properties dialog. Isn't there a cross-platform printer properties dialog? I can imagine printer settings will be applicable in other OSs too.

**Comment by dg0yt** [comment]
There is also the "page setup" dialog available from the preview dialog. It allows a few more adjustments.

**Comment by jan-gerard** [comment]
Yes, indeed. If I click "Preview..." then I can set the page setup, and by clicking the printer icon, the Print properties dialog opens, in which I can set the Printer Preferences. That seems to do it.
However, the settings made are not persistent (during the same OOM instance) and have to be re-set for every print I make. And it it quite some clicks from the print screen, while creating the preview is quite time consuming for larger maps. Could this print button be added to the main print screen, and could windows somehow be triggered to remember the settings?

**Comment by Symbian9** [comment]
Think, better way is also export to PDF and after that print PDF as default.

**Comment by dg0yt** [comment]
We already do our best to save printer settings, but it is really an area where platforms diverge. Good to know that the preview's page setup is an improvement for you. More investigation can start from that point.

**Comment by dg0yt** [comment]
It seems to me that Windows no longer offers a simple way to show the current printer's properties without showing its print dialog which has a "Print" we don't need at the moment.

**Comment by dg0yt** [comment]
Okay, [```DocumentProperties```](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183576(v=vs.85).aspx) gives the needed dialog, but it will take some effort to connect this to Qt, and to preserve the settings at least until the document or printer are changed.

**Comment by dg0yt** [comment]
The "unstable" development builds now have a printer properties dialog for Windows. Note that the extra properties are kept only in memory, until you close the document or configure another printer. Please report here if does not solve your issue.

**Comment by jan-gerard** [comment]
Works perfect! Thanks for solving.
