### ISSUE TITLE
include OCAD file version in Save as.. menu

### ISSUE THREAD

**Issue by matkoniecz** [OpenOrienteering/mapper#623]
Given that OCAD files are incompatible between different versions (OCAD 10 is unable to load OCAD 12 files), it may be useful to show which version is used in "save as..." menu.

Currently at least on Lubuntu 14.04 filetype is displayed simply as "OCAD".

![selection_001](https://cloud.githubusercontent.com/assets/899988/13930741/6d42d896-efa0-11e5-94c4-c7a3c63d1c05.png)

**Comment by dg0yt** [comment]
This will be solved when it is needed. At the moment, Mapper saves format version 8, always. 

The file name ending is .ocd. It will not be possible to change the display name of the file format in locations where the ending is the only indication of file format.

**Comment by dg0yt** [comment]
This is finally addressed in #1081.

**Comment by dg0yt** [comment]
Changes: db3b2ae34a4889d8e55acf72fbda05b14b781fcf, 838a92434445742d424b631d7be0fcab506c5706

**Comment by matkoniecz** [comment]
> This is finally addressed in #1081.

(...)

> reopened this on Mar 27

Is "addressed" intended to mean "now made fixable" or "fixed"?

**Comment by matkoniecz** [comment]
In that case I will close this issue as it is fixed.

**Comment by matkoniecz** [comment]
Thanks for your work on this program - it is very useful!

For example it was used during preparing a small even at school of my little sister - thanks for making it available!
