### ISSUE TITLE
Closed end on urban roads? 

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#629]
How can I close the endpoint of a "paved road with with border"? I can find no way in the symbol editor to create a road with closed ends.

A workaround however seems to be creating a road, and then creating an additional point that is located a bit back from the endpoint, along the same road. Then the end becomes a bend (180 degrees, though), and the road becomes capped. However, the actual end is then quite far, by two times the width of the road) from where I drew the original end-point.

**Comment by Symbian9** [comment]
What is "paved road with with border" in this situation? Can you give image with example?
Think you must view to how end points realized in symbol "517 Major power line", that included with inbuild symbol sets.
Think it have what you want, only thing is that you would duplicate needed road symbol in your map and add end point for it.

**Comment by jan-gerard** [comment]
This is what happens: [http://www.pasteall.org/pic/100854](http://www.pasteall.org/pic/100854)

**Comment by dg0yt** [comment]
There is no clear guidance in the ISOM. 
- In most situations, you will not have a plain end but a different kind of road/path.
- In some situations, you are to leave it open, see ISSOM 528.1 Area with forbidden access.
- In the remaining situation, it seems to be a common solution to leave it open.
- If you don't want to leave it open, and there is no fence or wall, you may draw an additional 529.1 Paved area, bounding line.

I did not see yet a road symbol with closed ends in orienteering maps. But apart from the ISSOM 528.1 Area with forbidden access, I don't see much arguments against.
