### ISSUE TITLE
Miss template after test printing

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#633]
1) Create new map with standart symbol set
2) Open template
3) Try print empty map with opened template and close it without printing. 
RESULT: template now not visible, but steal shown as opened in template dialog

**Comment by 999999333** [comment]
For printing with templates i use File-export-pdf, tick print templates, select page size and other things, preview it and then -export. this works for me

**Comment by dg0yt** [comment]
I can confirm the issue.

@999999333 This issue happens with PDF export, too. No surprise, it is almost the same code.
