### ISSUE TITLE
Can't run stable and unstable Mapper in same time

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#634]
As I know, mostly applications that have stable and development builds can be installed on one PC and run in same time (for example LibreOffice stable build can run in same time with development build on one PC)
Why Mapper cant do that?
I have Trusty 14.04 and both builds installed without errors, but cant run them in same time.

**Comment by dg0yt** [comment]
It is a feature. It prevents parallel edits of the same file.
