### ISSUE TITLE
Dutch (NL) translation

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#636]
I am working on OpenOrienteering_nl.ts.

**Comment by dg0yt** [comment]
Any news?

**Comment by jan-gerard** [comment]
Still ~500 items to go. It's quite some work :-)

**Comment by jan-gerard** [comment]
I'm finished. The Dutch translation is ready to be used.

**Comment by dg0yt** [comment]
Qt itself doesn't provide a Dutch translation. Thus standard elements (such as standard dialog buttons) will not be translated by default. I added a collection of Qt strings to the Dutch translation. You don't need to translate them all, but you will see that some are needed.

**Comment by dg0yt** [comment]
Published new unstable build with latest updates. Thanks a lot.
