### ISSUE TITLE
Consider hiding warnings from Qt compilation

### ISSUE THREAD

**Issue by matkoniecz** [OpenOrienteering/mapper#641]
> Performing build-host step for 'Qt5'

produces significant amount of messages like

    In file included from /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/include/QtCore/qvector.h:1:0,
                 from /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/include/QtCore/../../src/corelib/tools/qstack.h:37,
                 from /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/include/QtCore/qstack.h:1,
                 from /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/src/corelib/thread/qthread_p.h:52,
                 from /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/src/corelib/thread/qthreadstorage.cpp:38:
    /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/include/QtCore/../../src/corelib/tools/qvector.h: In static member function ‘static void QThreadStorageData::finish(void**)’:
    /home/mateusz/Desktop/tmp/mapper/build/3rd-party/qt5/Qt5-prefix/src/Qt5/qtbase/include/QtCore/../../src/corelib/tools/qvector.h:553:13: warning: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Wstrict-overflow]
             if (asize <= d->size) {
             ^`

Maybe it would be a good idea to hide lint complaining about problems in libraries that are separate projects?

**Comment by dg0yt** [comment]
Is it easy to fix? Who takes notice?
