### ISSUE TITLE
make deb fails with "make: *** No rule to make target `deb'.  Stop."

### ISSUE THREAD

**Issue by matkoniecz** [OpenOrienteering/mapper#643]
According to https://github.com/OpenOrienteering/mapper/blob/master/INSTALL.md#compiling-on-linux

one can  generate a DEB package by

> make deb

but running this command results in 

> make: *** No rule to make target `deb'.  Stop.

**Comment by dg0yt** [comment]
Packaging is not enabled by default on Linux. To enable, pass ```-DMapper_BUILD_PACKAGE=1``` to cmake. Note that this is more or less umaintained for Linux (that's why it is disabled). Packaging is now done in the distributions' (almost) native way, on build.opensuse.org, without cpack.

**Comment by matkoniecz** [comment]
What would be proper fix? Remove `make deb` from https://github.com/OpenOrienteering/mapper/blob/master/INSTALL.md#compiling-on-linux section or add mention about `-DMapper_BUILD_PACKAGE=1`?

Or maybe just mention that it is maintained and disable, with `sudo make install` expected to be used in normal situation?

**Comment by dg0yt** [comment]
I will review INSTALL.md for outdated sections, and either update or remove them. In the last years, there was not much indication of interest in reading INSTALL.md, that's why it did receive much care.

**Comment by rugk** [comment]
To show some interest: I tried it and also had this error.
So at least please correct the instructions.

**Comment by dg0yt** [comment]
With #674, we will new new instructions from 0.7.x.
