### ISSUE TITLE
GDAL-based import of OSM etc. depends on map georeferencing

### ISSUE THREAD

**Issue by matkoniecz** [OpenOrienteering/mapper#645]
based on  #606 I installed openorienteering-mapper-unstable package

Stable Mapper imported merely ways, ignoring poits, without assigning symbols based on tags - but at least lines were mostly imported right

In unstable version all what is imported is group of many "Point" objects, all located in the same place.

**Comment by dg0yt** [comment]
This work in progress, based on GDAL. However, it works in my tests. Check your georeferencing.

**Comment by matkoniecz** [comment]
OSM data has geographic coordinate system set (WGS84) so I expected that creation of empty file and importing OSM data should work. Is my assumption correct?

Result in Mapper
File | IMport  Select OSM file | non georeferenced, no for waypoints question


![selection_002](https://cloud.githubusercontent.com/assets/899988/14213428/2b56d630-f838-11e5-9a59-045b2c123247.png)


Result in Mapper-unstable
File | Import | select OSM file

![selection_001](https://cloud.githubusercontent.com/assets/899988/14213426/291d1e10-f838-11e5-83e4-d000fea493bc.png)

**Comment by matkoniecz** [comment]
OK, it seems that problem is with georeferencing, given that importing OSM data with georeferencing enabled in stable mapper results in no visible imported objects...

**Comment by dg0yt** [comment]
OSM data has geographic coordinates. This doesn't give them any position in the flat map (paper) unless a suitable coordinate reference system has been defined for the map. 

The old importer will ask what to do when you try to open an OSM template. The new importer does not catch this situation yet. It will require more work to factor out general features from the legacy code.

However, you may disable the new importer in the settings.

**Comment by rugk** [comment]
Does the old reporter have any disadvantages compared to the new one?

**Comment by dg0yt** [comment]
Well, they are different. 

When using OSM as a template:
- The old importer creates the internal structure of a GPS track, just wires, dots and sometimes labels for dots. It doesn't care for relations.
- The new importer creates the internal structure of a map, with the default styling delivered from GDAL (which is dark and ugly)

When importing GDAL into a map:
- The old importer creates the dots and wires, and imports all tags, but it still doesn't care for relations, such as holes.
- The new importer imports tags as aggregated by GDAL (at the moment). Thanks to GDAL, all relations are properly merged into complex areas.

The GDAL import is work-in-progress and won't replace an existing importer in stable builds before it is on par with the exisiting implementation. But it needs testing to uncover issues like this one.

**Comment by dg0yt** [comment]
In the absence of map georeferencing, the GDAL/OGR importer now uses a local orthographic projection.
