### ISSUE TITLE
Application icon License?

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#654]
I want add OOMapper application icon to Wikipedia articles, but what is current license state of application icon created by Anders Gressli?
https://github.com/OpenOrienteering/mapper/issues/43
Is it licensed in same way as JOSM icon?
https://commons.wikimedia.org/wiki/File:JOSM_Logo_2014.svg
And is it SVG version of OOM icon?

**Comment by guzh** [comment]
I'm the one who designed the icon, we didn't discuss the licensing during the progress, but I don't mind releasing it under creative commons :)

I'll see if I can find the original artwork and create a svg asap. I can send the Illustrator file as well and do a pull request!

Cheers,
Anders

**Comment by dg0yt** [comment]
Hello Anders,

thanks for the response. To be honest, I would like to have the Illustrator file in our repository, because it may be considered "source" in the sense of: preferred form for modification. Could you please create a pull request which adds the file to images/mapper-icon/? For clarification, you may put a README.txt there, too. 

Thanks a lot!
Kai.

**Comment by dg0yt** [comment]
Anders, any news on this?

Regards, Kai

**Comment by Symbian9** [comment]
According to CC BY 4.0 (Section 3 – License Conditions) <b>"You must give proper attribution to the author and retain the license notice."</b>

Thats why file https://github.com/OpenOrienteering/mapper/blob/master/images/mapper-icon/README.txt file must include string with original artwork author name. Something similar to:
<code>© Anders Gressli / CC-BY-SA-4.0</code>
 
So, all icons files in https://github.com/OpenOrienteering/mapper/blob/master/images/mapper-icon/ folder, based on original artwork (PSD files), also must have this notices (including original name of original author)

Also, it would be good add this notices to "OpenOrienteering Mapper Licensing" section of "About" dialog of OOMapper.

References:
* https://creativecommons.org/licenses/by/4.0/legalcode
* https://commons.m.wikimedia.org/wiki/Template:Credit_line

**Comment by Abbe98** [comment]
@Symbian9 did you actually read the *Section 3 – License Conditions*?

> retain the following if it is supplied by the Licensor with the Licensed Material:
 - identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
 - a copyright notice;
 - a notice that refers to this Public License;
 - a notice that refers to the disclaimer of warranties;
 - a URI or hyperlink to the Licensed Material to the extent reasonably practicable;

The existing license note is totally valid it and it's covering all of the files, I would personally recommend to add a author name or pseudonym´(but as long as it isn't requested by the Licensor it's not required).

Your claims in the comment above is mostly non-valid and adds noise to my notifications.
