### ISSUE TITLE
PANTONE and other color specifications

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#655]
I found that user can specify Spot color as color name in PANTONE or other coloring system. We no need in-build it, but need give instruction for user how use this trick, for example when client say make some logo in special corporate colors.
Here is how users of Scribus do it
* https://wiki.scribus.net/canvas/Scribus_and_Pantone_colors
And here is a online official PMS color finder
* http://www.pantone.com/color-finder
* http://colorbrewer2.org/

Also need think about ICC support
* http://www.color.org/opensource.xalter

And here is a trick with RGB-to-CMYK conversion
* http://stackoverflow.com/questions/3418268/script-or-some-other-means-to-convert-rgb-to-cmyk-in-pdf

**Comment by Abbe98** [comment]
Maybe something for the docs?

**Comment by Symbian9** [comment]
@Abbe98, Yeah.

**Comment by dg0yt** [comment]
You may name the spot colors any way you want but the OpenOrienteering project cannot distribute anything which as trademark or copyright terms which are incompatible with the GPL.
