### ISSUE TITLE
11th of May 2016 - World Orienteering Day

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#656]
Is OpenOrienteering developers ready to WOD'2016?
![WOD'2016 Logo](http://worldorienteeringday.com/wp-content/uploads/2016/03/wod-logo-color.png)
http://worldorienteeringday.com/
So, there are few publications: 
* http://worldorienteeringday.com/wp-content/uploads/2016/03/WOD-2016-1-Final-version.pdf
* http://worldorienteeringday.com/wp-content/uploads/2016/03/WOD-2016-2-English.pdf

![instagram.com/p/BDYCVdtS1Tg/](https://igcdn-photos-g-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-15/e35/12677564_1695942773978006_284444329_n.jpg)
So, what we would do in the world at this O-Day?
* http://worldorienteeringday.com/index.php/auth

**Comment by dg0yt** [comment]
Maybe you need to be reminded that there is only one active developer, and he is doing it as a hobby. So when you say "we", I always wonder who is actually meant.

**Comment by Symbian9** [comment]
@dg0yt
When I say "we" I mean community (users, testers and translators) ;-)
For now, ukrainian wiki page is very well thanks to few OOMapper users and many new ukrainian start use "our" program, thanks to "OpenOrienteeringUkraine" facebook group.
I understand that one developer cant give many time to this project, thats why need promote it and enlarge <b>OpenOrienteering Developers Team</b>! :-)
