### ISSUE TITLE
Convert OMAP to 3D mesh using Blender

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#657]
Hi, there is an idea for creating addon for Blender 3D editor (it will look like Caching Feature)  
![preview](http://www.sa.orienteering.asn.au/gfolder/events/Event%20Calendar%202015/Mt%20Dutton%20SA%20Champs%20Map%203D%20b.jpg)
While OMAP/XMAP file format is very similar to OSM Data, so its no need many changes for existing OSM addon.
* http://wiki.openstreetmap.org/wiki/Blender
* https://github.com/vvoovv/blender-geo/wiki/Import-OpenStreetMap-(.osm)

Also, here some info about other tools specially for OSM format:
* http://www.magben.de/?h1=3d&h2=openstreetmap_wielun
* http://sotm-eu.org/slides/32.pdf
* http://www.scoop.it/t/openstreetmap-and-3d/p/3928381118/2013/01/01/maperitive-3d-export

More details soon

**Comment by Symbian9** [comment]
Here is issue on blender-geo project page
https://github.com/vvoovv/blender-geo/issues/17

**Comment by dg0yt** [comment]
Mapper-related, but neiter a bug, nor a feature request. There is no "OSM addon" in Mapper.

**Comment by Symbian9** [comment]
Related solution:
* https://github.com/TIS-BoardSmashers/3DMapVisualization/
