### ISSUE TITLE
Cannot open moved template, on Android

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#660]
I moved a template file when using 0.6.1 on Android. I can only "duplicate" templates, not "open" or "reread" correct new place of file. I cannot remove "red" templates: those who have a new address or are removed from the machine.

**Comment by dg0yt** [comment]
It will be possible to remove missing templates in 0.6.2 (#586).

Opening is a different story, although it would require little more than making the file dialog open fullscreen.

**Comment by Zerbembasqwibo** [comment]
Great.

2016-04-18 9:54 GMT+02:00 Kai Pastor <notifications@github.com>:

> It will be possible to remove missing templates in 0.6.2 (#586
> <https://github.com/OpenOrienteering/mapper/issues/586>).
>
> Opening is a different story, although it would require little more than
> making the file dialog open fullscreen.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenOrienteering/mapper/issues/660#issuecomment-211250090>
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Zerbembasqwibo** [comment]
Possible to remove, that's ok.
