### ISSUE TITLE
Text framing problem with adobe Acrobat

### ISSUE THREAD

**Issue by gandym** [OpenOrienteering/mapper#661]
I have a map which uses white text framing to enhance the clarity of map text. I can export the map from OOM v0.6.1 to vector pdf without issue.

When trying to open the pdf in Adobe Acrobat X (or illustrator 16) in w7x64 the framed fonts either don't appear or the file will not open at all. However, the file opens up just fine when using the TeXWorks pdf editor (on w7x64) or using the native Document Viewer on Ubuntu 15.10.

Any chance framing can be reimplemented so that framing works natively with Adobe products?

Thanks
gandym

Minimal example: [Framing_MWE.zip](https://github.com/OpenOrienteering/mapper/files/220235/Framing_MWE.zip)

**Comment by Symbian9** [comment]
I just have quick test it on my old Symbian9 phone using few mobile apps :)
* <a href="https://sourceforge.net/projects/alternatedjvu/files/sisx/">AlternateViewer</a> v1.80(3)
![AlternateViewer text](http://www.pasteall.org/pic/show.php?id=102044)
* <a href="http://www.planetpdf.com/tools.asp?webpageid=616&PDFSCompanyID=249">PDF+ Standart</a> v1.76(3)
![PDF+ text](http://www.pasteall.org/pic/show.php?id=102046)
* <a href="http://www.adobe.com/jp/special/readerle/jp/">Adobe Reader LE</a> v1.5 (in-build)
![AdobeReaderLE text](http://www.pasteall.org/pic/show.php?id=102045)

**Comment by Symbian9** [comment]
@gandym, what OOMapper version you use for PDF export?
I read properties of your PDF-file and can't approve that this PDF created directly by OOMapper.

**Comment by gandym** [comment]
v 0.6.1 64-bit running on Windows 7

**Comment by dg0yt** [comment]
Don't mind, the PDF properties are okay.  Symbian9 applies for a temporay ban.

Adobe Reader DC reports problems on the page, and it doesn't display any text. When I disable framing in the map file everything is okay. There is no issue with files from Mapper 0.5.96 which used Qt 5.3.2. Mapper 0.6.1 use Qt 5.5.1. I need to see if can find and backport some fixes from later version of Qt.

**Comment by Symbian9** [comment]
<blockquote>Symbian9 applies for a temporay ban.</blockquote>
@dg0yt, why?
Anyway, when say about properties I mean that there no "Author field was empty".
<b>Sorry me, I forgot look to "Producer" and "Creator" property.</b>

**Comment by gandym** [comment]
I was just too lazy to go back and check old versions before raising the ticket. Reverting to 0.5.96 just to get this pdf made is a good workaround. 

Thanks Kai.

gandym

**Comment by Symbian9** [comment]
I open it for test using Master PDF Editor 3 (<a href="https://code-industry.net/free-pdf-editor/">free version for Linux</a>)
![Moved text outline](http://www.pasteall.org/pic/show.php?id=102049)
So, as I see, text outline is curve with specified width.
Maybe OOMapper must convert this "width curve" to filled path before export to PDF?(like now text converted to path)

**Comment by dg0yt** [comment]
What I can say for sure now is that this behaviour is related to the "miter limit" which we need to use in the current implementation of framing to avoid excess framing color spikes e.g. below Arial letter 'W':
![letter-w](https://cloud.githubusercontent.com/assets/13567791/14582778/a6eab9f6-040e-11e6-854c-d3403d3eacd4.png)

The issue with miter limiting seems to be rooted in bugs in Qt (which uses a [different way of miter limiting](http://doc.qt.io/qt-5/qpen.html#join-style) than PDF, but [doesn't compensate for the difference when generating PDF](http://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/painting/qpdf.cpp?h=dev&id=42bdbed7cedc5d77e999143c44c3e095b7cd4ebd)) and in the Adobe PDF products (which don't accept a miter limit below 1.0 although Adobe's PDF 1.4 reference says that parameters like miter limited "are forced into valid range, if necessary"). A random search engine hit, the French documentation of PHP' PDF_setmiterlimit, was the first indication that the miter limit for PDF should be at least 1.0.

I know how to fix one part of the issue in Qt, but it doesn't solve all aspects, and it will not be possible to get this into Linux distributions very soon. Maybe the current framing approach has to be changed.

**Comment by Symbian9** [comment]
What about converting text frame to filled path befor export?

**Comment by dg0yt** [comment]
@Symbian9 The problem is getting the text frame (white) from the the text (red), and get it right from A - Z. Really, I don't need this kind of support.

**Comment by Symbian9** [comment]
@dg, anyway, look at this "Stroke to Path" option, that I told about.
![stroke2path](http://i.stack.imgur.com/PDlQU.png)
http://graphicdesign.stackexchange.com/questions/50703/how-can-i-convert-a-path-to-a-shape-in-inkscape

**Comment by dg0yt** [comment]
The unstable packages are updated now.
