### ISSUE TITLE
can't save file without merge part on mac OS

### ISSUE THREAD

**Issue by Gaspard01** [OpenOrienteering/mapper#667]
Hi,
I use mapper 0.6.0 (Darwin-x64.dmg) on mac OS 10.7.5
when saving a file I get the message :

> Older versions of Mapper do not support multiple map parts. To save the map in compatibility mode, you must first merge all map parts.

I first get this message when working on a map created with mapper 0.6.0 on windows
saving on windows works fine
saving on mac works "strange"

if I create a new file on mac I still get this message if the map has several parts. Saving in xmap file I look at the code and I see :

map created on windows
```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://openorienteering.org/apps/mapper/xml/v2" version="6">
```

map created on mac 
```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://openorienteering.org/apps/mapper/xml/v2" version="5">
```

why the mapper 0.6.0 on mac does save file with version 5 in the "map" markup ?

**Comment by dg0yt** [comment]
This is **Settings**, **Retain compatibility with Mapper 0.5**. Your choice (at the moment).
