### ISSUE TITLE
Add template / raster issue

### ISSUE THREAD

**Issue by gudeso** [OpenOrienteering/mapper#669]
I have recently started to use the Open Orienteering Mapping Software, however when i add a template / raster it looks empty, see screen snapshot attached? have you encountered this issue before? changing opacity did not help.. any advice will be appreciated.

cheers 
![screenshot 2016-05-17 11 35 10](https://cloud.githubusercontent.com/assets/19400860/15310683/1157de44-1c25-11e6-88ee-2b7eab3e50e0.png)

**Comment by dg0yt** [comment]
There is no known issue with raster images. Did you try the action View > Show whole map?

**Comment by gudeso** [comment]
That helped! Thank you..
