### ISSUE TITLE
Opening OziExplorer's files as templates

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#67]
**Somebody reported on Sourceforge [[tickets:#67](https://sourceforge.net/p/oorienteering/tickets/67)]:**

Add compatibility for OziExplorer's:
a) map's (image file+.map; ozf2; etc.) 
b) trek's and waypoint's (.plt;
.wpt; etc.)

Maps, treks, and waypoints for OziExplorer are already georeferenced, and its only need to add support for this file formats into Mapper, and then it's easy will can use their as templates.

Links with info about OziExplorer's file formats:
1) OSM Wiki - File format compatible with OziExplorer 
http://wiki.openstreetmap.org/wiki/Oziexplorer#file_format_compatible_with_oziexplorer
2) Help Ozi - Data File Formats
http://www.rus-roads.ru/gps/help_ozi/fileformats.html
3) Help Ozi - Map File Formats
http://www.rus-roads.ru/gps/help_ozi/map_file_format.html

**Comment by Symbian9** [comment]
Import images with .map calibration/georeferencing map
* http://www.oziexplorer3.com/eng/help/map_file_format.html

There are many detailed raster topo maps already distributed with *.map files

Also few applications for downloading online maps, that can export single image with .map file
* http://www.sasgis.org/sasplaneta/
* http://mobac.sourceforge.net

**Comment by Symbian9** [comment]
Is there any progress on import *OziExplorer*'s georeferenced image (`name.jpg`+`name.map`) as template?

**Comment by dg0yt** [comment]
In principle, GDAL raster support covers OziExplorer's .map files. However, GDAL fails to provide information about supported filename extensions, so this driver is ignored by Mapper at the moment.
