### ISSUE TITLE
Selecting page in size in pdf export is broken

### ISSUE THREAD

**Issue by matkoniecz** [OpenOrienteering/mapper#670]
Mapper 0.6.1, Lubuntu 14.04 32 bit.

Select File | Export as... | PDF

Change page size (for example A4 to A3).

Note that page coverage of map is not changing and page size (below page format selector) is not changing.

**Comment by matkoniecz** [comment]
Workaround: go to "Select File | Export as... | Image", select wanted size, cancel export, export as PDF.

**Comment by dg0yt** [comment]
There is an issue, indeed. 

However, I'm not sure if I will fix this for Lubuntu 14.04. There were significant changes to print support in Qt 5.3. Ubuntu has a new long term support release, und Ubuntu 14.04 is really the last supported system which has a Qt < 5.3 (https://github.com/OpenOrienteering/mapper/wiki/Target-systems).

**Comment by matkoniecz** [comment]
Fixing it for Lubuntu 16.04 (if it even needs fixing) would be enough at least for me - I plan to switch to the new LTS (as soon as I will confirm that the most important software works there).

**Comment by matkoniecz** [comment]
Thanks!
