### ISSUE TITLE
Lost template cannot be removed from template setup window.

### ISSUE THREAD

**Issue by zmalinowski1968** [OpenOrienteering/mapper#671]
Seen on version 0.6.1.

When you lost one of your visible/active template files for any reason, you get error message while opening a map. Template is listed in brown-red color. You are not allowed to detach/hide/remove template from template list. Very annoying.

To reproduce here's my example.

1. I have a map calles Runow03.xmap with attached visible tamplate RunowHips1.jpg.
2. I save the map in OOMapper.
3. I change the name of template file from RunowHips1.jpg to RunowHips100.jpg.
4. I open Runow03.xmap in OOMapper, I get error message while opening telling the template does not exist.
5. I open Template setup window to displey templates. RunowHips1.jpg is on the list in red-brown but I cannot remove it. While clicking on template name I'm only allowed to select another file. I'm lucky if I have one otherwise I can do nothing about it. 

Same behavior on Android App.

**Comment by dl3sdo** [comment]
It seems that this is a known issue which is already solved for 0.6.2, see #586 
Have you tried the unstable build?
