### ISSUE TITLE
Switch to Qt 5.6

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#673]
Expected improvements:
- Improved high-resolution display support
- Various improvements for Android
- GPS availability on Windows

However, these changes will need good testing.

**Comment by Symbian9** [comment]
Qt 5.7 released
* https://blog.qt.io/blog/2016/06/16/qt-5-7-released/
* https://wiki.qt.io/New_Features_in_Qt_5.7

**Comment by dg0yt** [comment]
Qt 5.6 is a long term support release, and reached 5.6.1 recently. 5.7 is not under consideration at the moment.

**Comment by dg0yt** [comment]
Qt 5.6.2 is coming soon...

Qt 5.6 doesn't build the JPEG2000 (jp2) plugin by default unless there are system libraries (http://code.qt.io/cgit/qt/qtimageformats.git/commit/?id=531c30ea66d2b8fe517c89bed149a938e16332ec). Options are:
- trigger the build manually
- don't deploy qjp2 plugin (GDAL could take over eventually).

**Comment by dg0yt** [comment]
Using Qt 5.6.2 + patches via superbuild for Windows, macOS and Android.
