### ISSUE TITLE
New superbuild system

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#674]
The superbuild system (for building dependencies such as Qt, Proj.4, Gdal) needs to be factored out of the Mapper repository.

**Comment by rugk** [comment]
Wanna tag this with [build](https://github.com/OpenOrienteering/mapper/labels/build)?

**Comment by dg0yt** [comment]
All needed dependencies including curl and serial port support can now be build from OpenOrienteering/superbuild on openSUSE's build service. Mapper itself remains to be done.

**Comment by rugk** [comment]
But please don't host your builds there. (At least the stake versions) Still build them manually, probably sign them and upload them to GitHub.

**Comment by dg0yt** [comment]
Actually it is a feature that the unstable snapshots and the stable releases are build and provided in the same environment. What is the argument against the binaries provided there? 

Doing release builds for Windows locally means even more work locally. And we will need to provide even more 3rd-party sources und build scripts on Github... 

OTOH, this suberbuild is what makes it somewhat feasible to do more builds, because it can share the sources between Android arm, Android x86, Windows x32, Windows x64, it can build in parallel, and it can easily reuse the 3rd-party binaries when doing new builds.

**Comment by rugk** [comment]
I just don't like the insecure way [OpenSuse deploys their binaries](https://forums.opensuse.org/showthread.php/519595-Use-HTTPS-for-GPG-key-download).

**Comment by dg0yt** [comment]
Okay, security is valid reason to request changes. 

I acknowledge that shipping .EXE files from OBS is uncommon. But OBS does provide a secure and reproducible way to build binaries. I'm under the impression that some changes have been done to OBS since last year. 

The question of code signing is somewhat orthogonal. We would need to acquire an appropriate certificate, for Windows and for macOS.

**Comment by rugk** [comment]
Well... the code signing for Win and MacOS, sure. However generally you can also just sign the binaries with PGP. But both would be awesome, of course.

**Comment by dg0yt** [comment]
Superbuild is now working well on Linux and macOS, including cross-compiling on Android for Windows and Android. The Windows build on openSUSE OBS is based on this superbuild. By Debian tarballs, we collect copyright information and receive security fixes.
