### ISSUE TITLE
overprint doesnt work on OCD files

### ISSUE THREAD

**Issue by FEK10** [OpenOrienteering/mapper#675]
every time i open a ocd file and edit it and save it there is not overprint on it

**Comment by dg0yt** [comment]
This is expected at the moment. 

As displayed in the import warnings, mapper doesn't import spot color definitions when opening an OCD file. And for saving, I would need to touch the exporter which is a piece of code which I will rather rewrite than extend.

**Comment by dg0yt** [comment]
#205 tracks spot color import/export for OCD files.

**Comment by dg0yt** [comment]
This is resolved.
