### ISSUE TITLE
Templates in Export/Print Incorrectly Overrides Template Setup Window

### ISSUE THREAD

**Issue by xc-racer3** [OpenOrienteering/mapper#681]
After going to either Export (jpg or pdf) or Print, and choosing not to have the templates appear on the exported/printed map, the map itself hides the templates.  If instead of choosing to export/print the map, you click "close" on the dialogue box, you go back to the map editing screen, but the hidden templates do not re-appear.  The templates setup window will still say that the templates are visible, but changing their settings will do nothing; however, going and re-selecting Export/Print you can check the box "show templates" and then "close" and the templates will reappear and the template setup window will function again.
Tested in 0.6.1 in Windows.

**Comment by dg0yt** [comment]
This is likely to be fixed in 0.6.2 (by https://github.com/OpenOrienteering/mapper/commit/84a05a8a8641542e17dcf4b1299af6d75eec8b7c) but it was never not reported here.

If you find trouble in 0.6.2 please open a new issue.
