### ISSUE TITLE
Personal message to members

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#682]
Hi, all!
I yesterday send e-mails to both core members of OpenOrienteering project, but not have an answer yet.
Is e-mails, presented in your github profiles correct?

Also, where now we can discuss OOMapper? Earlyer we discuss all about related on mail lists located on old sourceforge project pages.

Kai, thank you anyway.

Regards,
Eugeniy F.
ukrainian translator team

**Comment by dg0yt** [comment]
My e-mail address is correct, of course. I get a lot of spam for that reason. And the sourceforge developer mailing list is still functional.
