### ISSUE TITLE
Broken colors after 'Replace symbol set' action

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#683]
Steps to reproduce:

1. Open map with old symbol set
2. Select all unused symbols
3. Remove all selected symbols
4. Use _Symbol -> Replace symbol set..._
5. Choose symbol set source file (It is ISOM 201X from orientering.no in my case)
6. Unset check-box '_Match replacement symbols by symbol number_'
7. Configure and perform the replacement

**Expected result**: All symbols are visible
**Actual result**: Only brown symbols are visible

Affected versions: 0.6.2, 0.6.20160602
Can't reproduce in 0.6.20151220
Tested on platforms: Windows x64, Gentoo Linux x64.

**Comment by Symbian9** [comment]
Related
* https://github.com/OpenOrienteering/mapper/issues/612

**Comment by dg0yt** [comment]
@Symbian9 Don't add speculation or nonsense noise to the issues, or you will be blocked.

**Comment by dg0yt** [comment]
Actually related is this: Creating new symbols from new colors (guess: in a new map...) will suffer the same: empty preview in symbol editor, empty icon. (This was an attempt to create a minimal example for reproducing this bug.)

**Comment by dg0yt** [comment]
@yevhenmazur  Can you check if this bug is still present in the "unstable" snapshots? As far as I can tell, the fix for #688 seems to have fixed this one here, too.

**Comment by yevhenmazur** [comment]
Still reproduced in 0.6.20160606. I'm on a field-work now and can't build OOM from trunk. I'll be able to check it after weekend.

**Comment by dg0yt** [comment]
I'm sorry, the latest build (20160607) wasn't published, but it is triggered now. This is trunk, then.

**Comment by yevhenmazur** [comment]
0.6.20160609 works as expected. Thanks a lot!

**Comment by dg0yt** [comment]
So this issue was a result of #688.
