### ISSUE TITLE
Map objects may become invisible after print or export

### ISSUE THREAD

**Issue by tinnishill** [OpenOrienteering/mapper#685]
Here's my first ever bug report.

I am making my first attempt at using OOM. I have version 0.6.2. , running on Ubuntu 16.04. I had loaded a dxf template of 5 meter contours and had traced about half of the area on to the map. I had the one template and the map with a grid on it. Just to see what it looked like on paper, I exported the work as an image and printed it. It looked fine. When I went back to OOM to resume work both the template and the map have disappeared, leaving only the grid. Checking the Template Setup window, both “Map” and “contour.dxf” are still listed, so presumably the work was still there but invisible. I assumed that I have somehow mis-selected something. 

I then started a new map, did a couple of hours work on it and tried the Print option, with the same result as the first attempt. I then removed and reinstalled the OOM from the machine and tried to reopen the saved .omap files; same result. Next I installed OOM on a different laptop running Ubuntu 14.04, then transferred my saved files between machines. Opening the files on the new machine found the same result.

Next I went back to the first machine and tried fiddling with settings. In Print, changing map area and page area both to "custom"  resulted in in my work reappearing but not the template. Deleting and reinstalling the template didn't help.

Regards.

**Comment by dg0yt** [comment]
I think it is a visibilty issue with the "- Map -" layer in the template window. I cannot (yet) reproduce this particular issue but I can reproduce some inconsistencies between indicated and actual visibility. However, toggling the check mark usually fixes it.

**Comment by tinnishill** [comment]
Some more information.

I started a third attempt at the map, tracing the same dxf file. It was all looking OK, I saved the work, closed the machine, and opened up again in the morning. On opening the map there was a warning box which read “ The map imported generated warnings. Some coordinates were out of bounds for printing. Map content was adjusted.”. I OK’d the warning and the work opened with the same result I had previously had, the grid is there but both map work and dxf template are invisible.

Cheers.

**Comment by dg0yt** [comment]
Did you try View > Show whole map?

The warning about out-of-bounds coordinates should not appear for files created in Mapper 0.6.2, normally, but it should not create problems anyway.

You can send me sample files directly via e-mail. This may be the only way to reproduce the issue.

**Comment by tinnishill** [comment]
Hallo Kai,

Thanks for your time. I did  try View > Show whole map, but just got a blank window. I think that this has been an operator error on my part. I have done a complete reinstall on the old lap top I am using for mapping, done super carefully and all now seems to be working. I am not sure, but I think that I might have done something wrong with georeferencing the dxf file I loaded first. Anyway, sorry to bother you. I have been writing careful notes as I go along of what works and what doesn't, so If anything weird happens I should have a better idea.

Regards.

**Comment by dg0yt** [comment]
Okay. I still suspect there are some hard-to-reproduce bugs left in the context of switching between print/export and normal view. And even if there is some room for user mistakes,  Mapper should make it hard to do such mistakes. So please report if you find some weird behavior which is reproducible.

**Comment by otoomet** [comment]
Can confirm the issue in 0.6.3, unfortunately not easy to replicate.  

I have a map with 5 templates, one of these is the map itself (related to a different issue).  When exporting to pdf several times, where the map (the uppermost layer) itself being invisible but two templates visible, the map became visible, in fact.  However, this was not reflected in the template window checkbox.  (It was also a bit confusing because it looks exactly as the map-template.)

**Comment by dg0yt** [comment]
@otoomet is reporting that after returning from exporting with the map layer invisible, the map layer became visible, but the check mark in the template window was missing. This is something I can reproduce easily.

However, the original post claims that after returning from exporting with both template and map visible, the map and template became invisible. The state of the check marks at this time wasn't reported.  This is something that I cannot reproduce (yet).

Anyway, these are quite opposite observations, only related by the fact that the misbehaviour occurs after returning from print/export.
