### ISSUE TITLE
Crash after move text in symbol description input field

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#687]
Reproducing:
* run OOMapper
* create or open any map
* open any symbol for editing
* in "General" tab of "Symbol settings" dialog select text in "Description" input field
* now try drag selected text by mouse

RESULT: program fully crashed

In terminal I got only <code>Segmentation fault</code> message string.

Tested on versions: 0.6.2(stable) and 0.6.20160602(unstable)
System: Trusty 14.04, 32bit

**Comment by dg0yt** [comment]
I cannot reproduce this crash on Ubuntu 14.04, 64 bit. Dragging text works as expected. 

This dragging feature is provided by Qt. Please check that this crash does not happen in other multiline editors, such as the map notes, or in other Qt application, such as Qt Linguist.

**Comment by Symbian9** [comment]
@dgOyt, yes its also happen with map notes input field and about dialog too.
So, its work not only in input field but if select text in info dialogs too.

**Comment by dl3sdo** [comment]
As Kai, I cannot reproduce this crash on Ubuntu 14.04, 64 bit. Dragging text from and to gedit works as expected.

**Comment by dg0yt** [comment]
I cannot reproduce this on Ubuntu 14.04 32 bit. It is likely to be an issue on your computer or with your locale, but not an issue in Mapper.
