### ISSUE TITLE
ISMTBOM translated to ukrainian

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#691]
@dg0yt, please, check your mail box for message with "ISMTBOM_uk.zip", that I send you!(its include translated symbol sets)

ISMTBOM symbol sets with ukrainian translation already fixed according to https://github.com/OpenOrienteering/mapper/issues/690

Reference:
http://orienteering.org.ua/Federacia/komisii/ISOM-MTB-UA-2012.pdf

**Comment by dg0yt** [comment]
You don't need to ask me to check my mailbox, and you don't need to send e-mails to multiple mail accounts. Including the automatic notification for this issue I have three e-mails now on this issue. This doesn't make anything faster.

**Comment by Symbian9** [comment]
Ok, sorry. So, you got zip file, right?

Anyway, which one email I can use for connect with you in future: on "mailbox.org" or on "darc.de" hosting?

**Comment by dg0yt** [comment]
There is an e-mail address published on Github, isn't it.

**Comment by Symbian9** [comment]
Ok. So, please, if you got my symbol sets give me an answer.

**Comment by dg0yt** [comment]
See my first comment: I have got three e-mails on this issue. And this is how it comes to three: There is the notification for #691, and the two copies of your personal e-mail with the ZIP.

**Comment by Symbian9** [comment]
Okey. Now I work on next translation of other symbol sets (ISSkiOM_uk, ISOM_uk, ISSOM_uk), that would try send in one email without duplications.

Thank You, Kai.

**Comment by dg0yt** [comment]
The preferred way of sending these changes and additions is either pull requests, or attachments (ZIP) to issues.

**Comment by Symbian9** [comment]
Yeah, but... I have connection only from my old mobile with GPRS and cant make pull request (phone browser not fully support github). When I try attach ZIP to issue it always give me an error. This is long story.

And thats why I still send it by email.

**Comment by dg0yt** [comment]
[ISMTBOM_uk.zip](https://github.com/OpenOrienteering/mapper/files/305401/ISMTBOM_uk.zip)

**Comment by Symbian9** [comment]
@dg0yt, Please, fix "302 Pond" symbol, that was automatically added to ISMTBOM_uk (now I test in fresh unstable built)

Current symbol in English, so fix it in ISMTBOM_uk by changing title from <code>Pond</code> to <code>Ставок</code>.

Also replace this English description with this translated:
<code>Малі площі води відображають суцільним кольором.

Це УЗ &quot;302 Ставок&quot; зі стандарту ISOM, але також є варіантом УЗ &quot;301 Озеро&quot; у специфікації ISMTBOM.</code>

Reference:
* https://github.com/OpenOrienteering/mapper/commit/6746b39d3b87cb252e9a29d6fe76cab597142d37
