### ISSUE TITLE
Compilling with Qt4 (question)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#692]
I few times think about it, and now back to this again: is it possible compile OOMapper 0.6.x with Qt4?

Now Qt5 very big and not fully supported by older Linux distro and have huge dependencies, that not presented in Qt4 tree.

This is not a request, but only question. So, it's not in high priority, but very interesting for me.

References:
* https://github.com/OpenOrienteering/mapper/wiki/Qt5
* http://stackoverflow.com/questions/19373486/porting-qt5-app-to-qt4

**Comment by dg0yt** [comment]
[Mapper needs at least Qt 5.2 at the moment.](https://github.com/OpenOrienteering/mapper/blob/v0.6.2/INSTALL.md) It uses a lot of features which are not available in Qt 4. The most significant change is the new connection syntax.

It is very likely that I raise this to Qt 5.3 with Mapper 0.7, dropping support for Ubuntu 14.04 (and Mint 17) which is [the oldest system we support](https://github.com/OpenOrienteering/mapper/wiki/Target-systems).

More than two years after #263, this isn't much of a surprise...

**Comment by Symbian9** [comment]
Please, keep support for 14.04 as long as it would be possible.

So, what least binary of OOM has support to Qt4?

**Comment by dg0yt** [comment]
Please don't keep me busy with that old stuff.
