### ISSUE TITLE
Opening message cut.

### ISSUE THREAD

**Issue by amalpeyre** [OpenOrienteering/mapper#693]
Hello, at the opening of OOMapper, the message is cut and I have to resize window to read it entirely. Maybe the fonts could be justified.

Bad :
![capture du 2016-06-09 10-00-04](https://cloud.githubusercontent.com/assets/11599504/15922650/24994734-2e29-11e6-8874-9c61cd43cc01.png)
Good :
![capture du 2016-06-09 10-00-19](https://cloud.githubusercontent.com/assets/11599504/15922649/247e9aec-2e29-11e6-86a1-77250b6e71a0.png)

Arnaud.

**Comment by dg0yt** [comment]
Well, this message is much shorter in English. For now, adding line breaks must suffice.
