### ISSUE TITLE
Windows: Occasional crash on print preview

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#695]
Mapper 0.62 Win x64 crashes sometimes on Win7 at print preview with the XPS document writer.
This happened before and was fixed, see #538 
However, the difference to #538 is that the crash already happens, when pressing the "Preview..." button.
Note: Mapper 0.61 Win x64 does not crash.

**Comment by dg0yt** [comment]
Does it also crash when printing these files? For 0.6.2, I introduced native printer properties for Windows. But this should be the same code path for preview and for printing:
https://github.com/OpenOrienteering/mapper/compare/1eaa24d...fd17b75

**Comment by dl3sdo** [comment]
I notice that sometimes the Preview is fine. If you close the Print window, open it again, then the Preview is crashing, sometime you have to repeat that procedure some times until the crash happens.
Printing seems to work: I can print to the XPS device, after printing the Preview crashes.

**Comment by dl3sdo** [comment]
Creating a new map, adding just a single point object, it seems that I need 3-4 Previews until the crash happens, so it is independent of the complexity of the map.
Although it looks like as maps with more objects are more likely to crash at the first Preview.
Apparently printing to XPS always works! In most cases a succeeding Preview crashes.

**Comment by dg0yt** [comment]
Confirmed.
