### ISSUE TITLE
How create new map in OOMapper on Android?

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#697]
I tested latest release of OOM v0.6.2 on Android and can't find buttons like "Create new map", "Open map" and "Save as".

I sew only "Examples" button and using it can open only 2 presented examples, but cant save them after modifications using button "Save".
 
Any ideas?

**Comment by dg0yt** [comment]
It is not possible until more work is done on the user interface for android. You need to prepare your map on a PC.
