### ISSUE TITLE
Fix "302 Pond" in ISMTBOM_uk symbol sets

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#698]
Please, fix "302 Pond" symbol, that was automatically added to ISMTBOM_uk (now I test in fresh unstable built)

Current symbol in English, so fix it in ISMTBOM_uk by changing title from <code>Pond</code> to <code>Ставок</code>.

Also replace current English description with this translation:
<code>Малі площі води відображають суцільним кольором.

Це УЗ &quot;302 Ставок&quot; зі стандарту ISOM, але також є варіантом УЗ &quot;301 Озеро&quot; у специфікації ISMTBOM.</code>

Reference:
* https://github.com/OpenOrienteering/mapper/issues/691
* https://github.com/OpenOrienteering/mapper/commit/6746b39d3b87cb252e9a29d6fe76cab597142d37

**Comment by dg0yt** [comment]
I did this correction three days ago, it just wasn't published on Github yet.

Don't edit your comments too often, it means double work for me when I must compare the old notification and the new issue. Rather take a breathe, and think twice before posting.

**Comment by Symbian9** [comment]
It (pond symbol in ukrainian sets) already added into unstable builds, so I cant understand how it  was possible if you sad that it was not published on github.

**Comment by dg0yt** [comment]
I said *the correction* was not published, on Github... Publishing the unstable builds is even another step.
