### ISSUE TITLE
Adjust precision for freehand line?

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#701]
Question: Is it possible to adjust the accuracy for the freehand line tool? The fastest way in the field is to use freehand mode, especially when doing revisions/minor changes on existing map. It seems the zooming in does not make the precision better? 

Would be nice to let the user change so that OOM save points more often when using free hand tool för lines.

**Comment by dg0yt** [comment]
Analyzing the source code, my findings are: Initially, the free hand tool is quite accurate, adding a new point every 0.06 mm. However, there are some other effects:
- The path, no matter if drawn fast or slowly, is passed through a simplification step when it is finished. This is is a special implementation, not the same as the tool "Simplify path".
- For a fast move, it is very likely that the tool doesn't receive every single point, but only "compressed" move events.

**Comment by dg0yt** [comment]
There is even an open issue for different levels of simplification with "Simplify path", #275.

**Comment by Zerbembasqwibo** [comment]
When I use freehand tool, the line is ver accurate. But when I finish the line, it become very much simplyfied. It's that simplification step I wish would be possible to make less rough to keep the small turns of lines in a better way.

**Comment by krticka** [comment]
I must confirm that simplification step how is implemented now is making freehand tool useless. For such reason I am not using it in terrain. Today I was making photo interpretation for which is freehand quite suitable tool, but I had to switch to ocad as simplification is too strong and wanted details are missing then.

**Comment by dg0yt** [comment]
I looked into this tool recently (on desktop). There are more remarks to add to above analysis:
- The recorded points (before simplification) are discretised (by pixels on screen). So rather than just removing points, real smoothing is needed.
- For the purpose of recording and smoothing, time (speed) could be taken into account. Slow drawing would create more points taken influence on the curve.

**Comment by Zerbembasqwibo** [comment]
Sounds great!

2017-08-25 9:43 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
As an intermediate step, I would be willing to add a setting to turn simplification off in v0.8.0.

**Comment by Zerbembasqwibo** [comment]
I can try new version and look for bugs as soon as there is something to
test.

2017-08-25 9:48 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
The tool now respects the current zoom for both drawing and simplification. You can test the unstable build (for Windows and Linux). FWIW it now works sufficiently well. (Only smoothing the discretization is not implemented yet.)

**Comment by Zerbembasqwibo** [comment]
I got two blue screens while starting 0.8.20180826 for Win 64 on Win 7 pro. I saw the list of files, and when starting new map it died and crashed computer. Maybe it's AVG that disturbes?

**Comment by Zerbembasqwibo** [comment]
Something went wrong on installation. As I can see it works nice now! Must try in field or on real job to see if there still are necessary improvements to do. Is it also implemented on Android?

Great job again!!

**Comment by dg0yt** [comment]
There shall be an explicit 0.8.0 preview version soon, also for Android and OSX.

**Comment by Symbian9** [comment]
> There shall be an explicit 0.8.0 preview version soon, also for Android and OSX.

Yeah, it would be cool release preview version for all supported platforms for testing and debuging before release stable 0.8.0.
