### ISSUE TITLE
Symbol numbering inside symbol sets modification

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#704]
Now in-built symbol sets have some issues with numbering additional symbols or their variants.
In official specifications there are no any 3rd level numbering, and additional symbols numbere use 2nd level. I propose use 3rd level numbering only for symbols like border line, pattern fill, minimum size, etc.

I propose use next <b>symbol numbering scheme for all symbol sets</b>:
- XXX.0 - main symbol number as it shown inside specification (101 or 302)
  - XXX.Y.0 - additional symbol as it numbered inside specificatins (101.1 or 301.1, 301.2)
    - XXX.Y.Z - special future or variant that additionaly created in OOMapper and needed for better usability, something like minimum size symbol or separate symbol with border line (101.0.1 or 301.2.1) and title must include character ":" for separate additional symbol info "Building: minimum size"

For example, if in Mapper we need create separate symbol with only border line, that based on "301 Uncrossable waterbody" then we must create "301.0.1 Uncrossable waterbody: bank line", and NOT "301.1 ..." because 2nd level numbering can be specified only in official specifications! It will help remove confusion like it now presented inside in-built ISSkiOM symbol sets, where official symbol "301.1 ..." renumbered to "301.0.1 ..."

Thats why need review all currently presented symbol sets in OOMapper and fix them according presented scheme (see above).

**Comment by dg0yt** [comment]
When I ever touch that, two more aspects should covered:
- Numbers should be prefixed with some "namespace" such as "iof", "issom2007" or "ocd". This could help with duplicate numbers after import/replacement of symbols.
- There should be some "hinting" for helping replacing symbols in maps created with previous version of the symbol sets.

**Comment by dg0yt** [comment]
We now have flexible replacements with CRT files. I still plan to add a symbol set identifier/namespace.

**Comment by dg0yt** [comment]
Maps now carry a symbol set ID. It is used for translations, and it might be used for CRT file selection or similar in the future.

The new ISOM2017 intentionally uses only xxx.y numbers.

**Comment by Symbian9** [comment]
> The new ISOM2017 intentionally uses only xxx.y numbers.

Need make review for numbering inside "Controls Description-2018"

* https://github.com/OpenOrienteering/mapper/issues/896
