### ISSUE TITLE
save to ocad crashes

### ISSUE THREAD

**Issue by snefat** [OpenOrienteering/mapper#710]
Open Orienteering mapper 0.6.3 crashes when I try to save to ocad format. The map I'm using is first drawn in OCAD 12 test version. Opened by open orientering mapper. OK to save in .omap-format but not to .ocd format.

**Comment by dl3sdo** [comment]
Please tell about your operating system and the Mapper version you use (e.g., 32 bit or 64 bit).
Does it always happen?

p.s.: I just made some tests with exports to .ocd (Win7, 64bit Mapper) and could not encounter any crashes.

**Comment by snefat** [comment]
Hi,
Windows 10
64-bit version.

I've only tried it today but it happens every time. Have only made it work with an almost blank map I made in mapper. But with the full map I previously made in ocad it did not work.

**Comment by dg0yt** [comment]
I'm sorry, but can't reproduce this issue with the files I have. You will need to provide a minimal sample file which reproduces the issue for you. You may send me a direct e-mail if you don't want to have the map in the public.

**Comment by dg0yt** [comment]
Do you a path (line, area) object with more than 32768 points? This is easily possible in Mapper and OCD >= 9, but may cause errors in Mapper's OCD 8 export.

**Comment by dg0yt** [comment]
No response, closing.
