### ISSUE TITLE
Geology symbol sets

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#711]
Here I will collect detailed specifications, that would help make "Geology" symbol sets soon.
* FGDC Digital Cartographic Standard for Geologic Map Symbolization
  * https://www.fgdc.gov/standards/projects/FGDC-standards-projects/geo-symbol
  * http://ngmdb.usgs.gov/fgdc_gds/geolsymstd/download.php
* ...

**Comment by dg0yt** [comment]
This will not be included "soon". Feel free to provide it yourself.
