### ISSUE TITLE
Selection to point symbol

### ISSUE THREAD

**Issue by gitdark** [OpenOrienteering/mapper#712]
I have a feature request. I would like an option to convert a selection of area objects to a point symbol. That feature will simplify a lot things like converting vector logo to point symbol. I converted my orienteering club logo to point symbol by editing .omap file and copying area objects into point symbol elements. That was slow and difficult process.

**Comment by Symbian9** [comment]
Duplication
* https://github.com/OpenOrienteering/mapper/issues/440

**Comment by gitdark** [comment]
@Symbian9 Thanks! I have the logo in SVG format, and I could import it as a template, but I thought it would be better if I make a point symbol with logo. My workflow was: export logo to DXF with Inkscape; import DXF in Mapper; change symbol type and scale it; create a point symbol "Logo" with one area element; save OMAP; edit OMAP in text editor and copy logo area objects into point symbol "Logo" area elements; load OMAP in Mapper and edit "Logo" symbol elements (center all elements, change color of area elements). I'm happy with the result, but it took lot of time.

**Comment by dg0yt** [comment]
Subscribe to #440 instead.

**Comment by M0OJM** [comment]
Symbol Editor

In the symbol editor there is the ability to add a point, line or area element but not a text element (Type 8).  I am trying to do this manually but struggling to get the correct syntax. 

It is very difficult to add co-ordinates to a line or area element as you can only pick one point at a time. Having the ability to click or drag in the "template" window, like in the normal drawing window, would be very useful for drawing on a template. Alternatively having the ability to just copy & paste a bit of map into the "template" window would be better still.

**Comment by dg0yt** [comment]
> In the symbol editor there is the ability to add a point, line or area element but not a text element (Type 8). I am trying to do this manually but struggling to get the correct syntax.

Don't expect this to work. You cannot add it because it is not supported.

This ticket was already closed. I'm locking conversation now. Having text as part of a point object is a different issue anyway.
