### ISSUE TITLE
Pasted text will not delete

### ISSUE THREAD

**Issue by PeterHoban** [OpenOrienteering/mapper#715]
I have copied some text from another map and pasted it into my current task.  I can move the pasted text from point A where ctrl-V pasted it to any point B, but a copy remains at point A.  I appear to be unable to delete the copy at point A.  The attached file has the problem manifest in the text "Basemap & Cadastral..."
A workaround would be welcome.  
Great software, thanks,  Peter
[Sample.omap.zip](https://github.com/OpenOrienteering/mapper/files/331453/Sample.omap.zip)

**Comment by dg0yt** [comment]
There are 23 identical copies of that text object. Select one of these objects, than invert the selection of symbols [!], than hide the selected symbols (i.e. all other symbols). Now it is easy to select all the identical text objects, and so I got the number (from the measure widget).

**Comment by PeterHoban** [comment]
Thanks Kai
    
    I cannot imagine how 23 copies were pasted.  Thanks for your fix.
    
    Regards,  Peter
    There are no problems more difficult to overcome than those which are merely imagined.
We never approach the truth in what we say unless that includes the expectation of being wrong.



    On 26/06/16 06:50, Kai Pastor wrote:
    
    
      There are 23 identical copies of that text object. Select one
        of these objects, than invert the selection of symbols [!], than
        hide the selected symbols (i.e. all other symbols). Now it is
        easy to select all the identical text objects, and so I got the
        number (from the measure widget).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
