### ISSUE TITLE
OCAD import: Area symbol loses outline.

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#716]
Having an OCAD10 map area-symbol which is combined with an separate outline-symbol this linking gets lost on import to Mapper (without warning).
![ocad](https://cloud.githubusercontent.com/assets/15611653/16433334/046d2cee-3d8a-11e6-950e-264d0ed12983.png) Symbol definition in OCAD.
![mapper](https://cloud.githubusercontent.com/assets/15611653/16433336/05d53a4a-3d8a-11e6-9fec-5f6bae848cce.png) Symbol definition in Mapper. Outline lost.
The simple workaround is to "fill" all objects of the area symbol in question with its outline symbol in Mapper. Would be nice to have 
1) a warning 
and 2) an automatic "fill" on import.

**Comment by dg0yt** [comment]
Can you provide a minimal test file?

**Comment by mlerjen** [comment]
![mapper2](https://cloud.githubusercontent.com/assets/15611653/16442484/39f5d070-3dd3-11e6-9b94-117af50683cc.png)

[http://www.ubol.ch/temp/Mapper.ocd](url) An OCAD12,consisting in a symbol 523.000 with a combined outline-symbol 523.013

**Comment by dg0yt** [comment]
It will get imported now, but we can't export it to OCD this way until we implement format V9 or later.
