### ISSUE TITLE
Course design and control description sheet symbol set

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#718]
Currently I'm near complete "Control Description" example with symbol set, that easy to use and fast to creating descriptions tables.
![Control Descriptions in OOM](http://pasteall.org/pic/show.php?id=104657)

All symbols are point ready for 6mm size boxes (use snapping to 3mm*3mm grid)

Think, it can be ready for this 65cm-wide holder
![Description holder](http://image.ol-shop.at/cache/data/zubehoer/descriptionholder-s-340x250.jpg) 

<b>References</b>:
* http://orienteering.org/wp-content/uploads/2010/12/IOF-Control-Descriptions-2004.pdf
* http://orienteering.org/a-project-to-revise-iof-control-descriptions/
* http://www.bko.org.uk/sites/default/files/basicpage/KYS-Control-Descriptions.pdf
* http://oalaska.org/training/meet-directors/course-design/
* https://ocad.com/wiki/ocad12/en/index.php?title=Course_Setting_Options

<b>Test skills</b>:
* http://www.richtig-orientieren.de/icd/
* http://www.wpoc.org/training.htm

<b>Related</b>:
* https://github.com/OpenOrienteering/mapper/issues/325

**Comment by dg0yt** [comment]
All right, but there are no really convenient tools for using it. And getting the symbols might have been less work using PurplePen's [symbol.xml](https://github.com/petergolde/PurplePen/blob/master/src/PurplePen/symbols.xml) which even has translations. (PurplePen is BSD-style licensed.)

**Comment by Symbian9** [comment]
@dg0yt, my symbol set fully from scratch work designed directly in OOMapper and not based on any part of PurplePen and have not any dependency to 3rd party software or licensing problems.

PurplePen good app, but it not fully work in my Linux distr with Mono installed. 

Also, I want use only OOMapper for whole mapping process without dependency to other applications.

I have some ideas for better course planning inside OOMapper, but firstly want complete this symbol set.

**Comment by dg0yt** [comment]
There are no problems with BSD licensed stuff, and reuse (or shared use) is the core of open source. We will need more contributions than extra symbol sets and ideas before course planning becomes a regular feature - I'm not even sure I will add such a symbol set to the official packages for now.

**Comment by Symbian9** [comment]
Well, I completed this symbol set and example,
So, after check if all correct I will send it to you.
![Control Descriptions example](http://pasteall.org/pic/show.php?id=104852)

**Comment by Symbian9** [comment]
<b>This example now availiable for testing!</b>
* http://profismart.org/f-193296.php

**Comment by Symbian9** [comment]
Direct link for this test file!
* http://d.profismart.org/files3/01/Control_descriptions-omap.zip

**Comment by Symbian9** [comment]
Now I try setup "control_descriptions.omap" for existing "sprint_sample.omap". This description file could be used as template in sprint map sample later
![Control description for Sprint map sample](https://z-1-scontent-lax3-1.xx.fbcdn.net/t31.0-8/fr/cp0/e15/q65/13411911_1116931028379952_2444159622042409209_o.jpg)

Direct link to updated "control_descriptions.omap" here:
* http://d.profismart.org/files3/01/Control_descriptions-for-sprint_sample_omap.zip

**Comment by Symbian9** [comment]
Add discussion thread on "Attackpoint"
* http://www.attackpoint.org/discussionthread.jsp/message_1174660

**Comment by dg0yt** [comment]
Now that snapping of text objects is done,I'm considering to give it a try. But it will need some modifications, so probably it won't make it into v0.6.4.

**Comment by Symbian9** [comment]
Cool and thanks! So, can you tell what I must fix in this template firstly?

**Comment by dg0yt** [comment]
Tentative version in https://github.com/OpenOrienteering/mapper/tree/course-design/symbol%20sets.

I still need to modify the FAQ symbol, or better move it to a manual page. The map notes are of no use (dropped) when this is used as a symbol set.

**Comment by Symbian9** [comment]
Think, better way is creating separate page in manual.

I create this "FAQ" symbol only for testing, and now you can remove it from this symbol set.

**Comment by dg0yt** [comment]
Description: http://www.openorienteering.org/mapper-manual/pages/course_design.html

**Comment by dg0yt** [comment]
Todo: Keep the grid settings when creating a new file from the course design symbol set.
