### ISSUE TITLE
"Text" object imported without any text symbols (from OCD file)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#720]
I try open this OCD file with logo
http://www.us.orienteering.org/sites/default/files/userfiles/u6/Orienteering%20USA%20logo.ocd

And found that it have not only polygons of logo, but one text object (look deeper, it was very small sized) that haven't any "Text" symbols in symbols list.

Maybe, Mapper must generate some "Text" symbol (with enabled "Helper symbol" checkmark) automatically for solve similar issues?

I found this file here:
* http://www.us.orienteering.org/mappers

**Comment by dg0yt** [comment]
The text you refer to doesn't have a symbol. It is an "unsymbolized object". It won't be printed or exported. Maybe the text is a little bit tiny at the moment, but well, there is simply no information in the OCD file. If it wasn't meant for deletion, you could create and assign a text symbol yourself.

**Comment by Symbian9** [comment]
@dg0yt, how create "unsymbolized object" from scratch in Mapper?

**Comment by dg0yt** [comment]
No.
