### ISSUE TITLE
Snap "Text" symbol before add on map

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#723]
Why its not possible snap text object when firstly try add it to map?

It must work similar to "Point" snap-before-add.

Now we need every time do one more unnecessary operation for every text object.
* select "text" symbol
* add it on map
* input text
* click outside input field for finish
* select this object (<b>unnecessary operation</b>)
* hold "Shift" for snap to needed other object or greed
* relax left mouse button after snapping, and then relax "Shift" tab

**Comment by dg0yt** [comment]
I guess this is related to editing control descriptions (#718)?

**Comment by Symbian9** [comment]
Its in some way related.

I also interested in possibility create "Combined" symbol that could consist from "Point" and "Text" symbols (both them already has mid point)

**Comment by dg0yt** [comment]
Closed in 6b5eab860ac7ae24f20ad89a15d4fd48edea0d9e (but with wrong reference in comment).
