### ISSUE TITLE
Redraw map after changing projection

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#724]
Now, if change projection settings, for example using "Custom PROJ.4" string, then coordinates would changed, but drawed map still shown as it was before changing projection.

![map](http://i.stack.imgur.com/SHUcv.png)

References:
* http://gis.stackexchange.com/questions/97589/creating-custom-projections-with-proj4

Related:
* https://github.com/OpenOrienteering/mapper/issues/722

**Comment by dg0yt** [comment]
Mapper is not a GIS. Mapper is for drawing an orienteering map on virtual paper. If you want reprojection, take a new sheet of paper (i.e. file), assign the desired projection, and import the original georeferenced file.

**Comment by Symbian9** [comment]
Ok, I will try it.
