### ISSUE TITLE
All ISMTBOM_uk has same symbol size

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#725]
Think, it was my mistake here:
* https://github.com/OpenOrienteering/mapper/issues/691

Currently I try fix it, and soon will resent "ISMTBOM_uk_5000.xmap", "ISMTBOM_uk_7000.xmap",  "ISMTBOM_uk_10000.xmap" with enlarged symbols.

**Comment by dg0yt** [comment]
The scaled .omap files are all created from the corresponding .xmap file in the src folder. If they are not scaled correctly, the issue is in tests/symbol_set_t.cpp.

**Comment by dg0yt** [comment]
The issue is in test/symbol_set_t.cpp which generates scaled symbol set .omap files from a single .xmap file.

**Comment by Symbian9** [comment]
So, can you check is problem in tests/symbol_set_t.cpp ?
