### ISSUE TITLE
"printtech2006.ocd" opening problems

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#726]
I try open "PrintTech2006", but few symbols have an issues
* http://lazarus.elte.hu/mc/print-tech/printtech2006.ocd

What a problems there are  with those symbols:
* 501.0 Motorway
* 501.1 Motorway under construction
* 502.0 Major road
* 502.1 Major road under construction
* 503.0 Minor road
* 503.1 Minor road under construction

Reference:
* http://www.openorienteering.org/mapper-manual/pages/mapping-introduction.html

**Comment by Symbian9** [comment]
Steps to reproduce:
* run Mapper
* goto "Open map..." dialog
* select "printtech2006.ocd" and try open it
* before it opened it give warning <code>The map import generated warnings.</code>, and in "Show Details..." it has info that in symbols 501.0-503.1 there is issues <code>This symbol cannot be saved as a proper OCD symbol again.</code>
* if anyway click to "OK" button it openned

So, what problem there? Think it in next version of Mapper "printtech2006.ocd" must be opened without issues, because this file is most known test case for orienteering mapping software.

**Comment by dg0yt** [comment]
File opens correctly, for what is meant to do.
