### ISSUE TITLE
Replace "spaces" with "_" in source files and folders naming 

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#727]
It would be good to replace "space" symbol with "_" in source files and folders names

For example:
* <code>/symbol sets/</code> must be renamed to <code>/symbol_sets/</code>
* <code>/example/sprint sample.omap</code> must be renamed to <code>/examples/sprint_sample.omap</code>

**Comment by dg0yt** [comment]
Why do you think it would be good? These non-sense tickets are annoying.

**Comment by Symbian9** [comment]
Because now in sources there is mix of "spaces" and "_": some folders and files already has "_" in their name, some other not.

"Spaces" symbol also is not good for file naming at all.
