### ISSUE TITLE
GDAL

### ISSUE THREAD

**Issue by gudeso** [OpenOrienteering/mapper#728]
Can anyone tell how to install GDAL to be used in OOM? couldn't find and guideline, as i want to import shp file to OOM. Thanks

**Comment by dg0yt** [comment]
You have to use one of the unstable packages.

**Comment by gudeso** [comment]
Which means what? Do we have guideline how to you or install them? Anywhere.. Cheers

**Comment by dg0yt** [comment]
They are found as "Development snapshots" on http://www.openorienteering.org/apps/mapper/, and they are installed and used like the regular packages, except that the packages and executables have "unstable" in the name. But of course, there is a reason why they are called unstable.

**Comment by gudeso** [comment]
Where i can find unstable version that supports SHP file, can you send a link? many thanks

**Comment by Symbian9** [comment]
@gudeso, try get them here
* http://download.opensuse.org/repositories/home:/dg0yt/

**Comment by dg0yt** [comment]
Today unstable builds solve some issues with GDAL e.g. #730.

**Comment by dg0yt** [comment]
To import a .shp file without accompanying .shx, add paramter SHAPE_RESTORE_SHX with value YES to the GDAL configuration in Mapper's settings.
