### ISSUE TITLE
Ocad import etrs-tm35fin

### ISSUE THREAD

**Issue by kshji** [OpenOrienteering/mapper#729]
If you have finnish coordinate etrs-tm35fin (EPSG:3067) used in Ocad and import that to the Omapper, you get error that coord ref 6005 is unknown. Ocad says that it's 3067.
When you have etrs-tm35fin, it's wide  UTM Zone 35 (not 24E - 30E).
When you calculate Convergence Angle, you need to use always Zone 35N. Ex. when using  GeoGraphLib.
Good testing is ex. 62.0000N and Lon: 29.90E  / 30.50E .
result shall be 2.56 and 3.09

Translating to finnish:
Declanation = "Neulaluvun korjaus (NEK)", older therm has been "eranto". "Deklanaatio" is not so much used.
Convergence Angle = "Napaluvun korjaus (NAK)"  negative from 27E to the east.
Grivation = "Kokonaiskorjaus (KOK)" ,  KOK=NEK+NAK 
Annual variation = Vuotuinen muutos

Source: http://www.maanmittauslaitos.fi/ammattilaisille/maastotiedot/koordinaatti-korkeusjarjestelmat/karttaprojektiot-tasokoordinaatistot/painetun-kartan

**Comment by dg0yt** [comment]
Import of georeferencing from OCD is work in progress. There is a combined-grid-and-zone field (with the value 6005 in your case), but so far I could only guess/test very few values (cf. https://github.com/OpenOrienteering/mapper/blob/master/src/fileformats/ocd_file_import.cpp#L286). It is also lost on OCD export, so I didn't even dare to announce this feature yet. However, these kind of reports help to add more support, so thank your very much.

**Comment by dg0yt** [comment]
For the record, testing declination/grivation/convergence seemed to work out-of-the-box for EPSG:3067.
