### ISSUE TITLE
Import of .shp fails

### ISSUE THREAD

**Issue by snefat** [OpenOrienteering/mapper#730]
I just tried the new unstable release, OpenOrienteering Mapper unstable 0.6.20160714, to test the GDAL import support.

I tried two scenarios for import. 1. with existing map, 2. with blank new map. Both scenarios ended upp with error in the import dialouge and the following message was displayed:

Error messages was:
```
Unable to load 54604 objects, reason: Can't determine the coordinate transformation: Unable to load PROJ.4 library (libproj-0.dll), creation of
OGRCoordinateTransformation failed.
```
and
```
Unable to load 7137 objects, reason: Can't determine the coordinate transformation: Unable to load PROJ.4 library (libproj-0.dll), creation of
OGRCoordinateTransformation failed.
```

Depening on what .shp-file I'm using and of course the number of objects in them.

**Comment by dg0yt** [comment]
This issue is solved in today's unstable build.

**Comment by dg0yt** [comment]
To import a .shp file without accompanying .shx, add parameter SHAPE_RESTORE_SHX with value YES to the GDAL configuration in Mapper's settings.
