### ISSUE TITLE
can't select objects from OSM template

### ISSUE THREAD

**Issue by nstjhp** [OpenOrienteering/mapper#732]
Using 0.6.3 on Linux (downloaded the i386 binary for Ubuntu 14.04 as this was closest to my system) I have loaded an OSM template and it appears as pink lines around the buildings etc. but I can't select these for further drawing. Have I done something wrong? I should just be able to click somewhere and select an object for then switching symbols or whatever right?

However when I load up the test maps that came with OOM I can select all the objects fine as I would expect. Thus have I loaded the OSM template incorrectly, or is there a bug somewhere here?

![screenshot](https://cloud.githubusercontent.com/assets/5261752/17079348/395efd4a-5105-11e6-885c-d9ec6d41d360.png)

**Comment by dg0yt** [comment]
Since you loaded as a template), it is just displayed. If you want to have selectable objects, you must import the template into your map.

**Comment by nstjhp** [comment]
Ah thank you, sorry I didn't see this in the manual.
