### ISSUE TITLE
Czech localization update

### ISSUE THREAD

**Issue by pafri** [OpenOrienteering/mapper#737]
Hi, here the file with Czech translation update - zipped archive as there is problem with uploading the .ts files directly
[OpenOrienteering_cs.ts.tar.gz](https://github.com/OpenOrienteering/mapper/files/401824/OpenOrienteering_cs.ts.tar.gz)
. Greetings, Pavel Fric

**Comment by dg0yt** [comment]
Hezky, https://hosted.weblate.org/projects/openorienteering/mapper/cs/.
