### ISSUE TITLE
List of passpoints not duplicated

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#742]
If passpoints are applied to a template, these are not duplicated if the template is
duplicated, i.e. the list of passpoints is empty, although it is possible to enable
and disable them by marking and unmarking the checkbox below the empty list in
the duplicated template.

Specifically tested after having a look at Template\* Template::duplicate() const
where the PassPointList passpoints; element is not duplicated.

Mapper Version: 0.6.4 x64
Operating System: Win7

**Comment by dg0yt** [comment]
The Template class hierarchy needs refactoring
- It uses a wrong pattern for object cloing.
- The base class includes a the superset of possible alignment features. It should be configuration instead. (This includes passpoints.)
