### ISSUE TITLE
Changing layer order

### ISSUE THREAD

**Issue by craigfeuerherdt** [OpenOrienteering/mapper#744]
When the symbols are moved in the symbol panel nothing happens in the map panel ie if I move a symbol to the bottom of the list all the other symbols should be drawn on top of it.

**Comment by dl3sdo** [comment]
In contradiction to many other 'normal' drawing tools there is no symbol layering in orienteering maps. The order of symbols is implicitly defined by their colors.
From the Mapper help: "each map file contains a prioritized list of available colors, where colors higher in the list overlap lower colors".

**Comment by dg0yt** [comment]
The reordering of symbols is just for convenience. The order of drawing is completely defined by the stacking of colors, as dl3sdo already pointed out.
