### ISSUE TITLE
Android: Problem with opening (and saving) maps

### ISSUE THREAD

**Issue by otoomet** [OpenOrienteering/mapper#745]
Sorry if missing something obvious--I am not good with android.

I created a folder OOMapper on the (external) sd-card on my android device, and copied a few maps + related templates there.  However, the Mapper still says "No map files found! Copy map file to a top-level folder named 'OOMapper' on the device or a memory card".

Do I understand correctly that "memory card" refers to "SD card", and alternatively I could use "Device storage"?

Samsung galaxy tab A, android 6.01

**Comment by dg0yt** [comment]
There is some variation how memory cards (typically SD cards) are represented internally (within Android) and externally (maybe depending on type of USB connection). Maybe some experimentation should give the fastest result for now. 

I will try to enable the file dialog soon, so we get more flexible on Android.

("sudo apt-get update
sudo apt-get install openorienteering-mapper" is unrelated to that issue, isn't it?)

**Comment by otoomet** [comment]
Thanks.  I was thinking that file dialogs might be useful.

Sorry, the apt-get is unrelated--copy-paste gone wild.

**Comment by dg0yt** [comment]
Wiko Sunny, Android 6.0, USB connection type MTP:
- Maps on the "internal memory" work as expected.
- Maps on the "SD card" don't appear in Mapper.

Can you confirm this? 

It was tricky enough to reliably determine the the external storage path before Android 6. Probably it needs another tweak (or permission). Mapper looks into
- environment variable SECONDARY_STORAGE
- environment variable EXTERNAL_STORAGE
- /mnt
- /mnt/sdcard
- /sdcard
- /storage

Unfortunately, the file manager on my test device won't start at the moment.

**Comment by dg0yt** [comment]
Even I manage to find the SD card, Android 6.0 allows Mapper only to read from the OOMapper directory, but not to write to it (i.e. save changes). I guess this has been the case for a while (Android 4.4 or 5) with some devices.

**Comment by dg0yt** [comment]
Long analysis: https://github.com/OpenOrienteering/mapper/wiki/Android#file-storage

Long story short: Without major changes, data can be written only to the "primary external storage volume" which may actually be a portion of the device's limited internal memory.

**Comment by otoomet** [comment]
Can confirm--it works if the folder is on the internal storage.  Unfortunately that one is in short supply..

**Comment by dg0yt** [comment]
The only thing I can offer in the short term is the application-specific storage with "synthesized permissions" - i.e. these files will be removed when you uninstall the app. 

I have got a working prototype which displays a warning when opening files from a "restricted" location. I still need to add hinting to Android's media scanner so that these files and directories become immediately visible to the PC via USB when using MTP. And I need to update the documentation.

**Comment by dg0yt** [comment]
New documentation: http://www.openorienteering.org/mapper-manual/pages/android-storage.html
