### ISSUE TITLE
Close button is not active

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#754]
### Steps to reproduce
1. In menu Map choose Georeferencing or any other option
2. Close button in top right corner is not active
3. -
### Actual behaviour

Close button in top right corner is not active
### Expected behaviour

Close button should be active and close window with mouse click.
### Configuration

Mapper Version: 0.6.5
Operating System: Win 8.1 64bit

**Comment by dg0yt** [comment]
How to deal with changed settings in the dialog?
- Traditionally: Open another dialog asking whether to save (Yes, No, Cancel).
- Modern: Save and close. Bu then the button bar should not offer Cancel. After all, there is Reset.

Remarks:
- On Linux, the close button does work, but drops changes.
- On Android, the modern approach is used for the settings dialog.

However we decide, this shall be consistent in all dialogs (settings, georefererencing, symbol properties, etc.)

**Comment by dg0yt** [comment]
No opinion?

I see some tendency to use the mobile app patterns also in desktop applications. Firefox can be taken as an example. This is a break in tradition in favour of simplicity.

**Comment by krticka** [comment]
I went trough some apps on Android and I think that modern approach is more suitable for dialog. Different situation is when you are doing some irreversible changes on data where traditional way is more suitable. Thinking about it, there is no simple solution.
