### ISSUE TITLE
Please add map-parts selection toolbar to Android version

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#757]
### Steps to reproduce
1. Examine user interface
2. Search for map-parts selection menu

### Actual behaviour
Cannot find menu

### Expected behaviour
Finding menu

### Configuration
Mapper Version: 0.6.4
Operating System: Android

**Comment by dg0yt** [comment]
See (17) in http://www.openorienteering.org/mapper-manual/pages/android-app.html for a screenshot. Learning to draw the icon as a vector graphics was the hardest part.
