### ISSUE TITLE
Mapper doesn't recognize upper-case file name extensions.

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#765]
Noticed by Martin Lerjen.

### Steps to reproduce
1. Rename a .ocd file in .OCD.
2. Try to open that file im Mapper.

### Actual behaviour
Error message "Cannot open file ....OCD
File format not recognized"

### Expected behaviour
The file shall be opened as if the file name extension would be all lower case.

### Configuration
Mapper Version: 0.6.5
Operating System: Linux (case-sensititve file system)

### Workaround

Don't use upper case file name extensions.
Rename files with upper case file name extensions. On Windows (case-insensitive file system), you may have to choose a different extension as an intermediate step.

**Comment by dg0yt** [comment]
In addition, the file dialog might NOT list files with the wrong case in some configurations (native dialog for GTK3, [QTBUG-51712](https://bugreports.qt.io/browse/QTBUG-51712)). Fixing this in Mapper is too much effort. As workaround, the native dialog might be disabled for these configurations.

**Comment by Symbian9** [comment]
Funny, this presented in other projects too.
https://github.com/solvespace/solvespace/issues/42

**Comment by dg0yt** [comment]
@Symbian9 Issue #765 is only in Mapper: You can't open .OCD even if it is displayed in the dialog. The extra issue in my first comment is related to the GTK file dialog and may affect any application which directly or indirectly (e.g. via QGtk[23]FileDialogHelper) uses this dialog.
