### ISSUE TITLE
Remove incorrect intems when open .omap file

### ISSUE THREAD

**Issue by ychausson** [OpenOrienteering/mapper#769]
Hello, 

I'am a French user of OpenOrienteering Mapper.

### Steps to reproduce
1. convert .osm file to .omap file with this tutorial : https://github.com/kolesar-andras/osm-omap
2. Open file output.omap with OpenOrienteering Mapper

### Actual behaviour
- There is a Warning box : " Importing map generated warnings " (L'import de la carte a généré des avertissements)
- when I click on the button "Show Details...."  "Remove 80 incorrect items" (Suppression de 80 objets erronés.)
- The map is empty

### Expected behaviour
- Where is the bug in the .omap format file ????
[maps.zip](https://github.com/OpenOrienteering/mapper/files/522990/maps.zip)

### Configuration
Mapper Version: OpenOrienteering Mapper 0.6.5
[maps.zip](https://github.com/OpenOrienteering/mapper/files/522985/maps.zip)
Operating System: Debian Jessie (Linux Mint LMDE Betsy)

**Comment by dg0yt** [comment]
In this omap file, all coordinates of map objects are x=0 y=0, if not missing completely. This makes the object considered "irregular" during import, and that's correct from my POV.

Report and discuss at [kolesar-andras/osm-omap](https://github.com/kolesar-andras/osm-omap) (@kolesar-andras).

**Comment by ychausson** [comment]
Hello Kay,

Thank you very much for your quick response.

Best regards.
