### ISSUE TITLE
Feature Request: Automatick sticking to point or line.

### ISSUE THREAD

**Issue by Xeenych** [OpenOrienteering/mapper#770]
Please make option to sticking one object to another. E.g. i want to stick end of one line to the middle of another line.

**Comment by dg0yt** [comment]
Some tools allow you to "snap to" existing points, cf. http://www.openorienteering.org/mapper-manual/pages/toolbars.html#tool_draw_path. Usually this is achieved by pressing the Shift key. Does this cover your request?

**Comment by Xeenych** [comment]
Yes, partially.
Snapping is very useful.

But it will be even more useful if "snapped" points move together. E.g. I have a road and a forest along it. I would like to move some points of the road so, that forest border moves with road too.

**Comment by dg0yt** [comment]
Moving points together seems to be a popular request: #624. You may subscribe there.
