### ISSUE TITLE
Russian symbol names not imported correctly from OCD 9

### ISSUE THREAD

**Issue by Xeenych** [OpenOrienteering/mapper#771]
### Steps to reproduce
1. import ocad 9 ocd with russian symbol names
### Actual behaviour

Imported symbols have garbled names or incorrect encoding
### Expected behaviour

symbol names should be readable
### Configuration

Mapper Version: 0.6.6
Operating System: Win7

**Comment by dg0yt** [comment]
- Can you provide a test file? Just the symbols, maybe some text objects if affected.
- Did you really experience this issue in Mapper 0.6.6? If yes:
  - Do you know if the issue was already present in previous version?
  - Did you try to set a different 8-bit encoding?
  
  (Mapper 0.6.6 has a bug fix which makes it respect your settings, #753.)

**Comment by Xeenych** [comment]
Can't attach file here. The symbol names are in russian.
use the link
https://yadi.sk/d/O2pbFcGKwiesv

**Comment by dg0yt** [comment]
You need to set the 8-bit encoding to Windows-1251 (aka cp1251) for Russian symbol names.

I guess your Windows is configured for Russian. So this means the default setting ("System") doesn't work properly for your case? Maybe we need to explicit map current system locale and ancient 8-bit encoding.

**Comment by sembruk** [comment]
@Xeenych, this file opened correctly by Mapper 0.6.6. See `Settings` -> `8-bit encoding`. Should be 
 `Windows-1251`. Not `Windows-1252` as default.

**Comment by Xeenych** [comment]
Ok, Семён

**Comment by dg0yt** [comment]
Not so quick: I still want to know if the the default 8-bit encoding setting ("System") doesn't work properly for old Russian OCD files on a current Russian Windows system.

**Comment by Xeenych** [comment]
Yes, default "System" encoding works.
At first install the encoding was set to win-1252 by default - thats why symbol names were unreadable.

**Comment by dg0yt** [comment]
Oops, "Windows-1252" is the default indeed. Well, imported was tested mainly with German and English maps. I will change the default to "System", as this works for Russian and for Western Europe. However, this needs some more testing, and probably even runtime checks, to avoid issues like #773.

**Comment by dg0yt** [comment]
No, "System" is not working out of th ebox for German. So System needs to be mapped to a suitable codepage. What we know is:
- German: Windows-1252
- Russian: Windows-1251

**Comment by dg0yt** [comment]
There is an explicit mapping from languages to encodings now. See https://github.com/OpenOrienteering/mapper/blob/master/src/util/encoding.cpp#L36. The settings dialog works a little different now.

This needs more real testing if the setting the language in Mapper and chosing "default" encodings works as expected. I checked only with Russian and German.
