### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by palmestal** [OpenOrienteering/mapper#773]
I made some changes to my map and saved that as a copy.
The next day, I couldn't open the file. This message appeared:
 Error at line 1 collumn 457481: Unexpected ".

As an experiment, I opened the file in Notes and tried to see if I could fix this issue, but then all I got was that the program didn't recognize the file format.

The original file works just fine.

I use OpenOrienteering Mappar 0.6.6

**Comment by dg0yt** [comment]
Send the file or a link via personal e-mail if you don't want to attach a ZIP here. I could also send you a link where you can upload the file.

**Comment by palmestal** [comment]
Well, now I realized that this happened only when trying to save the file to .omap instead of .ocd.

When staying in .ocd, it works just fine.



/Mattias


________________________________
Från: Kai Pastor <notifications@github.com>
Skickat: den 14 oktober 2016 05:45
Till: OpenOrienteering/mapper
Kopia: palmestal; Author
Ämne: Re: [OpenOrienteering/mapper] Cannot open file (#773)


Send the file or a link via personal e-mail if you don't want to attach a ZIP here. I could also send you a link where you can upload the file.

-

**Comment by dg0yt** [comment]
I still want to fix the error, so please send me the .ocd file. After all, a similar issue was solved in Mapper 0.6.5 (#748).

**Comment by palmestal** [comment]
Ok, here it is!

________________________________
Från: Kai Pastor <notifications@github.com>
Skickat: den 14 oktober 2016 08:06
Till: OpenOrienteering/mapper
Kopia: palmestal; Author
Ämne: Re: [OpenOrienteering/mapper] Cannot open file (#773)


I still want to fix the error, so please send me the .ocd file. After all, a similar issue was solved in Mapper 0.6.5 (#748<https://github.com/OpenOrienteering/mapper/issues/748>).

-

**Comment by dg0yt** [comment]
No, it doesn't work by e-mail to github issues. My e-mail is in my github profile: https://github.com/dg0yt.

**Comment by dg0yt** [comment]
Some text objects contain invalid data. This includes symbolized and unsymbolized objects. Very similar to #748 indeed, only that it was the map notes in the other issue.

However, even OCAD Viewer doesn't really know what to display for some text objects. What is the expected blue text in the north of the map?

**Comment by palmestal** [comment]
I reall have no idea what the text should be,

________________________________
Från: Kai Pastor <notifications@github.com>
Skickat: den 14 oktober 2016 09:39
Till: OpenOrienteering/mapper
Kopia: palmestal; Author
Ämne: Re: [OpenOrienteering/mapper] Cannot open file (#773)


Some text objects contain invalid data. This includes symbolized and unsymbolized objects. Very similar to #748<https://github.com/OpenOrienteering/mapper/issues/748> indeed, only that it was the map notes in the other issue.

However, even OCAD Viewer doesn't really know what to display for some text objects. What is the expected blue text in the north of the map?

-

**Comment by dg0yt** [comment]
Okay, than I can only try to prevent the errors in writing omap files.

**Comment by dg0yt** [comment]
This is really a corner case.

The reading stops on some control characters (< 0x20) which are valid UTF but not allowed in XML 1.0, even not as a character reference. The rules for valid characters can be found [in the XML specification](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-Char) and [in Qt's implementation](http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/xml/qxmlstream.cpp?h=5.6.2&id=d4302ec6936b8b3799a266b640b5d116b3296b29#n1717):

~~~
ok &= (s == 0x9 || s == 0xa || s == 0xd || (s >= 0x20 && s <= 0xd7ff)
           || (s >= 0xe000 && s <= 0xfffd) || (s >= 0x10000 && s <= QChar::LastValidCodePoint));
~~~

Unfortunately, there seems to be [no general solution for escaping these characters in Qt's XML writer (QTBUG-15766)](https://bugreports.qt.io/browse/QTBUG-15766), and there is no indication of errors during writing.

A solution could be to use a proxy UTF-8 codec when writing OMAP files, which either catches and replaces the special characters, and creates proper warnings. Replacements could be the empty string (for non-printing control characters), the question mark ('?'), or a CDATA section with the offending data (if we want to restore the data on input). This adds a performance penalty in Mapper's native format, and changes made during writing will be hidden until the file is opened again.

As an alternative, Mapper could catch and replace these characters on import from other formats, making the modification immediately visible. However, this solution could easily go missing when adding new importers.

**Comment by dg0yt** [comment]
Do you need the file with the broken text removed? I'm not sure if and when I can deal with the underlying issue.

**Comment by palmestal** [comment]
No thanks, I can do without those changes in the map.


/Mattias


________________________________
Från: Kai Pastor <notifications@github.com>
Skickat: den 18 oktober 2016 08:15
Till: OpenOrienteering/mapper
Kopia: palmestal; Author
Ämne: Re: [OpenOrienteering/mapper] Cannot open file (#773)


Do you need the file with the broken text removed? I'm not sure if and when I can deal with the underlying issue.

-
