### ISSUE TITLE
Do NOT remove geometry after symbol deleting

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#774]
### Steps to reproduce
1. Create any geometry using some symbol
2. Try delete used symbol from symbol panel and in ask dialog set "Yes" (remove all objects with this symbol)

### Actual behaviour
After deleting symbol all geometry, that use it, will lost.

### Expected behaviour
While try delete symbol OOMapper must ask "Keep geometry as constructed?", that give a chance keep geometry in map without any symbols as constructed ('draft'). Think, its can be released as ask dialog with 3 tabs:
> Did you want delete symbol and all related elements?
| Delete All | Delete Symbol(s) | CANCEL

If user will choose "Delete Symbol(s)" - delete only symbols and keep related elements and its geometry as constructed. 

### Configuration
Mapper Version: 0.6.6
Operating System: LinuxMint 17.3 Xfce (amd64)

**Comment by dg0yt** [comment]
This is nonsense. Assign a different symbol before removing the first one if you want to keep your objects.
