### ISSUE TITLE
Polygon *.dxf from Qgis to OOM

### ISSUE THREAD

**Issue by Nabesar** [OpenOrienteering/mapper#775]
I have problems when I export a file with QuantumGIS 2.16 (from poligon *.shp to *.dxf) and try to import it with Openorienteering Mapper. What characteristics must have the file *.dxf to be imported into OOM 0.6.6 ?.

**Comment by dg0yt** [comment]
There is no simple answer to that question. The DXF import in the stable version of Mapper was implemented to handle a small set of real word files (cf. #204). There is a significant number of [open and closed tickets related to DXF](https://github.com/OpenOrienteering/mapper/issues?utf8=%E2%9C%93&q=is%3Aissue%20dxf). Situation will not improve until we can switch to the new importer based on GDAL/OGR (#574). You may activate and test this work-in-progress in the unstable builds for Windows and Linux.

(IIRC sometimes only a few special lines in the beginning of QGIS DXF output needed to be removed in a text editor to make the files usable.)
