### ISSUE TITLE
Bug: Ocad10 curve texet not imported

### ISSUE THREAD

**Issue by Xeenych** [OpenOrienteering/mapper#777]
This file produces import errors
https://yadi.sk/d/O2pbFcGKwiesv

All "text along curve" symbols are not imported.

Is there a "text along curve" symbol type in OOM?

**Comment by dg0yt** [comment]
The "line text symbol" is not yet implemented in Mapper (#323)
Are there any other errors, apart from the warnings?

**Comment by Xeenych** [comment]
First of all, the details window is too small and cannot be resized

This is the list of errors

Spot color information was ignored.
In line symbol 103.0 'Дополнительная горизонталь': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 114.1 'Скальный отрог': Skipped secondary point symbol.
In line symbol 114.2 'Скальный отрог2': This symbol cannot be saved as a proper OCD symbol again.
In text symbol 105.0 'Подписи к горизонталям': Ignoring text framing (mode 3).
In area symbol 108.2 'Осыпь (Галечниковая и гравийна)': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 112.2 'Промоина': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 932.0 'Промоина': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 108.4 'Контур покрытий': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern cannot be imported correctly.
In line symbol 110.0 'Проселочная дорога': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 111.0 'Полевые и лесные дороги': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern's end length (1.7 mm) cannot be imported correctly. Using 1.25 mm.
In line symbol 112.0 'Караванная тропа': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern's end length (0.7 mm) cannot be imported correctly. Using 0.75 mm.
In line symbol 113.0 'Пешеходная тропа': This symbol cannot be saved as a proper OCD symbol again.
In text symbol 118.1 'Высота отметки': Custom character spacing may be incorrect.
In text symbol 118.1 'Высота отметки': Ignoring custom word spacing (40 %).
In text symbol 118.2 'Высота отметки': Custom character spacing may be incorrect.
In text symbol 118.2 'Высота отметки': Ignoring custom word spacing (40 %).
In text symbol 118.3 'Высота отметки': Custom character spacing may be incorrect.
In text symbol 118.3 'Высота отметки': Ignoring custom word spacing (40 %).
In line symbol 306.0 'Река до 5м': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 305.0 'Основная река 5 - 30 м': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 200.0 'Горизонталь ледника': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 201.0 'Толстая горизонталь ледника': This symbol cannot be saved as a proper OCD symbol again.
In area symbol 229.1 'Фирновые поля и снега': This symbol cannot be saved as a proper OCD symbol again.
In area symbol 229.7 'Скалы и скалистые обрывы': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 235.0 'Обрыв': This symbol cannot be saved as a proper OCD symbol again.
In area symbol 272.0 'Болото проходимое': This symbol cannot be saved as a proper OCD symbol again.
In area symbol 301.0 'Заливка озерных пространств': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 308.0 'Исчезающая река': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 307.0 'Пересыхающая река': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 307.1 'Сухое русло': This symbol cannot be saved as a proper OCD symbol again.
In text symbol 318.0 'Текст по кривым линиям': Custom character spacing may be incorrect.
In text symbol 318.0 'Текст по кривым линиям': Ignoring custom word spacing (70 %).
In text symbol 318.0 'Текст по кривым линиям': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 316.0 'Текст нормальный': Custom character spacing may be incorrect.
In text symbol 316.2 'Названия рек и озер': Justified alignment is not supported.
In text symbol 316.2 'Названия рек и озер': Custom character spacing may be incorrect.
In text symbol 316.2 'Названия рек и озер': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 316.8 'Названия ледников': Justified alignment is not supported.
In text symbol 316.8 'Названия ледников': Custom character spacing may be incorrect.
In text symbol 316.8 'Названия ледников': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 316.6 'Названия ледников': Justified alignment is not supported.
In text symbol 316.6 'Названия ледников': Custom character spacing may be incorrect.
In text symbol 316.6 'Названия ледников': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 316.3 'Названия ледников': Justified alignment is not supported.
In text symbol 316.3 'Названия ледников': Custom character spacing may be incorrect.
In text symbol 316.3 'Названия ледников': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 316.7 'Названия ледников': Justified alignment is not supported.
In text symbol 316.7 'Названия ледников': Custom character spacing may be incorrect.
In text symbol 316.7 'Названия ледников': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 318.1 'Текст по кривым линиям': Custom character spacing may be incorrect.
In text symbol 318.1 'Текст по кривым линиям': Ignoring custom word spacing (70 %).
In text symbol 318.1 'Текст по кривым линиям': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 318.2 'Текст по кривым линиям': Custom character spacing may be incorrect.
In text symbol 318.2 'Текст по кривым линиям': Ignoring custom word spacing (70 %).
In text symbol 318.2 'Текст по кривым линиям': Line text symbols are not yet supported. Marking the symbol as hidden.
In line symbol  '': The dash pattern's end length (0.76 mm) cannot be imported correctly. Using 0.75 mm.
In line symbol 505.0 'Границы заповедников': Skipped secondary point symbol.
In line symbol 515.0 'Бровка': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern's end length (1.24 mm) cannot be imported correctly. Using 1.25 mm.
In text symbol 904.5 'Названия строений, населенных п': Ignoring text framing (mode 3).
In line symbol  '': Different lengths for pointed caps at begin (0 mm) and end (0.6 mm) are not supported. Using 0.3 mm.
In line symbol 700.0 'Контура растительности': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 901.5 'Линия рамки минутная (гор.)': Suppressing dash symbol at line ends.
In line symbol 901.5 'Линия рамки минутная (гор.)': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 901.6 'Линия рамки минутная (верт.)': Suppressing dash symbol at line ends.
In line symbol 901.6 'Линия рамки минутная (верт.)': This symbol cannot be saved as a proper OCD symbol again.
In text symbol 903.2 'Широкий текст по кривой': Justified alignment is not supported.
In text symbol 903.2 'Широкий текст по кривой': Custom character spacing may be incorrect.
In text symbol 903.2 'Широкий текст по кривой': Ignoring custom word spacing (500 %).
In text symbol 903.2 'Широкий текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 903.11 'Широкий текст по кривой': Justified alignment is not supported.
In text symbol 903.11 'Широкий текст по кривой': Custom character spacing may be incorrect.
In text symbol 903.11 'Широкий текст по кривой': Ignoring custom word spacing (500 %).
In text symbol 903.11 'Широкий текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 903.14 'Коментарий по кривой': Justified alignment is not supported.
In text symbol 903.14 'Коментарий по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 903.17 'Коментарий по кривой': Justified alignment is not supported.
In text symbol 903.17 'Коментарий по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 904.0 'Текст маленький': Custom character spacing may be incorrect.
In text symbol 904.0 'Текст маленький': Ignoring custom word spacing (70 %).
In text symbol 904.1 'Текст маленький': Custom character spacing may be incorrect.
In text symbol 904.2 'Текст маленький': Custom character spacing may be incorrect.
In text symbol 904.2 'Текст маленький': Ignoring custom word spacing (70 %).
In text symbol 904.3 'Текст маленький': Custom character spacing may be incorrect.
In text symbol 904.3 'Текст маленький': Ignoring custom word spacing (70 %).
In text symbol 904.4 'Текст маленький (1)': Custom character spacing may be incorrect.
In text symbol 904.4 'Текст маленький (1)': Ignoring custom word spacing (70 %).
In text symbol 905.0 'Нормальный текст по кривой': Custom character spacing may be incorrect.
In text symbol 905.0 'Нормальный текст по кривой': Ignoring custom word spacing (80 %).
In text symbol 905.0 'Нормальный текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 905.1 'Нормальный текст по кривой': Custom character spacing may be incorrect.
In text symbol 905.1 'Нормальный текст по кривой': Ignoring custom word spacing (30 %).
In text symbol 905.1 'Нормальный текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 905.2 'Нормальный текст по кривой': Custom character spacing may be incorrect.
In text symbol 905.2 'Нормальный текст по кривой': Ignoring custom word spacing (80 %).
In text symbol 905.2 'Нормальный текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 905.3 'Нормальный текст по кривой': Custom character spacing may be incorrect.
In text symbol 905.3 'Нормальный текст по кривой': Ignoring custom word spacing (80 %).
In text symbol 905.3 'Нормальный текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 906.0 'Большой текст по кривой': Custom character spacing may be incorrect.
In text symbol 906.0 'Большой текст по кривой': Ignoring custom word spacing (70 %).
In text symbol 906.0 'Большой текст по кривой': Line text symbols are not yet supported. Marking the symbol as hidden.
In text symbol 907.1 'Текст сжатый': Custom character spacing may be incorrect.
In line symbol 903.15 'Указатель': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 903.16 'Указатель': This symbol cannot be saved as a proper OCD symbol again.
In text symbol 907.2 'Текст сжатый': Custom character spacing may be incorrect.
In text symbol 907.3 'Текст сжатый': Custom character spacing may be incorrect.
In line symbol 300.0 'Контур озера, береговая линия': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 931.0 'Оролиния толстая': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 931.1 'Оролиния средняя': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 931.2 'Оролиния тонкая': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 931.7 'Оролиния запасная': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern's end length (3 mm) cannot be imported correctly. Using 2.25 mm.
In line symbol 931.3 'Оролиния тонкая прерывистая': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 931.4 'Оролиния для выделения скал': This symbol cannot be saved as a proper OCD symbol again.
In line symbol 903.10 'Выделение скал': This symbol cannot be saved as a proper OCD symbol again.
In line symbol  '': The dash pattern's end length (0.2 mm) cannot be imported correctly. Using 2.5 mm.
In line symbol  '': The dash pattern's end gap (0 mm) cannot be imported correctly. Using 1 mm.
In line symbol  '': The dash pattern's end length (0.2 mm) cannot be imported correctly. Using 2.5 mm.
In line symbol  '': The dash pattern's end gap (0 mm) cannot be imported correctly. Using 1 mm.

**Comment by dg0yt** [comment]
This is the list of warnings I already saw when opening the text file. But I asked for errors apart fromt this warnings.

Mapper is not a drop-in replacement for editing .ocd files. Both import and export are lossy. The warnings from the test file give an indication which improvements might be desired (feature requests), not what is broken (bugs).

**Comment by Xeenych** [comment]
Then, as far as i can see there are no errors
