### ISSUE TITLE
Encoding problem inside undo steps import error message

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#778]
### Steps to reproduce
1. Try get error message "Error while loading undo steps."
* Error in English
![..._en.ts](http://pasteall.org/pic/show.php?id=107635)

2. Switch language from English to any other implemented translations
3. Retry get this error message again

### Actual behaviour
Encoding problems with "Error while loading undo steps." string translation.
* error in ukrainian
![..._uk.ts](http://pasteall.org/pic/show.php?id=107637)

* error in polish
![..._pl.ts](http://pasteall.org/pic/show.php?id=107638)

* error in russian
![..._ru.ts](http://pasteall.org/pic/show.php?id=107639)

* error in french
![..._fr.ts](http://pasteall.org/pic/show.php?id=107640)

* error in latvian
![..._lv.ts](http://pasteall.org/pic/show.php?id=107641)

* error in czech
![..._cz.ts](http://pasteall.org/pic/show.php?id=107643)

* error in svenska
![..._sv.ts](http://pasteall.org/pic/show.php?id=107642)

* error in netherland
![..._nl.ts](http://pasteall.org/pic/show.php?id=107644)
* error in hungarian
![..._hu.ts](http://pasteall.org/pic/show.php?id=107677)

I don't test Japanese and Chinese, but all other languages seems not has this encoding issue. 

### Expected behaviour
Need check how translation for this error message work. Here is line from language file used for that:
```
<message>
    <location filename="../src/file_format_native.cpp" line></location>
    <source>Error while loading undo steps.</source>
    <translation>Помилка під час завантаження попередніх кроків.</translation>
</message>
```

### Configuration
Mapper Version: 0.6.5, 0.6.6 
Operating System: LinuxMint 17.3 Xfce (amd64)

**Comment by dg0yt** [comment]
One screenshot with the error would have been enough...
