### ISSUE TITLE
Tools drop-down list not compact

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#779]
### Steps to reproduce
1. Open map or create new in OOMapper 
2. Keep cursor over "Tools" submenu or open it

### Actual behaviour
Drop-down list of tools cover menubar and unevenly distributed between two columns
![Tools drop-down list](http://pasteall.org/pic/show.php?id=107645)

### Expected behaviour
Drop-down list of tools (or any other submenu) must be compact and don't cover menubar. As for me some tools, like "Enable touch cursor", must be moved to "View" submenu. Also "Tools" list could be scrolled.

### Configuration
Mapper Version: 0.6.6
Operating System: LinuxMint 17.3 Xfce (amd64)

**Comment by dg0yt** [comment]
The handling of overflowing menu items depends on the platform. We will not deal with that on PCs.

**Comment by Symbian9** [comment]
@dg0yt, at least move "Enable touch cursor" from "Tools" to "View" submenu, because it's interaction, not special mapping tool.
