### ISSUE TITLE
Wrong placement on OCAD import

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#784]
### Steps to reproduce
1. I have a geo-referenced Mapper project of an area.
2. I want to import other geo-referenced data from an OCAD file. (same coordinate system; f.ex. laser contours)
### Actual behaviour

The imported geo-referenced data gets placed at the wrong place with an offset (which seems to be the offset between the reference points of the two map files)
### Expected behaviour

The imported data should be placed accordingly to the position information given in the imported file.
### Configuration

Mapper Version: 0.6.6
Operating System: Windows 7

**Comment by dg0yt** [comment]
It looks like template maps are simply at the origin, complete ignoring georeferencing and current map:
https://github.com/OpenOrienteering/mapper/blob/v0.6.6/src/template_map.cpp#L93

**Comment by dg0yt** [comment]
Please test the fix with the soon-to-be-released unstable snapshots. Only newly added template maps will be placed differently. Existing templates shall stay where they are.

There is another fix to the OCD *export* of the real world coordinates offset (https://github.com/OpenOrienteering/mapper/commit/82daa6fcbb0e8cbbfabca0b22f6f75eee051af26).

**Comment by dg0yt** [comment]
Okay, the issue was about import, not templates. Anyway, nice to have map template placement improved now.

**Comment by dg0yt** [comment]
And here is the existing TODO remark for map import: https://github.com/OpenOrienteering/mapper/blob/v0.6.6/src/map.cpp#L836. Lots of ugly code here...
