### ISSUE TITLE
Feature: Android: Drawing protection with overlay protector layer

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#786]
Sometimes I am fighting with unwanted deletions and changes in finished parts during my work in forest. My idea is to solve this problem with overlay protection layer - an editable semitransparent layer under which finished areas (objects) would be protected against additions, changes and deletions.
For line and polygon objects partially overlapped with protector layer only the vertexes outside protection layer would be editable. 

![bitmap](https://cloud.githubusercontent.com/assets/15969434/19835132/2a7b7f72-9e7d-11e6-93d3-91c3a4ca3aeb.png)

**Comment by dg0yt** [comment]
As a workaround, you may move finished objects to another map part. The mobile version still has very limited supported for dealing with map parts. But you might try to do most field work in a "field work" map part.
