### ISSUE TITLE
Show/hide symbols in Android version

### ISSUE THREAD

**Issue by agustincaballero** [OpenOrienteering/mapper#788]
### Steps to reproduce
1. 
2. 
3. 

### Actual behaviour
In Android version, can not show/hide symbols like we can do on desktop version

### Expected behaviour
Being able to hide a symbol from palette, or show it back again. One method could be by in the select symbol screen, have a button which activates the hide or show symbols

### Configuration
Mapper Version:
Operating System:

**Comment by Zerbembasqwibo** [comment]
In field today I tried to push and hold to get a menu to change this. So that's my proposal for interace for changing sow/hide symbols.
