### ISSUE TITLE
"Course Design" example small fixes

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#790]
### Steps to reproduce
1. Open inbuilt example of course design
2. View latest string in table

### Actual behaviour
Currently Course Design example include some mistakes.

### Expected behaviour
Fix default course design example using attached fixed template.
* http://d.profismart.org/files3/02/Course_design_10000__fixed_.zip

### Configuration
Mapper Version: 0.6.6
Operating System: LinuxMint 17.3 (64 bit)

**Comment by dg0yt** [comment]
Thanks.

**Comment by Symbian9** [comment]
@dg0yt, Thank you for fast reaction!

As for me, maybe also need remove so many black's and white's colors? Maybe one black, one white and one purple could be enough? What you think?

**Comment by dg0yt** [comment]
All these colors do matter for the stacking of symbols (one covering the other). If I would think less colors were easily possible, then there would be less colors. This doesn't mean there couldn't be some less obvious improvements.

**Comment by Symbian9** [comment]
@dg0yt, I now view "Course Design" templates from "master" branch and found there few mistakes:
* in symbol 14.2 title must be "Taped Route from finish funnel to Finish" (now its mistake in first word "Tape")
* in example table last string must use "14.1 Taped Route from last control to Finish" because it is last part of route between last control point and finish (now it use 13.1 Taped Route, away from control, that used betwen control points)
