### ISSUE TITLE
Text on path, is it possible?

### ISSUE THREAD

**Issue by Kostromushkin** [OpenOrienteering/mapper#798]
Hi,

I am a new user of OOM, due to the fact that I design city plan and need to put the street names on the curved lines, so I noticed that missing of one important option, namely - writing the text on the path. Is this option exists or just I don't know how to do this?

Best regards,
K.

**Comment by krticka** [comment]
I am afraid, that such functionality is not implemented in OOM.

**Comment by Kostromushkin** [comment]
Ouch, sad news. It is planned to implement this functionality in future? Unavailability that feature in such a great software is like a missing blade in shovel...

Best regards,
K.

**Comment by krticka** [comment]
Yes, see ticket [323](https://github.com/OpenOrienteering/mapper/issues/323).

**Comment by Kostromushkin** [comment]
OK, thank you for answer.

Best regards,
K.

**Comment by dg0yt** [comment]
Feel free to subscribe to #323, or indicate your interest by using one of the "social" buttons.
