### ISSUE TITLE
[Build] edit files in place with BSD Sed

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#800]
BSD Sed and GNU Sed treat -i option differently.

[GNU Sed](https://linux.die.net/man/1/sed):
```
$ man sed
...
-i[SUFFIX], --in-place[=SUFFIX]
            edit files in place (makes backup if SUFFIX supplied)
...
```
[BSD Sed](http://www.unix.com/man-page/FreeBSD/1/sed/):
```
$ man sed
...
     -i extension
	     Edit files in-place similarly to -I, but treat each file independently from other
	     files.  In particular, line numbers in each file start at 1, the ``$'' address
	     matches the last line of the current file, and address ranges are limited to the
	     current file.  (See Sed Addresses.)  The net result is as though each file were
	     edited by a separate sed instance.
...
```

### Steps to reproduce
1.
```
$ make
...
Scanning dependencies of target translate-text-files
[  7%] Generating text-files.stamp, desktop_file_comment.txt, mime_type_comment.txt
sed: -I or -i may not be used with stdin
*** Error code 1
```
Root cause:
```
$ cat translations/translate_text_files.sh
...
sed -i "../packaging/linux/Mapper.desktop" -e '
  /^Comment=/ r desktop_file_comment.txt
  /^Comment\[/ d
'
...
sed -i "../packaging/linux/openorienteering-mapper.xml" -e '
  /^ *<comment>/ r mime_type_comment.txt
  /^ *<comment [^>]*lang=/ d
'
...
```
### Actual behaviour
Build fails.

### Expected behaviour
Build successed.

### Configuration
Mapper Version: latest
Operating System: any BSD

**Comment by dg0yt** [comment]
I will look into this when I finished the restructuring (simplifying) the build system (#674).

**Comment by dg0yt** [comment]
Out of curiosity (related to #799), which `sed` is used by GNU make on BSD?

**Comment by sikmir** [comment]
Make know nothing about which sed is available, 'gsed' should be used explicitly.
Another portable way to select proper one:
```make
find_tool_impl = $(shell \
for i in $1; do \
    type $$i >/dev/null 2>&1 && \
    echo $$i && \
    exit; \
done; \
echo $2)
export SED := $(call find_tool_impl,gsed sed,sed)
export AWK := $(call find_tool_impl,gawk awk nawk mawk,awk)
```

**Comment by dg0yt** [comment]
Well, this better solved in CMake where `find_program` can look for different names.
An alternative would be to avoid sed completely, using CMake (scripts) to do the file processing. More portable, but more difficult to achieve the same result.

**Comment by dg0yt** [comment]
To be reviewed after completing a release based on superbuild, and subsequent cleanup.

**Comment by dg0yt** [comment]
Shall I take any actions here, or just close the issue?

**Comment by sikmir** [comment]
Currently build on FreeBSD fixed by [the patch](https://github.com/freebsd/freebsd-ports/blob/master/graphics/openorienteering-mapper/files/patch-translations_translate__text__files.sh). Generally, it would be good to avoid such workaround.

**Comment by dg0yt** [comment]
With 0fbefe8 in `dev`, I generally applied the pattern
~~~
sed -e EXPRESSION -i -- FILE
~~~
which just creates `--` suffixed backup files with `sed` from macOS. So I guess this is solved.

**Comment by sikmir** [comment]
Verified on FreeBSD, it's OK now, thanks.
