### ISSUE TITLE
Make it possible to build with system polyclipping

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#801]
### Steps to reproduce
1. make
```shell
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Polyclipping: Found unsuitable version "6.4", but required
  is exact version "6.1.3" (found /usr/include/polyclipping)
```
Root cause:
```cmake
if(Mapper_BUILD_CLIPPER)
   add_subdirectory(3rd-party/clipper)
   add_feature_info(Mapper_BUILD_CLIPPER 1 "version: ${CLIPPER_VERSION}")
   add_library(Polyclipping::Polyclipping ALIAS polyclipping)
else()
   find_package(Polyclipping 6.1.3 EXACT MODULE REQUIRED)
   set(CLIPPER_VERSION "${POLYCLIPPING_VERSION}a")
endif()
```

### Actual behaviour
Build fails.

### Expected behaviour
Build successed.

### Configuration
Mapper Version: latest
Operating System: any

**Comment by dg0yt** [comment]
Polyclipping had some source incompatible changes in the past and wasn't packaged at all in most distributions in 2014. Version 6.1.3a is what is widely tested, and it is not expensive to link it statically with Mapper. However, I can confirm that Mapper compiles and links with 6.4 so I will relax this requirement. But I cannot test it thoroughly.

**Comment by sikmir** [comment]
Anyway it's worth just trying out. At first sight it looks like OOM is working correctly with 6.4. I will try to use it a bit more.

Yes, version 6.1.3a is used in all Linux distros, but statistics show:

Ver|Downloads/week
------------ | -------------
6.4|578
6.2.1|333
6.1.3a|38
