### ISSUE TITLE
Installation file for Windows phone 10

### ISSUE THREAD

**Issue by lipa1982** [OpenOrienteering/mapper#804]
There is no installation file for Windows phone 
Operating System:Windows phone 10

**Comment by dg0yt** [comment]
Windows Phone is not supported, and there are no plans on my side.

If someone wants to work on this, the following points need to be adressed:
- Sufficient C++11 compiler support in for this target. (Visual C++ was lagging in the past.)
- GPL-compatibility of binary packages to be released for this target.
- Building of at least the Proj.4 library, ideally also of the GDAL library, for this target.
