### ISSUE TITLE
Android errors and crashes when opening maps

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#805]
Intermittently, when I open a map in the Android version, I see the one or more of the following behaviors:

A) Warnings about Mapper having crashed last time the map was opened.  Occasionally, the warning will loop ten or more times after which Mapper may crash. 

B) Same as A except that the warning is about missing template files.

C) A combination of A and B.

D) Mapper quits with the following error message:
Cannot open file:  /storage/emulated/0/OOMapper/TEST/TEST.omap
std::bad_alloc

It seems that all four errors happen more often (perhaps only) after copying a map from the standard version of Mapper to the Android.

Sometimes retrying opening the map will succeed for scenarios A-C.  Error D, when it occurs, is persistent. Error D may be related to large template files.

The crashes and, possibly, the loops seem to have started after an upgrade to Mapper and the Android OS.

Sorry about the vagueness in this report. I will try add more specific data later. Suggestions for specific items are welcome.

### Actual behaviour
Mapper crashes.
Warning loops.

### Expected behaviour
No crashes.
No loops.

### Configuration
Mapper Version: 0.6.6
Operating System:  Latest version for Samsung Tab S2  (I will provide the exact version later)

**Comment by dg0yt** [comment]
I guess the app is not getting enough memory for loading the map (and its templates). Especially D) is an indicator for lack of memory, and the crashes (A) might be related to this, too. 

You could provide more information on the file size of the map and on the templates. Note that Mapper tries to load templates even if they are set to not visible.
