### ISSUE TITLE
Incorrect adjustment of coordinates on import

### ISSUE THREAD

**Issue by marcovandersson** [OpenOrienteering/mapper#806]
I usually use Karttapullautin (KP) to generate contours and vegetation. 

### Steps to reproduce
1. After it is done, I import it into a georeferenced omap. I use the swdish standard EPSG:3006. The background images (vegetation.png + the .pgw) is shown ok coordinate wise. So far so good. 

2. Second step is to import the out2.dxf from KP to omap to get the vector contours. This works fine as well (even though I am heavily missing the function of set symbol by tag/dxf layer...!). I save the map and close it.

3. When reopening the map after a application restart I get the warning in swedish "Vissa koordinater var utanför det aktuella området. Kartans innehåll justerades." which could be translated to "Some coordinates were outside the current area. The content of the map was adjusted". 
This results in that the georeferences background images like vegetation.png is correct, but the imported dxf-contours is redrawn completely elsewhere. Probably near the 0 of the Y-axis.

I have discovered this earlier (pre 0.60 I believe). But is seams to be back here in 0.65 and 0.66.
And it is not only relevant to KP dxf-files. I get the same behaviour when using dxf files with other data, e.g. data from swedish Lantmäteriet (nat. land survey dep.) originally in shape-format, but converted in FME to dxf.

### Expected behaviour
The map should not redraw the vector graphics wrongly after restart.

### Configuration
Mapper Version: 0.6.5 and 0.6.6
Operating System: Win7,  64-bit

[dxf_plus_vegetation.zip](https://github.com/OpenOrienteering/mapper/files/628836/dxf_plus_vegetation.zip)

[Omap-file_1-15000.zip](https://github.com/OpenOrienteering/mapper/files/628849/Omap-file_1-15000.zip)

**Comment by dg0yt** [comment]
Mapper 0.6.x introduced a new behaviour to move the data into the printable area of the paper coordinate system (1000 m wide and high). This should work for map data and all kinds of templates, but your files indicate that there is something broken here.

**Comment by dg0yt** [comment]
A quite embarrassing bug, both in the implementation itself and in the test code for this implementation... The objects imported before were discarded when loading the file again, because Mapper failed to the coordinate adjustment correctly. Please test the unstable build which will be released later this evening on build.opensuse.org.

**Comment by marcovandersson** [comment]
Perfect, I will try the nightly!
