### ISSUE TITLE
Pretty print of .omap (XML) file

### ISSUE THREAD

**Issue by dominikzalewski** [OpenOrienteering/mapper#808]
### Steps to reproduce
1. Save the file from OOMapper in default .omap format
2. Add and commit the file to version control (any, but let us focus on git for now)
3. Make a change in the .omap file and save it again
4. Commit changes made in the .omap file to version control

### Actual behaviour
Version control system (git) detects that a single line has changed.

### Expected behaviour
Because the .omap file is actually written without a single line break, a line based VCS (Version Control System) like GIT, has to keep a full copy of each revision. If the .omap file was pretty-printed, the VCS would have a chance to optimize and save storage for revisions.

Keeping in mind that after importing contours from LIDAR my initial file size is about 2MB, an improvement here would make a real storage difference. I know that git keeps the revisions compressed, but all the revisions compressed in total are still quite large.

### Configuration
Mapper Version: 0.6.5 (but applicable to any version <=)
Operating System: Mac OS (but applicable to any OS)

**Comment by dg0yt** [comment]
Use the .xmap extension if you want pretty print. Mapper saves coordinates much more verbose in this format, so be warned that the files get much larger indeed (and also slower to load).

You may even [configure git to use `xmllint` or pretty XML diffs of .omap files](https://github.com/OpenOrienteering/mapper/commit/fd663045a2d2a8c1dacd0f8ff78408aede9d4f5e).

**Comment by dg0yt** [comment]
Not yet in RC2.
