### ISSUE TITLE
GDAL (OSM) Importer not applying tags to all objects

### ISSUE THREAD

**Issue by mitchellkrome** [OpenOrienteering/mapper#810]
### Steps to reproduce
1. Import any OSM file which has an area or relations

### Actual behaviour
Areas and relations (which end up as wkbMultiPolygon, wkbMultiPoint, wkbMultiLineString or wkbGeometryCollection) get no tags applied to them (importGeometryCollection returns nullptr so tag setting is skipped).

### Expected behaviour
I think here the tags for the feature should be applied to all objects that were imported as a result?

### Configuration
Mapper Version: master/HEAD with GDAL enabled
Operating System: Ubuntu 14.04

**Comment by dg0yt** [comment]
I'm not sure if our implementation is already complete here. But there are some GDAL configuration parameters which influence the import of tags, see http://gdal.org/drv_osm.html. Use Mapper' GDAL settings for adjustments.

**Comment by mitchellkrome** [comment]
The tags are there (I made it print the tags even if it doesn't apply them to an object) it's just that because the object isn't returned from importGeometry the tags can't be applied.

Not sure the best way to make this work in the code but - Maybe the feature definition could be passed into importGeometry then there could be a function applyTags which is called inside importGeometryCollection on the returned objects. 

As an aside -  most of the tags end up in a single tag as something like
`all_tags:"key"=>"value1","key2"=>"value2"`
unless you spend a lot of time setting up osmconf.ini - We decoding these down into their individual tags inside mapper be acceptable (helps with selection based on tags)?

**Comment by dg0yt** [comment]
The GDAL OSM driver is a little special.

Ubuntu 14.04 comes with [GDAL 1.10](https://github.com/OpenOrienteering/mapper/wiki/Target-systems). Do you use that version?

**Comment by mitchellkrome** [comment]
I started with that version and thought maybe that's why it didn't work - so I looked up the version in 3rd party and installed that from source and it still behaved the same.

**Comment by dg0yt** [comment]
Someone has to implement splitting of `all_tags` for GDAL/OGR templates which use the OSM driver.

**Comment by dg0yt** [comment]
I guess this will be unchanged in the v0.7.0. You may test the release candidate.

**Comment by dg0yt** [comment]
OSM tag import customization is possible through `osmconf.ini` in the gdal data folder. An alternative location maybe specified in configuration variable `OSM_CONFIG_FILE`. Cf. http://gdal.org/drv_osm.html.

(This may not work on Debian 8.0, Ubuntu 16.04, openSUSE Leap 42.1 or similar which still use GDAL 1.x.)

**Comment by dg0yt** [comment]
Actually, there was indeed an issue in our implementation. On the other hand, it is not really clear to me why OGR puts some simple closed ways as only geometry inside a geometry collection.

**Comment by Symbian9** [comment]
> (This may not work on Debian 8.0, Ubuntu 16.04, openSUSE Leap 42.1 or similar which still use GDAL 1.x.)

As workaround could try this PPA:UbuntuGIS
* https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

Details here:
* https://stackoverflow.com/questions/37294127/python-gdal-2-1-installation-on-ubuntu-16-04
