### ISSUE TITLE
Import SHP file or DXF

### ISSUE THREAD

**Issue by gudeso** [OpenOrienteering/mapper#813]
Hi,

Is it possible to import SHP file or DXF? as I get non support message when I try,

Thanks Ori

### Steps to reproduce
1.
2.
3.

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dg0yt** [comment]
DXF to some extent in the stable version. DXF in a different way and SHP to some extent in the unstable version.
