### ISSUE TITLE
Font rendering issues

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#819]
### Steps to reproduce
1. Install TTF-font. For this issue as test case used one of this files:
*  "CC Icons" - https://github.com/cc-icons/cc-icons/blob/master/fonts/cc-icons-simple/cc-icons.ttf
*  "Creative Commons" - https://github.com/cc-icons/cc-icons/blob/master/fonts/cc-icons.ttf

2. In OOM create empty symbol set
3. Add in this symbol set one "Text" symbol with font described above (as color use registered or create any color for this symbol)
4. Create text object with this symbol using all letters described here (at least all characters from "Round Icons" block):
* http://cc-icons.github.io/icons/

### Actual behaviour
Some symbols look like broken with incorrect shapes in "OpenOrienteering Mapper":
![CCIcons in OpenOrienteering Mapper](http://img-host.org.ua/images/cciconsfontoom.png)

### Expected behaviour
All symbols must look correctly, with similar style and correct shapes, for example, how it look like in other software:
* in "FontForge"
[CCIcons in FontForge](http://img-host.org.ua/images/cciconsfontff.png)

* in "LibreOffice"
![CCIcons in LibreOffice](http://img-host.org.ua/images/cciconsfontlo.png)

* in "sK1 2.0"
![CCIcons in sK1 2.0](http://img-host.org.ua/images/cciconsfontsk1.png)

### Configuration
Mapper Version: 0.6.7 (and older?)
Operating System: LinuxMint 17.3 XFCE (64bit)

P.S.: I found this issue when try "CC Icons" font, but maybe it's also presented with other fonts in OOM too.

**Comment by dg0yt** [comment]
Cannot reproduce in Ubuntu 16.04: PD icon rendered as expected. Reopen the issue and provide a test file if this issue is still present in Linux Mint 18.x.
