### ISSUE TITLE
"Tag window" - unified window for Tag Editor & Tag Selector widgets

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#825]
### Steps to reproduce
1. Run OOM
2. Create or open map
3. Open "Tag Editor" & "Tag Selector"

### Actual behaviour
Currently there are two different widgets for working with objects tags

### Expected behaviour
Unify those widgets in single "Tag window" widget (like "Symbol window", "Template Window", "Color window")

### Configuration
Mapper Version: 0.6.7
Operating System: all supported

P.S.: Also check widget naming because currenty it's "Tag Selection" and "Tag editor" names, but in manual there are "Tag Selector" and "Tag Editor"
* http://www.openorienteering.org/mapper-manual/pages/

**Comment by dg0yt** [comment]
Note that you may already merge the windows to a tabbed group (unless you are on an old system) by drag-and-drop of one window onto the other:

![unified-window](https://cloud.githubusercontent.com/assets/13567791/23586778/002dc580-019d-11e7-9956-0bcc8b6308d7.png)

**Comment by dg0yt** [comment]
The tag selector may become fairly obsolete by the new find dialog which accepts more complex queries, e.g. highway = "track" AND (foo = bar OR x != y).

**Comment by Symbian9** [comment]
Has you a new UI mockup for it?

**Comment by dg0yt** [comment]
It is in the "unstable" builds...

**Comment by Symbian9** [comment]
@dg0yt, fix menu entry for "Tag Editor" & "Tag Selector"

**Comment by Symbian9** [comment]
@dg0yt, in 'unstable' builds menu entry for "Tag Editor" & "Tag Selector" still not fixed.

Is it related to locales or is it mistake in sources?

**Comment by Symbian9** [comment]
@dg0yt, please, fix this issue in menu and widget naming!
![Tag Editor & Tag Selector](http://hnng.moe/f/WaF)
