### ISSUE TITLE
'Pick on map' button in 'Map CRS' dialogue does not work

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#830]
### Steps to reproduce
1. Create new map
2. Setup map coordinate reference system 
3. Open any georeferenced template
4. Try to pick reference point on the map

### Actual behaviour
'Map CRS' dialogue opened again, but field 'Geographic coordinates' is still unchanged 

### Expected behaviour
'Map CRS' dialogue opened again, and field 'Geographic coordinates' and other fields in section 'Reference point' are filled by proper values 

### Configuration
Mapper Version: All versions (tested on 0.6.1 and current) 
Operating System: All OSs (tested on Linux and Windows x64)

**Comment by dg0yt** [comment]
So far, it is meant to behave like this, for correction of where the real reference point is located on the map.

**Comment by yevhenmazur** [comment]
Sorry, it seems I've not understood how does it work.
So, is there a convenient way to change the reference point, except manually fill-in 'Geographic coordinates' field?

**Comment by dg0yt** [comment]
There is no such thing. What is the use case for changing both paper and real reference point synchonously? The intented use case is picking out a prominent point feature and entering the known coordinates of this feature.

**Comment by yevhenmazur** [comment]
I just want pick the point which will be used for magnetic declaration lookup. What is the proper way to do it?
Please note - I can't just copy-paste the coordinates in the field 'Geographical coordinates'

**Comment by dg0yt** [comment]
I wouldn't expect this point to make a significant difference for most orienteering maps.

To copy coordinates to the clipboard, first choose the desired format by right click on the coordinates in the status bar. Then right click the desired position and choose the top-right symbol:
 ![copy-coords](https://cloud.githubusercontent.com/assets/13567791/22407652/0231b636-e66b-11e6-82b0-a9f69be85128.png)

**Comment by yevhenmazur** [comment]
In my country the magnetic declaration can variate from 5.42° to 8.28°, so I look it up every time when I founding a new map (as often as setup georeference, or even create a new file).

Thanks, there is no problem to grab coordinates in to a clipboard, but impossible paste them in to the field 'Geographic coordinates'.

**Comment by yevhenmazur** [comment]
I'll create new issue, because the original topic and description are incorrect.
