### ISSUE TITLE
Ctrl+C, Ctrl+V

### ISSUE THREAD

**Issue by 999999333** [OpenOrienteering/mapper#831]
Version 0.6.7., windows,  have broken copy/paste within one map, crs UTM.
It will paste the item somewhere far away out of map area. try yourself

**Comment by 999999333** [comment]
![before](https://cloud.githubusercontent.com/assets/4051127/22407525/5e45b312-e668-11e6-8c4c-213d463b0113.PNG)
![paste](https://cloud.githubusercontent.com/assets/4051127/22407526/5e496ed0-e668-11e6-8c4e-cbf5351eedb6.PNG)

Pictures

**Comment by dg0yt** [comment]
Confirmed.
