### ISSUE TITLE
Unable to paste values in 'Geographic coordinates' field 

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#832]
### Steps to reproduce
1. Open 'Map coordinate reference system' dialogue
2. Try to fill-in 'Geographic coordinates' field from clipboard

### Actual behaviour
Nothing happened. Only symbol-by-symbol edit is available.

### Expected behaviour
The values from clipboard are pasted in the field.

### Configuration
Mapper Version: All versions
Operating System: All platforms

**Comment by SQ5TB** [comment]
Is decimal separator in your operating system the same as that in copied text? If copied text contains other than allowed characters you can't paste it.

**Comment by dg0yt** [comment]
The point of this issue is that the clipboard contains both latitude and longitude, but the input focus is on a single field.

**Comment by yevhenmazur** [comment]
Actually, the point of this issue was in my clipboard manager. When I'm trying to switch content in clipboard, blank field is filling by 0.000000, so the insert after does not occur.
