### ISSUE TITLE
Import from OCAD - rail symbol is lost

### ISSUE THREAD

**Issue by PeterHoban** [OpenOrienteering/mapper#834]
### Steps to reproduce
1. take an OCAD 11 map with rail alignments on it
2. open the map in OOMapper
3. the rail symbol is largely blank and railways are not rendered correctly

### Actual behaviour
Tell us what happens - Railway alignments are not rendered correctly

### Expected behaviour
Tell us what should happen instead - pretty obvious

### Configuration
Mapper Version: 0.6.1 
Operating System: Linux Mint

**Comment by dg0yt** [comment]
Please attach a minimal test file (in a ZIP container).
0.6.1 is pretty old ;-)

**Comment by PeterHoban** [comment]
Hello Kai
    I don't have OCAD so I cannot create one
        for you.  The smallest file I have with railway on it is
      600kB - attached.
    Regards,  Peter
    
    There are no problems more difficult to overcome than those which are merely imagined.
We never approach the truth in what we say unless that includes the expectation of being wrong.



    On 03/02/17 19:59, Kai Pastor wrote:
    
    
      Please attach a minimal test file (in a ZIP container).
        0.6.1 is pretty old ;-)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenOrienteering/mapper","title":"OpenOrienteering/mapper","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenOrienteering/mapper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dg0yt in #834: Please attach a minimal test file (in a ZIP container).\r\n0.6.1 is pretty old ;-)"}],"action":{"name":"View Issue","url":"https://github.com/OpenOrienteering/mapper/issues/834#issuecomment-277196987"}}}

**Comment by dg0yt** [comment]
You must attach on Github https://github.com/OpenOrienteering/mapper/issues/834, not via e-mail.

**Comment by PeterHoban** [comment]
[Inveresk - ISSOM - v3.6 - 4000.ocd.zip](https://github.com/OpenOrienteering/mapper/files/752051/Inveresk.-.ISSOM.-.v3.6.-.4000.ocd.zip)

**Comment by dg0yt** [comment]
We miss a black line below the white dashes. Unlike other suggestions for the railway symbol, in the given map this black line is not implemented as a "framing" but as "double line fill color" - despite the fact that there is no double line...

BTW I would like to know the coordinate reference system used by this map. Is this UTM? Even the OCAD 11 Viewer complain about an unknow grid (65000).
