### ISSUE TITLE
Problems with area pattern direction

### ISSUE THREAD

**Issue by ogeo-project** [OpenOrienteering/mapper#844]
### Steps to reproduce
1. In new map, draw area with symbol having adjustable direction (example 411)
2. Change default direction (90°) to other (example 23°)
3. Change this area with other symbol having not adjustable direction (example 409)
4. At this state all seems correct at screen with mapper
5. Export this file from omap to ocad format
6. Then we can see that area having not default direction but the changed direction at step 2

### Actual behaviour
A try to export OMAP map from Linux ubuntu 14.04 (64 bits) to OCAD map for use with Windows 7 pro (64 bits). When I print map, area with fixed direction is in not at default direction (usually 90°).

### Expected behaviour
I thinks it is a bug in OCAD export

### Configuration
Mapper Version: 0.6.8
Operating System: Linux  Ubuntu 14.04 LTS

Thank you
Eric (France)

**Comment by dg0yt** [comment]
Hm, when I switch from 411 Vineyard to 311 Indistinct Marsh, the new pattern is rotated as was the old pattern, without OCD format being involved. In addition, the rotation seems to be applied inconsistently to both rows, for 311 only.
