### ISSUE TITLE
OOMapper for PuppyLinux

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#846]
Some builds & comments for PuppyLinux users 
* packages - http://www.murga-linux.com/puppy/viewtopic.php?t=109888
* xcb issue (solved) - http://www.murga-linux.com/puppy/viewtopic.php?t=109874

Mapper Version: 0.6.8
Operating System: PuppyLinux

**Comment by dg0yt** [comment]
Not even listed on repology.

https://repology.org/metapackage/openorienteering-mapper/information
