### ISSUE TITLE
Too small point symbols in symbol menu

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#848]
### Steps to reproduce
1. Change symbol in Android version
2. Almost impossible to see difference between small point symbols in same colors
3. You get no text showing what symbol you chosed, you can see it when you are in drawing mode - but still no access to name of symbol

### Actual behaviour
The point symbols are shown unnessacarey small and there is no way to see the symbols' names

### Expected behaviour
- [ ] Point symbol should fill more of the available area. (Line symbols works OK)
- [ ] Android: Display the symbol names

### Configuration
Mapper Version: 0.6.8
Operating System: Android

**Comment by dg0yt** [comment]
Which symbol number and map scale in particular?
Which screen resolution and size?

**Comment by Zerbembasqwibo** [comment]
Actually it is just not Android version. I mean that point symbols are so small compared to line objects, they should not be shown in same scale. It's just that the Android device is so much smaller so there I can see the difference. I think all point objects could be shown in a bigger scale, maybe also on desktop versions of OOM.

I would prefer them shown bigger, as in the left part of my picture. The map symbols are from the 1:15 000 ISOM-template in OOM 0.6.8 where I started a new map to show this.

![image](https://cloud.githubusercontent.com/assets/16168975/24103672/46762020-0d80-11e7-9cba-ad3163424f7a.png)

I used OOM 0.6.8 on a screen 5 inch Full HD, 1080 × 1920, Pixel Density 446 ppi according to specification.

**Comment by dg0yt** [comment]
For 1:15000 ISOM, most symbols are quite small indeed. What is your opinion on the 1:10000 icons?

All icons are created with a default zoom of 200%. The zoom is reduced for some icons if needed to fit the space. In general, this works reasonably well (i.e. relative sizes are correct for most symbols, biggers symbols are not cut off). If we increase the default zoom, more icons might need a reduced zoom. So there is a trade-off with correct relative sizes. Note that this also affects other types of symbols.

Increasing the default to 300%, the 1:15000 icons will look like the 1:10000 icons now, but 1:10000 will be really large:
![300percent-isom-10000](https://cloud.githubusercontent.com/assets/13567791/24135880/845268cc-0e0c-11e7-93e0-3c4486349ec2.png)

The simplest remedy is to make the symbol zoom a configuration option.

**Comment by Zerbembasqwibo** [comment]
I see no need of correct relative sizes in the menu.

I never use other symbols than 1:15 000 so I can't say. (When to use?? All maps should be drawn in 15'? Well that's another question.)

I think it would be a good solution, to make it a configuration option. It depends on the size of you device (and you eyes...) so good if you can choose.

But my other question: is it possible to read the name of the symbol somewhere in that menu, or in drawing mode? Sometimes you have symbols that you want to read name of (if you use own symbols, or if you don't know by heart  difference between 402 and 404).

**Comment by Symbian9** [comment]
It would be cool, if in symbol window could set 2x symbol preview zooming

**Comment by dg0yt** [comment]
For ISSOM, 1:5000 is a common size...
Relative size matters at least for symbols where we have more than one size (broken ground, boulder, boulder field, boulder cluster, stony ground).
I made the request for displaying the name an explicit sub-issue in the original posting.

Regarding zoom: Apart from the explicit preference, we might add direct zooming to change the preference (mouse wheel, pinch gesture).

Regarding displaying the symbol name on Android: I don't think it is a good idea to add much text to the symbol window. Would it be acceptable to make symbol selection a two-click process? On first click, we would just show the symbol name. Only on second click on the same symbol, it would be accepted as the new drawing symbol.

**Comment by Zerbembasqwibo** [comment]
I mean of course, why draw ISOM-maps in other scales than 15 000? But maybe
one thing would be better: I think the freehand-tool has too bad
resolution. I wrote it in another issue I think. If you draw with enlarged
symbols maybe you can use freehand tool with better precision? Later,
change scale and symbol sizes.

Zoom: find a good solution and I'll be happy.

Displaying namnes: it is rare/seldom you want to see the name, make see
name through the complicated process, for example by "press-hold" option?

2017-03-22 7:29 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
Press-and-hold is best solved with #788 then.
Free-hand resolution is #701.
