### ISSUE TITLE
Number of decimals in symbol specification (to prevent moire).

### ISSUE THREAD

**Issue by arenol** [OpenOrienteering/mapper#849]
In order to prevent moire on certain symbols (particulalry marshes - 310 and 311) when printing maps on laser printers, more than two decimals are needed to produce a hatch that aligns with the native resolution of printers. Alternatively, it also helps being able to specify dimensions in points.

See http://www.emap.no/docs/ISOMMarshMoire.pdf for rationale.

Agnar

**Comment by dg0yt** [comment]
We can add more decimals or a different unit to the file format we control (OMAP), but it will be lost when exporting to OCD. 

I wonder if it would be feasible to do rounding of some dimensions to multiples of the printer resolution.

**Comment by arenol** [comment]
Dear Kai.
    
    I looked into a file using a text editor, and recognized that
      dimensions were given as integers in units of micrometers.  Thus,
      a line weight of 0.12 mm was given as 120.  Since I can only
      specify the line weight with 2 decimal accuracy, I cannot specify
      the last digit inside the OOM-GUI.  Though I might open the file
      in a text editor, and specify the last digit if I want 0.127  mm =
      127 .  The value seem to be preserved when I save the file back
      fro OOM, unless I have edited the value in OOM.
    So there's a good reason to allow that extra digit in the GUI.
    
    Kind regards, 
      Agnar
    Agnar Renolen
eMap as (www.emap.no)
Vegamot 4B. 7049 Trondheim
m: 489 50 480
    On 22.03.2017 07:39, Kai Pastor wrote:
    
    
      We can add more decimals or a different unit to the file format
        we control (OMAP), but it will be lost when exporting to OCD.
      I wonder if it would be feasible to do rounding of some
        dimensions to multiples of the printer resolution.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenOrienteering/mapper","title":"OpenOrienteering/mapper","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenOrienteering/mapper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dg0yt in #849: We can add more decimals or a different unit to the file format we control (OMAP), but it will be lost when exporting to OCD. \r\n\r\nI wonder if it would be feasible to do rounding of some dimensions to multiples of the printer resolution."}],"action":{"name":"View Issue","url":"https://github.com/OpenOrienteering/mapper/issues/849#issuecomment-288311766"}}}

**Comment by dg0yt** [comment]
The GUI change for the pattern itself is done.
We probably need another change, for the point symbol inside the pattern (e.g. dash line width inside the marsh pattern).

**Comment by dg0yt** [comment]
Okay, trying to deal with the Cyan color uncovered hidden issues with map colors. Now (in the next unstable build), all features should be ready. 

I attach a sample file for experimentation and comments. On my Linux machine, I cannot get output which is on par with the PDF above, but the improvement is already significant.

[#849 Moiré.omap.zip](https://github.com/OpenOrienteering/mapper/files/870082/849.Moire.omap.zip)
