### ISSUE TITLE
Mapper on Windows mobile phone?

### ISSUE THREAD

**Issue by ohartvic** [OpenOrienteering/mapper#852]
I just wanted to ask whether OMapper runs on Windows mobile phones (W10)?

**Comment by dg0yt** [comment]
AFAICT this would require binaries for "Windows Runtime" (WinRT) which we do not provide (and probably cannot provide).

**Comment by ohartvic** [comment]
What a quick answer! You prompted me to lookup on WinRT and it seems that for W10 applications can be built using [Universal Windows Platform (UWP)](https://docs.microsoft.com/en-gb/windows/uwp/get-started/whats-a-uwp). As they (MS) say, application built using UWP  can be used on W10 running on any device (theory I guess).

Perhaps this is something you guys are considering? Asking selfishly as I have a W10 mobile phone :)

**Comment by dg0yt** [comment]
At the moment, we don't even support Microsoft Visual C++ for traditional Windows application. Supporting the quite different UWP is really out of scope.

**Comment by ohartvic** [comment]
Understand, thank you for your answer.

**Comment by dg0yt** [comment]
I suppose the Windows mobile phone platform is obsolete now.
