### ISSUE TITLE
russian tooltips on english translation

### ISSUE THREAD

**Issue by greglondon** [OpenOrienteering/mapper#853]
### Steps to reproduce
1. place a mouse over the symbols on the right hand side

### Actual behaviour
Xubuntu 16.04. English system settings. Russian toolips in symbols panel on the right

### Expected behaviour
Should be English tooltips

### Configuration
Mapper Version: 0.6.7
Operating System: Xubuntu 16.04

**Comment by sikmir** [comment]
What symbol set in use? Maybe ISOM_ru_15000?

**Comment by greglondon** [comment]
ISMTBOM_uk_20000 which comes with the Mapper so not Russian at all.

**Comment by yevhenmazur** [comment]
_uk_ means Ukrainian in this case (like in locale name), so it is Ukrainian, not Russian. If you need English, just use symbol set without language mark.

**Comment by greglondon** [comment]
Silly me. so embarrassing. Will do. Thanks.
