### ISSUE TITLE
Broken packages??

### ISSUE THREAD

**Issue by cmorse01** [OpenOrienteering/mapper#857]
Have previously run OOM on an older linux machine (no longer in use) and also under Android.  Attempted to download the lastest version on my current linux machine but hit the following error(s):

The following packages have unmet dependencies:
 openorienteering-mapper : Depends: libproj9 (>= 4.8.0) but it is not installable
                           Depends: qtbase-abi-5-6-1 but it is not installable
                           Recommends: qttools5-dev-tools but it is not going to be installed
                           Recommends: qt5-image-formats-plugins but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Suspect perhaps the 17.04 repositories have not caught up with the 16.10 versions?  Or maybe something else going on.

### Configuration
Mapper Version: 0.6.8 (attempted)
Operating System: Ubuntu 17.04, Kernel 4.10.0-19-generic, MATE desktop

**Comment by dg0yt** [comment]
There is nothing broken in the packages, but you attempted to install packages built for a different (version of your) distribution. 

Now I added Ubuntu 17.04 repositories for Mapper on opensuse.org, so the desired packages should appear soon.

https://software.opensuse.org//download.html?project=home%3Adg0yt&package=openorienteering-mapper
