### ISSUE TITLE
Build fail when adding new symbol set

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#859]
### Steps to reproduce
1. Add  new .xmap file in ./symbol sets/src
2. Add appropriate strings in CMakeLists.txt 
3. Run configure and make commands

### Actual behaviour
`make[2]: *** No rule to make target '../symbol sets/10000/ISOM2017_10000.omap', needed by 'symbol sets/10000/COPY_OF_ISOM2017_10000.omap'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:369: symbol sets/CMakeFiles/Mapper_symbol_sets.dir/all] Error 2
make: *** [Makefile:139: all] Error 2`

### Expected behaviour
Build successfully compiled.

**Comment by dg0yt** [comment]
You must not add the scaled files to the build system before they do exist: there are no build rules for generating or updating the scaled symbol sets from the src folder. 

(test/symbol_set_t can do this step once adjusted for the new src symbol set, but it won't be invoked automatically when the scaled version is missing or outdated.)

**Comment by yevhenmazur** [comment]
Unfortunately I'm not familiar with C, cmake and with programming at all. Could you provide a clear instruction how to add a symbol set properly, or add it by yourself?
Thanks.

**Comment by dg0yt** [comment]
If you can't prepare a pull request with just the new file in symbol sets/src/, then attach the symbol set (in a ZIP file) in #612, and I will prepare it for review and integration.

**Comment by yevhenmazur** [comment]
Done.
https://github.com/OpenOrienteering/mapper/pull/860
Anyway, I'll be happy to know how to invoke test/symbol_set_t

**Comment by dg0yt** [comment]
test/symbol_set_t is just another executable, and in Qt Creator it can be selected and started like Mapper. It is a test (for historical reasons), not a program for end users. Actually I still try to keep the source code simple, so it can serve very well as an example how to programmatically load map files, enumerate symbols and perfom certain actions on them. The core symbol set handling is here, for source and target files list in the _data function just before this line:

https://github.com/OpenOrienteering/mapper/blob/master/test/symbol_set_t.cpp#L142

The examples don't need scaling so they are easier to handle:

https://github.com/OpenOrienteering/mapper/blob/master/test/symbol_set_t.cpp#L361
