### ISSUE TITLE
Implement alternatives to area pattern clipping

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#863]
At the moment, area fill patterns are simply clipped at the are outline. For implementing symbols like ISOM 2017 "209 Boulder field", it is desirable to always draw fill pattern elements either unclipped (inside or close to the outline) or not at all (otherwise).

(1) clipping  ................................................... (2) elements completely inside area outline
![alternatives-to-clipping](https://cloud.githubusercontent.com/assets/13567791/25450337/e53720aa-2abe-11e7-9528-beb14707fe59.png)
(3) element center inside area outline ....... (4) elements partially inside area outline

(For simplicity/performance, the rectangular extent of the element is used here instead of the actual element outline.)

**Comment by Zerbembasqwibo** [comment]
Much code, little use. Make this a low priority question pls.

**Comment by dg0yt** [comment]
Actually not that much code (most commits from #862 are for general quality, not for this feature). It adds value to the area symbol, and in helps to handle OCD 12 file format.

**Comment by Zerbembasqwibo** [comment]
Ah, correct, OOM must copy everything OCAD puts into it's format.

2017-04-26 22:39 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
No, we don't do that, and it's a waste of my time to make me read such comments.

**Comment by Zerbembasqwibo** [comment]
Sorry, It was not meant wasting your time. But to explain: I understand
that it might be necassary to handle tgose things that OCAD puts into it's
format. That was what I mean.

2017-04-26 22:59 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by wanacode** [comment]
I have been using the Stony ground area symbols (210 - 212) and my preference would be number 2. When areas of the different symbols meet it looks very messy with the current clipping.

![screenshot at 2017-05-09 20-53-07](https://cloud.githubusercontent.com/assets/2317149/25842894/a9bfe602-34f9-11e7-96d2-128b6f9a857c.png)

**Comment by lpechacek** [comment]
I gave a shot to origin/area-symbol branch and tested it with the stony ground and boulder field area symbols from the ISOM 2017 set I am working on. I was surprised to see that clipping works on "pattern block" level rather than individual pattern elements. As a result the outer boundary is not smooth and elements overlap on the boundary between areas. To be honest, I have no idea how to solve the inter-area boundary problem.

![areas](https://cloud.githubusercontent.com/assets/5584406/25852866/15c6a608-34cb-11e7-9e00-58e9f5930637.png)

**Comment by dg0yt** [comment]
Not really surprising, with regard to the screenshot at the top and my last comment in #862. For the screenshot in that comment, I split the area symbol in multiple fill patterns (by editing XML) to circumvent the current limitations.

I started #862 in order to explore what is possible with reasonable effort, to support ISOM 2017. Looks like it needs to go a little further, but it still seems possible for the limited set of primitives in a fill pattern (point symbol). Since this is on a hot path (called very often) when editing filled objects, I cannot solve it quick and dirty, but there seems to be a good chance for optimization. But it needs more testing then.

**Comment by Zerbembasqwibo** [comment]
Didn't IOF MC had some ideas of how to implement this?

2017-05-09 21:27 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by lpechacek** [comment]
On second thought I agree. I was surprised that area boundary looks _that bad_ with dotted pattern. With commit 7759583 the result looks acceptable to me. The outer boundary is fine and inter-area boundary shows dot doubling with stony ground pattern. Maybe dot (point) diameter should be taken into account when deciding if all pattern element points are within the area boundary.

I like the changes in area-symbol branch. Thanks!

**Comment by dg0yt** [comment]
> Maybe dot (point) diameter should be taken into account when deciding if all pattern element points are within the area boundary.

This is not done in "center is inside" mode (why?), but "completely inside" and "partially inside" do use the diameter to determine four points on the outline (left, top, right, bottom) to make their decision.

The dot doubling (with "partially inside" and "center") is not an issue if they use the same map color. It could be reduced if we used three or five coords for a circle and another mode "majority inside".

**Comment by lpechacek** [comment]
> but "completely inside" and "partially inside" do use the diameter to determine four points on the outline

Hmm? I switched between all "Draw elements if ..." modes on the stony ground area symbol and saw that the border dots looked the same regardless of the mode. From that I inferred that dot diameter is not taken into account and didn't look into the code.

**Comment by dg0yt** [comment]
>> but "completely inside" and "partially inside" do use the diameter to determine four points on the outline
>
> Hmm? I switched between all "Draw elements if ..." modes on the stony ground area symbol and saw that the border dots looked the same regardless of the mode. From that I inferred that dot diameter is not taken into account and didn't look into the code.

Actually, the behaviour I described was applied only to the (default) central dot/circle. Fixed in dev  1625696.

BTW line width for circles and for line elements is also not taken into account.

TODO: Write documentation.

**Comment by dg0yt** [comment]
Closing this issue despite missing documentation: symbol editor documentation is incomplete anyway.
