### ISSUE TITLE
Use GDAL for extended raster file format support

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#864]
Adding GDAL support for extended file format support was initially tracked in #574. Vector format support was completed for v0.7.0.
Raster file format support still needs to be done and and must be delivered in a future version.

(Split from #574:)
- [x] Implement a Template class for _raster_ formats based on GDAL
- ~Consolidate existing Template classes~ (separate from this GDAL issue)

This feature will be required or beneficial for the following issues:
- #67 OziExplorer files
- #84 WMS support
- #106 Georeferenced raster images
- #124 Laser scanning files
- #284 GeoTIFF support
- [DXF-related issues](https://github.com/OpenOrienteering/mapper/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dxf)
- #601 GPX/KML export
- #795 Export to Geospatial PDF
- #931 Template/world files with different projection

**Comment by sikmir** [comment]
GDAL 2.2.0 is released ([release notes](http://trac.osgeo.org/gdal/wiki/Release/2.2.0-News)).

**Comment by dg0yt** [comment]
I subscribed to all Debian source packages which are used in superbuild. gdal 2.2.0 is in Debian experimental. But we will probably stay on sources for Debian testing (or even stable, after the next release).

(A quick attempt on using the 2.2.0 Debian tarballs failed when I was preparing RC3.)

**Comment by Symbian9** [comment]
> GDAL 2.2.0 is released

There no builds for 2.2.0 in 'stable' PPA...

* https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa

..., but in 'unstable' & 'experimental' PPA's there is 2.2.x

* https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable
* https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-experimental

**Comment by Symbian9** [comment]
> #124 Laser scanning files

It would be cool if there would be also an option for use `gdaldem` for generate [Maperitive](http://maperitive.net/)-like "hillshading" templates based on DEM:

- https://github.com/OSGeo/gdal/pull/1339

**Comment by dg0yt** [comment]
This is the list of raster formats which will probaly be supported as templates via GDAL, with the next release of Mapper:

| Driver | Long name  | Extensions |
|--------|------------|------------|
| AAIGrid | [Arc/Info ASCII Grid](https://gdal.org/frmt_various.html#AAIGrid) | asc |
| ACE2 | [ACE2](https://gdal.org/frmt_various.html#ACE2) | ACE2 |
| ADRG | [ARC Digitized Raster Graphics](https://gdal.org/frmt_various.html#ADRG) | gen |
| BIGGIF | [Graphics Interchange Format (.gif)](https://gdal.org/frmt_gif.html) | gif |
| BLX | [Magellan topo (.blx)](https://gdal.org/frmt_various.html#BLX) | blx |
| BMP | [MS Windows Device Independent Bitmap](https://gdal.org/frmt_bmp.html) | bmp |
| BT | [VTP .bt (Binary Terrain) 1.3 Format](https://gdal.org/frmt_various.html#BT) | bt |
| BYN | [Natural Resources Canada's Geoid](https://gdal.org/frmt_byn.html) | byn err |
| CAD | [AutoCAD Driver](https://gdal.org/drv_cad.html) | dwg |
| CALS | [CALS (Type 1)](https://gdal.org/frmt_cals.html) | .cal .ct1 |
| COASP | DRDC COASP SAR Processor Raster | hdr |
| DTED | [DTED Elevation Raster](https://gdal.org/frmt_various.html#DTED) | dt0 dt1 dt2 |
| E00GRID | [Arc/Info Export E00 GRID](https://gdal.org/frmt_various.html#E00GRID) | e00 |
| ECRGTOC | [ECRG TOC format](https://gdal.org/frmt_various.html#ECRGTOC) | xml |
| EHdr | [ESRI .hdr Labelled](https://gdal.org/frmt_various.html#EHdr) | bil |
| ENVI | [ENVI .hdr Labelled](https://gdal.org/frmt_various.html#ENVI) |  |
| ERS | [ERMapper .ers Labelled](https://gdal.org/frmt_ers.html) | ers |
| ESAT | [Envisat Image Format](https://gdal.org/frmt_various.html#Envisat) | n1 |
| FIT | [FIT Image](https://gdal.org/frmt_various.html#) |  |
| GFF | [Ground-based SAR Applications Testbed File Format (.gff)](https://gdal.org/frmt_various.html#GFF) | gff |
| GIF | [Graphics Interchange Format (.gif)](https://gdal.org/frmt_gif.html) | gif |
| GPKG | [GeoPackage](https://gdal.org/drv_geopackage.html) | gpkg |
| GRIB | [GRIdded Binary (.grb, .grb2)](https://gdal.org/frmt_grib.html) | grb grb2 grib2 |
| GS7BG | [Golden Software 7 Binary Grid (.grd)](https://gdal.org/frmt_various.html#GS7BG) | grd |
| GSAG | [Golden Software ASCII Grid (.grd)](https://gdal.org/frmt_various.html#GSAG) | grd |
| GSBG | [Golden Software Binary Grid (.grd)](https://gdal.org/frmt_various.html#GSBG) | grd |
| GTX | NOAA Vertical Datum .GTX | gtx |
| GTiff | [GeoTIFF](https://gdal.org/frmt_gtiff.html) | tif tiff |
| GXF | [GeoSoft Grid Exchange Format](https://gdal.org/frmt_various.html#GXF) | gxf |
| VRT | [Virtual Raster](https://gdal.org/gdal_vrttut.html) | vrt |
| XPM | [X11 PixMap Format](https://gdal.org/frmt_various.html#XPM) | xpm |
| XYZ | [ASCII Gridded XYZ](https://gdal.org/frmt_xyz.html) | xyz |
| ZMap | [ZMap Plus Grid](https://gdal.org/frmt_various.html#ZMap) | dat |

**Comment by dg0yt** [comment]
The list was incomplete. Now the post is updated: https://github.com/OpenOrienteering/mapper/issues/864#issuecomment-566927083

**Comment by dg0yt** [comment]
We may have to watch for formats/extensions which support both raster and vector data, e.g. .kml.
