### ISSUE TITLE
Easy drawing of given direction and distance

### ISSUE THREAD

**Issue by zlenhart** [OpenOrienteering/mapper#867]
Mapmaker often needs to mark a point in the direction and distance measured from the actual standpoint by compass and distance meter, i.e. given as numeric values.

### Actual behaviour
Not emploied yet.

### Expected behaviour
1. User selects point object (standpoint, may be drawn manualy or gained by function GPS point draw), any point symbol (for target point) and this new tool.
2. Small window with direction and distance values appears, values follow the moves of cursor.
3. User puts the target point on any  position on screen and moves it immediately until the values equal to desired (measured) values.
Alternative solution (not preferred): 
1. Same as above
2. Small window with numerical keyboard and fields for direction and distance appears.
3. User types the measured values and clicks Finish.
4. Target point is drawn on given position.

**Comment by dg0yt** [comment]
#398
