### ISSUE TITLE
WARNING using file "ISOM2017_15000.xmap" together with Kartapullauttin

### ISSUE THREAD

**Issue by Freemapper** [OpenOrienteering/mapper#869]
I tried importing and changing the new symbol-file ”ISOM2017_15000.xmap” but the white backround changed to brown on part of my basemap. 
The brown background cannot be taken away and has destroyed  the (brown) squarefield of 2,5*2,5 km where I had imported lidar data and done field work but not in the other parts of my map done in the same way. I tried to uncheck the crosses in the option boxes during the process, but had the same result.
I have found the background turns brown after having imported template "contours.dfx" wich I have after processing Lidar-data in Kartapullauttin.
This Kartapullauttin-file "contours.dfx" gives 30 cm contourlines as a background template but is a big file forcing me to upgrade my surfplate to a Huawei with 4 Gb RAM-memmory (about 350 euro). The curves are beautiful to have  during field work, but the file "ISOM2017_15000.xmap" for upgrading the symbols, destroys the map (=Warning!)
I`m lucky to have tried on a backupp-file only so its just a day´s work wich is destroyed.
(Have tested this after imorting one more of this template "contours.dfx"-file in another part of the basemap)

Im using OOM version 0.6.8 but started in 0.6.6 when the basemap was made. Have Windows 10 on my home computer. Field wor made on a Samsung Mediapad and later upgraded to Hawei Mediapad 3.

I have no idea wat´s causing the problem, but has sent a mapfile to OOM for testing.

**Comment by Freemapper** [comment]
Also found symbol 509 Narrow ride changes to the new 509 Railway ( from the new symbol-file ”ISOM2017_15000.xmap”).
Today I found I can open my old files I thought were destroyed without problem, but the problem comes back when I try to use the ISOM2017_15000.xmap file.

**Comment by dg0yt** [comment]
> Also found symbol 509 Narrow ride changes to the new 509 Railway ( from the new symbol-file ”ISOM2017_15000.xmap”).

As I told you before, ISOM 2017 sometimes has a different number for an otherwise unchanged symbol. If you want to use the work-in-progress ISOM 2017 Mapper symbol set, you will have to adjust the suggested replacements which are only based on code numbers. Blindly doing replacements by code number doesn't count as destroying files.

**Comment by dg0yt** [comment]
You can still use the "Replace symbol set..." feature. Just remove the check mark in front of "Match replacement symbols by symbol number". Then you can edit the replacement column for 509 and friends.

Cf. http://www.openorienteering.org/mapper-manual/pages/symbol_replace_dialog.html

**Comment by Freemapper** [comment]
Even if I do so the whole 2,5*2,5km field turns to brown background. I
guess you mean I still should use the file "ISOM2017_15000.xmap"?

Stefan

2017-05-06 17:55 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
I can't tell. I still have no files for investigation. I even don't which version ISOM2017_15000.xmap you downloaded.
You may try to hide (brown) symbols until you found the offending one.

**Comment by Freemapper** [comment]
Problem solved by dg0yt. I had created a frame around my map and used the symbol for "Motorway". This made the area after conversion, to be an "paved area" symbol 2,5*2,5 km big. I think this thread can be deleted so no one else gets scared of trying. My map works just fine after conversion now.
