### ISSUE TITLE
Error openorienterig mapper v-0.6.8. cierre inesperado windows 7-64bits

### ISSUE THREAD

**Issue by ghost** [OpenOrienteering/mapper#870]
### Steps to reproduce
1. mucha lentitud de trabajo con oppenorientering mapper al trabajar con un archivo que funcionaba bien.
2. 
3.

### Actual behaviour
Estaba trabajando con un archivo sin ningun problema y de repente empezo a ir muy lento el oppenorintering mapper, ahora mismo no puedo trabajar con ese archivo, windows da error de que la aplicación oppenorientering mapper a dejado de funcionar y se cierra, he comprobado que el archivo tiene un tamaño exagerado. como se puede solucionar?

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:0.6.8
Operating System:windows 7-64bits

**Comment by romoma** [comment]
Lo que me sucede es lo siguiente: yo estoy trabajando con un fichero en openorienterig mapper sin ningún problema, pintado el mapa, pero con el tiempo el openorientering mapper se vuelve cada vez mas lento hasta que apenas puedo hacer nada y windows termina cerrando el openorientering mapper. apago el ordenador y vuelvo a encenderlo y nada de nada sigue igual, he comprobado que el fichero pasa a tener un tamaño de casi el doble de lo normal y que mejora borrando el historial de deshacer. he conseguido solucionarlo ocultado alguna capa, pero en cuanto la vuelvo a activar, se vuelve muy lenta la aplicación.

**Comment by dg0yt** [comment]
Not enough details to reproduce this.
