### ISSUE TITLE
OOM not responding when import OCD file

### ISSUE THREAD

**Issue by JayneSales** [OpenOrienteering/mapper#875]
### Steps to reproduce
1. Open OpenOrienteeringMapper
2. Start New Map
3. Templates -> Import Template

### Actual behaviour
Just downloaded OOM, tried to import map file as base map and I just get not responding

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: 0.6.8
Operating System: Windows 10 Pro x64

![image](https://cloud.githubusercontent.com/assets/28725930/26095670/c0726af6-3a61-11e7-99ef-21cc59a6156a.png)

**Comment by dg0yt** [comment]
Do I understand correctly that this happens after the file dialog?
If yes, which version of OCD file?

**Comment by JayneSales** [comment]
It's version 9.

It happens if I try open the file, or if I try open it as a template.

**Comment by dg0yt** [comment]
Again, do I understand correctly that this happens after the file dialog?
Doesn't this happen with other files.

If yes, I will probably need to look at the offending file. You can sent it to my personal e-mail, see https://github.com/dg0yt.

**Comment by JayneSales** [comment]
What do you mean it happens after the file dialog?  It happens after I do
Create a new map -> Set symbol set.  Template -> Open Template then
navigate to the file.

I'm afraid I don't have other ocad files to try it on, but I can send you
the file.

Jayne

**Comment by dg0yt** [comment]
I try to understand when the "not responding" state is triggered: already when Mapper tries to open the native file dialog (i.e. the dialog would not appear), or after selecting the file (double click, or click on "Open").

**Comment by JayneSales** [comment]
Ok, I understand now.  It's after selecting the file.

**Comment by dg0yt** [comment]
Updated "unstable" builds with the fix for this issue are now available.

**Comment by JayneSales** [comment]
Thanks
