### ISSUE TITLE
Importing shp file

### ISSUE THREAD

**Issue by gudeso23** [OpenOrienteering/mapper#876]
Any updates when it will be feasible and easy to import shp files to OOM?

Ori

### Steps to reproduce
1.
2.
3.

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dg0yt** [comment]
Please test release candidate Mapper 0.7.0-RC3. SHP file import works fine with OSM-derived files from Geofabrik.

https://github.com/OpenOrienteering/mapper/releases

**Comment by dg0yt** [comment]
... and report the result here.

**Comment by gudeso23** [comment]
Importing a shp file was smooth, but now there are issues to georeferenced it with the aerial image/


Dr. Ori Gudes
Research Fellow, City Futures Research Centre
Built Environment
UNSW SYDNEY NSW 2052 AUSTRALIA
T: +61 (2) 9385 6201
E: o.gudes@unsw.edu.au<mailto:o.gudes@unsw.edu.au>
W: cityfutures.net.au<http://www.cityfutures.net.au/>

List of publications (Updated April 2017) https://tinyurl.com/krt2jzc

[CF_Logo]

**Comment by dg0yt** [comment]
Either the issue is resolved, or you need to explain the issues.

**Comment by gudeso23** [comment]
I could not georeferenced the shp layer to the raster image had to do it in ArcGIS


First name Last name
Title
Department/Faculty

UNSW SYDNEY NSW 2052 AUSTRALIA
E: xxxxx@unsw.edu.au<mailto:xxxxx@unsw.edu.au>
T: +61 2 9385 xxxx
W: unsw.edu.au
CRICOS Provider Code 00098G

 [cid:image001.png@01D2758A.1DD460C0] <http://www.unsw.edu.au/>

**Comment by dg0yt** [comment]
You are saying that you failed to achieve a desired outcome, but you provide no hint what you actually did do. See the issue template in your initial posting for how to provide a good report.

(For the record, I can easily import SHP files of OpenStreetMap data from http://download.geofabrik.de/ into a georeferenced map. I assume that GDAL consults the accompanying .prj files for georeferencing.)

**Comment by gudeso23** [comment]
Dear Kai


Apologize for not replying before. As a GIS person I found it easier to do the georeferencing process within ArcGIS Desktop because the available tools to do so. So, I guess my suggestion would be to try to improve the georeferencing tool avilable in OOM.


Regards Ori



Dr. Ori Gudes
Research Fellow, City Futures Research Centre
UNSW Built Environment
UNSW SYDNEY NSW 2052 AUSTRALIA
T:+ 61 (2) 9385 4931
<mailto:c.ticzon@unsw.edu.au>o.gudes@unsw.edu.au<mailto:o.gudes@unsw.edu.au>
http://cityfutures.be.unsw.edu.au


 [1487291223426_image010.png]

________________________________

**Comment by dg0yt** [comment]
Dear Ori,
please understand that your suggestion is too abstract to have any effect. No particular feature in Mapper is considered perfect. Only you can explain what kind of improvement you think of.
Feel free to reopen when you find time to provide more details.
Regards, Kai.
