### ISSUE TITLE
DXF import error "The path is empty..."

### ISSUE THREAD

**Issue by FEK10** [OpenOrienteering/mapper#877]
### Steps to reproduce
1.everytime i try to import FOT_Polygons_gillelejefot.dxf it says it is empty
2.
3.

### Actual behaviour
![2017-05-17](https://cloud.githubusercontent.com/assets/19652414/26156215/e4e25fae-3b15-11e7-9342-657fd15d6dcb.png)

### Expected behaviour

Tell us what should happen instead

### Configuration
Mapper Version: 0.6.8
Operating System: windows 10

**Comment by dg0yt** [comment]
Please test release candidate Mapper 0.7.0-RC3 instead. DXF import is fundamentally different (when the new GDAL/OGR based import is enabled in the settings).

https://github.com/OpenOrienteering/mapper/releases

**Comment by dg0yt** [comment]
I assume this is fixed by the new GDAL/OGR based import.
