### ISSUE TITLE
Crash during symbol set replacement

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#880]
### Steps to reproduce
1. open replacement-crash-map.omap from [replacement-crash.zip](https://github.com/OpenOrienteering/mapper/files/1018873/replacement-crash.zip)
2. change symbol set Symbols > Replace symbol set..., choose replacement-crash-new-symbols.omap
3. confirm use of different scales
4. **UNcheck** Match replacement symbols by symbol number
5. map 537.0 Cairn to 526 Cairn, click OK
6. **confirm** Rescale the imported data.

### Actual behaviour
crash (SEGV)
in debug mode the Q_ASSERT(symbol_map.contains(item.key())) at src/map.cpp:837 triggers

### Expected behaviour
Unsure... I wasn't able to understand how code introduced in 0d4479ea989c3 is supposed to work.

### Configuration
Mapper Version: v0.7.0-RC2-15-gd72dacddff54 (ISOM 2017 devel branch)
Operating System: openSUSE Tumbleweed 20170516-0

**Comment by dg0yt** [comment]
Thanks for reporting. I'm currently working on symbol replacement (for ISOM2017), but different scales were not on my list.

**Comment by dg0yt** [comment]
Symbol set replacement [with files of different scales](https://github.com/OpenOrienteering/mapper/blob/master/test/map_t.cpp#L95) is covered by a test, but [the scale is adjusted before the import](https://github.com/OpenOrienteering/mapper/blob/master/test/map_t.cpp#L140), probably to avoid [GUI dialogs](https://github.com/OpenOrienteering/mapper/blob/master/src/core/map.cpp#L814) during tests. There is still too much GUI/QMessageBox in the Map class...

**Comment by lpechacek** [comment]
Checked the fix and it works fine. Thanks, Kai!
