### ISSUE TITLE
Cannot detect Esperanto system locale

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#881]
### Steps to reproduce
1. Reset language settings (current system locale will be used):
`sed -i '/language=/d' .config/OpenOrienteering.org/Mapper.conf`
2. Start Mapper with eo locale:
`LANG=eo Mapper`

### Actual behaviour
English language is used.

### Expected behaviour
Esperanto language is used.

### Configuration
Mapper Version: 0.7.0-RC3
Operating System: Linux

### RCA
src/settings.cpp:82
```cpp
registerSetting(General_Language, "language", QLocale::system().name().left(2));
```
QLocale::system() returns wrong locale.

**Comment by dg0yt** [comment]
IMO this is directly related to QTBUG-57802 which also causes #792: QLocale cannot handle Esperanto. Not when instantiated from code, and not when initialized from LANG and friends.

I'm not much inclined to implement a workaround, because the user can fix it in the settings.

**Comment by dg0yt** [comment]
QTBUG-57802 will be fixes in Qt 5.12, which translates to Mapper 1.0

**Comment by dg0yt** [comment]
I'm about to prepare Qt 5.12 for Mapper 0.9. Linux distributions will take a little bit longer, of course.

**Comment by sikmir** [comment]
ArchLinux moved to Qt 5.12 first (compared with other distros). So it works now with Mapper 0.8.3 from AUR.

**Comment by dg0yt** [comment]
Mapper 0.9 will use Qt 5.12.
