### ISSUE TITLE
Keyboard arrow keys do not scroll map when an object is selected

### ISSUE THREAD

**Issue by sfroyen** [OpenOrienteering/mapper#882]
### Steps to reproduce
1. Select "Edit objects" mode
2. Make sure no objects are selected
3. Verify that keyboard arrow keys will scroll map
4. Select an object
5. Try to scroll using keyboard arrow keys

### Actual behaviour
Keyboard arrow keys will not scroll map when an object has been selected.

### Expected behaviour
Map should scroll whether or not an object has been selected.
(This is how 0.6.8 behaves.)

### Configuration
Mapper Version: 0.70 RC4
Operating System: MacOS Sierra

**Comment by dg0yt** [comment]
Reproduceable on Linux.

**Comment by sfroyen** [comment]
Thanks for fixing! The just released 0.70 version works great.
