### ISSUE TITLE
Unneccessary possibility to change symbol while drawing an object (line/area)

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#883]
### Steps to reproduce
1. Run in Andriod version
2. Draw some line/area object without finishing it
3. Try to change symbol

### Actual behaviour
You end up and the program cannot retur, you must you the andoid "back" key

### Expected behaviour
You shoud ot be able to try to change symbol during editing, no need to open the dialog since you anyway cannot change.

### Configuration
Mapper Version: 0.6.8
Operating System: Android

**Comment by dg0yt** [comment]
I noticed this, too. The desktop behaviour already is that you cannot change the symbol while drawing.
