### ISSUE TITLE
Minor norwegian translation error (

### ISSUE THREAD

**Issue by okvittem** [OpenOrienteering/mapper#885]
### Steps to reproduce
0. env LC_ALL=no_NO Mapper
0.5 Ctrl-N : new map
1. Go to Kart->georeferering
2. choose UTM as 'Referansesystem'

### Actual behaviour
This text pops up : 
"Ved CRS-endringer, behold: Prosjekterte koordinater"
I think you mean 'Prosjiserte koordinater' which means 'projected coordinates' as
opposed to "project plan for coordinates". One word in english two words in norwegian.

### Expected behaviour
More precise norwegian language.

### Configuration
Mapper Version: 0.7.0
Operating System: linux ubuntu 16.04

**Comment by dg0yt** [comment]
@cschive ?

**Comment by cschive** [comment]
I agree. The Norwegian translation is now updated.
