### ISSUE TITLE
Failed to build on Slackware

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#886]
### Steps to reproduce
1. Build OOM without superbuild:
```bash
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DMapper_PACKAGE_NAME=$PRGNAM \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE=Release ..
```

### Actual behaviour
Build failed:
```bash
-- Configuring Mapper packaging
-- Configuring Mapper licensing documentation
-- Licensing information provided by: slackware
CMake Error at doc/licensing/CMakeLists.txt:119 (include):
   include could not find load file:
      slackware-licensing.cmake
...
-- Configuring incomplete, errors occurred!
```

### Expected behaviour
Build successed.

### Configuration
Mapper Version: 0.7.0
Operating System: Slackware 14.2
```bash
$ . /etc/os-release; echo $ID
slackware
```

### RCA
What is preferable way to fix it?
- contribute missed _slackware-licensing.cmake_ to the upstream
- distribute _slackware-licensing.cmake_ as a patch within Slackware package

**Comment by jtojnar** [comment]
Same problem occurs on Manjaro (Arch derivative): https://forum.manjaro.org/t/missing-manjaro-licensing-cmake/25383

**Comment by dg0yt** [comment]
In general, I accept patches and pull requests even for unsupported Linux distributions, but I cannot provide maintenance unless they can be build by OBS.

**Comment by dg0yt** [comment]
@jtojnar For an Arch derivative, you may either configure cmake with `-DLICENSING_PROVIDER=arch`, or add a file `doc/licensing/manjaro-licensing.cmake` with the following content:

~~~
include("arch-licensing.cmake")
~~~

As a packager, you will still have to verify the transitive usage requirements for 3rd-party software which requires display of copyright and legal terms. (What I already checked is in `linux-licensing.cmake`.) For a personal build, you may even turn off 3rd-party licensing documentation by passing `-DLICENSING_PROVIDER=BOOL:OFF` to cmake.

**Comment by sikmir** [comment]
> For a personal build, you may even turn off 3rd-party licensing documentation by passing -DLICENSING_PROVIDER=BOOL:OFF to cmake.

`-DLICENSING_PROVIDER:BOOL=OFF`

**Comment by sikmir** [comment]
> In general, I accept patches and pull requests even for unsupported Linux distributions, but I cannot provide maintenance unless they can be build by OBS.

Well, I thought a bit more and think i'd rather keep it within a package (Slackware package, FreeBSD port).
