### ISSUE TITLE
OOMapper 0.6.x binary for Linux

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#887]
### Steps to reproduce
1. Go to latest 0.6.x release page - https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.8
2. Follow "Linux package selection" - https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper
3. Choose any distributive

### Actual behaviour
If try download it, it say that there is 0.7.x only builds

### Expected behaviour
Keep alive both: latest 0.6.x and latest 0.7.x builds. Because on LTS releases its impossible use 0.7.x builds due to increased dependency, but still possible run and use 0.6.x builds.

### Configuration
Mapper Version: 0.6.8
Operating System: Ubuntu 14.04 LTS

**Comment by dg0yt** [comment]
Oops, the 0.6.8 Windows links were already changed to point to the archive folder, but Linux was omitted. Fixed now.

**Comment by dg0yt** [comment]
BTW there is no issue with current LTS.
