### ISSUE TITLE
Loose georeferencing converting to .ocad

### ISSUE THREAD

**Issue by Romein70** [OpenOrienteering/mapper#888]
No georeferencing yet in OOM 0.70 when converting an .omap to .ocd? Will this be added soon?
I prefer drawing in OOM, but most people in my club use OCAD. I can import a georeferenced ocad-file, but when I convert it back, I loose the georeferencing...

### Configuration
Mapper Version: 0.70
Operating System: Win10

**Comment by dg0yt** [comment]
Not possible as long as we export OCD version 8, and likely to need more investigation/feedback about grid system numbers in OCD.

More or less a duplicate of #868.
