### ISSUE TITLE
It is not possible to cut a line from the end (beginning)

### ISSUE THREAD

**Issue by klidas01** [OpenOrienteering/mapper#890]
### Steps to reproduce
1.select a line
2.cut tool & shift together
3.cut the line from it's end (beginning)

### Actual behaviour
nothing happens

### Expected behaviour
the line under the cursor disappears (v0.6.8)

### Configuration
Mapper Version:v0.7.0 
Operating System:Windows 7 (64)

**Comment by dg0yt** [comment]
Actually, it is not possible to start cutting from any explicit point. Only starting between points does work.
