### ISSUE TITLE
Show Details for map import warning too small

### ISSUE THREAD

**Issue by wanacode** [OpenOrienteering/mapper#899]
This is a suggestion for improvement.

### Steps to reproduce
1. Open a file that has a missing template or similar that will create the warning "The map import generated warnings."
2. Click "Show Details..."

### Actual behaviour
The details window is very tiny making it hard to read all the warnings.

![warning](https://user-images.githubusercontent.com/2317149/28000363-7036687e-6579-11e7-850b-62997111aa23.png)

### Expected behaviour
Ideally it would be a bigger window or a window that can be made bigger by dragging a corner. At the moment it is fixed size.

### Configuration
Mapper Version: 0.7.0
Operating System: LinuxMint

**Comment by dg0yt** [comment]
For the record, at the moment this is a "standard dialog", which is provided by the system in some cases (e.g. Android). Where it is provided by Qt, we may look into tuning the window configuration.

**Comment by Symbian9** [comment]
Make this window resizable would be a solution hete?

**Comment by dg0yt** [comment]
> a window that can be made bigger by dragging a corner

= resizable

**Comment by dg0yt** [comment]
At least for Linux, this cannot be changed as long as ```QMessageBox``` is used here: Setting custom window flags or enabling the right-corner size grid does not make the window resizable.

**Comment by Symbian9** [comment]
But, maybe, its possible use same window tipe as used in "About OpenOrienteering Mapper" dialog, that is resizable on Linux?
