### ISSUE TITLE
Unwanted text on buttons in Color window

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#906]
### Steps to reproduce
1. Open Color window

### Actual / Expected behaviour
Please see image below
![selection_208](https://user-images.githubusercontent.com/10380431/28747739-a2d86dec-74ae-11e7-99ef-2eba499325cd.jpg)

### Configuration
Mapper Version: 0.7.20170726
Operating System: Linux. (Tested on Gentoo Linux with QT 5.7.1)

**Comment by Symbian9** [comment]
Strange, on my PC all buttons showed correctly

![Buttons without text](https://img-host.org.ua/images/oombuttons.png)

Mapper Version: 0.7.20170726

Operating System: Linux Mint 18.1 XFCE (x86_64), with Qt 5.5.1

**Comment by dg0yt** [comment]
These segmented buttons are based on QToolButton and are not meant to display text. QToolButton has a [tool button style property](http://doc.qt.io/qt-5/qtoolbutton.html#toolButtonStyle-prop) which is "icon only" by default.

Now here there are two issues:
- The color list widget actively sets the style to follow the environment settings (which seems to be text beside icon in the Gentoo example). This is a bug in Mapper and needs to be fixed.
- The text is shown incompletely. This might be a bug in Mapper or in Qt. However, no fix is needed unless we want segmented buttons to show text.
