### ISSUE TITLE
Android Missing Buttons on Cut Area Tool

### ISSUE THREAD

**Issue by xc-racer3** [OpenOrienteering/mapper#908]
### Steps to reproduce
1. Select cut area tool in mapper for android.
2. Try to cut area

### Actual behaviour
The only way to finish cutting the area is to double tap on the edge of the area, and there is no way to abort.  There are no buttons along the bottom of the screen allowing you to undo, finish the line, abort the line, etc.  

### Expected behaviour
It should be similar to all the other drawing tools, with buttons along the bottom for "undo", "finish", and "abort".

### Configuration
Mapper Version: 0.7.0
Operating System: Android

**Comment by dg0yt** [comment]
Guessing from the symbol, this is "Cut object" (which works also for lines on the desktop but not for Android - probably another defect).
