### ISSUE TITLE
Cut away tool broken in latest unstable

### ISSUE THREAD

**Issue by xc-racer99** [OpenOrienteering/mapper#910]
### Steps to reproduce
1. Draw a line symbol
2. Cover part of it with an area symbol
3. Attempt to use the "Cut away" tool and press enter

### Actual behaviour
The line symbol is entirely deleted.  

### Expected behaviour
Only the part of the line symbol that is covered should be deleted (as in previous versions, including 0.7.0)

### Configuration
Mapper Version: 0.7.1 (latest unstable - last git commit is https://github.com/OpenOrienteering/mapper/commit/c9e89e9131aef25d162df53944daf756f37e1c8a)
Operating System: Linux and Windows

### Additional info
Based on a git bisect, this regression appears to have been introduced in https://github.com/OpenOrienteering/mapper/commit/9bb9f2542b59cc66b1824765496af53f0183b2c6

**Comment by 999999333** [comment]
👍
