### ISSUE TITLE
ISOM 2017 - symbol outlook

### ISSUE THREAD

**Issue by 999999333** [OpenOrienteering/mapper#912]
Well dash symbols are scaling but that isn't good. Look at the 1.major power line square in sharp bends 2. lenght of power line dash symbols

![obrazek](https://user-images.githubusercontent.com/4051127/29125851-1d6fc48a-7d1d-11e7-97aa-50854b9d1601.png)

### Configuration
Mapper Version: 0.7.20170809
Operating System: Windows

**Comment by Symbian9** [comment]
Related

* https://github.com/OpenOrienteering/mapper/issues/664

**Comment by dg0yt** [comment]
For sharp bends of major power line, "no scaling" doesn't look perfect either:
![no-scaling](https://user-images.githubusercontent.com/13567791/29446141-e5bcb37a-83ea-11e7-9505-b8b2b9b54b1a.png)

Either we need scaling settings per dash symbol element (here: small line, rectangle), or this major power line must be formed as a combined symbol:
![combined-symbol](https://user-images.githubusercontent.com/13567791/29446548-04b9958e-83ed-11e7-88bb-fd41dc083da6.png)

Given that the major power line context is quite unique, I'm fine with the combined symbol solution.
