### ISSUE TITLE
How to find text symbol?

### ISSUE THREAD

**Issue by Freemapper** [OpenOrienteering/mapper#921]
Tried for hours to find text symbol by right clicking in the symbol Pane/symbol window etc. Maybe I earlier had taken some symbols away to get a smaller symbol window, but how di I do to get/find a new text symbol?

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dg0yt** [comment]
With that description, I will try for hours to find out what you want to achieve. Create a new text symbol? Then the right click on the symbol window should get you there quickly:

![new-text-symbol](https://user-images.githubusercontent.com/13567791/29467442-e00b8b58-8440-11e7-81a9-9bf16b0d76fc.png)

Or create a new text object?
Or are you working on Android?
Or did you remove the text symbols from the file and want them back? Than you will have to copy and paste (by right click in symbol pane) from the original symbol set or map.

**Comment by Freemapper** [comment]
Now I understand. Right click-new symbol-text but the dialog box then comming upp, is not included in the manual (How to actually produce a new symbol). Not easy for beginners.
Thank´s anyway for helping me.

**Comment by dg0yt** [comment]
Most details are not covered by the manual. It is all work-in-progress. But we keep it in a separate repository, so it is easy as it can be to make contributions, and contributions get online as soon as accepted:
https://github.com/OpenOrienteering/mapper-manual
