### ISSUE TITLE
Page border disappear during zooming (in Printing/Export view)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#929]
### Steps to reproduce
1. Create or open map
2. Go to "File -> Print" (or "Export to...", as it same view)
3. Chose paper size
4. Zoom in or out (scroll mouse roll in workspace)

### Actual behaviour
After zooming page bounding box disappear. And for see it again need  click in workspace after scrolling

### Expected behaviour
Page bounding box should be showed always and must follow map scrolling/zooming

### Configuration
Mapper Version: 0.8.20170819-0+458.1
Operating System: xUbuntu 16.04, x86_64

**Comment by dg0yt** [comment]
Fixed together with #932, thanks.
