### ISSUE TITLE
Selection bounding box disappears after zooming

### ISSUE THREAD

**Issue by 999999333** [OpenOrienteering/mapper#932]
### Steps to reproduce
1. Select some symbol in map
2. Zoom in/ out / move with map

### Actual behaviour
Selection is "cleared"(not showing bounding box) but after some time it become visible again

### Expected behaviour
It shoudlbe visible all the time

### Configuration
Mapper Version: unstable 0.8.   20.8.2017
Operating System:Windows 10 64bit

**Comment by 999999333** [comment]
There is video of problem [https://www.youtube.com/watch?v=81Lg72ZdJEc]  (sry for use of forest symbol)

**Comment by Symbian9** [comment]
I think there is related issue with similar effect

* https://github.com/OpenOrienteering/mapper/issues/929

**Comment by dg0yt** [comment]
Thanks for reporting. Updated build is coming.
