### ISSUE TITLE
Mapper crashed on opening a map

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#935]
### Steps to reproduce
Not stably reproducable, but occurs from time to time.

### Actual behaviour
Program terminated with signal SIGSEGV, Segmentation fault.

### RCA
```bash
$ gdb -q -ex 'thread apply all bt full' -ex quit ./Mapper ./core.Mapper > thread-apply-all-bt-full.txt
$ cat thread-apply-all-bt-full.txt
...
#0  0x00007f453acaf3e8 in QAbstractItemView::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
...
```
Fo full backtrace, see [thread-apply-all-bt-full.txt](https://github.com/OpenOrienteering/mapper/files/1248128/thread-apply-all-bt-full.txt)

### Configuration
Mapper Version: latest master (e6aec80918203aca38bdfa2eece3ef7dc196608d)
Operating System: Arch Linux
Qt: 5.9.1

**Comment by dg0yt** [comment]
Does this happen (only) when opening a file from the list of recent maps?
