### ISSUE TITLE
Garbage inside xmap file

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#936]
I began to draw some new map in the spring. Now I'm going to continue working on it, but I found that the .xmap file takes up a lot of disc space (about 30 Mb for 0.5 sq.km sprint map). I have tried to copy-paste the content in new xmap file, and this file took up 1.9 Mb. Than, I've removed all content, including templates, symbols and colours from original file and such empty file still contains 27 Mb some xml code. What is this? How can I safely remove this code from original file to reduce the file size? 

### Configuration
Mapper Version: The original file produced by Mapper 0.6.8
The empty file attached.
[kyiv-sprint-center-test.zip](https://github.com/OpenOrienteering/mapper/files/1249581/kyiv-sprint-center-test.zip)

**Comment by sikmir** [comment]
It's only 14Mb after minification, so 50% - whitespaces.

**Comment by dg0yt** [comment]
Choose Edit > Clear undo / redo history, that's where the data is. (Or click undo to see what you get...)
After clearing and by saving as .omap, it 34 KB.

**Comment by yevhenmazur** [comment]
Thanks! It was undo / redo history.
.omap is not suitable for me, because I'm using git for my map projects.
Maybe make sense to limit the size of  undo / redo history? The file size can be critical for usage on mobile device.

**Comment by dg0yt** [comment]
Sure, this limit is on the wish list.

By the way, the omap files should be fairly usable for git now (since v0.7.0, #808) as well, although less pretty. Cf. https://github.com/OpenOrienteering/mapper/blob/master/examples/overprinting.omap

**Comment by dg0yt** [comment]
For the record, there is a limit of 128 steps at the moment.
