### ISSUE TITLE
OpenFileDialog's extension string is too long

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#938]
### Steps to reproduce
1. Open map/template dialog

### Actual behaviour
![scr1](https://user-images.githubusercontent.com/688044/29775874-72b41d14-8c0f-11e7-97fa-47f17509a5f3.png)
![scr2](https://user-images.githubusercontent.com/688044/29775875-72b5ea54-8c0f-11e7-81cd-ec4eda9e1ee0.png)

### Expected behaviour
At least, no need to duplicate each extension in uppercase. Anyway all variants (e.g. *.foo, *.FOO, *.Foo, *foO, etc) are accepted.

### Configuration
Mapper Version: latest master
Operating System: Arch Linux

**Comment by dg0yt** [comment]
That's two issues:
- capitalization: This was probably planned as a temporary workaround for https://bugreports.qt.io/browse/QTBUG-51712 (P3: Somewhat important). However, there is no upstream activity. It could be changed for most platforms, but we need to catch ```QGtk2FileDialogHelper``` / ```QGtk3FileDialogHelper```.
- length: This is related to the formats supported by GDAL. Solution would be to group by first letter, such as "Geospratial vector data A-F (.abc .csv .fmt)" etc.

**Comment by dg0yt** [comment]
Capitalization is still an issue in Qt 5.9.1, tested with ```-style gtk3```.

**Comment by dg0yt** [comment]
Regarding length:
-  There is the option to not display the extensions [QFileDialog::HideNameFilterDetails](http://doc.qt.io/qt-5/qfiledialog.html#Option-enum). However, it needs to be verified that this works on all platforms. 
(I tried to find out what is the standard on Windows, but Microsoft's Windows 10 appliciations are inconsistent: Notepad displays extensions, but Internet Explorer does not.)
- Gimp lists only the first extensions and then prints an ellipsis. Again, I'm not sure whether we can implement this with Qt, in a cross-platform way.
