### ISSUE TITLE
Add link to binary packages of QtLinguist (wiki)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#940]
Add on the wiki-page for translators...
* https://github.com/OpenOrienteering/mapper/wiki/Translation

... link to **binary builds of QtLinguist for macOS & Windows**
* https://github.com/lelegard/qtlinguist-installers/releases

Because currently...
> Linguist is also included in our <a href="http://download.opensuse.org/repositories/home:/dg0yt/Windows/">unstable Windows package</a>

... not true (there are NO builds for QtLinguist in your repo now)

**Comment by dg0yt** [comment]
The recommended tool is Weblate.
Removed obsolete link to out Linguist packages.
