### ISSUE TITLE
DXF - import / change symbol -- remaing stuff can't remove

### ISSUE THREAD

**Issue by Tiekku** [OpenOrienteering/mapper#941]
### Steps to reproduce
1. import dxf file
2. change symbol
3. there is remaining symbols with can't be romoved and when zooming those size changes...

### Actual behaviour
You can found example file from the attachment.

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: OpenOrienteering Mapper 0.6.7
Operating System: OSx

**Comment by dg0yt** [comment]
There is no attachment. Please add a ZIP file.

**Comment by dg0yt** [comment]
Side note: The v0.6.7 DXF import feature is considered legacy. It is replaced with code based on GDAL/OGR from v0.7.0.

**Comment by Tiekku** [comment]
The file size is so big that upload failed.  Problem was solved so that I save it to OCAD format and re-oppened --> those remaining symbols disappears.  But as you just wrote may be it was old import error.  I saved that file to our company ftp server, you can down load it from there.

http://www.maailmasta.fi/oomapper/karoituspohja.omap.zip

**Comment by dg0yt** [comment]
That is a nice corner case. It needs the combination of a) overprinting simulation on screen and b) imported symbols which do not have a symbol assigned. These objects use special helper symbols. Due to the special color, they are drawn on top of the overprinting simulation, but without proper coordinate transformation.

**Comment by dg0yt** [comment]
Minimal test file:

[karoituspohja-minimal.omap.zip](https://github.com/OpenOrienteering/mapper/files/1271289/karoituspohja-minimal.omap.zip)
