### ISSUE TITLE
Additional line ends bocks line combine 

### ISSUE THREAD

**Issue by Tiekku** [OpenOrienteering/mapper#942]
### Steps to reproduce
1. Draw line
2. zoom it
3. try to combine

### Actual behaviour
The is additional line end in display?!?!?!  You can't combine those 2-lines.
![nayttokuva 2017-09-01 kello 9 33 03](https://user-images.githubusercontent.com/14234135/29959979-7ccb8698-8f02-11e7-8520-476deeb93833.png)
![nayttokuva 2017-09-01 kello 9 33 25](https://user-images.githubusercontent.com/14234135/29959980-7cfafae0-8f02-11e7-8c19-863dadc03790.png)

Both are selected but you can't combined those.
![nayttokuva 2017-09-01 kello 10 45 34](https://user-images.githubusercontent.com/14234135/29960082-d4f84310-8f02-11e7-8bff-261e5a2f3587.png)

### Configuration
Mapper Version: OpenOrienteering Mapper 0.7.0
Operating System: OSx

**Comment by dg0yt** [comment]
The point is: These nodes are corners, not ends of line. So what looks like an "additional line end" is in fact the joining of two lines segments with an angle of zero. Hint: The start of a line is a larger square, the end of an line is a cross.

(To solve your issue, you may use the "Cut object" tool. Click on the two nodes which are to be turned into the end of the lines. Now you need to click the line once (actually to select a single line out of two) and remove it. Then there is left what can be connected.)
