### ISSUE TITLE
Build failed on macOS

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#946]
### Steps to reproduce
1. Install dependencies using MacPorts:
```bash
$ git clone git@github.com:sikmir/macports-ports.git
$ sudo sh -c "echo 'file:///Users/sikmir/macports-ports' >> /opt/local/etc/macports/sources.conf"
$ (cd macports-ports && portindex)
$ sudo port install gdal polyclipping proj qt5
$ port installed | grep "proj\|gdal\|polyclipping\|qt5"
  gdal @2.2.1_0+expat (active)
  polyclipping @6.4.2_0 (active)
  proj @4.9.3_0 (active)
  qt5 @5.8.0_0 (active)
...
```
2. Build OOM
```
$ git clone git@github.com:OpenOrienteering/mapper.git
$ mkdir mapper/cmake-build-debug
$ cd mapper/cmake-build-debug
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
...
-- Found Polyclipping: /opt/local/include/polyclipping (found suitable version "6.4.2", minimum required is "6.1.3")
-- Found PROJ4: /opt/local/lib/libproj.dylib (found version "4.9.3")
-- Found GDAL: /opt/local/lib/libgdal.dylib
...
-- Configuring Mapper packaging
CMake Error at packaging/CMakeLists.txt:274 (message):
  PROJ4_ROOT must be set when Mapper_PACKAGE_PROJ is enabled.


-- Configuring incomplete, errors occurred!
...
$ cat CMakeCache.txt
...
//The directory containing a CMake configuration file for PROJ4.
PROJ4_DIR:PATH=PROJ4_DIR-NOTFOUND

//Path to a file.
PROJ4_INCLUDE_DIR:PATH=/opt/local/include

//Path to a library.
PROJ4_LIBRARY_DEBUG:FILEPATH=PROJ4_LIBRARY_DEBUG-NOTFOUND

//Path to a library.
PROJ4_LIBRARY_RELEASE:FILEPATH=/opt/local/lib/libproj.dylib
...
```
So, include and lib paths detected correct. But why PROJ4_DIR not found? Is this problem with cmake/FindPROJ4.cmake?

### Configuration
Mapper Version: latest master
Operating System: macOS 10.12

**Comment by dg0yt** [comment]
I don't know much about MacPorts, I use Superbuild. Did you try what the error message says ("PROJ4_ROOT must be set when Mapper_PACKAGE_PROJ is enabled.")?

**Comment by dg0yt** [comment]
You build a Debug build, but don't have a debug library...

**Comment by sikmir** [comment]
> You build a Debug build, but don't have a debug library...

The same for Release build.

**Comment by dg0yt** [comment]
In fact, the error message is about locating the PROJ.4 data files needed for packaging. You will have to study https://github.com/OpenOrienteering/mapper/blob/master/packaging/CMakeLists.txt#L266 ff.

**Comment by sikmir** [comment]
> Did you try what the error message says ("PROJ4_ROOT must be set when Mapper_PACKAGE_PROJ is enabled.")?

Sure, it helps.

**Comment by dg0yt** [comment]
Well, PROJ4_DIR is expected to be set by CMake if a PROJ4 configuration file is found. Does MacPorts provide the proj4-config.cmake file? (Superbuild does.)
And CMake 3.9.0 seems to have broken something related to find_package config mode, cf. https://blog.kitware.com/cmake-3-9-1-available-for-download/

**Comment by sikmir** [comment]
> Does MacPorts provide the proj4-config.cmake file?
No, doesn't provide. ArchLinux doesn't provide as well.

**Comment by dg0yt** [comment]
I guess they still use traditional ```configure``` instead of CMake for building PROJ.4.
Then you must use ```PROJ4_ROOT```. That is why it exists.

Otherwise I don't know if a MacPorts package is meant to work standalone at all, i.e. if really needs ```Mapper_PACKAGE_PROJ``` and friends.

**Comment by sikmir** [comment]
> Then you must use PROJ4_ROOT. That is why it exists.

Well, maybe I took something wrong, but why it works on ArchLinux without using PROJ4_ROOT?

**Comment by dg0yt** [comment]
Which versions of CMake?

**Comment by sikmir** [comment]
> Which versions of CMake?

The same as on macOS - make 3.9.1.

**Comment by dg0yt** [comment]
(Okay, proj4-config will be ignored anyway because I'm waiting for PROJ4 to export its target proj to namespace PROJ4... https://github.com/OSGeo/proj.4/pull/451)

In fact, the difference between (Arch) Linux and macOS (or Android, or Windows) is that for Linux, our packaging defaults to not including PROJ.4 and GDAL data. Cf. https://github.com/OpenOrienteering/mapper/blob/master/CMakeLists.txt#L78

**Comment by sikmir** [comment]
> In fact, the difference between (Arch) Linux and macOS (or Android, or Windows) is that for Linux, our packaging defaults to not including PROJ.4 and GDAL data.

It all makes sense now. So, in case of MacPorts we need `set(mapper_package_default OFF)`.
```cmake
if(ANDROID OR APPLE OR WIN32)
    set(mapper_package_default ON)
else()
    set(mapper_package_default OFF)
endif()
```

**Comment by dg0yt** [comment]
At the moment, this is not a cache variable (so it can be set from outside) but just the default value for individual cache variables:
~~~cmake
option(Mapper_PACKAGE_PROJ      "Include all required Proj components in the packages" ${mapper_package_default})
option(Mapper_PACKAGE_GDAL      "Include all required GDAL components in the packages" ${mapper_package_gdal})
option(Mapper_PACKAGE_QT        "Include all required Qt components in the packages"   ${mapper_package_default})
option(Mapper_PACKAGE_ASSISTANT "Include Qt Assistant in the packages"                 ${mapper_package_assistant})
