### ISSUE TITLE
scale selected symbol element

### ISSUE THREAD

**Issue by iccander** [OpenOrienteering/mapper#950]
For scaling logos (e.g. symbol 999 OpenOrienteering logo, club logos ...) or other custom symbols like north arrows it shouldn't only be possible to scale the entire symbol set, but to enlarge or reduce the size of a single selected item.

### Configuration
Mapper Version: 0.8.20170829
Operating System: Windows

**Comment by iccander** [comment]
Now I have found the (hidden) solution myself. The function can be accessed via the context menu in the symbol window. Right-click the symbol icon and "Scale...".

**Comment by dg0yt** [comment]
Good to know that you found it. For completeness, this is covered in the manual:
http://www.openorienteering.org/mapper-manual/pages/symbol_dock_widget.html
