### ISSUE TITLE
Draw azimuth mode

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#951]
Please add this functionality. I think this is the last barrier to get converts from other map softwares.

In Draw azimuth mode  a small screen shall appear (perhaps in the same place as color icons for scribbling) in which degrees and distance is stated when drawing a line. This will enable usage of data from other measurements tools like compass, range finder or pacing.

I see now it has been [discussed](https://github.com/OpenOrienteering/mapper/issues/398), I would very much like to revive this debate.

I think there is no need for "numeric mode", that could make fieldwork clumsy.  Just show degrees and distance when drawing a line.

**Comment by dg0yt** [comment]
Duplicates #398. Already recognized as popular, thus tagged v0.x.x ;-)

**Comment by dg0yt** [comment]
Duplicate of #398. Already recognized as popular, thus tagged v0.x.x ;-)
