### ISSUE TITLE
OBS builds unavailiable (temporary)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#954]
Currently site `http://download.opensuse.org` unavailiable
* https://status.opensuse.org/incidents/18

So, users can't get latest binary for Windows and Linux
* https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.91
  * https://download.opensuse.org/repositories/home:/dg0yt/

P.S.: it would be good to keep mirror for such situations

**Comment by Symbian9** [comment]
> Hey in case you haven't heard yet: we have a major 💩 problem with our content delivery network entry server download.opensuse.org
https://mobile.twitter.com/openSUSE/status/905530011540746250

**Comment by Symbian9** [comment]
> Most data recovered, starting the official service again. We are still validating some data in the repositories, so not everything is accessible yet. Please note that some /repositories/* directories might contain old files until the next sync from OBS. In that regard, rsync access to stage.opensuse.org is still disabled until we verified that really everything is ok on the master server.
> 
> https://status.opensuse.org/incidents/18#update-20

**Comment by dg0yt** [comment]
Seems fixed.
