### ISSUE TITLE
Some strings are not available for translation on Weblate

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#957]
### Steps to reproduce
```bash
$ cat << 'EOF' > check-trans.sh
#!/bin/sh

WEBLATE="http://hosted.weblate.org"
PROJECT="OpenOrienteering"
COMPONENT="mapper"

wget -qO- "$WEBLATE/exports/stats/$PROJECT/$COMPONENT/?format=csv" | \
  awk -F',' 'NR == 1 {next} {print $2,$3-$4}' | \
  while read line; do \
    wget -qO- "$WEBLATE/download/$PROJECT/$COMPONENT/${line%% *}" | \
      grep -c 'unfinished' | sed -e "s/^/$line /"; done | \
  awk '$2 != $3 {print}'
EOF
$ sh ./check-trans.sh
eo 238 248
```
What does it mean is that 10 strings are not available for translation on Weblate. It affects only eo locale.
As example of such string:

> Ready to draw!
> 
> Start drawing or load a base map.
> To load a base map, click
> Templates -> Open template...

**Comment by dg0yt** [comment]
Not sure what this really indicates - maybe a different interpretation of "unfinished" by Weblate?
The example string is there:

https://hosted.weblate.org/translate/openorienteering/mapper/eo/?checksum=&offset=&q=Ready&search=substring&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=

I see different numbers of "All strings" for de vs. eo on Weblate, but this is another story, maybe related to obsolete strings. I don't see different number for de vs. eo in Qt Linguist.

**Comment by sikmir** [comment]
OK, It turns out that it works for **substring** search type (in your case), but not for **fulltext** one.
Compare:

1. (de) https://hosted.weblate.org/translate/openorienteering/mapper/de/?checksum=&offset=&q=Ready+to+draw!&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=
2. (eo) https://hosted.weblate.org/translate/openorienteering/mapper/eo/?checksum=&offset=&q=Ready+to+draw!&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=

Anyway, something wrong with Weblate, maybe it's a bug.

**Comment by sikmir** [comment]
Well, I got it. That difference caused by delay within Weblate between commiting pending changes.
What about broken search with fulltext type, this is another story as well.
