### ISSUE TITLE
Issues when reopening map files

### ISSUE THREAD

**Issue by pinnabilli** [OpenOrienteering/mapper#966]
### Steps to reproduce
Let A.omap, B.omap and C.omap be any existing map files.
1. Run Mapper and open A. Edit the map in some way.
2. Open B, then switch to the window of A and close it, discarding the changes made.
3. Reopen A.
4. Open C from the window of A.

### Actual behaviour
At step 3, A is loaded with the changes still present.
At step 4, C is opened on top of A.

### Expected behaviour
At step 3, A should be loaded without the discarded changes.
At step 4, C should be opened in a new window, leaving A opened.

### Configuration
Mapper Version: 0.7.0
Operating System: Windows 7

**Comment by dg0yt** [comment]
I didn't believe it, but now it happened to me, too. Re-opening goes way too fast, without warning from loading, and the reopened map is marked as having unsaved modifications. I guess the map window is not destroyed properly, making it re-appear on re-open.

Workaround: close the program.

**Comment by pinnabilli** [comment]
Thanks for the fix!
