### ISSUE TITLE
Installation problems on Linux Mint 18.2

### ISSUE THREAD

**Issue by kjetilk** [OpenOrienteering/mapper#970]
Hi!

I have failed to install the supplied packaged on Linux Mint 18.2. It is based on Ubuntu 16.04, and it seems to me that the problem would be the same on that version. 

### Steps to reproduce
1. Follow the instructions to add sources.
2. ```apt-get install openorienteering-mapper```

### Actual behaviour

```
The following packages have unmet dependencies:
 openorienteering-mapper : Depends: qtbase-abi-5-5-1
E: Unable to correct problems, you have held broken packages.
```

### Analysis
```qtbase-abi-5-5-1``` doesn't appear to be a package known to my system:
```
dpkg -l qtbase-abi-5-5-1
dpkg-query: no packages found matching qtbase-abi-5-5-1
```
Indeed, the [Ubuntu package search returns no result](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=qtbase-abi-5-5-1&searchon=names).

However, it appears to be a virtual package:
```
roo tmp # apt-get install qtbase-abi-5-5-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qtbase-abi-5-5-1 is a virtual package provided by:
  libqt5core5a 5.5.1+dfsg-16ubuntu7.5 [Not candidate version]
  libqt5core5a 5.5.1+dfsg-16ubuntu7 [Not candidate version]

E: Package 'qtbase-abi-5-5-1' has no installation candidate
```

I'm not sure what to make of that.

### Configuration
Mapper Version: 0.7.0
Operating System: Linux Mint 18.2

**Comment by dg0yt** [comment]
As you already found out, `qtbase-abi-5-5-1` is a virtual package provided by libqt5core5a. AFAIK it marks the ABI version and thus serves to manage binary compatibility when a software (here: Mapper) uses private features of Qt. 

You probably installed a more recent version of Qt which provides a different ABI version, and you cannot install a compatible version at the same time ('Not candidate version'). Check the output of `dpkg-query -s libqt5core5a`.

**Comment by kjetilk** [comment]
Thanks for figuring it out! I've been digging a bit more, and it turns out that Linux Mint uses Kubuntu backports to establish their own KDE LTS version, and this brings along Plasma 5.8, which again seems to require ```qtbase-abi-5-6-1```, and therefore brings that along too.

Any chance the opensuse build system could be configured to support Linux Mint releases?

**Comment by dg0yt** [comment]
- I cannot configure the opensuse build system to download Mint DEBs. 
- Mint doesn't provide an easy way to discover the sources it uses to build these Qt packages. (I do not have a Mint installation. I need to rely on web pages. The lack of transparency is what kept me away from Mint.)
- Qt 5.6.1 is not in the current Debian or Ubuntu sources, including backports. Cf. https://tracker.debian.org/pkg/qtbase-opensource-src.

So I even can't rebuild the Mint Qt packages from source at the moment.

**Comment by kjetilk** [comment]
OK, I can see that makes it more than worth the effort. Thanks for looking into it.

I'm trying to figure out whether to use Mint on just straight Debian on my desktop, and this is clearly a factor against Mint.
