### ISSUE TITLE
Debian Linux: Black/white PNG templates are printed as white/black

### ISSUE THREAD

**Issue by SparksDJ** [OpenOrienteering/mapper#973]
### Steps to reproduce
1. add a png template with a two-colour palette (black/white) to a map
2. print the map (including templates!) to a printer or PDF file

### Actual behaviour
The template is printed with the colours reversed (white/black instead of black/white)

### Expected behaviour
The template should be printed with the correct colours

### Configuration
Mapper Version: 0.8.20170916
Operating System: Debian 8.9 (Jessie) 64-bit

The template is shown correctly in the print preview.
PNG black/white images with no palette print correctly, as do images with a white/grey palette.

I tried to attach a ZIP file of test data, but I don't think it worked (Chromium 57.0.2987.98)

**Comment by dg0yt** [comment]
I guess this affects also PDF export on Debian Jessie. This distribution uses a fairly old version of Qt (5.3.2). The latest bugfix for monochrome images is in Qt 5.6.3 (http://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/painting/qpdf.cpp?h=5.6&id=b38145a11d03c3e3fe8baf37800a017359283861).

(We do have a fork of Qt's PDF classes, version 5.5.1, but we use it only for CMYK output at the moment.)

**Comment by SparksDJ** [comment]
So I can expect the problem to go away when I upgrade to Stretch.  Since I've got a workaround, and the error is outwith your code, there's no need to do anything.

**Comment by dg0yt** [comment]
Did this issue go away with the Debian update?

**Comment by SparksDJ** [comment]
On Thu, 2018-03-01 at 23:54 -0800, Kai Pastor wrote:
> Did this issue go away with the Debian update?

I've checked with black/white, white/black and 1-bit greyscale images,
and all now print correctly.

Debian Jessie, libpng12-0 1.2.50-2+deb8u3,
openorienteering-mapper-unstable 0.8.20180121-0+483.1

**Comment by dg0yt** [comment]
Thanks!
