### ISSUE TITLE
Sharp angle gets lost when moving corner node

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#974]
### Steps to reproduce
1. When I want to move a node on a sharp angle on bezier curve
2.  Sharp angle disappears and a bend appears

### Expected behaviour
I would like to keep the sharp angle and move the node only

### Configuration
Android App 0.7.0

![1_cornernode](https://user-images.githubusercontent.com/20535899/30910201-17b8b3ca-a384-11e7-8e9e-f331e29f28b1.jpg)
![2_cornernode](https://user-images.githubusercontent.com/20535899/30910203-1922d13c-a384-11e7-9f1b-5a7056137694.jpg)

**Comment by dg0yt** [comment]
Note that the corner also got lost when moving one of the line segment neighboring the corner.
