### ISSUE TITLE
3D view mode (using Qt 3D framework)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#978]
### Expected behaviour
Add 3D view mode for preview mapped landscape & terrain in OpenOrienteering Mapper.

Illustration:
* http://digimap.blogs.edina.ac.uk/2014/11/13/visualising-os-mastermap-topography-layer-building-height-attribute-in-autocad-map-3d-and-infraworks/
  ![3D visualizitation](http://digimap.blogs.edina.ac.uk/files/2014/11/map3d_final_visualisation-1024x598.png)

### Configuration
Mapper Version: 0.8.x – 1.0
Operating System: all supported

### REFERENCE
* http://blog.qt.io/blog/2016/06/16/introducing-qt-3d/
  * https://wiki.qt.io/Qt3D
  * https://doc.qt.io/qt-5/qt3d-overview.html
* https://github.com/wonder-sk/qgis3d
  * https://github.com/qgis/QGIS-Enhancement-Proposals/issues/105
  * http://www.lutraconsulting.co.uk/blog/2017/08/06/qgis3d-build/
* https://github.com/afourmy/pyEarth

### Related
* https://github.com/OpenOrienteering/mapper/issues/657

**Comment by Symbian9** [comment]
@wonder-sk, could you help?

**Comment by wonder-sk** [comment]
@Symbian9 maybe - what would you like to help with?

**Comment by dg0yt** [comment]
You will have to do this in a fork. I won't accept such complex features while the basics and fundamentals are incomplete.
