### ISSUE TITLE
Insufficient documentation of key Mapper features

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#983]
There seem to be issues OCAD users frequently hit when migrating over to OOM. I'm one of them and I still remember how long it took me to learn how to move whole map objects. Following topics should be covered in documentation so that OCAD users find their way into OOM world.

1. Moving whole objects
2. Corner points
3. Partial map export
4. Double line symbols and their edge lines

I'm willing to draft the text.

References:
http://www.attackpoint.org/discussionthread.jsp/message_1256887
https://github.com/OpenOrienteering/mapper/issues/469#issuecomment-135998412

**Comment by dg0yt** [comment]
Well, the [mapper-manual](https://github.com/OpenOrienteering/mapper-manual/) is gladly accepting contributions.
On the other hand, I'm not too optimistic about people reading instructions. Some even don't mind cross-posting.
https://sourceforge.net/p/oorienteering/discussion/mapper/thread/f7d14b6b/
https://sourceforge.net/p/oorienteering/discussion/mapper/thread/b3ec1280/

**Comment by lpechacek** [comment]
That should not stop us from providing information to those who seek it, should it? :)

I'll give a shot to starting some sort of OCAD user's FAQ soon. Feel free to migrate the issue over to mapper-manual repo.

**Comment by Symbian9** [comment]
As for me, it would cool add forum on official website
* https://github.com/OpenOrienteering/OpenOrienteering.github.io

Here is example of lightweight CMS for simple forum (where users can post without registration)
* http://solvespace.com/forum

Source of this CMS
* http://github.com/solvespace-web

@dg0yt, what you think on adding such functionality as part of official website?
* http://openorienteering.org/forum

It would be cool place for feedback and users talks.

P.S: from time to time I think: "*- Why still there are no #openorienteering and/or #mapper channels on Freenode?*"
* http://xkcd.com/1782
![XKCD: Team Chat](https://imgs.xkcd.com/comics/team_chat.png)

**Comment by lpechacek** [comment]
When it comes to my preferences, I'd welcome a mailing list. ;) Sorry for the OT but CNR.

**Comment by dg0yt** [comment]
@lpechacek There is a developers mailing list in the sourceforge project.

>  Moving whole objects

May we should simply add more direct moving from the "Edit tool"?

> Partial map export

Shall this be added to PDF/Image export?

**Comment by lpechacek** [comment]
AFAICT this has been addressed in https://github.com/OpenOrienteering/mapper-manual/pull/32. Closing.
