### ISSUE TITLE
"Tourist mode"

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#987]
### Steps to reproduce
It would be nice for some occasions to have a "Tourist mode". For times when you stroll through terrain faster and need to see your movement on screen legibly.

### Expected behaviour
In "Tourist mode" the position dot shall be bigger. The gps position shall be in centre of screen all time. The position line shall be thicker (that can be solved by #986).

**Comment by Zerbembasqwibo** [comment]
Anyone else that feels this would be cool/useful?

**Comment by lpechacek** [comment]
To be honest, I occasionally recall this ticket while walking through a forest. However, the pressure is not sufficient to make me jump into writing code for this enhancement. So, at the risk of sounding rude, let me remind that Mapper is an open-source project. Anyone can try contributing code. I promise I'll be friendly to the person who comes with the first implementation of this feature.

**Comment by Zerbembasqwibo** [comment]
I know, I have thought about giving coding a chance even I have just small
experience. :)

onsdag 19 februari 2020 skrev Libor Pecháček <notifications@github.com>:

**Comment by lpechacek** [comment]
@ollesmaps, is the below what you meant?

Tourist mode can be activated after long press on "move to current location".
![image](https://user-images.githubusercontent.com/5584406/82835342-09001380-9ec4-11ea-9c72-b0abd0f67950.png)

Then the location cursor is free to wander within the central area of the screen and the map gets scrolled only when the cursor would leave the center region.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5584406/82835427-3fd62980-9ec4-11ea-8c2e-c1fa872876f2.gif)

Quite naturally, attempts to pan the map view by hand get overridden by the automatic adjustment.

**Comment by lpechacek** [comment]
During the next two weeks, I won't have the possibility to test this enhancement in the field. Those interested in trying out tourist mode can download a test build at the location mentioned in https://github.com/OpenOrienteering/mapper/issues/1242#issuecomment-633700552. The test build, identifying itself as _OpenOrienteering Mapper git-mobile_ui_gadgets_, can be installed alongside the official Mapper release. Any feedback is welcome.

**Comment by ollesmaps** [comment]
@lpechacek 
Libor, looks prefect, I will surely test it. Thank you!

**Comment by mlerjen** [comment]
@lpechacek: Testing the tourist mode the app started zooming in minimum-stepwise ad nauseam resp. until I closed the app. It happened twice. A third try the mode worked as intended. I cannot reproduce the error.

**Comment by lpechacek** [comment]
Thanks, Martin, for the report. I'll review the code one more time to see what could have gone wrong.

**Comment by ollesmaps** [comment]
It works perfectly well! Some mapping days I have it all time on. It saves time.
One detail: when returning to normal regimen it could say "Stop autopan..." instead of "Autopan..." (sentence from the start).

**Comment by ollesmaps** [comment]
As a sidenote: isn't the autopanning a way how to introduce fluent drawing enhancement #988 ?

**Comment by dg0yt** [comment]
I'm preparing this for merging and releasing with the next master release. I can confirm that unexpected changes of zoom may happen quite regularly. I will try to implement the repositioning a little differently.
