### ISSUE TITLE
Switch to default drawing tool when choosing a symbol

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#989]
### Steps to reproduce
There are unnecessary click paths when vectorizing. Now you have to:
1- select a point symbol 2-  select Set point objects mode
1- select a line/area symbol 2- select Draw free-handedly or Draw paths mode

### Expected behaviour
Step 2 is unneeded. It is obvious that when you select a point symbol you will draw a point symbol. So the switch to Set point objects mode shall be automated.
In case of line/area symbols you shall be able to select a prefered mode in Settings (Editor). Either Draw free-handedly or Draw paths mode. I would suggest not to select preferred mode for each symbol, rather group it for line and area symbols.

### Configuration
Android app 0.7.0

**Comment by Zerbembasqwibo** [comment]
Or in case 2. it uses same tool as last time you draw a line symbol?

**Comment by ollesmaps** [comment]
@Zerbembasqwibo That is right, that is another good option.

**Comment by lpechacek** [comment]
FTR, also requested by zlenhart.

**Comment by lpechacek** [comment]
I've looked into the code and played with Mapper a bit and I can tell that Mapper chooses Point drawing tool or Path drawing tool depending on symbol. There are certain circumstances when it does it and when it does not (e.g. upon object symbol change) but in general the feature is there, AFAICT.
I've tested both mobile (with Android 7) and desktop version v0.8.4. What Android version is running on your device, please?

**Comment by ollesmaps** [comment]
You are right it works perfectly well now! (0.8.4)
I assume it concerned version 0.7.0 as stated in the original issue.
You guys do miracles and do not tell us :D

**Comment by lpechacek** [comment]
FTR, the feature is there since v0.3.0 (commit a3b3db5a0daa3) but it may had been broken. dg0yt did some rewrites a few years ago which perhaps fixed the code. In any  case, issue closed. Thanks! :)

**Comment by dg0yt** [comment]
I guess this issue never got much attention because it was not clear enough in which situation the actual behaviour deviates from the expected behaviour.

To clarify:
- When a *drawing tool* is active, it is changed as needed to follow symbol selection.
- When an *editing tool* is active, selecting a new symbol will *not* switch to any drawing tool.

So probably you see the inconvenient case when editing an object after drawing, and then switching to the next symbol.

(And yes, I tried to make the tools' source code a little more maintainable, but it is still more complex than clean.)

**Comment by ollesmaps** [comment]
As a reference. This bug was present as of version 0.8.2 (Sept 2018) see #1143.

**Comment by ollesmaps** [comment]
1. Scribble mode
2. Select symbol
3. Unable to _draw_
4. Have to select Set point objects mode or Draw free-handedly or Draw paths mode first
5. Then it is possible to _draw_

Version  0.8.4 (Android)
