### ISSUE TITLE
Internal GPS in Galaxy note 8/ Android 7.1.1 does not work, anymore

### ISSUE THREAD

**Issue by TerjeWP** [OpenOrienteering/mapper#990]
### Steps to reproduce
1. Start OOM app using Galaxy Note 8
2. After latest phone update
3. GPS position display toggle button does not turn red

### Actual behaviour
After an automatic Note 8 update a few days ago, the GPS stopped working in the OOM app. The button “GPS position display toggle” does not turn red. The GPS still works with other apps

### Expected behaviour
I hope this is fixable because it’s a great phone for part time mapping and hopefully the GPS will be more accurate when more Galileo satellites are up. 

### Configuration
Mapper Version: 0.7.91
Operating System: Android 7.1.1

**Comment by dg0yt** [comment]
Please verify that the Mapper app has sufficient permissions.

**Comment by TerjeWP** [comment]
I have tried giving the app all permissions. Still doesn’t work.

**Comment by TerjeWP** [comment]
Realized now that this was only a georeferencing problem. Something had happen with the georeferencing, probably because I switch a lot between Mapper and OCAD. The GPS is now working on my Note 8 after I filled in the reference data from an older version of my map.
