### ISSUE TITLE
Non existent gpx

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#993]
### Steps to reproduce 
1. Open  file
2. Start gps
3. Close file (without saving)
4. Open the same file
5. Error message. Can not find gpx.

### Configuration
Android App 0.7.0

**Comment by dg0yt** [comment]
That's a side effect of the bizarre #966. When you immediately open the first file again, it is reused from memory. The file on disk doesn't refer to the GPX file which was never saved.
