### ISSUE TITLE
Manual files (.qch, .qhc) compressed during packaging and not uncompressed after install

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#994]
### Steps to reproduce
1. Download latest package of `0.7.0` or latest `unstable_0.8.x`
2. Install it (with all recommended packages)
3. Try open distributed "Help" (bundled manual)

### Actual behaviour
Can't open distributed "Help" (aka "Manual"). Error message show look like this:
> **Error**
> 
> Failed to locate the help files.

Then I dig into doc folder and see that manuals files distributed (inside package) and installed in compressed form as:
* `/usr/share/doc/openorienteering-mapper-unstable/Mapper 0.8.0 Manual.qch.gz`
* `/usr/share/doc/openorienteering-mapper-unstable/Mapper 0.8.0 Manual.qhc.gz`

### Expected behaviour
Those files should be installed in non-compressed form as:
* `/usr/share/doc/openorienteering-mapper-unstable/Mapper 0.8.0 Manual.qch`
* `/usr/share/doc/openorienteering-mapper-unstable/Mapper 0.8.0 Manual.qhc`

If manualy unpack those files, as I show here, then Mapper normally open manual if click on "Help". 

P.S.: In `0.6.x` those files packaged and installed in non-compressed form, so this issue not related to releases before `0.7.x`!

### Configuration
Mapper Version: 0.7.0, 0.8.x
Operating System: LinuxMint 18.2 / xUbuntu 16.04 (amd64)

### NOTE
Related to this found that manual files include 'space' characters inside names, so HIGHLY RECOMMEND rename those files:
* `Mapper_0.8.0_Manual.qhc`
* `Mapper_0.8.0_Manual.qch`

**Comment by dg0yt** [comment]
There must have been a change in packging behaviour. Documentation is now compressed by dh_compress (https://build.opensuse.org/package/live_build_log/home:dg0yt:staging/openorienteering-mapper-unstable/Ubuntu_16.04/x86_64):

~~~
[  279s]    dh_compress -O--builddirectory=build -O--parallel
[  279s] 	cd debian/openorienteering-mapper-unstable
[  279s] 	chmod a-x "usr/share/doc/openorienteering-mapper-unstable/Mapper 0.7.1 Manual.qch" "usr/share/doc/openorienteering-mapper-unstable/Mapper 0.7.1 Manual.qhc" usr/share/doc/openorienteering-mapper-unstable/changelog.Debian usr/share/doc/openorienteering-mapper-unstable/common-licenses/GPL-3.txt usr/share/man/man1/Mapper-unstable.1
[  279s] 	gzip -9nf "usr/share/doc/openorienteering-mapper-unstable/Mapper 0.7.1 Manual.qch" "usr/share/doc/openorienteering-mapper-unstable/Mapper 0.7.1 Manual.qhc" usr/share/doc/openorienteering-mapper-unstable/changelog.Debian usr/share/doc/openorienteering-mapper-unstable/common-licenses/GPL-3.txt usr/share/man/man1/Mapper-unstable.1
~~~

Your recommendation about space is unrelated, and repeating without substance is pointless.

**Comment by dg0yt** [comment]
New builds are coming, both for 0.7.0 and unstable.

~~~
[  269s]    debian/rules override_dh_compress
[  269s] make[1]: Entering directory '/usr/src/packages/BUILD'
[  269s] dh_compress -X.qhc -X.qch -X.txt -X.html
[  269s] 	cd debian/openorienteering-mapper-unstable
[  269s] 	chmod a-x usr/share/doc/openorienteering-mapper-unstable/changelog.Debian usr/share/man/man1/Mapper-unstable.1
[  269s] 	gzip -9nf usr/share/doc/openorienteering-mapper-unstable/changelog.Debian usr/share/man/man1/Mapper-unstable.1

**Comment by Symbian9** [comment]
> New builds are coming, both for 0.7.0 and unstable.

Just look on latest builds numbering

Previouse numbers was:
* `openorienteering-mapper_0.7.0-0+2.1`
* `openorienteering-mapper-unstable_0.8.20171022-0+479.1`

Latest builds numbers:
* `openorienteering-mapper_0.7.0-0+3.1`
* `openorienteering-mapper-unstable_0.8.20171022-0+459.1`

With number of latest version all OK (it increased now).

But number of latest build decreased comparing to previouse.

@dg0yt, is it some another bug with packaging?
* http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_16.04/amd64/

Latest build should be named such as:
* [ ] `openorienteering-mapper-unstable_0.8.20171024-0+480.1`
