### ISSUE TITLE
Not included file of GPL-3 for "About" dialog

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#995]
### Steps to reproduce
1. Install Mapper
2. Go to menu "Help -> About OpenOrienteering Mapper"
3. Click on links related to `file:/doc:/common-licenses/GPL-3.txt`

### Actual behaviour
File `file:/doc:/common-licenses/GPL-3.txt` is empty (or not exist?)

### Expected behaviour
Show text of GNU GPL-3 license.

### Configuration
Mapper Version: unstable 0.8.20171022 (build479)
Operating System: LinuxMint 18.2 / xUbuntu 16.04 (amd64)

**Comment by dg0yt** [comment]
It is there as GPL-3.txt.gz, i.e. another effect of unexpected documentation compression during packaging, #995.
