### ISSUE TITLE
Draw circles mode - simplify circle

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#996]
### Steps to reproduce
At the moment when drawing a circle  - 4 nodes are used and 8 "bezier handles". That many nodes make circle handling difficult. Note that usually when drawing a circle you draw a small one. Big regular contour hills (depressions) are almost nonexistent.

### Expected behaviour
I would suggest to lower the number of nodes to 2 (and 4 "bezier handles"). That would make editing of hills more straightforward.

### Configuration
Android app 0.7.0

**Comment by Symbian9** [comment]
For the record
* https://stackoverflow.com/questions/1734745/how-to-create-circle-with-bézier-curves
* https://math.stackexchange.com/questions/449035/is-it-possible-to-build-a-circle-with-quadratic-bézier-curves

**Comment by lpechacek** [comment]
As @Symbian9 suggests with the above links, the 2-curve shape will not resemble circle very much. But given printing resolution, the deformation might not be obvious on paper.
![image](https://user-images.githubusercontent.com/5584406/31946182-712b96e0-b8d1-11e7-8971-405a59985153.png)
Blue circle is a 2-segment shape, black one is 4-segment one. In general I'm not much in support of the proposal at the moment as it seems to contradict my map editing habits. I'm used to moving the curve end control points (marked with square) as opposed to the shape control points (circles).

**Comment by Symbian9** [comment]
> That many nodes make circle handling difficult. Note that usually when drawing a circle you draw a small one. Big regular contour hills (depressions) are almost nonexistent.

@ollesmap, there is no clear description for why this feature request should be implemented.

If you want scale already drawn big circle/ellipse to smaller – use "Tools -> Scale objects (Z)".

**Comment by dg0yt** [comment]
As already said, even four point is just an approximation of a proper circle, We can hardly go for less. And maybe there other ways to achieve what you want:
- draw an ellipse (same tool)
- scale the circle object ("Scale objects" tool)
- draw the line with the regular tool ("Draw-paths" tool). You don't want many points, so it should be many clicks.

**Comment by ollesmaps** [comment]
OK, you are right, it would not be beneficial for drawing big circles.
Simplify the path does the trick for small ones.
You shall close the issue. Thank you for your feedback.
@dg0yt Is it possible to draw ellipses within Android app?

**Comment by dg0yt** [comment]
@ollesmaps Yes, it is possible to draw ellipses in the Android app like on the desktop.
However, there is no feedback on the first click (on the desktop we start tracking the pointer) - you just have to start dragging (and thus define the second point) to see some progress.
A touch-friendly implementation could check the direction of dragging: dagging along the line through both points, it would change the the first diameter, and in orthogonal direction, it would change the second diameter.

**Comment by ollesmaps** [comment]
@dg0yt Thanks for the ellipse tip! It really works :)
