### ISSUE TITLE
Some contradictions in Manual

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#997]
Some officially unsupported file formats appear in Open Template dialog:

![screenshot1](https://user-images.githubusercontent.com/688044/32001007-202c98f4-b9a1-11e7-91c1-dceae309eddf.jpg)

[Mapper Manual (Introduction to Templates)](http://www.openorienteering.org/mapper-manual/pages/templates.html#types-of-templates):

> OpenOrienteering Mapper supports the following file formats to be loaded as templates:
> 
> * Image templates: bmp, jpg, png, tif, gif files
> * Track templates: dxf, gpx, osm files
> * Map templates: omap, ocd files

* template_image.cpp:
```c++
const std::vector<QByteArray>& TemplateImage::supportedExtensions()
{
	static std::vector<QByteArray> extensions;
	if (extensions.empty())
	{
		using namespace std;
		auto formats = QImageReader::supportedImageFormats();
		extensions.reserve(formats.size());
		extensions.insert(end(extensions), begin(formats), end(formats));
	}
	return extensions;
}
```

[QImageReader::supportedImageFormats()](http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats):

> By default, Qt can read the following formats:
> 
> Format | MIME type | Description
> -- | -- | --
> BMP | image/bmp | Windows Bitmap
> GIF | image/gif | Graphic Interchange Format (optional)
> JPG | image/jpeg | Joint Photographic Experts Group
> PNG | image/png | Portable Network Graphics
> PBM | image/x-portable-bitmap | Portable Bitmap
> PGM | image/x-portable-graymap | Portable Graymap
> PPM | image/x-portable-pixmap | Portable Pixmap
> XBM | image/x-xbitmap | X11 Bitmap
> XPM | image/x-xpixmap | X11 Pixmap
> SVG | image/svg+xml | Scalable Vector Graphics
> 
> Reading and writing SVG files is supported through the Qt SVG module. The Qt Image Formats module provides support for additional image formats.

* template_track.cpp:
```c++
const std::vector<QByteArray>& TemplateTrack::supportedExtensions()
{
	static std::vector<QByteArray> extensions = { "dxf", "gpx", "osm" };
	return extensions;
}
```

* template_map.cpp:
```c++
const std::vector<QByteArray>& TemplateMap::supportedExtensions()
{
	static std::vector<QByteArray> extensions = { "ocd", "omap", "xmap" };
	return extensions;
}
```

Issues:
* Trying to open PDF files lead to crash, but "Cannot open template" warning is expected.
* KML (Keyhole Markup Language) and JSON (GeoJSON) templates, on the other hand, seems to work correctly and should be mentioned in Mapper Manual. KML files are very often distributed in KMZ files, which are zipped KML files, so what about KMZ support?
* TIF format is not actually supported.
* SVG and some other image formats should be added to Manual.

**Comment by dg0yt** [comment]
Thanks for looking at documentation. However, it is not so simple. 

- You miss the vector file formats supported via OGR (GDAL) in unstable builds. For GDAL >2.0, we query GDAL for the [available formats](http://www.gdal.org/ogr_formats.html). This where PDF or XLS may come from. This is what is just about to be released with 0.8.0.
- You cannot assume that generic Qt or GDAL documentation matches actual deployment, or that your configuration matches another user's configuration. For example, I have no issues with TIFF support, and it is in our superbuilds, too. On the other hand I would not bet on XPM support on Windows.

So at best, there are "officially supported" formats: Formats which are more or less garantueed to be available.

Note that we don't have unit tests for officially supported formats, unfortunately.

**Comment by sikmir** [comment]
I see.

**Comment by sikmir** [comment]
> For example, I have no issues with TIFF support, and it is in our superbuilds, too.

@dg0yt Well, I've installed [unstable build](http://download.opensuse.org/repositories/home:/dg0yt/Arch_Community/x86_64/openorienteering-mapper-unstable-0.8.20171022-0-x86_64.pkg.tar.xz) and I still can't open TIFF image templates. What is wrong?

**Comment by sikmir** [comment]
@dg0yt By the way, [Arch package database](http://download.opensuse.org/repositories/home:/dg0yt/Arch_Community/x86_64/) is not up to date, it still refers to `openorienteering-mapper-unstable-0.8.20171004-0-x86_64.pkg.tar.xz`, instead of `openorienteering-mapper-unstable-0.8.20171022-0-x86_64.pkg.tar.xz`.

**Comment by dg0yt** [comment]
> Well, I've installed unstable build and I still can't open TIFF image templates. What is wrong?

I guess the PKGBUILDs need an ```optdepends ('qt5-imageformats: Support for TIFF etc.')```...

**Comment by sikmir** [comment]
> I guess the PKGBUILDs need an optdepends ('qt5-imageformats: Support for TIFF etc.')

Thanks, it works now!
